### ISSUE TITLE
Colour westphalian disctricts in red when hovering over map

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#101]
Customer feedback from our meeting on 2015-04-13 (see https://wiki1.hbz-nrw.de/x/DQBEB): The districts in the Westphalian part of Northrhine Westphalia should be coloured in the red of the coat of arms  – instead of green – when hovering over the map on the start page.

**Comment by fsteeg** [comment]
Deployed to staging: http://test.lobid.org/nwbib

**Comment by acka47** [comment]
+1. I didn't check for each district whether the colouring is correct, though. :-)
