### ISSUE TITLE
Create BEACON file for NWBib contributors

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#102]
Customers want to be listed in the [person search](http://tools.wmflabs.org/persondata/) linked from some German Wikipedia articles (e.g. [Heinrich Böll](http://de.wikipedia.org/wiki/Heinrich_B%C3%B6ll) -> Normdaten -> Wikipedia-Personensuche) if the person in question has created a work that is part of NWBib. THus, we will have to create a BEACON file with GND IDs of all persons that have a creator/contributor role in NWBib. The file should look something like this:
EDIT @dr0i: this template has changed. For the actual version, see https://github.com/lobid/lodmill/blob/master/lodmill-rd/doc/scripts/hbz01/stats/stats.sh

```
#FORMAT: BEACON
#VERSION: 0.1
#PREFIX: http://d-nb.info/gnd/
#TARGET: http://lobid.org/nwbib/search?person={ID}
#FEED: [URL of the BEACON file]
#CONTACT: lobid-Team im hbz <semweb@hbz-nrw.de>
#NAME: Nordrhein-Westfälische Bibliographie (NWBib)
#INSTITUTION: Hochschulbibliothekszentrum des Landes Nordrhein-Westfalen (hbz)
#MESSAGE Literatur dieser Person in der Nordrhein-Westfälischen Bibliographie (NWBib)
#DESCRIPTION: This is an automatically generated BEACON file for all contributors of works catalogued in the Northrhine-Westphalian Bibliography.
#TIMESTAMP: [yyyy-mm-dd]
#UPDATE: weekly
#LINK: http://www.w3.org/2000/01/rdf-schema#seeAlso
#EXAMPLES: 118515470

118515470|11
118512676|254
```
Format description at http://de.wikipedia.org/wiki/Wikipedia:BEACON/Format.
(See https://wiki1.hbz-nrw.de/x/DQBEB for documentation of original customer feedback.)

**Comment by dr0i** [comment]
The script in https://github.com/lobid/lodmill/issues/663 generates the beacon, see http://lobid.org/download/beacons/ .
However, since getting the NWBib dataset results in an error (-> hbz/lobid#107), some data is missing right now.

**Comment by acka47** [comment]
Looks good, we have to adjust the person queries, though, as the URL template `http://lobid.org/nwbib/search?person={ID}` doesn't work with hyphenated GND IDs, e.g.
-  http://lobid.org/nwbib/search?person=10007642-7 (In contrast to http://lobid.org/nwbib/search?q=%22http://d-nb.info/gnd/10007642-7%22)
- http://lobid.org/nwbib/search?person=10008170-8 (in contrast to http://lobid.org/nwbib/search?q=%22http://d-nb.info/gnd/10008170-8%22)

Using the whole URI – whether as phrase or not – doesn't work either with the `person` parameter, e.g.:
- http://lobid.org/nwbib/search?person=%22http://d-nb.info/gnd/10007642-7%22 and http://lobid.org/nwbib/search?person=http://d-nb.info/gnd/10007642-7
- http://lobid.org/nwbib/search?person=%22http://d-nb.info/gnd/10008170-8%22 and http://lobid.org/nwbib/search?person=http://d-nb.info/gnd/10008170-8

**Comment by dr0i** [comment]
Fixed that, see the updates.

**Comment by acka47** [comment]
@dr0i, you changed the `#TARGET` to `http://lobid.org/nwbib/search?q=%22http://d-nb.info/gnd/{ID}%22` which isn't correct as results also contain resources _about_ a person and not only resources where the person is contributor. We have to bease this on the `/person` query as said in https://github.com/hbz/nwbib/issues/102#issuecomment-97706585 and adjust the query according to #107 .

**Comment by dr0i** [comment]
BUt that doesn't work, using e.g the example used in the beacon: http://lobid.org/nwbib/search?person=%22http://d-nb.info/gnd/118515470%22

**Comment by dr0i** [comment]
Resolving hbz/lobid#107 we can work on this further.
Regenerated the beacon. Have a look.
Interestingly the file starts with an empty ID which the ocurence of `2`. I investigated this and found the cause in the catalog, see e.g. http://lobid.org/resource/HT017587220.

**Comment by acka47** [comment]
Same problem here as in https://github.com/hbz/lobid/issues/163. E.g. http://lobid.org/nwbib/search?person=100120318 which -- according to the BEACON file -- is expected to deliver 2 results gives 2248 results.

Also, search with hyphenated GND IDs doesn't work.

I will review this more thorougly as soon as #107 and  https://github.com/hbz/lobid/issues/163 are resolved.

**Comment by acka47** [comment]
> Interestingly the file starts with an empty ID with the ocurence of `2`. I investigated this and found the cause in the catalog, see e.g. http://lobid.org/resource/HT017587220.

If you tell me the other resource that is incorrectly catalogued or even provide me with your method to find the one with missing GND IDs I will write to the NWBib editors to fix it in the source.

**Comment by dr0i** [comment]
Re: finding missing GND IDs: it's all about context:

Grep the contributors and pipe that into sed like in https://github.com/lobid/lodmill/blob/master/lodmill-rd/doc/scripts/hbz01/stats/stats.sh (don't (!) sort it etc.).
This will get you a list of ids. Now open `vi` and find the empty lines ( pattern '^$'). Now you copy the resources directly before or after that empty line. Open the `NWBib_all.nt` with `less`and search for that resoure. The neighbour of it is the incorrect catalogued one.

There is of course a faster and more convenient way (there are always thousand of ways) but that's the one I went.

**Comment by dr0i** [comment]
> I will review this more thorougly as soon as #107 and hbz/lobid#163 are resolved.

So , go on :)

**Comment by acka47** [comment]
Similar to https://github.com/hbz/nwbib/issues/106#issuecomment-113063614, this looks good but mostly doesn't give the exact number of result that one will get. Examples:

- http://lobid.org/nwbib/search?person=100057160: BEACON 10, query 6
http://lobid.org/nwbib/search?sort=newest&person=10007031-0: BEACON 33, query 35

**Comment by dr0i** [comment]
> http://lobid.org/nwbib/search?person=100057160: BEACON 10, query 6

This result is caused by resources having a person as e.g. contributor AND creator thus counting double. After discussing with @acka47 we should adjust the data to decide which one to use. `dct:contributor` should only be used if not already `dct:creator` was chosen before. `dct:contributor` would be chosen at last.

**Comment by dr0i** [comment]
After further discussion and musing: we will have resources where the same person will have more than one role anyway. So we leave the data as it is.

**Comment by acka47** [comment]
+1. Added this BEACON file and the subject BEACON ( #106) to the Wikipedia BEACON list, see https://de.wikipedia.org/w/index.php?title=Wikipedia%3ABEACON&type=revision&diff=144300548&oldid=143700048. Contacted APPER to add NWBib to the Wikipedia-Personensuche, see. https://de.wikipedia.org/w/index.php?title=Benutzer_Diskussion%3AAPPER&type=revision&diff=144300753&oldid=144252720. Closing.
