### ISSUE TITLE
Remove Feedback buttons from NWBib

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#103]
Customers want the mail feedback buttons removed as the contact information is sufficient (see https://wiki1.hbz-nrw.de/x/DQBEB).

**Comment by fsteeg** [comment]
If I remember correctly, all of the feedback we received came via these links. They also automatically provide details about the current page as part of the subject. I therefore don't think we should remove them. Or is this about something else and I'm getting it wrong?

**Comment by acka47** [comment]
You are getting it righ and I argued the same way at the NWBib meeting. Customers said the feedback received hadn't been useful and too much. Wha they want are suggestions of resources to be included in NWBib. They argued that the feedback information would be redundant as contact linkswould already be presentged behind the ":information_source:" sign.

We'll ask at the [meeting at Lokal K on Wednesday](https://de.wikipedia.org/wiki/Wikipedia:Lokal_K/Termin/NWBib-Vorstellung) how customers would like a feedback function to work. Will you also be there?
