### ISSUE TITLE
Subject chains with double angle brackets aren't shown correctly in HTML 

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#104]
See e.g. http://lobid.org/nwbib/HT018312899. It reads: 
`Schlagwortfolge 	Grabbe, Christian Dietrich | <> Cid | Dramaturgie | Rezeption`

The [underlying data](http://lobid.org/resource?id=HT018312899&format=full): `subjectChain": "Grabbe, Christian Dietrich | <<Der>> Cid | Dramaturgie | Rezeption (231,321)"`

**Comment by dr0i** [comment]
I will remove this '<<>>' "crab"-crap from the data (really, looks like a crab).
Will not fix html.

**Comment by dr0i** [comment]
Deployed test to staging.

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Deployed to production, closing.
