### ISSUE TITLE
Wrong links in single resource views

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#105]
All the links in a single resourc view are based on a generic `q` query. They have to be adjusted with regard to their location.

Example: http://lobid.org/nwbib/HT018112985
- Current link behind `Autor/in`: http://lobid.org/nwbib/search?q=%22http%3A%2F%2Fd-nb.info%2Fgnd%2F128586516%22
- I should be the following: http://lobid.org/nwbib/search?person=http%3A%2F%2Fd-nb.info%2Fgnd%2F128586516 (Obviously, the phrase search doesn't work with `person` parameter.)
- Current link behind `Schlagwort` "Kreissparkasse <Köln>": http://lobid.org/nwbib/search?q=%22http%3A%2F%2Fd-nb.info%2Fgnd%2F2001375-9%22
- It should be: http://lobid.org/nwbib/search?subject=http%3A%2F%2Fd-nb.info%2Fgnd%2F2001375-9

Example: http://lobid.org/nwbib/HT016531289 (where "Kreissparkasse <Köln>" is contributor instead of subject):
- Behind `Mitwirkung` "Kreissparkasse <Köln>" should be the link http://lobid.org/nwbib/search?person=http%3A%2F%2Fd-nb.info%2Fgnd%2F2001375-9 (which currently doesn't work. Will open another issue for this one.)
- Behind the `Schlagwort` links should be a query à la `http://lobid.org/nwbib/search?subject={URI}`.

**Comment by acka47** [comment]
While we are at it, we should also specify the links behind the spatial and subject notations from NWBib classification. For this, we will use the following link types:
- for NWBib spatial: http://lobid.org/nwbib/search?nwbibspatial={URI}
- for NWBib subject: http://lobid.org/nwbib/search?nwbibsubject={URI}

Example http://lobid.org/nwbib/HT014318568:
- Link behind `Raumsystematik` "Nordrhein-Westfalen" should be: http://lobid.org/nwbib/search?nwbibspatial=http%3A%2F%2Fpurl.org%2Flobid%2Fnwbib-spatial%23n01
- Link behind "Information und Dokumentation": http://lobid.org/nwbib/search?nwbibsubject=http%3A%2F%2Fpurl.org%2Flobid%2Fnwbib%23s884000

For the subject links applies the same as written [above](https://github.com/hbz/nwbib/issues/105#issue-71220413).

**Comment by fsteeg** [comment]
Deployed to staging, see your samples from above:

http://test.lobid.org/nwbib/HT018112985
http://test.lobid.org/nwbib/HT016531289
http://test.lobid.org/nwbib/HT014318568

The search `param` to use is configured in the document template, see:

https://github.com/hbz/nwbib/blob/master/app/views/tags/result_doc.scala.html#L42

**Comment by acka47** [comment]
+1
