### ISSUE TITLE
Create BEACON file for NWBib subjects

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#106]
Besides a BEACON for literature by a ceratin person (see #102 ) we should also add another BEACON with resources in NWBib _about_ a person and other subjects. It should look like this:
EDIT @dr0i: this template has changed. For the actual version, see https://github.com/lobid/lodmill/blob/master/lodmill-rd/doc/scripts/hbz01/stats/stats.sh

```
#FORMAT: BEACON
#VERSION: 0.1
#PREFIX: http://d-nb.info/gnd/
#TARGET: http://lobid.org/nwbib/search?subject={ID}
#FEED: [URL of the BEACON file]
#CONTACT: lobid-Team im hbz <semweb@hbz-nrw.de>
#NAME: Nordrhein-Westfälische Bibliographie (NWBib)
#INSTITUTION: Hochschulbibliothekszentrum des Landes Nordrhein-Westfalen (hbz)
#MESSAGE Literatur über diese Ressource in der Nordrhein-Westfälischen Bibliographie (NWBib)
#DESCRIPTION: This is an automatically generated BEACON file for all contributors of works catalogued in the Northrhine-Westphalian Bibliography.
#TIMESTAMP: [yyyy-mm-dd]
#UPDATE: weekly
#LINK: http://xmlns.com/foaf/0.1/isPrimaryTopicOf
#EXAMPLES: 118515470

118515470|36
118512676|213
```

**Comment by dr0i** [comment]
The script in lobid/lodmill#663 generates the beacon, see http://lobid.org/download/beacons/nwbibSubjects.bf.
However, since getting the NWBib dataset results in an error (-> hbz/lobid#107), some data is missing right now.

**Comment by acka47** [comment]
Something went wrong with this one. Firstly, it is quite short and secondly there are no GND IDs but lobid URIs in the second part of the file.

**Comment by dr0i** [comment]
Fixed that, see the updates.

**Comment by acka47** [comment]
Similar to what I said in https://github.com/hbz/nwbib/issues/102#issuecomment-103039221 the  #TARGET` shouldn't be `http://lobid.org/nwbib/search?q=%22http://d-nb.info/gnd/{ID}%22`as the results contain – at least for persons and corporate bodies – not only resources _about_ them but also _by_ them.

Example: http://lobid.org/nwbib/search?q="http%3A%2F%2Fd-nb.info%2Fgnd%2F10017689-6" contains http://lobid.org/nwbib/HT013695389 which is by and not about 10017689-6.

As – unlike the person query – hyphenated GND IDs work with the subject query, we just have to adjust the `#TARGET` – as originally proposed –  to `http://lobid.org/nwbib/search?subject={ID}`.

**Comment by dr0i** [comment]
Yes, but again: these don't work , eg. http://lobid.org/nwbib/search?subject=%22http://d-nb.info/gnd/10017689-6%22 .

**Comment by acka47** [comment]
@dr0i Please run the script once again so that we can close this issue.

**Comment by dr0i** [comment]
Resolving hbz/lobid#107 we can work on this further.
Regenerated the beacon. Have a look.

**Comment by acka47** [comment]
This one looks good. +1 with onr limitation: The result numbers in the BEACON file and in the actual result differ a bit for some result lists. This isn't a big problem I think as it is ok when the numbers only give an approximation. Thus, just correct it if there is an easy fix.

Examples:
- http://lobid.org/nwbib/search?subject=10073784-5 gives 170 results though the BEACON says 167.
- http://lobid.org/nwbib/search?subject=801210-6 gives 34 results, BEACON says 32.
- http://lobid.org/nwbib/search?subject=7864098-2 gives 9, BEACON says 10.
- http://lobid.org/nwbib/search?subject=7862100-8 gives 1, BEACOn says 2.
- http://lobid.org/nwbib/search?subject=7847343-3 gives 2, BEACON says 4.

**Comment by dr0i** [comment]
Interesting! This gives us a way to validate if the API is ok and the scripts are wrong or vice versa. Will investigate this.

**Comment by dr0i** [comment]
Ah! The scripts worked on an old, wrong NWBib dump, where some records were multiple times in it. Will make a whole new dump and run the scripts again.

**Comment by acka47** [comment]
> Ah! The scripts worked on an old, wrong NWBib dump, where some records were multiple times in it. Will make a whole new dump and run the scripts again.

Let me know as soon as you have done so and I will do another review.

**Comment by dr0i** [comment]
The wrong NWBib dump was a result of the old way to load the data (using deep pagination). With hbz/lobid#176 the dumps are coherent (=> no more doublets). Now getting this dump and work on it.

**Comment by dr0i** [comment]
@acka47 please have a look again.

**Comment by acka47** [comment]
+1
