### ISSUE TITLE
Adjust query with person parameter to find hyphenated GND IDs

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#107]
As a general user I want to search for/link to literature by a person using the persons GND ID – whether the ID is hyphenated or not.

Quoting from https://github.com/hbz/nwbib/issues/102#issuecomment-97706585;

>  the URL template `http://lobid.org/nwbib/search?person={ID}` doesn't work with hyphenated GND IDs, e.g.
-  http://lobid.org/nwbib/search?person=10007642-7 (In contrast to http://lobid.org/nwbib/search?q=%22http://d-nb.info/gnd/10007642-7%22)
- http://lobid.org/nwbib/search?person=10008170-8 (in contrast to http://lobid.org/nwbib/search?q=%22http://d-nb.info/gnd/10008170-8%22)

> Using the whole URI – whether as phrase or not – doesn't work either with the `person` parameter, e.g.:
- http://lobid.org/nwbib/search?person=%22http://d-nb.info/gnd/10007642-7%22 and http://lobid.org/nwbib/search?person=http://d-nb.info/gnd/10007642-7
- http://lobid.org/nwbib/search?person=%22http://d-nb.info/gnd/10008170-8%22 and http://lobid.org/nwbib/search?person=http://d-nb.info/gnd/10008170-8

**Comment by acka47** [comment]
This is a lobid API problem and not a problem with how the query is configure in NWBib: http://lobid.org/resource?author=10007642-7 doesn't work as well.

**Comment by dr0i** [comment]
Deployed to staging.

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Deployed to production, closing.
