### ISSUE TITLE
Don't show person twice –  as contributor and under specific role

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#109]
See e.g. http://lobid.org/nwbib/HT016161271.

We should leave the redundancy in the base data though. For background to the implementation of specific role attributes instead of generic `Mitwirkung` see #36 .

**Comment by dr0i** [comment]
Deployed to staging, please test.

**Comment by acka47** [comment]
+1 (I just now realized that we only have the redundancy for `dct:creator` and `dct:contributor` but not for specific roles (e.g singer, see http://lobid.org/resource/HT016568152/about). To remove this inconsistency, I now did make a ticket to remove reduntant entries on data level https://github.com/hbz/lobid/issues/158. I am sorry I haven't seen this before and you have to do double work. :grimacing: )

**Comment by dr0i** [comment]
deployed to production, closing
