### ISSUE TITLE
Prefer MultiVolumeBook icon to Book icon

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#113]
See this result list: http://lobid.org/nwbib/search?q=*&t=http%3A%2F%2Fpurl.org%2Fontology%2Fbibo%2FMultiVolumeBook

Although, all results are f type `MultiVolumeBook` the respective icon is only shown on some of them. Mostly the `Book` icon is shown.

(The way to tackle this might be similar to this closed issue: #61.)

**Comment by fsteeg** [comment]
Here's a slightly different, more general suggestion to fix this: when the type facet is active, always use its icon in the result list. Deployed to staging, see: http://test.lobid.org/nwbib/search?q=*&t=http%3A%2F%2Fpurl.org%2Fontology%2Fbibo%2FMultiVolumeBook

**Comment by acka47** [comment]
I would like to always see the more specific icons in the result list, whether a type facet is active or not.

**Comment by fsteeg** [comment]
For that I'd need an ordering of specificity. Perhaps you could order the entries in `nwbib.conf`?

**Comment by acka47** [comment]
> For that I'd need an ordering of specificity. Perhaps you could order the entries in `nwbib.conf`?

As far as I know, I did this last week and submitted a pull request. Can't see where it went, though...

**Comment by fsteeg** [comment]
@acka47 Hm, me neither - nothing at https://github.com/hbz/nwbib/pulls

**Comment by acka47** [comment]
There it is now: https://github.com/hbz/nwbib/pull/123. Assigning to you, @fsteeg .

**Comment by fsteeg** [comment]
Deployed to staging, see:
http://test.lobid.org/nwbib/search?q=*&t=http%3A%2F%2Fpurl.org%2Fontology%2Fbibo%2FMultiVolumeBook

**Comment by acka47** [comment]
Looks good for now. +1

**Comment by fsteeg** [comment]
Deployed to production:
http://lobid.org/nwbib/search?q=*&t=http%3A%2F%2Fpurl.org%2Fontology%2Fbibo%2FMultiVolumeBook
