### ISSUE TITLE
Show readable label for lV:EditedVolume instead of URI

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#115]
Currently, the URI is shown under "Publikationstyp", see resources from http://lobid.org/nwbib/search?q=*&t=http%3A%2F%2Fpurl.org%2Flobid%2Flv%23EditedVolume.

At least, we should have a better readable label for this and – in a second step – also an icon.

**Comment by dr0i** [comment]
Deployed to staging. Looks nice :+1:

**Comment by acka47** [comment]
I also added the [package octicon](https://octicons.github.com/icon/package/) for this. It seemed the best choice from what is available. We will have to rework the icon set anyhow..

However, looks good. +1 Can be deployed to production.

**Comment by dr0i** [comment]
Deployed to production, closing.
