### ISSUE TITLE
Person search doesn't work

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#117]
See e.g. http://lobid.org/nwbib/search?sort=newest&person=adenauer%20konrad.
We would expect around 50 hits.

**Comment by dr0i** [comment]
Deployed to staging.

**Comment by dr0i** [comment]
Redeployed. Now test URL reveals 61 hits.

**Comment by acka47** [comment]
Strange that there are six more results than before this bug. Will investigate this next week (or we will get some customer feedback on this, anyway=. Please deploy to production anyway.

**Comment by dr0i** [comment]
Deployed to production.
