### ISSUE TITLE
Type all resources with 90* "Aufsatzsammlung" as lv:EditedVolume

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#118]
See e.g. http://lobid.org/resource/HT018295975 where the [source](http://lobid.org/resource?id=HT018295975&format=source) says:

```xml
<datafield tag="907" ind1="-" ind2="1">
  <subfield code="f">Aufsatzsammlung</subfield>
</datafield>
```

Obviously, https://github.com/lobid/lodmill/issues/271 didn't work for all cases.

**Comment by acka47** [comment]
Other example is http://lobid.org/resource/HT014965738.

**Comment by dr0i** [comment]
Deployed test to staging.

**Comment by dr0i** [comment]
>  Other example is http://lobid.org/resource/HT014965738.

No, it's not (or "no more").

**Comment by dr0i** [comment]
Deployed to production, closing.
