### ISSUE TITLE
When only literals exists and no GND id, a search should use that literal

### ISSUE THREAD

**Issue by dr0i** [hbz/nwbib#120]
E.g. clicking on "Wimmer, Jeffrey, 1972-" at http://lobid.org/nwbib/HT017587220 a GND search is triggered with only the base URL of the GND , because the actual ID is not in the data. If the latter is the case, a simple literal search would be much better.

**Comment by dr0i** [comment]
@acka47 please qualify and priorize if this is actually an issue.

**Comment by acka47** [comment]
@dr0i #105 is related and should be solved before we discuss special features like you suggest.

**Comment by acka47** [comment]
(Actually, I don't think that customers want this feature.)

**Comment by dr0i** [comment]
Closing, as it is not necessary to be solved.
