### ISSUE TITLE
Use http://beta.lobid.org/organisations for item details

### ISSUE THREAD

**Issue by fsteeg** [hbz/nwbib#121]
To push our API 2.0 efforts, we should dogfood our new organisations API in NWBib.

**Comment by fsteeg** [comment]
Deployed to staging, see e.g. http://test.lobid.org/nwbib/HT013313122

**Comment by acka47** [comment]
http://test.lobid.org/nwbib currently gives "Action not found For request 'GET /error/HTTP_SERVICE_UNAVAILABLE.html.var'".

**Comment by fsteeg** [comment]
Restarted, now running again: http://test.lobid.org/nwbib

**Comment by acka47** [comment]
Looks good. +1
