### ISSUE TITLE
Use http://beta.lobid.org/hbz01 for hidden source links

### ISSUE THREAD

**Issue by fsteeg** [hbz/nwbib#122]
To push our API 2.0 efforts, we should dogfood our new source data API in NWBib.

**Comment by fsteeg** [comment]
Deployed to staging, see hidden link in: 
http://test.lobid.org/nwbib/HT018604501

Which points to:
http://beta.lobid.org/hbz01/HT018604501

**Comment by acka47** [comment]
+1
