### ISSUE TITLE
Differentiate presentation of various hasPart information

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#126]
- [ ] Show link at multi-volume work to list of volumes (properties `volumeIn`->`multiVolumeWork`) with "Bände – Zugehörige Bände anzeigen."
- [ ] Show links to list of articles contained in a resource (property `containedIn`) with "„Enthält“ – „Enthaltene Beiträge anzeigen“"

Customers requested this via mail to email list on 14./15. July.

Example for a resource that should contain both types of links: http://lobid.org/nwbib/HT009821451

We don't know the exact text for resources contained within a series. My suggestion for now:

- [ ] Show link at series to resources that are part of the series (properties `inSeries` -> `series`) with "Enthält – Enthaltene Titel anzeigen"

**Comment by acka47** [comment]
Working on this, we should also take into account this customer feedback from today (2015-08-19):

> Mehrbändige Werke als Aufsatzsammlung: Als Beispiel wäre zu nennen: [[HT018486420](http://test.lobid.org/nwbib/HT018486420)] Oberhausen : eine Stadtgeschichte im Ruhrgebiet. – Studienausg.   An jedem der vier Bände hängen etliche Aufsätze, die wir für die NWBib katalogisiert haben. In der neuen NWBib sind diese Aufsätze aber nicht an den Bänden anhängend. Genauso trifft dies auf das Beispiel   [HT014974933](http://lobid.org/nwbib/HT014974933)   Rheinische Glasmalerei zu. An den beiden Bänden „Essays“ und „Katalog“ hängen jeweils mehrere Aufsätze, die aber in der neuen NWBib nicht angezeigt werden. – Bei einfachen Monographien (einbändige Werke), die Aufsätze enthalten, die von uns für die NWBib aufgenommen wurden, scheint die Anzeige der Aufsätze in der neuen NWBib zu funktionieren. Nur bei mehrbändigen Werken als Aufsatzsammlung scheint es noch Probleme zu geben.

**Comment by fsteeg** [comment]
Is this really `ready`? The sample you linked to (http://lobid.org/resource/HT009821451?format=full) contains none of the fields from the issue description. Or am I not getting what this is about?

**Comment by acka47** [comment]
> The sample you linked to (http://lobid.org/resource/HT009821451?format=full) contains none of the fields from the issue description

No, but the subordinated resource behind the link "Enthaltene Beiträge anzeigen" in http://lobid.org/nwbib/HT009821451 contain this information. See also the "sister ticket" #124  that deals with the presentation for subordinated resources.

**Comment by fsteeg** [comment]
Ok, I'm starting to understand. But given a resource like http://lobid.org/nwbib/HT009821451, how can I decide which type of link(s) to show? The current `Enthaltene Beiträge anzeigen` link is inserted based on the resource type. But http://lobid.org/nwbib/HT009821451 is only `http://purl.org/ontology/bibo/Journal` - should all journals get both these links?

**Comment by acka47** [comment]
>  The current `Enthaltene Beiträge anzeigen` link is inserted based on the resource type.

Is this necessary? If possible, I'd suggest checking for contained articles or volumes and show them when existing.

If this is too much of a hassle, we might select the types where it should be shown but there are a lot. I could find the following that have articles linked to them with `cointainedIn`:
- `Journal` (example article http://lobid.org/nwbib/HT018616958 contained in http://lobid.org/nwbib/HT006988707 (currently no link at the journal)
- `Newspaper` (example article http://lobid.org/nwbib/HT001387709 contained in http://lobid.org/nwbib/HT001387709)
- `EditedVolume`
- `Festschrift`
- Also `Book` where it currently isn't shown (example: http://lobid.org/nwbib/HT018568810 with contained article http://lobid.org/nwbib/HT018592576)
- maybe others...

**Comment by acka47** [comment]
`inSeries` -> `series` and `volumeIn`->`multiVolumeWork` are easier to handle than `containedIn`. You only have to look for subordinated resources pointing to a resource with these properties when the resource in question is a `Series` resp. a `MultiVolumeBook`.

**Comment by dr0i** [comment]
New data with index profile set to `not_analyzed` deployed to staging.

**Comment by fsteeg** [comment]
Deployed to staging, see:

http://test.lobid.org/nwbib/HT009821451
http://test.lobid.org/nwbib/HT018486420
http://test.lobid.org/nwbib/HT014974933
http://test.lobid.org/nwbib/HT015131678
http://test.lobid.org/nwbib/HT017306644
http://test.lobid.org/nwbib/HT001387709

**Comment by acka47** [comment]
Here also a series example: http://test.lobid.org/nwbib/HT018346684

**Comment by acka47** [comment]
Lookes very good! +1

**Comment by fsteeg** [comment]
The subordination restriction was not considered in the facets.

Deployed a fix to staging, see query linked from http://test.lobid.org/nwbib/HT018346684

But there's still an issue: if we come from such a link, and set facets, there is no hint in the UI about the superordination query. We used to have the `Überordnung` advanced search for that. Should that basically be replaced by the three new fields?

**Comment by fsteeg** [comment]
Deployed a suggested solution for the issue described in https://github.com/hbz/nwbib/issues/126#issuecomment-134991235 to staging: add an advanced search option to display the current subordination restriction. The displayed string is the full Elasticsearch field query, so I named the new option `Expertensuche`. See e.g. query linked from http://test.lobid.org/nwbib/HT018346684.

**Comment by acka47** [comment]
> But there's still an issue: if we come from such a link, and set facets, there is no hint in the UI about the superordination query. We used to have the `Überordnung` advanced search for that. Should that basically be replaced by the three new fields?

I am not sure whether this solution is the way to go. I suggest for the start not to show the query at all, maybe it isn't that important for customers to have the info in this case. 
If they want it, we may also try a solution based on HTTP header as imagined for https://github.com/hbz/nwbib/issues/130#issue-102091367...

**Comment by fsteeg** [comment]
But consider a usage workflow like this: on http://test.lobid.org/nwbib/HT009821451 click on `91 Beiträge`, then use the `Regionen und Orte` facet to select `Rheinland`. We have 2 hits. Without the new advanced search option, the UI only indicates that facet, it looks exactly [like this](http://test.lobid.org/nwbib/search?nwbibspatial=http%3A%2F%2Fpurl.org%2Flobid%2Fnwbib-spatial%23n03), but with 2 hits only. I don't think that's understandable.

I don't understand the part about the HTTP header in this context.

**Comment by acka47** [comment]
Now I really understand the problem. Let's talk tomorrow. I will call you.

**Comment by fsteeg** [comment]
We decided offline that we should try to add a notice about the restriction to the area showing the number of results, using the superordination title, instead of the new advanced search option.

**Comment by fsteeg** [comment]
Deployed to staging, see links from:

http://test.lobid.org/nwbib/HT009821451
http://test.lobid.org/nwbib/HT018486420

**Comment by acka47** [comment]
I think this is a good solution. I'd chang eone thing, though, and put the number of hits before the "Titel"/"Beiträge". E.g.: "91 Beiträge in: Altenberger Blätter, zeige 1 bis 10". This would make it even shorter.

**Comment by fsteeg** [comment]
Deployed tweaked label to staging, see links from:

http://test.lobid.org/nwbib/HT009821451
http://test.lobid.org/nwbib/HT018486420

**Comment by acka47** [comment]
+1 Let's keep it like that for now and ask customers what they think about it.

**Comment by fsteeg** [comment]
Deployed to production, closing. See links from:

http://lobid.org/nwbib/HT009821451
http://lobid.org/nwbib/HT018486420
