### ISSUE TITLE
Access-restricted ebooks as "fulltextOnline"

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#127]
There are also links to ebooks that are only accessible from within certain IP ranges in the RDF (property `lv:fulltextOnline`). The NWBib UI should use appropriate wording so that people won't expect actually being able to access the fulltext.

From a customer mail from 2015-08-19:

> Mittlerweile sind ja nicht nur frei verfügbare elektronische Dokumente in der NWBib enthalten, sondern auch E-Books, die wir zwar in die NWBib aufnehmen, die aber nur auf den Lesesaalrechnern der DNB im Volltext anzuschauen sind, da sie nicht in NRW erschienen sind. Z.B. die E-Books des Autors Werner Balhauff. In der alten NWBib ist der Link ja mitten in der Titelaufnahme mit der neutralen Bezeichnung „Externer Link“. In der neuen NWBib ist der Link ja rechts oben abgesetzt, was ja auch übersichtlicher ist. Aber könnte man die Überschriften etwas neutraler formulieren:  Statt „online verfügbar“ lieber „Online-Ressource“, und statt „Volltext“ lieber „Link“. Denn sonst würden wir in manchen Fällen mehr versprechen als wir halten können. Was meinen Sie?

**Comment by fsteeg** [comment]
Deployed to staging: http://test.lobid.org/nwbib/HT018523444

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
Deployed to production, closing. See: http://lobid.org/nwbib/HT018523444
