### ISSUE TITLE
Show subject search term in search field

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#128]
Currently, the search term for a subject field is displayed in the subject facet (after the query was submitted). Customers want the term to be shown in the search field with search parameter "Schlagwort".

Thus, we will have to differentiate between `?subject=` searches with GND URIs (to be shown in the subject facet) and `?subject=` searches with strings (to be shown in the search field.

**Comment by fsteeg** [comment]
Deployed to staging, see: http://test.lobid.org/nwbib/search?subject=Bauvorhaben

The URI idea didn't quite work out and is incompatible with out future plans for the subject labels, which probably won't be URI-based in the future, see https://github.com/hbz/lobid/issues/84 and related issues.

Instead, I've implemented it this way: effectively, if coming from the advanced search form, you get the advanced search form above the search results, else only the facets are used.

Some technical details: The `q` parameter is used as an alias for `word`, marking the simple search, while `word` is used from the advanced search. If `q` and `location` (the other simple search triggered from the index page) are empty, use the advanced search form, else simple.

From my testing this seems to work, but some additional testing of different usages of advanced search and facets before deploying to production would probably make sense.

**Comment by acka47** [comment]
With the proposed solution the search term is also shown in the subject facet (here: "Bauvorhaben"). This  should not be the case. We should follow a strict separation here: Strings to the search field and authority resources to the facet. (Otherwise we would have to select all authority resources containing the search string in prefered or alternate name in the facet. (This would be in this case up to seven resources, see http://lobid.org/subject?name=bauvorhaben.)

**Comment by fsteeg** [comment]
How should I handle literals on `nwbibspatial` queries then? e.g. http://lobid.org/nwbib/search?nwbibspatial=Overath. Here, like with literal subjects, the facet is active. There is currently no `nwbibspatial` advanced search.

**Comment by fsteeg** [comment]
Added a `nwbibspatial` advanced search option as a suggested solution.

Deployed to staging, see:

http://test.lobid.org/nwbib/search?subject=Bauvorhaben
http://test.lobid.org/nwbib/search?nwbibspatial=Marsberg

**Comment by fsteeg** [comment]
Redeployed after offline discussion, `nwbibspatial` literals in facet, as they are a controlled vocabulary:

http://test.lobid.org/nwbib/search?subject=Bauvorhaben
http://test.lobid.org/nwbib/search?nwbibspatial=Marsberg

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
Deployed to production, closing. See:

http://lobid.org/nwbib/search?subject=Bauvorhaben
http://lobid.org/nwbib/search?nwbibspatial=Marsberg
