### ISSUE TITLE
Enable combination of multiple libraries in holdings filter

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#129]
The libraries should be combined with OR.

**Comment by fsteeg** [comment]
Deployed to staging, see: http://test.lobid.org/nwbib

**Comment by acka47** [comment]
Here, everything is too slow for me. The loading and reloading of the facet as well the loading of the result list when I select a facet.

Also I think it would make sense to somehow group the libs under the location label so that I can select als libraries in Bochum by cklicking on "Bochum".

**Comment by acka47** [comment]
Closing this one. Made another ticket for grouping libraries in one location, see #137.
