### ISSUE TITLE
Enable paging detail views in search list and favorites

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#130]
Customers request a feature to page through the detailed title views of a certain query [UPDATE: and the favorites list]. Somehow we will need to retain information about the query a resource was called from. There are at least two approaches to this:

1. We may do this by using the HTTP referer (e.g. `Referer: http://lobid.org/nwbib/search?location=&q=b%C3%B6cke` for resource http://lobid.org/nwbib/BT000105325) 
2. We could fall back to the paging mechanism, e.g. when I click on "Knuffige Böcke, urige Sauen." in http://lobid.org/nwbib/search?location=&q=b%C3%B6cke, the URL http://lobid.org/nwbib/search?location=&q=b%C3%B6cke&size=1&from=4 is called which should then deliver the detail view and not a list with one result. (If we chose this approach we will have to keep in mind that result lists for a query change over time.)

**Comment by fsteeg** [comment]
Deployed to staging, see pager at bottom of details view after a search, e.g.
http://test.lobid.org/nwbib/search?q=ehrenfeld

Some technical details:

Store hbz IDs and URL of the last result list in the session. Store previous and next hbz ID on access of details view in the session. Use all three to create previous and next pager links and
link to last result list at the bottom of the details view.

Large data (previous and next ID for each ID, the list of IDs in the last search result) is not stored in the session directly (too large for the session), but in the cache, using a unique session ID. Small data (current `previous` and `next` ID, URL to the last search) are stored directly in the session.

To get correct pagination in the details view, individual detail pages are removed from the cache when they are part of a new search result, but stay cached when paging back and forth.

**Comment by fsteeg** [comment]
Deployed UI changes based on our offline discussion to staging, see pager at top of details view after a search, e.g. http://test.lobid.org/nwbib/search?q=ehrenfeld

Leaving assignment as is (Merkliste, functional issues), but could you review the UI change @acka47?

**Comment by acka47** [comment]
I like it better now. Is it possible to only put the link under "letzten Trefferliste"?.

**Comment by fsteeg** [comment]
Not with the current UI elements (only the link is rendered as that round button).

**Comment by fsteeg** [comment]
Deployed support for favorites and fixes for caching issues to staging: http://test.lobid.org/nwbib

**Comment by acka47** [comment]
Looks good. Could you adjust the text in the middle to "Treffer 3 von 5 in der Merkliste" for favorites?

**Comment by fsteeg** [comment]
Deployed label adjustment for favorites to staging: http://test.lobid.org/nwbib/stars

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
Deployed to production, closing. See:

http://lobid.org/nwbib/search?q=ehrenfeld
http://lobid.org/nwbib/stars
