### ISSUE TITLE
Wrong behaviour when clicking hyphenated 

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#131]
When clicking on `Raumsystematik: Köln-Longerich` in http://lobid.org/nwbib/HT016911934 I get a list of results (http://lobid.org/nwbib/search?nwbibspatial=K%C3%B6ln-Longerich) including hits only for "Köln". 

We will have to correct this as only hits for "Köln-Longerich" should be served. A phrase search currently isn't the solution: http://lobid.org/nwbib/search?nwbibspatial=%22K%C3%B6ln-Longerich%22

**Comment by acka47** [comment]
Another example ("Düsseldorf-Bilk"): http://lobid.org/nwbib/HT018572150 & http://lobid.org/nwbib/search?nwbibspatial=D%C3%BCsseldorf-Bilk

**Comment by fsteeg** [comment]
Deployed to staging, see:

http://test.lobid.org/nwbib/search?nwbibspatial=K%C3%B6ln-Longerich
http://test.lobid.org/nwbib/search?nwbibspatial=D%C3%BCsseldorf-Bilk

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
Deployed to production, closing. See:

http://lobid.org/nwbib/search?nwbibspatial=K%C3%B6ln-Longerich
http://lobid.org/nwbib/search?nwbibspatial=D%C3%BCsseldorf-Bilk
