### ISSUE TITLE
Add thesis information

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#132]
Since https://github.com/hbz/lobid/issues/178 we have a new field with `thesisInformation` in the data for most resources of type `bibo:Thesis`. Example http://lobid.org/nwbib/HT018645839:

```
{
  "@graph" : [ {
    "@id" : "http://lobid.org/resource/HT018645839",
    "@type" : [ "http://purl.org/dc/terms/BibliographicResource", "http://purl.org/ontology/bibo/Book", "http://purl.org/ontology/bibo/Thesis" ],
    "creator" : "http://d-nb.info/gnd/1071744127",
    "issued" : "2015",
    "title" : "Eine autofreie Innenstadt für Münster",
    "otherTitleInformation" : "Voraussetzungen und Maßnahmen",
    "thesisInformation" : "Zugl., Münster (Westfalen), Univ., Bachelor-Arb., 2013",
  } ]
}
```

We should add this field to the NWBib HTML view, I suggest right after publisher/Verlag.

**Comment by acka47** [comment]
Many thesises (~ one quarter of all thesises) don't have this field.

Other examples with this field:

- http://lobid.org/resource/HT016713698: "Zugl., Münster (Westf.), Univ., Diss., 2008/09 u.d.T.: Harding, Elizabeth: Landsässige Ritterschaften im Nordwesten des Alten Reiches"
- http://lobid.org/resource/HT003428601: "Dortmund, Univ., Diss., 1988"
- http://lobid.org/resource/HT010735207 "Bonn, Univ., Diss., 1999"
- http://lobid.org/resource/HT016591804 "Zugl., Dortmund, Techn. Univ., Diss., 2010"
- http://lobid.org/resource/HT015440982 "Vollst. zugl., Bochum, Univ., Diplomarb., 2007" (Whatever that means)
- http://lobid.org/resource/HT009632116 "Dortmund, Univ., Diplomarbeit, 1998"

We may think about omitting the leading "Zugl." in future transformations.

**Comment by fsteeg** [comment]
Deployed to staging, see:

http://test.lobid.org/nwbib/HT003428601
http://test.lobid.org/nwbib/HT018645839

**Comment by acka47** [comment]
+1 I think this is ok for the start and may even work as a permanent solution.

**Comment by fsteeg** [comment]
Deployed to production, closing. See:

http://lobid.org/nwbib/HT003428601
http://lobid.org/nwbib/HT018645839
