### ISSUE TITLE
Adjust some labeling

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#134]
As requested by customers via mail today.

- [x] For series and journals that have other resources as parts show the link as "Bände - x zugehörige Bände". Examples: http://lobid.org/nwbib/HT015563767 & http://lobid.org/nwbib/HT009821451
- [x] For articles, add an "In" as label for the link to the superordinated resource (After the "Quelle" field). Examples: http://lobid.org/nwbib/HT017574738 & http://lobid.org/nwbib/HT018730167 

We will discuss on the mailing list whether using "Hochschulschrift" instead of "Abschlussarbeit" really makes sense.

**Comment by fsteeg** [comment]
Deployed to staging, see:

http://test.lobid.org/nwbib/HT015563767
http://test.lobid.org/nwbib/HT009821451

http://test.lobid.org/nwbib/HT017574738
http://test.lobid.org/nwbib/HT018730167

**Comment by acka47** [comment]
Looks good. Check. Before closing this I have another one: 

- [ ] Use "Von" statt "In" for volume descriptions. E.g. http://test.lobid.org/nwbib/HT017898225 & http://test.lobid.org/nwbib/HT017671721 (as requested by customers.

From the mail:

> Bei Bänden von Schriftenreihen, mehrbändigen Werken und Stücktiteln von Zeitschriften möchten wir vorschlagen, die Angabe der Reihe, des mehrb. Werkes oder der Zeitschrift einzuleiten mit "Von" und nicht mit "In", denn direkt oberhalb steht ja jetzt die Bandzählung, z.B. bei
> http://lobid.org/nwbib/HT016912901
> also,    Band    6
>               Von      Römerlager in Westfalen
> Analog die Beispiele
> http://lobid.org/nwbib/HT017898225
> http://lobid.org/nwbib/HT017671721

**Comment by fsteeg** [comment]
Deployed to staging, see:

http://test.lobid.org/nwbib/HT017898225
http://test.lobid.org/nwbib/HT017671721

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
Deployed to production, closing. See:

http://lobid.org/nwbib/HT017898225
http://lobid.org/nwbib/HT017671721
