### ISSUE TITLE
Don't show holdings information for online resources with fulltext link

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#135]
Reported by customers on 2015-09-03:

> Unverständlich ist uns, warum bei einer elektr. Ressource die Karte und Standorte mit Bibliotheken angezeigt wird. Zwar ist für Münster auch für elektr. Ressourcen ein Lokalsatz angehängt und für den Standort Münster könnte ich das noch nachvollziehen. Aber in etlichen Fällen tauchen Standorte/Bibliotheken auf, die ich mir nicht erklären kann, weil in der alten NWBib dazu kein weiterer Bestand außer 6 angezeigt wird, z.B.
> http://lobid.org/nwbib/ZDB2830721-5

**Comment by fsteeg** [comment]
Duplicate of #92 (if I understand correctly), closing.
