### ISSUE TITLE
Some partOf's not shown/found for a series

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#136]
Short version:

- Click on "In	Schriften des NS-Dokumentationszentrums der Stadt Köln" in http://lobid.org/nwbib/HT007499897 ("Die Macht der Worte")
- You are now in the superordinated resource http://lobid.org/nwbib/HT006514951. Then click on "Enthält	17 Titel" and expand list to 25 results view
- Search for "Die Macht der Worte" and you won't find it although the system "knows" that htis one is one of the volumes of HT006514951.

Reported by customers today:

> Bei der beteiligten Reihe oben scheint sowieso etwas nicht zu stimmen.
http://lobid.org/nwbib/HT006514951
In der neuen NWBib sind 17 Bände mit der Reihe verknüpft, in der alten NWBib sind es 21. 

Indeed, there are actually 26 volumes linked to the series in the old NWBib. Here are some examples of the nine resources that aren't shown when clicking on "Enthält	17 Titel" in http://lobid.org/nwbib/HT006514951:

- http://lobid.org/resource/HT007499897/about
- http://lobid.org/resource/TT001990541/about
- http://lobid.org/resource/HT006563770/about
- http://lobid.org/resource/HT006425397/about

The underlying data seems ok and, oddly, the reverse link is shown in the NWBib volume description, e.g. http://lobid.org/nwbib/HT007499897 or http://lobid.org/nwbib/HT006563770

**Comment by fsteeg** [comment]
Fix: Don't restrict subordination queries to NWBib set:

- Not all subordinations are marked as NWBib members, so the set restrictions resulted in missing results
- Also rename `series` label since we now have resources with all three types of subordination, which resulted in identical labels

Deployed to staging, see:

http://test.lobid.org/nwbib/HT006514951
http://test.lobid.org/nwbib/HT001387709

**Comment by acka47** [comment]
> ... since we now have resources with all three types of subordination

Wasn't this already the case before this change.

Anyway, +1.

**Comment by fsteeg** [comment]
> Wasn't this already the case before this change.

No, looks like the resources associated with `multiVolumeWork` and `series` are not `collectedBy` NWBib, see: http://lobid.org/nwbib/HT001387709 (vs. http://test.lobid.org/nwbib/HT001387709).

As agreed offline, we will wait with production deployment for stakeholder communication.

**Comment by acka47** [comment]
+1 Please deploy to production so that we have a basis for discussion on the mailing list.

**Comment by fsteeg** [comment]
Deployed to production, closing. See:

http://lobid.org/nwbib/HT006514951
http://lobid.org/nwbib/HT001387709
