### ISSUE TITLE
Link to super-ordinated resource missing

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#138]
See the examples http://lobid.org/nwbib/HT018290299, http://lobid.org/nwbib/HT017500124, http://lobid.org/nwbib/HT018483380. Two volume numbers are associated with only one link, the other link to a super-ordinated resource is not shown. We will have to adjust this so that the links to series and multi-volume work are displayed separately with the associated volume number.

**Comment by fsteeg** [comment]
Deployed to staging, see:

http://test.lobid.org/nwbib/HT018290299
http://test.lobid.org/nwbib/HT017500124
http://test.lobid.org/nwbib/HT018483380

Fixing this required a solution that pulls the superordination and numbering into a single row (see 40b1983c69aa19a90c5f655513242041a4871e5b for details), which was also requested by stakeholders (in NWBib mail UP, 2015-09-04).

**Comment by acka47** [comment]
+1 I think the solution is good and I'm curious what stakeholders will think about it. Please deploy to production and I will write a mail to the list next week.

**Comment by fsteeg** [comment]
Deployed to production, closing. See:

http://lobid.org/nwbib/HT018290299
http://lobid.org/nwbib/HT017500124
http://lobid.org/nwbib/HT018483380
