### ISSUE TITLE
Explore map based facet for coverage

### ISSUE THREAD

**Issue by fsteeg** [hbz/nwbib#139]
To facet over the `coverage` values, we want to experiment with a map for visualization and selection of regions.

**Comment by fsteeg** [comment]
Deployed to staging: http://test.lobid.org/nwbib/search?q=wandern

**Comment by acka47** [comment]
This already looks great! Generally, the UI can stay like this IMO. I would like to see two improvements:

- When choosing on an area, the search results should adjust accordingly to only show results about places in the chosen area. (This would mean that you don't need the "Titel mit Bezug zu diesem Ort filtern" popup in the end as chosing an area or place always results in this behaviour.)
- The search term (in your example "andern") isn't passed though when I click on a single place and on "Titel mit Bezug zu diesem Ort filtern".

Other thoughts:
- At first the colouring of the bubbles isn't clear but when playing around with it a bit I got it that it is about numbers of places (and not bibliographic resources) in this bubble.
- It might be nice to show how many resources a click on the filter would result in.

**Comment by fsteeg** [comment]
Deployed to staging with two changes:

* Consider current query parameters in location links (actual filtering based on the location)
* Show number of results in pin hover, popup, and size (use small, medium, or large icon)

See: http://test.lobid.org/nwbib/search?q=wandern

Some thoughts about your suggestion of an area search and removing the popup:

* This would be a major change: the current implementation only uses the `subjectLocation` points, creates map markers for each point, and leaves the rest basically to a marker cluster plugin used with leaflet, the mapping framework. 
* It would be restrictive to disable the drill down / zoom in functionality altogether. Combining drill down and area search could be tricky: when do we want to keep zooming in, when trigger an area search.
* The current final zoom-in + popup is useful to see what place the marker is about. Since we don't have the labels at this point (since we facet over the `subjectLocation` field), we actually need the map itself to see what place the marker is about, and small villages will only have labels when zoomed in (and zoomed in so far, the back link in the popup is very useful).

**Comment by acka47** [comment]
As discussed on the phone, we had misunderstandings. My suggestion ist to leave the actual map navigation as is but adjust the result list with every click on an area by applying the polygon shown on the map as filter.

**Comment by fsteeg** [comment]
Deployed to staging with these changes:

* Support area search (directly searching on a cluster click doesn't work nicely, because a search requires a reload, and after a reload the map shows different content than the previous map, so instead a popup opens offering area search or zooming in. I think this makes all available navigation modes very accessible and self-explanatory).
* Add `Orte` to the cluster icons to avoid the misunderstanding you mentioned of titles vs. places.
* Tweak the chosen cluster marker color for the size of places, so we actually get the high-frequency red icons on common searches (e.g. http://test.lobid.org/nwbib/search?q=wandern).
* Fix issues with map links resulting in zero results (e.g. for clusters of two points).

**Comment by acka47** [comment]
This is better. Klicking through bubbles is more time-consuming now as you always have to choose whether to zoom or to search. Using +/- or the mouse wheel to zoom and only ckicking on a bubble to search is a good way, though, to circumvent the popups when they are not necessary.

Generally, I am not that fond of the line with "Titel mit Bezug zu: " showing the geo filter. Personally, i often overlook it and would be happy if the area or places chosen for filtering would be highlighted on the map. (This would also be nice when clicking on the map on the start page.) However, this is a different issue we should open if we agree on this.

Neonetheless. When I finally choose a filter by clicking "Titel mit Bezug zu x Orten filtern", the result list reloads correctly but the map shows a rather random cluster and not the one I chose as filter. Example: http://tinyurl.com/nwyqkq9. In this, I filtered by two places around Siegen but the map shows a cluster with 3 places and one individual place. This is rather irritating. 

As far as I understand you don't have any control about the clusters being shown when a specific area with a specific zoom is chosen. This might work for building an intuitive UI...

**Comment by fsteeg** [comment]
We don't have the scroll wheel zooming enable (also in the items map) because it makes it harder to scroll in the page (suddently zooms when entering the map area). With just the buttons and manual panning navigation is cumbersome. I actually like the explicit choice of search or zoom at every step. Perhaps this is a case where we could await user feedback?

As we discussed offline, the seemingly random clusters on the filtered map are due to the different `coverage` data on the new result set, which can contain multiple values/locations.

Other than that, there is one issue: visualize the currently filtered polygon in the map. Right?

I'll look into this, and I don't think we need a separate issue.

**Comment by fsteeg** [comment]
Deployed to staging with two changes:

* Show current `location` query parameter as polygon on map
* Highlight spatial label in same color as current map polygon

See http://test.lobid.org/nwbib

**Comment by fsteeg** [comment]
Deployed one more minor change:

Change default page size from 10 to 15 results. With the new coverage map, this yields a more balanced view, see: http://test.lobid.org/nwbib/search?q=wandern

**Comment by acka47** [comment]
We are nearly there to present it to stakeholders. I see one last problem, though. Example:

- Clicking on [Kreis Mettmann](http://test.lobid.org/nwbib/search?location=Kreis%20Mettmann|51.31,7.17+51.31,7.14%2051.31,7.13%2051.30,7.12%2051.30,7.12%2051.30,7.11%2051.29,7.10%2051.28,7.10%2051.28,7.08%2051.26,7.06%2051.26,7.06%2051.26,7.04%2051.25,7.03%2051.25,7.02%2051.24,7.02%2051.24,7.02%2051.24,7.04%2051.23,7.04%2051.23,7.05%2051.22,7.03%2051.21,7.05%2051.19,7.03%2051.19,7.03%2051.17,6.99%2051.17,6.98%2051.17,6.96%2051.16,6.96%2051.15,6.95%2051.15,6.96%2051.14,6.96%2051.15,6.97%2051.14,6.98%2051.14,7.00%2051.14,7.00%2051.12,6.99%2051.11,7.00%2051.11,6.99%2051.08,6.99%2051.07,6.97%2051.07,6.96%2051.07,6.95%2051.07,6.94%2051.08,6.93%2051.08,6.92%2051.06,6.90%2051.07,6.86%2051.08,6.85%2051.09,6.85%2051.10,6.88%2051.11,6.88%2051.11,6.88%2051.13,6.86%2051.13,6.86%2051.13,6.86%2051.13,6.88%2051.13,6.89%2051.12,6.90%2051.13,6.92%2051.13,6.92%2051.14,6.93%2051.14,6.92%2051.14,6.92%2051.16,6.89%2051.16,6.90%2051.17,6.90%2051.17,6.90%2051.18,6.91%2051.19,6.91%2051.19,6.92%2051.19,6.92%2051.20,6.91%2051.20,6.90%2051.21,6.91%2051.21,6.88%2051.22,6.87%2051.23,6.87%2051.23,6.88%2051.23,6.87%2051.24,6.87%2051.24,6.88%2051.24,6.88%2051.24,6.89%2051.24,6.90%2051.24,6.91%2051.24,6.92%2051.24,6.93%2051.24,6.93%2051.25,6.93%2051.25,6.93%2051.26,6.93%2051.27,6.93%2051.26,6.93%2051.27,6.94%2051.28,6.94%2051.27,6.92%2051.28,6.91%2051.27,6.90%2051.26,6.89%2051.27,6.89%2051.27,6.88%2051.27,6.88%2051.27,6.87%2051.28,6.85%2051.28,6.85%2051.28,6.84%2051.28,6.83%2051.28,6.82%2051.28,6.81%2051.28,6.80%2051.31,6.80%2051.31,6.81%2051.31,6.81%2051.32,6.82%2051.32,6.81%2051.33,6.80%2051.34,6.81%2051.34,6.80%2051.35,6.81%2051.35,6.81%2051.35,6.82%2051.35,6.83%2051.35,6.84%2051.36,6.85%2051.36,6.85%2051.36,6.86%2051.36,6.87%2051.36,6.87%2051.36,6.88%2051.37,6.89%2051.36,6.92%2051.35,6.92%2051.35,6.93%2051.35,6.92%2051.35,6.93%2051.35,6.95%2051.35,6.96%2051.36,6.98%2051.35,6.98%2051.36,6.99%2051.36,7.01%2051.36,7.01%2051.36,7.02%2051.36,7.04%2051.37,7.04%2051.36,7.05%2051.37,7.08%2051.37,7.08%2051.37,7.09%2051.37,7.09%2051.37,7.10%2051.38,7.10%2051.38,7.12%2051.38,7.12%2051.38,7.12%2051.38,7.13%2051.38,7.14%2051.38,7.15%2051.37,7.16%2051.35,7.15%2051.35,7.15%2051.34,7.15%2051.33,7.15%2051.33,7.17%2051.31,7.17) on the start page
- Then clicking on the place east of Bielefeld (Blomberg) and "1 Titel mit Bezug zu diesem Ort filtern"
- The result list doesn't show the one title referencing Mettmann AND Blomberg but 149 titles referencing Blomber alone.

**Comment by fsteeg** [comment]
Deployed to staging with two changes:

* Don't filter `coverage` facet options based on current value. This makes the `coverage` facet behave like our other facets: The facets show their currently selected value but don't filter their options based on their own value, but on other facets or query parameters, to enable switching values for that facet. The previous behaviour was responsible for the issue reported in https://github.com/hbz/nwbib/issues/139#issuecomment-144719328 (basically: wrong hit numbers or wrong search results. This should no longer happen with the new behaviour).
* Draw circle on map if precision is too low for a polygon. Polygon with too low precision (one decimal digit) looks broken. The low precision is required for the few cases where we have too many coordinates to pass them with high precision as an HTTP query parameter (e.g. `Hochsauerlandkreis`).

See: http://test.lobid.org/nwbib/search?q=wandern

**Comment by acka47** [comment]
+1 Please deploy so stakeholders can play around with it and we can discuss further adjustments.

**Comment by fsteeg** [comment]
Deployed to production, closing.

See http://lobid.org/nwbib/search?q=wandern

@dr0i As the code is not yet reviewed and merged, I did not merge into master in the `nwbib` repo on `quaoar1`, but instead switched that repo to `issue-139-map` and rebased that locally on master. So in case we need to revert the facet map, we can easily checkout master and redeploy `nwbib` on `quaoar1`.
