### ISSUE TITLE
Quotation marks escaped in heading of volume list

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#140]
Go to http://lobid.org/nwbib/HT018576758 and click on "Enthält	3 Beiträge" and then look on the heading which includes ` &quot;`.

**Comment by fsteeg** [comment]
Fix deployed to staging, follow link from http://test.lobid.org/nwbib/HT018576758

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
Deployed to production, closing. Follow link from http://lobid.org/nwbib/HT018576758
