### ISSUE TITLE
Show creators & contributors without GND ID

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#142]
After https://github.com/hbz/lobid/issues/154, we now have person names without GND ID in fields `creatorName` and `contributorName`. These should also be shown in NWBib along the creators/contributors with GND ID.

Examples:

http://lobid.org/nwbib/HT018617137
http://lobid.org/nwbib/HT018700720 (which is not a NWBib resource but acts as a good example anywa)

**Comment by fsteeg** [comment]
1) Should we always show both?

2) Only `contributorName` and `creatorName`? What about `contributorLabel`? http://lobid.org/resource/HT018617137?format=full has only `contributorLabel`, no `contributorName`, http://lobid.org/resource/HT018700720?format=full has both `contributorName` (1 value) and `contributorLabel` (4 values).

**Comment by fsteeg** [comment]
Deployed to staging after @acka47 answered my questions offline (both: yes), see:

http://test.lobid.org/nwbib/HT018617137
http://test.lobid.org/nwbib/HT018700720

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
Deployed to production, closing. See:

http://lobid.org/nwbib/HT018617137
http://lobid.org/nwbib/HT018700720
