### ISSUE TITLE
Insecure connection with HTTPS due to non-HTTPS map tile server

### ISSUE THREAD

**Issue by fsteeg** [hbz/nwbib#143]
See: https://lobid.org/nwbib/HT018263803 vs. http://lobid.org/nwbib/HT018263803

**Comment by fsteeg** [comment]
Deployed a fix to production, see: https://lobid.org/nwbib/HT018263803

The map is now shown, but we get an insecure connection warning due to mixed insecure content coming from the map tile server (see Javascript console on the page linked abovefor details).

Will rename the issue accordingly and leave it open.

**Comment by acka47** [comment]
Fixed. Closing.
