### ISSUE TITLE
Adjust UI for paging single results

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#145]
As requested by customers (mail by E. Lakomy from 2015-09-28) the arrows for paging detailed result pages should be besides the middle button that says "Treffer x von y in der letzten Trefferliste".

**Comment by fsteeg** [comment]
Deployed to staging: http://test.lobid.org/nwbib/search?q=ehrenfeld

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
Will deploy after https://github.com/hbz/nwbib/pull/147 is merged (ping @dr0i).

**Comment by dr0i** [comment]
Merged.

**Comment by fsteeg** [comment]
Deployed to production, closing. See http://test.lobid.org/nwbib/search?q=ehrenfeld
