### ISSUE TITLE
Use boxes instead of drop downs for facets

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#146]
As discussed on the phone today we should try to
- use boxes instead of drop downs for the different facetting options
- Sort filters by number of hits they result in and only show the five first filters.
- Expand the result list to show 25 results by default.

**Comment by fsteeg** [comment]
Deployed to staging, see: http://test.lobid.org/nwbib/search?q=wandern

I tried to use actual boxes, but simple lists looked cleaner.

**Comment by acka47** [comment]
Looks good with the lists. While it's ok for the other filters to show all elements when expanding, we at some points get very long lists for "Schlagwörter" and "Sachgebiete". Thus, I'd propose a different behaviour for these: Instead of a button "Zeige alle Sachgebiete/Schlagwörter" the button should be named "Zeige mehr Sachgebiete/Schlagwörter". When one clicks on it, you will see 15 more entries with another "Zeige mehr Sachgebiete/Schlagwörter" button at the end.

**Comment by fsteeg** [comment]
Deployed to staging: Show more facet values in steps of 15 items.

See: http://test.lobid.org/nwbib/search?q=wandern

**Comment by acka47** [comment]
+1 I think we can deploy this as is and talk about the details with stakeholders.

**Comment by fsteeg** [comment]
Deployed to production, closing. See: http://lobid.org/nwbib/search?q=wandern
