### ISSUE TITLE
Label "inSeries" row as "Erschienen als"

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#148]
As proposed by NWBib stakeholder (mail by U. Pflughaupt from 2015-09-29):

> http://lobid.org/nwbib/HT018290299
Z.Z. „In“, aus Münster kam der Vorschlag „Zu“, wie wäre es mit „Erschienen als“ ? (Für TA von Aufsätzen müsste natürlich „In“ bestehen bleiben), also
Erschienen als        Biographien und Materialien Band 2
Erschenen als         Schriften des …. Köln Band 19

**Comment by fsteeg** [comment]
Deployed to production, closing. See: http://lobid.org/nwbib/HT018290299
