### ISSUE TITLE
Remove holdings + map for journal articles

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#150]
Reported by NWBib stakeholders on 2015-09-29 (mail by U. Pflughaupt):

> z.B. http://lobid.org/nwbib/BT000128765
Bei alten TA zu Aufsätzen findet man bisweilen Bestandangaben von kleineren Spezialbibliotheken. Wäre es nicht sinnvoll, bei Aufsätzen Bestandsangaben mit Karte wegzulassen, wie bei Online-Ressourcen, damit die Nutzer nicht denken, dass dieser Aufsatz nur in Solingen im Stadtarchiv sei. Den Link zu den Bestandsangaben der Überordnung gibt es ja oben rechts.

**Comment by fsteeg** [comment]
Deployed to staging, see: http://test.lobid.org/nwbib/BT000128765

**Comment by acka47** [comment]
Looks like this is already deployed to production. Anyway, +1.

**Comment by fsteeg** [comment]
Right, the pull request was already merged when I deployed #195 (same for the bugfix part of #193).

Since these were small fixes, I figured it was OK.

Still: Deployed to production, closing. See: http://lobid.org/nwbib/BT000128765
