### ISSUE TITLE
Subject search with comma gives to much results

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#151]
Reported via email list today by I. Niemann:

>die Schlagwortrecherchen mit Personennamen ergeben in der alten und neuen NWBib z.T. sehr große Unterschiede bei den Trefferzahlen.
Bei der Eingabe in Form [Nachname, Vorname] wird der Personenname nicht als Zeichenkette gesucht.
Die Treffermenge in der neuen NWBib enthält auch Titel, in denen Personen mit gleichlautenden Vor- oder Namennamen in den Schlagwortfeldern vorkommen.
Außerdem gibt es unterschiedliche Trefferzahlen bei der Recherche mit Umlauten.

Examples: 
- [subject search for "Ney, Elisabet"](http://lobid.org/nwbib/search?subject=ney%2C+elisabet) (24 results) vs. [subject search for "Elisabet Ney"](http://lobid.org/nwbib/search?subject=elisabet+ney) (14 results)
- [subject search for "Boehm, Elisabet"](http://test.lobid.org/nwbib/search?subject=Boehm%2C+Elisabet) (95 results) vs. [subject search for "Elisabet Boehm"](http://lobid.org/nwbib/search?sort=newest&subject=Elisabet+Boehm) (1 results)
- [subject search for "Lembcke, Marjaleena"](http://lobid.org/nwbib/search?subject=Lembcke%2C+Marjaleena) (1 result) vs. [subject search for "Marjaleena Lembcke"](http://lobid.org/nwbib/search?subject=Marjaleena+Lembcke) (0 results)

**Comment by fsteeg** [comment]
Deployed to staging, see:

http://test.lobid.org/nwbib/search?subject=ney,+elisabet
http://test.lobid.org/nwbib/search?subject=elisabet+ney

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
Can be deployed after https://github.com/hbz/lobid/pull/246 is merged.

**Comment by fsteeg** [comment]
Deployed to production, closing. See:

http://lobid.org/nwbib/search?subject=ney,+elisabet
http://lobid.org/nwbib/search?subject=elisabet+ney
