### ISSUE TITLE
After filtering by location/polygon the map should reload showing the same map section

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#156]
Currently, after a a filter by map polygon, the result list is updated and the map reloaded to the uppermost zoom level. It would rather be nice to show the same map section with the same zoom level as it wasthe moment one had clicked the "Filter" button.

This is good for two reasons:
- It is more intuitive and people can go ahead zooming and filtering even further from the point they last set a filter
- If I chose a filter using only one or two places, you currently can't see on the map which filter is set as the red polygon is covered by a bubble on the higher level view. See e.g. http://test.lobid.org/nwbib/search?location=2%20Orte%20aus%20Kartenauswahl|51.75499998964369,8.040277753025293+51.8366667162627,8.025555443018675&q=wandern&sort=newest

**Comment by fsteeg** [comment]
Moving comment here from #74.

Also requested by U.P., 2016-02-25:

> durch Rollen des Mausrädchens soweit gezoomt habe, dass ich nur noch die Titel zu einem Ort, z.B. Solingen, habe und auf der Karte anklicke, dann zeigt mir die Trefferliste die 15 Titel zu Solingen an, die Karte springt aber gleichzeitig wieder in die Ausgangsposition. Wäre es nicht besser, sie würde bei Solingen stehen bleiben, sodass ich immer weiß, welche Titel mir jetzt in der Trefferliste angezeigt werden? https://nwbib.de/search?subject=juden+geschichte&location=51.166666662320495%2C7.0833333022892475

**Comment by fsteeg** [comment]
Deployed to staging:

- http://test.nwbib.de/search?location=2%20Orte%20aus%20Kartenauswahl|51.75499998964369,8.040277753025293+51.8366667162627,8.025555443018675&q=wandern&sort=newest
- http://test.nwbib.de/search?subject=juden+geschichte&location=51.166666662320495%2C7.0833333022892475

**Comment by acka47** [comment]
+1
