### ISSUE TITLE
Show links to descriptions

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#158]
We added links to descriptions in the RDF, see https://github.com/lobid/lodmill/issues/729. These should be shown in NWBib under the label "Inhaltsangabe" (probably before field "Inhaltsverzeichnis").

**Comment by fsteeg** [comment]
Deployed to staging: http://test.lobid.org/nwbib/HT018705251

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
Deployed to production, closing. See http://lobid.org/nwbib/HT018705251
