### ISSUE TITLE
Evaluate link resolver usage

### ISSUE THREAD

**Issue by fsteeg** [hbz/nwbib#16]
Direct link from item map into catalogue.

We should discuss this with @heikojansen

**Comment by fsteeg** [comment]
Was implemented in b34de9bd1a612d0d58856d92b0092abb0433fd0f, closing.

**Comment by acka47** [comment]
Actually, a link resolver is something different from what we have implemented. A link resolver not just checks against the holdings of one library via the OPAC but also checks – based on the OpenURL standard – whether the library provides any other access (through a repository, licensed eRessources etc.) to a resource. 

From [Wikipedia](https://en.wikipedia.org/wiki/OpenURL):

> The OpenURL standard is designed to enable linking from information resources such as abstracting and indexing databases \[or regional bibliographies, AP] (sources) to library services (targets), such as academic journals, whether online or in printed or other formats. The linking is mediated by "link resolvers", or "link-servers", which parse the elements of an OpenURL and provide links to appropriate targets available through a library by the use of an OpenURL knowledge base.

Anyway, the first comment on this issue describes what we have implemented (and not what a link resolver does). We can leave this closed until someone asks for actual link resolver usage.
