### ISSUE TITLE
Don't show paging options in UI for directly accessed titles 

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#160]
If I have once used the detailed results paging mechanism(see #130 ), I will also get the paging buttons when I directly access a title via a link, e.g. http://lobid.org/nwbib/BT000096406. The buttons should only be show when clicking through to the details view via a result list.

**Comment by fsteeg** [comment]
Deployed to staging. Steps to reproduce:

- Click some result on http://test.lobid.org/nwbib/search (result: pager)
- Use pager to go forward and backward (result: pager)
- Copy URL, open new tab, paste, and open (result: no pager)

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
Deployed to production, closing. Steps to reproduce:

- Click some result on http://lobid.org/nwbib/search (result: pager)
- Use pager to go forward and backward (result: pager)
- Copy URL, open new tab, paste, and open (result: no pager)
