### ISSUE TITLE
Replace "Autor/in" by "Urheber/in"

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#164]
I suggest replacing the label "Autor/in" by "Urheber/in" as not all entities under `dct:creator` have an author role in relation to the work described. As examples where it doesn't work see http://lobid.org/nwbib/HT018771475, http://lobid.org/nwbib/HT015828173 & http://lobid.org/nwbib/HT018527580.

@fsteeg What do you think? Should I just change it or should we first discuss this on the email list?

**Comment by acka47** [comment]
http://lobid.org/nwbib/HT018771475 looks broken now, see https://github.com/lobid/lodmill/issues/742.

**Comment by fsteeg** [comment]
+1 for "Urheber/in". I think we could just change it and then communicate our reasoning on the list.

**Comment by acka47** [comment]
Ok. I will do it. Cataloguers might not be happy, though. In cataloguing rules, "Urheber" is used for corporations and "Verfasser" for persons... Will address this in the mail to the list.

**Comment by fsteeg** [comment]
In that case, maybe it'd be better to discuss it first.

**Comment by acka47** [comment]
We will get a clear differentiation between corporate bodies as creators and persons as creators with API 2.0. The issue will be solved then. Closing.
