### ISSUE TITLE
Show marcrel:red in HTML

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#165]
After https://github.com/lobid/lodmill/issues/736 some persons aren't contributors anymore but `marcrel:red` (`redaktor` in json). See e.g. http://lobid.org/resource/HT018331662. Currently, they are not shown in NWBib see http://lobid.org/nwbib/HT018331662, thus, `redaktor` has to be added to the template.

**Comment by dr0i** [comment]
Deployed to staging.

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Deployed to production, closing.
