### ISSUE TITLE
Show icons for online resources in result list

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#167]
See https://github.com/lobid/lodmill/issues/730#issuecomment-147994306 where stakeholders are quoted with this requirement:

> Im VK kann man bei einer Trefferliste von Parallelausgaben sofort erkennen, welche der beiden Titel die eRessouce ist. Dieser Titel ist mit einem sprechenden Icon und dem Zusatz „Elektronische Ressource“ versehen. Wir finden diese Anzeige recht übersichtlich und würden uns das für die Trefferliste in der neuen NWBib ebenfalls wünschen http://lobid.org/nwbib/search?location=&q=digitalisierungsstrategie+westfalens. 
Könnte man bei dieser Trefferliste hier beispielsweise zum Icon Publikationstyp „Buch“ eventuell die Medienart „Online“ hinzufügen? Oder ebenfalls im Titel [Elektronische Ressource] ergänzen?

**Comment by fsteeg** [comment]
Instead of a special case for online resources I'd propose:

- Always show the `medium` icon in addition to the `type` in the result list
- Don't add any text to the title

Deployed to staging: http://test.lobid.org/nwbib/search?q=digitalisierungsstrategie+westfalens

**Comment by acka47** [comment]
+1. Please deploy on production and we will see what stakeholders think about it.

**Comment by fsteeg** [comment]
Deployed to production, closing.

See: http://lobid.org/nwbib/search?q=digitalisierungsstrategie+westfalens
