### ISSUE TITLE
Filtering by region doesn't work

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#169]
Example:

- http://lobid.org/nwbib/search?q=trauerseeschwalbe
- Click on bubble and "Titel mit Bezug zu 3 Orten filtern"
- [No results](http://lobid.org/nwbib/search?location=3%20Orte%20aus%20Kartenauswahl|51.766666593030095,6.399999987334013+51.80889998562634,6.396110113710165+51.80060005746782,6.368890050798655&q=trauerseeschwalbe&person=&name=&subject=&publisher=&issued=&medium=&nwbibspatial=&nwbibsubject=&owner=&t=&sort=newest&set=&word=&corporation=&raw=)

**Comment by fsteeg** [comment]
Deployed to staging, see: http://test.lobid.org/nwbib/search?q=trauerseeschwalbe

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
Deployed to production, closing. See: http://lobid.org/nwbib/search?q=trauerseeschwalbe
