### ISSUE TITLE
Show overview at /classification and /register

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#171]
Reported by  @nichtich via email on 2015-10-28:

> die URLs http://lobid.org/nwbib/classification und 
> lobid.org/nwbib/register lieferen Fehler statt vorhandene Systematiken 
> aufzulisten

**Comment by fsteeg** [comment]
Deployed to staging, see:

http://test.lobid.org/nwbib/classification
http://test.lobid.org/nwbib/register

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
Deployed to production, closing.

See:
http://lobid.org/nwbib/classification
http://lobid.org/nwbib/register
