### ISSUE TITLE
Dual use of pictograms

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#174]
Reported by EL on 2015-10-27:

> Beim Durchsehen von Trefferlisten ist nun aufgefallen, dass leider einige Symbole doppelt verwendet werden.  In der Trefferliste http://lobid.org/nwbib/search?location=&q=landeskunde der 4. Treffer „Auslese“ http://lobid.org/nwbib/HT015514475. Hier haben Medienart „Print“ und  Publikationstyp „Zeitschrift“ das gleiche Symbol. Das ist etwas unglücklich. Ebenso ist eine Doppelverwendung bei den Publikationstypen „Konferenzschrift“ und Mehrbändig“ zu finden.

**Comment by fsteeg** [comment]
Deployed to staging, see: http://test.lobid.org/nwbib/search

New icons: Konferenzschrift, Zeitschrift (Publikationstypen), Print (Medientypen).

**Comment by fsteeg** [comment]
Redeployed with new icon for "Print" medium after offline discussion with @acka47.

See http://test.lobid.org/nwbib/search

**Comment by acka47** [comment]
+ 1 BTW, we will have an additional publication type `Report` soon, see https://github.com/hbz/lobid/issues/242.

**Comment by fsteeg** [comment]
Deployed to production, closing. See: http://lobid.org/nwbib/search

New icons: Konferenzschrift, Zeitschrift (Publikationstypen), Print (Medientypen).
