### ISSUE TITLE
Show NRW border on map

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#175]
UP suggested ion 2015-11-03:

> Bei der kartenbasierten  Ortsfacettierung wäre ein deutlicherer Umriss 
> des Landes NRW schön zur Orientierung 

EL responded on same day:

> Wie Frau P. wären wir wohl mit einem Umriss der Landesgrenzen 
> von NRW einverstanden, jedoch nicht ganz so stark betont, zumal je nach 
> Trefferliste nur Teile der Grenze zu sehen wären.

**Comment by acka47** [comment]
We should also try out to completely blank out the NRW environment.

**Comment by fsteeg** [comment]
Deployed to staging, see: http://test.lobid.org/nwbib/search

Completely blanking out the non-NRW map would be possible, but it would cut off labels that begin outside of NRW (e.g. "Osnabrück"). I've restricted zooming out to the NRW border. Together with the border highlighting, I think this is a good solution.

**Comment by acka47** [comment]
+1. BTW, I guess the current version of NWBib isn't very usable for colour-blind people. At some point, we probably should test the UI with respect to colour-blind persons.

**Comment by fsteeg** [comment]
Deployed to production, closing. See: http://lobid.org/nwbib/search
