### ISSUE TITLE
Improve colouring of clusters on facet map

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#176]
Reported by UP on 2015-11-03:

> der Sinn der verschiedenen 
> Farben für die unterschiedlich hohe Zahl von Orten in den Markern 
> erschließt sich nicht wirklich für Nutzer. Von braun zu gelb zu grün zu 
> rot, wieso gerade diese Farben in dieser Reihenfolge? Wie wäre es mit 
> einer einzigen Farbe? Würde man sich nicht dann mehr auf die Zahl der 
> Orte konzentrieren? Auf dem jetzt roten Marker könnte auch einfach „1 
> Ort“ stehen. Die Häuschen sollen dies natürlich bedeuten. Aber ist das 
> einfacher zu verstehen?

EL agrees on same day:

> Die farbigen Punkte der Orte sind eher unübersichtlich. Vielleicht 
> sollte man tatsächlich nur eine einzige Farbe (z.B. Gelb) wählen, die 
> sich natürlich von den roten Markern unterscheiden sollte.  Bei den 
> roten Markern sind wir gern mit „1 Ort“ einverstanden.

**Comment by fsteeg** [comment]
Deployed to staging, see: http://test.lobid.org/nwbib/search

**Comment by acka47** [comment]
+1 (here also with doubts regarding usage by colour-blind persons)

**Comment by fsteeg** [comment]
Deployed to production, closing. See: http://lobid.org/nwbib/search

**Comment by fsteeg** [comment]
Looking at http://lobid.org/nwbib/search?q=braunkohle I think we should swap the red and green (many hits red, single hit green). Reopening.

**Comment by fsteeg** [comment]
Deployed to staging, see:

http://test.lobid.org/nwbib/search?q=braunkohle
http://test.lobid.org/nwbib/search?q=steinkohle
http://test.lobid.org/nwbib/search?q=schiefer
http://test.lobid.org/nwbib/search?q=radwandern
http://test.lobid.org/nwbib/search?q=wandern

**Comment by acka47** [comment]
What about using a pin again for single places to differentiate them from clusters?

**Comment by fsteeg** [comment]
I know no way to display "1 Ort" on a pin (part of the original request).

I also think using the same cluster look is in the spirit of the request (to make it simpler).

**Comment by acka47** [comment]
ok, +1 then.

**Comment by fsteeg** [comment]
Deployed to production, closing. See:

http://lobid.org/nwbib/search?q=braunkohle
http://lobid.org/nwbib/search?q=steinkohle
http://lobid.org/nwbib/search?q=schiefer
http://lobid.org/nwbib/search?q=radwandern
http://lobid.org/nwbib/search?q=wandern
