### ISSUE TITLE
Enable mouse-zoom in facet map

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#177]
EL writes on 2015-11-03:

> Grundsätzlich ist das Facettieren über die Karte sowohl Stück für Stück 
> über die verschiedenen Ebenen bis in die Tiefe hinein möglich, als auch 
> über ein direktes Ansteuern mit Hilfe der Zoomfunktion „+“  und „ –„. 
> Und man kann auch beides gut miteinander kombinieren.  Bestünde hier 
> wohl  die Möglichkeit,  das Zoomen mit „+“  und“ –„  durch die Funktion 
> mit dem Mausrad zu ergänzen – so wie das bei Goggle Maps ebenfalls 
> möglich ist?

**Comment by fsteeg** [comment]
Deployed to staging, see: http://test.lobid.org/nwbib/search?q=wandern

**Comment by acka47** [comment]
+1 I see that mouse-scrolling zoom isn't possible in holdings map. We should better also enable it there for sake of consistency.

**Comment by fsteeg** [comment]
Deployed scroll wheel zooming on items map to staging.

For further consistency, I also made the items map the same height as the coverage map.

See http://test.lobid.org/nwbib/HT018146030

**Comment by acka47** [comment]
+1
> For further consistency, I also made the items map the same height as the coverage map.

Very good.

**Comment by fsteeg** [comment]
Deployed to production, closing. See: http://lobid.org/nwbib/search?q=wandern
