### ISSUE TITLE
UI details

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#178]
A list of UI details reported by UP (2015-10-19, 2015-11-03) and EL (2015-10-26).

- [x] "Regionen" instead of "Regionen/Orte"

> Solange die Ortssuche über die Systematik oben im Menü und über die 
> nicht-kartenbasierte Facettierung nicht funktioniert, sollten da nicht 
> die Begriffe „Orte“  aus den Überschriften rausgenommen werden?
> 

- [x] Adjust language to sungular use for one sub-ordinated resource:

> a – Wenn eine Schriftenreihe nur mit einem einzigen Band verknüpft ist, 
> steht in der Zeile „Serienbände“   „1 zugehörige Serienbände“ z.B. 
> http://lobid.org/nwbib/HT018221619 oder 
> http://lobid.org/nwbib/HT018148146 oder 
> http://lobid.org/nwbib/HT017677665 . Wenn man den Feldeintrag umdrehen 
> würde „zugehörige Serienbände: 1“ , wäre das nicht so unschön. Oder man 
> nennt das Feld „Zugehörige Serienbände“ und der Feldinhalt ist dann nur 
> „1“ oder „23“ oder was auch immer gerade zutrifft. Das gleiche Problem 
> würde ja auch auftauchen, wenn eine Aufsatzsammlung mal nur 1 
> nwbib-relevanten Aufsatz enthielte: „1 Beiträge“ sieht auch nicht schön 
> aus. Aber es ist wahrscheinlich programmiertechnisch nicht möglich, bei 
> der Zahl „1“ im Feld immer den Singular „Beitrag“ oder „zugehöriger 
> Serienband“ hinzuzufügen, nicht wahr?

- [x] "Erschinen als" instead of "In" for volumes:

> B – Sollten Bandaufnahmen zu mehrbändigen Werken nicht auch statt „In“ 
> besser „Erschienen als“ als Feldnamen haben, so wie Bände von 
> Schriftenreihen? Beispiel: http://lobid.org/nwbib/HT017180452 
> http://lobid.org/nwbib/HT017261040

- [x] "Medientyp " instead of "Medienart" in facet

**Comment by fsteeg** [comment]
Deployed to staging, see:

- http://test.lobid.org/nwbib/search?q=wandern ("Regionen" in menu and facet)
- http://test.lobid.org/nwbib/HT018221619 (singular form, also in linked result list)
- http://test.lobid.org/nwbib/HT017180452 ("Erschienen als")
- http://test.lobid.org/nwbib/search?q=wandern ("Medientyp" in facet)
- http://test.lobid.org/nwbib/HT018781126 ("Medientyp" in details)

**Comment by acka47** [comment]
> - http://test.lobid.org/nwbib/search?q=wandern ("Regionen" in menu and facet)

+1

> - http://test.lobid.org/nwbib/HT018221619 (singular form, also in linked result list)

+1 (I see that you also covered articles in edited volumes, e.g. http://test.lobid.org/nwbib/HT018595883)

> - http://test.lobid.org/nwbib/HT017180452 ("Erschienen als")

+1

> - http://test.lobid.org/nwbib/search?q=wandern ("Medientyp" in facet)

+1

> - http://test.lobid.org/nwbib/HT018781126 ("Medientyp" in details)

+1

**Comment by fsteeg** [comment]
Deployed to production, closing. See:

- http://lobid.org/nwbib/search?q=wandern ("Regionen" in menu and facet)
- http://lobid.org/nwbib/HT018221619 (singular form, also in linked result list)
- http://lobid.org/nwbib/HT017180452 ("Erschienen als")
- http://lobid.org/nwbib/search?q=wandern ("Medientyp" in facet)
- http://lobid.org/nwbib/HT018781126 ("Medientyp" in details)
