### ISSUE TITLE
Weekly creation of list of 700n without 078n

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#179]
Customers ask for a monthly list of titles with NWBib classification entries in 700n but without NWBib mark in 078n. @dr0i Can you do this (automatically)?

**Comment by acka47** [comment]
We decided to create such a list each week after the new index was created and let NWBib editors fetch it from the server whenever they want.

**Comment by dr0i** [comment]
Done. At least one time per week http://lobid.org/download/nwbib700Missing078.txt is generated anew.

**Comment by acka47** [comment]
+1 Wrote to the mailing list. Closing.

**Comment by dr0i** [comment]
Stakeholder wrote per Mail to separate the lists by Sigel.

**Comment by dr0i** [comment]
As it seems possible to simply query the data, this should be the preferred way.

**Comment by acka47** [comment]
Yes, here is the query: http://lobid.org/resources/search?q=subject.source.id:%22http\:\/\/purl.org\/lobid\/nwbib*%22+AND+_missing_:inCollection I will suggest NWBib customers to use this.

**Comment by acka47** [comment]
Done with adding some provenance data to the API ( #455) an documenting queries at https://github.com/hbz/nwbib/wiki/Titel-ohne-NWBib-Sortierzeichen-aber-mit-NWBib-Notationen. Closing.
