### ISSUE TITLE
Visualize subjectLocation in resource details view

### ISSUE THREAD

**Issue by fsteeg** [hbz/nwbib#185]
Using the coverage map from the facet, above the items map.

@acka47 would you agree?

**Comment by acka47** [comment]
Sounds good to me. Maybe we should only show the items map when people want to look for items (with a popup or having it collapsed by default.

**Comment by fsteeg** [comment]
After some initial prototyping I'm not so sure this is a good idea. It would certainly require some work, because the use case is quite different, and just reusing the coverage map is rather confusing (visualize 1-5 places about a resource VS use the subjectLocation as a facet).

Moving to backlog. Feel free to close, @acka47.
