### ISSUE TITLE
Collapse function for facets

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#192]
Feedback provided by E.L. on 2015-11-27 via email list:

> Das Ausklappen der Listen funktioniert gut, aber das Einklappen ist etwas umständlich, nämlich über den Browser-Pfeil hin und zurück. Vielleicht könnte man hier nachbessern und eventuell einen  Pfeil neben der  Facettenüberschrift anbringen, wie beispielsweise im Katalog der Universitätsbibliothek Bayreuth. Mit diesem Pfeil könnte man dann auch generell die Facetten einklappen, die nicht interessieren.

**Comment by fsteeg** [comment]
Deployed to staging, see: http://test.lobid.org/nwbib/search?location=&q=radwandern

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
Deployed to production, closing. See: http://lobid.org/nwbib/search?location=&q=radwandern
