### ISSUE TITLE
Problem with subject facet after subject search 

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#193]
Bug report by E.L. on 2015-11-27 via email list:

> Bei der Schlagwort-Facette ist uns Folgendes aufgefallen: Diese Facette scheint gut zu funktionieren. Allerdings nicht, wenn die Trefferliste durch eine „SW-Suche“ generiert wurde.  Hier erscheinen in der SW-Facette absteigend nach Häufigkeit unverhältnismäßig viele Titeltreffer bei den aufgeführten Schlagwörtern -  http://lobid.org/nwbib/search?subject=abfallbeseitigung. Und  das ist nicht nur bei dem Beispiel „Abfallbeseitigung“ so. Gleichgültig mit welchem SW man eine Trefferliste generiert. In der SW-Facette stehen an erster Stelle immer die gleichen SW „Nordrhein-Westfalen“ (13237), Köln (6540), Geschichte (6066) mit immer derselben Trefferzahl. Und klickt man diese Schlagwörter an, erhält man auch keine Titeltrefferliste. Die Verlinkung führt ins Leere.

**Comment by fsteeg** [comment]
A few issues here:

1. It is normal facet behavior that a facet is not restricted by its own selection, i.e. no matter which subject is selected, the most frequent alternative values will always be the same. This is true for all the facets.
2. When we search by subject using a string, not a GND-URI, we don't get a selection in the subject facet. This is one of a few points where the interaction of advanced search and facet search is rocky, and I don't see a sensible solution at this point.
3. Zero hits when selecting a subject facet after a subject strign search: this is a bug. My proposed fix is discarding the string search and give the result for the facet search. Deployed to staging, see: http://test.lobid.org/nwbib/search?subject=abfallbeseitigung

**Comment by fsteeg** [comment]
As mentioned in https://github.com/hbz/nwbib/issues/150#issuecomment-162858198, the bugfix part of this is already deployed to production, see: 
http://lobid.org/nwbib/search?subject=abfallbeseitigung

For the other issue, perhaps a solution related to #194 would be feasible (I will comment there).

**Comment by fsteeg** [comment]
After an offline discussion, @acka47 and I were able to narrow down the actual remaining issue: we want to be able to combine a string based advanced subject search with the subject facet. This is currently not possible because internally, they are both `subject` searches. So the string based advanced subject search should use a different query parameter internally.

**Comment by fsteeg** [comment]
Deployed to staging, see: http://test.lobid.org/nwbib/search?subject=abfallbeseitigung

**Comment by acka47** [comment]
This goes in the right direction and it will also speed up loading of the subject facet. It still has some issues, though. After I tried out the linked example http://test.lobid.org/nwbib/search?subject=abfallbeseitigung, I tried out two other examples http://test.lobid.org/nwbib/search?subject=pferd & http://test.lobid.org/nwbib/search?subject=hund. The subject facet doesn't change with the different queries but remains the same as in the first query for the foloowing queries.

**Comment by fsteeg** [comment]
Deployed to staging, see:

http://test.lobid.org/nwbib/search?subject=abfallbeseitigung
http://test.lobid.org/nwbib/search?subject=pferd
http://test.lobid.org/nwbib/search?subject=hund

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
Deployed to production, closing. See:

http://lobid.org/nwbib/search?subject=abfallbeseitigung
http://lobid.org/nwbib/search?subject=pferd
http://lobid.org/nwbib/search?subject=hund
