### ISSUE TITLE
Speed up loading of subject facet

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#194]
As provided by E.L. on 2015-11-27 via email list:

> Die Geschwindigkeit für das Laden der Schlagwörter  hängt offensichtlich von der  Größe der Trefferliste ab. Vielleicht kann man das noch etwas beschleunigen.

**Comment by acka47** [comment]
I guess we are already using the quickest API call for this, don't we? This would be querying by id with `format=short.preferredName` parameter I guess, e.g. http://lobid.org/subject?id=http://d-nb.info/gnd/4079041-1&format=short.preferredName

**Comment by fsteeg** [comment]
The reason that this is slow is that we don't have the labels we want to display in the data. The facet request against Elasticsearch uses the `subject` field. That part is fast. Then, we load all the labels for display in the facet. That's the slow part. If we'd facet over values we actually have in the data (like `subjectLabel` or `subjectChain`) it would be very fast. Would it be feasible to facet over `subjectLabel`, @acka47? Or will we wait for API 2.0? (this rings a bell, we've had this discussion before...)

**Comment by acka47** [comment]
> Would it be feasible to facet over `subjectLabel`, @acka47? Or will we wait for API 2.0? (this rings a bell, we've had this discussion before...)

I don't think we can use `subjectLabel` for this as we want the facet to display single subject headings which aren't always clearly separated in this field. Thus, we will wait for API 2.0 which is on its way.

**Comment by acka47** [comment]
Moved to backlog.

**Comment by acka47** [comment]
Demanded again by stakeholders on 2016-01-26 (mail by G.C.):

> 	Problematisch ist auch die lange Ladezeit bei Facetten (insb.
	Schlagwort) bei großen Treffermengen. Es ist uns wichtig, dass hier noch bis
	März eine Verbesserung erzielt wird.

**Comment by fsteeg** [comment]
Improved speed by loading only 250 facet values for subject facet. Loading all was a remnant from alphabetically sorted facets (where we needed all before we could sort the list). Deployed to staging:

http://test.lobid.org/nwbib 

(Facet queries will be cached, so I'm not providing specific queries, test with some random queries).

**Comment by acka47** [comment]
I suggest only loading 150 facet values to even speed it up more.

**Comment by fsteeg** [comment]
Deployed to staging, see: http://test.lobid.org/nwbib

I actually changed the number of facet values to 150 for all facets, since depending on the connection, they can all get a little slow. It also makes no sense to have these giant lists, and it's more consistent.

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
Deployed to production, closing. See: http://lobid.org/nwbib
