### ISSUE TITLE
Error on details page, related to session data

### ISSUE THREAD

**Issue by fsteeg** [hbz/nwbib#195]
Steps to reproduce:

1. Restart your browser, or remove the PLAY_SESSION cookie
2. Visit http://lobid.org/nwbib/HT016558942 - should work with clean session
3. Visit http://lobid.org/nwbib/search?q=braunkohle
4. Visit http://lobid.org/nwbib/HT016558942 again - error

Works again after removing the PLAY_SESSION cookie from the browser (or restarting the browser).

**Comment by acka47** [comment]
I not reproduce this in Chromium. This reminded me of another incident from a few days ago: @jschnasse had a maybe similar problem. He got an error for NWBib resources that I could view on my laptop sitting next to him... The resource in question was something from http://etherpad.lobid.org/p/20151203_publisso-telko. @jschnasse can you reproduce this?

**Comment by fsteeg** [comment]
Deployed to staging, steps to reproduce:

1. Restart your browser, or remove the PLAY_SESSION cookie
2. Visit http://test.lobid.org/nwbib/HT016558942
3. Visit http://test.lobid.org/nwbib/search?q=braunkohle
4. Visit http://test.lobid.org/nwbib/HT016558942 again

Note that I also added the first step to steps to reproduce the problem in the issue description.

**Comment by fsteeg** [comment]
Ha, we commented at the same second. Try again with the new first step, I also had problems reproducing in a running browser session.

**Comment by acka47** [comment]
Yes, this "worked". I guess, the underlying problem was the same some days ago.

**Comment by acka47** [comment]
+1 for the fix.

**Comment by fsteeg** [comment]
Deployed to production, closing. Steps to reproduce:

1. Restart your browser, or remove the PLAY_SESSION cookie
2. Visit http://lobid.org/nwbib/HT016558942
3. Visit http://lobid.org/nwbib/search?q=braunkohle
4. Visit http://lobid.org/nwbib/HT016558942 again
