### ISSUE TITLE
Tweak details view

### ISSUE THREAD

**Issue by fsteeg** [hbz/nwbib#201]
Mail GC, 2015-12-10

- [x] Straffung durch geringere Zeilenabstände
- [x] Straffung der Schlagwortanzeige, allerdings darf auf keinen Fall die Verlinkung des Einzelschlagworts für weitere Titelsuche und  die Verlinkung des Schlagworts mit der GND verloren gehen. Von Münster wird die Verlinkung der Schlagwortkette in die Themensuche gewünscht, s. Punkt 6b/4.
- [x] Verkleinerte Darstellung der Bestandsangaben
- [x] Verkleinerte Karte für Bestand in Bibliotheken s. Punkt 6 c (Kartengröße bleibt beim Zoomen gleich)

**Comment by fsteeg** [comment]
Deployed to staging:

- Make column narrower (like right column in search results)
- Move holdings map zoom controls to avoid overlap with popup
- Don't show holdings details table by default, add link to show
- Decrease holdings map height
- Link subject chains to corresponding search requests
- Use single table for all fields in details view
- Custom labels for links to toc, description, and catalog
- Subsume multiple values for a field in a single table row
- Decrease table padding to make tables more condensed

Some samples:

- http://test.lobid.org/nwbib/HT017557310
- http://test.lobid.org/nwbib/HT018263803
- http://test.lobid.org/nwbib/HT018845503
- http://test.lobid.org/nwbib/HT018810939
- http://test.lobid.org/nwbib/HT006916592

**Comment by acka47** [comment]
+1 with one minor adjustment I did in https://github.com/hbz/nwbib/commit/085a7459bb8d5f79512c97241bb0e8a7ffecdaa7.

**Comment by fsteeg** [comment]
Deployed to production, closing. See:

- http://lobid.org/nwbib/HT017557310
- http://lobid.org/nwbib/HT018263803
- http://lobid.org/nwbib/HT018845503
- http://lobid.org/nwbib/HT018810939
- http://lobid.org/nwbib/HT006916592
