### ISSUE TITLE
Add orientation text to see which facets are set

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#203]
Reported by NWBib stakeholder E.L. on 2015-12-07:

> Allerdings vermissen wir hier einen Orientierungstext über der Suche wie z.B.: "Ergebnisse mit Schlagwort ,Eisenherstellung' und Publikationstyp ,Aufsatz' und ,Bestandsbibliothek ,Bochum'.

**Comment by fsteeg** [comment]
But this is done by the checkboxes in the facets, or am I getting this wrong?

**Comment by acka47** [comment]
Yes, but they would like to have an overview in one place.

**Comment by acka47** [comment]
We should implement this as a breadcrumb overview.

**Comment by fsteeg** [comment]
Implemented a potential fix for this as part of general facets changes, see https://github.com/hbz/nwbib/issues/202#issuecomment-167788729.

Deployed to staging, see [this sample search with multiple facets set](http://test.lobid.org/nwbib/search?location=30%20Orte%20aus%20Kartenauswahl|51.449417855436764,8.832754828013321+51.44937047153849,8.832901119471547+51.44933726428079,8.833057141563273+51.449318981539946,8.833219380589528+51.44931603507083,8.83338418284281+51.44932849123249,8.833547836890444+51.48738456784118,9.140214516570794+51.48740256407482,9.140327770814416+51.4874279506594,9.140437313683712+51.48746044023585,9.140541905279095+51.48749966504474,9.140640361743676+51.48754518108945,9.140731568663293+51.6417135770432,9.418509516148742+51.64182395153764,9.418669596822497+51.641953216313986,9.418787372208422+51.64209523897022,9.418857255089822+51.64224328192216,9.418875930251+51.64239032204781,9.418842511749915+51.766834300119925,9.367731342590503+51.76684085081933,9.367728592236197+51.766847384249644,9.367725736648671+51.76685389976343,9.367722776110936+51.76686039671505,9.367719710916319+51.766866874460675,9.367716541368573+51.859899886938884,9.321329748112769+51.85991204604513,9.32132347591101+51.859924130145686,9.321316834541555+51.859936134966006,9.321309826353765+51.85994805625956,9.321302453826696+51.85995988980935,9.321294719568304+52.38359010353675,8.967681670776418+52.38370812030344,8.967577763877173+52.38381117317047,8.967437492908612+52.383895148504024,8.967266457325836+52.38395669422264,8.967071484671694+52.38399335358991,8.966860358029404+52.43875921924421,8.465193394928972+52.43876828682663,8.46492867382997+52.43873842913906,8.464668098267241+52.43867138509592,8.46442684484692+52.438571059360925,8.464218964802862+52.4384432949654,8.464056565615605+51.95423590884823,7.992390110346746+51.95415350717696,7.992322198772901+51.95406617333185,7.992273128228632+51.953975534528645,7.992243813016255+51.95388327957153,7.992234799348683+51.9537911273877,7.992246255172252+51.75490187877131,8.039190612627028+51.75478664500367,8.039234578186143+51.754677877781496,8.039310163998712+51.754578874066674,8.039415078941087+51.75449263488929,8.039546142877988+51.754421774372815,8.039699383057496&q=&person=&name=&subject=&publisher=&issued=2000-2013&medium=&nwbibspatial=http%3A%2F%2Fpurl.org%2Flobid%2Fnwbib-spatial%23n12%2Chttp%3A%2F%2Fpurl.org%2Flobid%2Fnwbib-spatial%23n01&nwbibsubject=&owner=&t=&sort=&set=&word=&corporation=&raw=).

**Comment by acka47** [comment]
I think think this goes in the right direction. We won't have the sequence the user set the different filters (as we would have with breadcrumbs) but that is Ok.

One thing hast to be resolved to make it work: When setting a publication year or subject facet besides the orientation text at the respective facets (which I think are a good way to go) there additionally is a row from the extended search with the publication date resp. the GND URI. See for example http://test.lobid.org/nwbib/search?person=m%C3%BCller&subject=http%3A%2F%2Fd-nb.info%2Fgnd%2F4123092-9&issued=1996&nwbibspatial=http%3A%2F%2Fpurl.org%2Flobid%2Fnwbib-spatial%23n03

These rows shouldn't be shown for orientation as they are redundant and will rather confuse users. The "Person" row should stay, though, as it is the only way to indicate the user made a Person search (for "Müller" in the example).

**Comment by fsteeg** [comment]
Deployed to staging, see:

http://test.lobid.org/nwbib/search?person=m%C3%BCller&subject=http%3A%2F%2Fd-nb.info%2Fgnd%2F4123092-9&issued=1996&nwbibspatial=http%3A%2F%2Fpurl.org%2Flobid%2Fnwbib-spatial%23n03

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
Deployed to production, closing. See:

http://lobid.org/nwbib/search?person=m%C3%BCller&subject=http%3A%2F%2Fd-nb.info%2Fgnd%2F4123092-9&issued=1996&nwbibspatial=http%3A%2F%2Fpurl.org%2Flobid%2Fnwbib-spatial%23n03
