### ISSUE TITLE
Missing subject labels in facet

### ISSUE THREAD

**Issue by fsteeg** [hbz/nwbib#204]
See https://github.com/hbz/lobid/issues/84 for root cause, but will take a different approach, because labels in the resources should be displayed, so we will look them up using the resource API.

**Comment by fsteeg** [comment]
Deployed to staging, see e.g.:

- Issue: http://lobid.org/nwbib/search?q=ehrenfeld (expand subject facet twice, two missing labels)
- Fix: http://test.lobid.org/nwbib/search?q=ehrenfeld

**Comment by acka47** [comment]
+1 Also works for others, e.g. http://test.lobid.org/nwbib/search?location=&q=Bottrop vs. http://lobid.org/nwbib/search?location=&q=Bottrop

**Comment by fsteeg** [comment]
Deployed to production, see: http://lobid.org/nwbib/search?q=ehrenfeld
