### ISSUE TITLE
Improve design of map on home page

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#205]
Reported by G.C. on 2015-12-10:

> Eine optische Betonung der Karte durch Verstärkung der Umrisse (ggf. in rot/weiß/grün) wäre bis zur „Freischaltung“ wünschenswert, da die Karte ein Charakteristikum der neuen NWBib ist und dann nicht mehr kurzfristig geändert werden sollte.

Low priority.

**Comment by fsteeg** [comment]
Deployed to staging: http://test.lobid.org/nwbib

(Light green and red initially, strong colors on hover).

**Comment by acka47** [comment]
As far as I can remember, stakeholders weren't happy when we the last time presented green/red for Rhineland vs. Westphalia. Anyway, as it isn't clear at all what they want, I think we should deploy this as a proposal, thus: +1 If they don't like it, we should ask them to clarify their expectations and/or to contact a designer...

**Comment by fsteeg** [comment]
Deployed to production, closing. See: http://lobid.org/nwbib
