### ISSUE TITLE
Remove "Überordnung" from advanced search & volume lookup

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#206]

**Comment by fsteeg** [comment]
Deployed to staging, see: 

- subordination links e.g. in: http://test.lobid.org/nwbib/HT006984941
- advanced search: http://test.lobid.org/nwbib/advanced

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
Deployed to production, closing. See: 

- subordination links e.g. in: http://lobid.org/nwbib/HT006984941
- advanced search: http://lobid.org/nwbib/advanced
