### ISSUE TITLE
No correct polygon for some Kreise

### ISSUE THREAD

**Issue by fsteeg** [hbz/nwbib#207]
When searching from the index page map, we don't get proper polygons for Hochsauerlandkreis and Kreis Euskirchen. These polygons have too many coordinates to be passed a query params. We will have to store the polygons elsewhere (e.g. in ES) and get them from there. This will also allow us to increase polygon precision.

**Comment by fsteeg** [comment]
Deployed to staging, see [Hochsauerlandkreis](http://test.lobid.org/nwbib/search?location=Hochsauerlandkreis|u1nm1x+u1nm1x+u1nm4r+u1nm4m+u1nm4k+u1nm4t+u1nm4e+u1nm56+u1nm58+u1nmh1+u1nmh0+u1nkfv+u1nkf7+u1nkf6+u1nkfb+u1nkdy+u1nkej+u1nkdf+u1nke6+u1nked+u1nke8+u1nk7x+u1nk7q+u1nk7s+u1nk77+u1nk6g+u1nk67+u1nk32+u1nk34+u1nk34+u1nk2f+u1nk2g+u1nk27+u1nhrd+u1nhr3+u1nhq8+u1nhmb+u1nhm8+u1nhjr+u1nhjw+u1nhjt+u1nhjm+u1nhjj+u1nhj5+u1nhhg+u1nhhf+u1nhhd+u1nhh1+u1nhh0+u1n5gz+u1n5gv+u1n5ge+u1n5fb+u1n5dw+u1n5eh+u1n5e6+u1n5e9+u1n5ec+u1n5s6+u1n5s7+u1n5s7+u1n5tt+u1n5ty+u1n5ty+u1n5wq+u1n5wk+u1n5wg+u1n5w9+u1n5qu+u1n5rd+u1n5r3+u1n5r0+u1n5pj+u1n5pk+u1n5nf+u1n5nc+u1n4yr+u1n4yr+u1n4vu+u1n4y1+u1n4y3+u1n4y2+u1n4vb+u1n4sv+u1n4ew+u1n4dw+u1n4f3+u1n4f1+u1n4cf+u1n4ce+u1n4cs+u1n4cn+u1n4cp+u1n4bw+u1n4bw+u1n4bm+u1n4bk+u1jfzy+u1jfzh+u1jfwr+u1jfwr+u1jfwj+u1jftv+u1jftm+u1jftj+u1jfsy+u1jfsr+u1jfey+u1jfer+u1jfg8+u1jfg1+u1jfg4+u1jffg+u1jffd+u1jffd+u1jff6+u1jffe+u1jff7+u1jffs+u1jffk+u1jffm+u1jffn+u1jffn+u1jfcz+u1jfcz+u1jfcv+u1jfct+u1jfcw+u1jfcm+u1jfcn+u1jg10+u1jg13+u1jg17+u1jg1j+u1jg1j+u1jg0y+u1jg0z+u1jg0x+u1jg29+u1jg23+u1jg27+u1jg27+u1jg2k+u1jg2y+u1jg2z+u1jg2r+u1jg80+u1jexb+u1jex3+u1jex1+u1jerp+u1jeqz+u1jeqx+u1jew8+u1jew8+u1jew3+u1jew2+u1jew0+u1jeqp+u1jemz+u1jet2+u1jekx+u1jekw+u1jes2+u1jes8+u1jes0+u1jes4+u1jes7+u1jesh+u1jeey+u1jeez+u1jesn+u1jesp+u1jesp+u1jeez+u1jeu0+u1jeu5+u1jegg+u1jegu+u1jeuh+u1jeuq+u1jeuw+u1jeur+u1jsh9+u1jsh5+u1js5g+u1jshh+u1js5y+u1js7b+u1js7e+u1js7s+u1js7t+u1js7x+u1jse8+u1jsed+u1jse6+u1jse7+u1jse7+u1jsem+u1jsdz+u1jsg0+u1jsg1+u1jsg3+u1jsg6+u1jsg7+u1jsg7+u1jsgk+u1jsgv+u1jsgv+u1jsuh+u1jsu4+u1jsuc+u1jsv6+u1jsv9+u1jsvf+u1jsy4+u1jsy2+u1jswz+u1jsxj+u1ju8m+u1ju8w+u1ju8y+u1ju8t+u1ju9h+u1ju9s+u1jud4+u1jud8+u1ju6z+u1ju6z+u1ju6y+u1ju7q+u1ju7m+u1jukq+u1jukf+u1jum5+u1jum5+u1juqh+u1juqk+u1juqy+u1jurj+u1jurw+u1jurw+u1nh8d+u1nh8e+u1nh8s+u1nh9j+u1nhf9+u1nhg1+u1nhg7+u1nhgu+u1nhgg+u1nhu7+u1nhug+u1nhv4+u1nhvd+u1nhvb+u1nhy0+u1nhwr+u1nhz1+u1nhxq+u1nhxt+u1nhxz+u1nkb7+u1nkcn+u1nm10+u1nm0c+u1nm0d+u1nm07+u1nm0k+u1nm0s+u1nm0w+u1nm0y+u1nm0y+u1nm1n+u1nm1q+u1nm1r+u1nm32+u1nm1x) and [Kreis Euskirchen](http://test.lobid.org/nwbib/search?location=Kreis%20Euskirchen|u1hbu2+u1hbsw+u1hbsy+u1hbtn+u1hbtj+u1hbt7+u1hbt4+u1hbt4+u1hbsc+u1hbsb+u1hbsb+u1hbkp+u1hbkn+u1hb7u+u1hbk7+u1hbk6+u1hbk2+u1hbk2+u1hbhn+u1hbhn+u1hbhj+u1hbhj+u1hbhh+u1hbhh+u1hbhk+u1hbh6+u1hbhc+u1hbj2+u0uzvj+u0uzvk+u0uzue+u0uzud+u0uzuc+u0uzsy+u0uzsy+u0uzsy+u0uztp+u0uztr+u0uztq+u0uztq+u0uztr+u0uztx+u0uztw+u0uzty+u0uztm+u0uzte+u0uzte+u0uzmx+u0uzmj+u0uzky+u0uzmn+u0uzkw+u0uzks+u0uzku+u0uzkf+u0uzm1+u0uzhz+u0uzjp+u0uzjn+u0uzhv+u0uzjh+u0uzj5+u0uzh6+u0uzh0+u0uz5d+u0uz5h+u0uz4z+u0uz4z+u0uz4q+u0uz4n+u0uz4n+u0uz1u+u0uz1k+u0uz17+u0uz1e+u0uz1s+u0uz1g+u0uz1f+u0uz1c+u0uz1c+u0uz1b+u0uycq+u0uycm+u0uycu+u0uyfj+u0uyf5+u0uyf6+u0uyf3+u0uydr+u0uydj+u0uyd6+u0uydc+u0uydb+u0uy6x+u0uyd8+u0uyd0+u0uy6p+u0uy6p+u0uy3w+u0uy3n+u0uy2s+u0uy27+u0uy2p+u0uwx9+u0uwx3+u0uwrr+u0uwrm+u0uwrj+u0uwqy+u0uwqw+u0uwqx+u0uwwc+u0uwwd+u0uww6+u0uww5+u0uww7+u0uwwk+u0uwtg+u0uwtf+u0uwt6+u0uwt3+u0uwsb+u0uwsc+u0uws9+u0uws2+u0uwkq+u0uwkp+u0uwkn+u0uw7t+u0uw7e+u0uw77+u0uw7h+u0uw6g+u0uw6g+u0uw6u+u0uw7p+u0uwdb+u0uwd9+u0uwd3+u0uwd2+u0uwd1+u0uwd4+u0uw9f+u0uwd5+u0uw9v+u0uw9k+u0uw97+u0uw93+u0uw99+u0uw98+u0uw9b+u0uw3x+u0uw3v+u0uw3u+u0uw3f+u0uw64+u0uw61+u0uw39+u0uw3g+u0uw3e+u0uw3t+u0uw3p+u0uw2z+u0uw2z+u0uw89+u0uw87+u0uw8t+u0uwbb+u0uwbf+u0uwcn+u0ux10+u0ux0c+u0ux0b+u0ux06+u0ux07+u0ux0h+u0ux0q+u0ux0x+u0ux0p+u0ux0p+u0urr8+u0ux24+u0ux2e+u0ux2u+u0ux3p+u0ux3p+u0ux2w+u0ux8b+u0ux8u+u0uxc8+u0uxc6+u0uxcg+u0uxf5+u0uxfj+u0uxfp+u0uxgj+u0uxge+u0uxuh+u0uxu7+u0uxuu+u0uxv5+u0uxv5+u0uxvh+u0uxvk+u0uxvj+u0uxvr+u1h8j2+u1h8jd+u1h8jt+u1h8jm+u1h8jz+u1h8mb+u1h8q0+u1h8q5+u1h8qh+u1h8qj+u1h8mv+u1h8my+u1h8mz+u1h8w2+u1h8w2+u1h8w9+u1h8wd+u1h8wg+u1h8xb+u1hb87+u1hb8k+u1hb8m+u1hb8q+u1hb8q+u1hb8r+u1hb8r+u1hb8r+u1hb8x+u1hb8x+u1hb8z+u1hb8y+u1hb8s+u1hb8g+u1hb9e+u1hbd1+u1hbdy+u1hbdw+u1hbg0+u1hbg1+u1hbg3+u1hbg6+u1hbg9+u1hbgd+u1hbgd+u1hbgf+u1hbge+u1hbgv+u1hbuj+u1hbuk+u1hbu6+u1hbu1+u1hbu2).

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
Deployed to production, closing. See: [Hochsauerlandkreis](http://lobid.org/nwbib/search?location=Hochsauerlandkreis|u1nm1x+u1nm1x+u1nm4r+u1nm4m+u1nm4k+u1nm4t+u1nm4e+u1nm56+u1nm58+u1nmh1+u1nmh0+u1nkfv+u1nkf7+u1nkf6+u1nkfb+u1nkdy+u1nkej+u1nkdf+u1nke6+u1nked+u1nke8+u1nk7x+u1nk7q+u1nk7s+u1nk77+u1nk6g+u1nk67+u1nk32+u1nk34+u1nk34+u1nk2f+u1nk2g+u1nk27+u1nhrd+u1nhr3+u1nhq8+u1nhmb+u1nhm8+u1nhjr+u1nhjw+u1nhjt+u1nhjm+u1nhjj+u1nhj5+u1nhhg+u1nhhf+u1nhhd+u1nhh1+u1nhh0+u1n5gz+u1n5gv+u1n5ge+u1n5fb+u1n5dw+u1n5eh+u1n5e6+u1n5e9+u1n5ec+u1n5s6+u1n5s7+u1n5s7+u1n5tt+u1n5ty+u1n5ty+u1n5wq+u1n5wk+u1n5wg+u1n5w9+u1n5qu+u1n5rd+u1n5r3+u1n5r0+u1n5pj+u1n5pk+u1n5nf+u1n5nc+u1n4yr+u1n4yr+u1n4vu+u1n4y1+u1n4y3+u1n4y2+u1n4vb+u1n4sv+u1n4ew+u1n4dw+u1n4f3+u1n4f1+u1n4cf+u1n4ce+u1n4cs+u1n4cn+u1n4cp+u1n4bw+u1n4bw+u1n4bm+u1n4bk+u1jfzy+u1jfzh+u1jfwr+u1jfwr+u1jfwj+u1jftv+u1jftm+u1jftj+u1jfsy+u1jfsr+u1jfey+u1jfer+u1jfg8+u1jfg1+u1jfg4+u1jffg+u1jffd+u1jffd+u1jff6+u1jffe+u1jff7+u1jffs+u1jffk+u1jffm+u1jffn+u1jffn+u1jfcz+u1jfcz+u1jfcv+u1jfct+u1jfcw+u1jfcm+u1jfcn+u1jg10+u1jg13+u1jg17+u1jg1j+u1jg1j+u1jg0y+u1jg0z+u1jg0x+u1jg29+u1jg23+u1jg27+u1jg27+u1jg2k+u1jg2y+u1jg2z+u1jg2r+u1jg80+u1jexb+u1jex3+u1jex1+u1jerp+u1jeqz+u1jeqx+u1jew8+u1jew8+u1jew3+u1jew2+u1jew0+u1jeqp+u1jemz+u1jet2+u1jekx+u1jekw+u1jes2+u1jes8+u1jes0+u1jes4+u1jes7+u1jesh+u1jeey+u1jeez+u1jesn+u1jesp+u1jesp+u1jeez+u1jeu0+u1jeu5+u1jegg+u1jegu+u1jeuh+u1jeuq+u1jeuw+u1jeur+u1jsh9+u1jsh5+u1js5g+u1jshh+u1js5y+u1js7b+u1js7e+u1js7s+u1js7t+u1js7x+u1jse8+u1jsed+u1jse6+u1jse7+u1jse7+u1jsem+u1jsdz+u1jsg0+u1jsg1+u1jsg3+u1jsg6+u1jsg7+u1jsg7+u1jsgk+u1jsgv+u1jsgv+u1jsuh+u1jsu4+u1jsuc+u1jsv6+u1jsv9+u1jsvf+u1jsy4+u1jsy2+u1jswz+u1jsxj+u1ju8m+u1ju8w+u1ju8y+u1ju8t+u1ju9h+u1ju9s+u1jud4+u1jud8+u1ju6z+u1ju6z+u1ju6y+u1ju7q+u1ju7m+u1jukq+u1jukf+u1jum5+u1jum5+u1juqh+u1juqk+u1juqy+u1jurj+u1jurw+u1jurw+u1nh8d+u1nh8e+u1nh8s+u1nh9j+u1nhf9+u1nhg1+u1nhg7+u1nhgu+u1nhgg+u1nhu7+u1nhug+u1nhv4+u1nhvd+u1nhvb+u1nhy0+u1nhwr+u1nhz1+u1nhxq+u1nhxt+u1nhxz+u1nkb7+u1nkcn+u1nm10+u1nm0c+u1nm0d+u1nm07+u1nm0k+u1nm0s+u1nm0w+u1nm0y+u1nm0y+u1nm1n+u1nm1q+u1nm1r+u1nm32+u1nm1x) and [Kreis Euskirchen](http://lobid.org/nwbib/search?location=Kreis%20Euskirchen|u1hbu2+u1hbsw+u1hbsy+u1hbtn+u1hbtj+u1hbt7+u1hbt4+u1hbt4+u1hbsc+u1hbsb+u1hbsb+u1hbkp+u1hbkn+u1hb7u+u1hbk7+u1hbk6+u1hbk2+u1hbk2+u1hbhn+u1hbhn+u1hbhj+u1hbhj+u1hbhh+u1hbhh+u1hbhk+u1hbh6+u1hbhc+u1hbj2+u0uzvj+u0uzvk+u0uzue+u0uzud+u0uzuc+u0uzsy+u0uzsy+u0uzsy+u0uztp+u0uztr+u0uztq+u0uztq+u0uztr+u0uztx+u0uztw+u0uzty+u0uztm+u0uzte+u0uzte+u0uzmx+u0uzmj+u0uzky+u0uzmn+u0uzkw+u0uzks+u0uzku+u0uzkf+u0uzm1+u0uzhz+u0uzjp+u0uzjn+u0uzhv+u0uzjh+u0uzj5+u0uzh6+u0uzh0+u0uz5d+u0uz5h+u0uz4z+u0uz4z+u0uz4q+u0uz4n+u0uz4n+u0uz1u+u0uz1k+u0uz17+u0uz1e+u0uz1s+u0uz1g+u0uz1f+u0uz1c+u0uz1c+u0uz1b+u0uycq+u0uycm+u0uycu+u0uyfj+u0uyf5+u0uyf6+u0uyf3+u0uydr+u0uydj+u0uyd6+u0uydc+u0uydb+u0uy6x+u0uyd8+u0uyd0+u0uy6p+u0uy6p+u0uy3w+u0uy3n+u0uy2s+u0uy27+u0uy2p+u0uwx9+u0uwx3+u0uwrr+u0uwrm+u0uwrj+u0uwqy+u0uwqw+u0uwqx+u0uwwc+u0uwwd+u0uww6+u0uww5+u0uww7+u0uwwk+u0uwtg+u0uwtf+u0uwt6+u0uwt3+u0uwsb+u0uwsc+u0uws9+u0uws2+u0uwkq+u0uwkp+u0uwkn+u0uw7t+u0uw7e+u0uw77+u0uw7h+u0uw6g+u0uw6g+u0uw6u+u0uw7p+u0uwdb+u0uwd9+u0uwd3+u0uwd2+u0uwd1+u0uwd4+u0uw9f+u0uwd5+u0uw9v+u0uw9k+u0uw97+u0uw93+u0uw99+u0uw98+u0uw9b+u0uw3x+u0uw3v+u0uw3u+u0uw3f+u0uw64+u0uw61+u0uw39+u0uw3g+u0uw3e+u0uw3t+u0uw3p+u0uw2z+u0uw2z+u0uw89+u0uw87+u0uw8t+u0uwbb+u0uwbf+u0uwcn+u0ux10+u0ux0c+u0ux0b+u0ux06+u0ux07+u0ux0h+u0ux0q+u0ux0x+u0ux0p+u0ux0p+u0urr8+u0ux24+u0ux2e+u0ux2u+u0ux3p+u0ux3p+u0ux2w+u0ux8b+u0ux8u+u0uxc8+u0uxc6+u0uxcg+u0uxf5+u0uxfj+u0uxfp+u0uxgj+u0uxge+u0uxuh+u0uxu7+u0uxuu+u0uxv5+u0uxv5+u0uxvh+u0uxvk+u0uxvj+u0uxvr+u1h8j2+u1h8jd+u1h8jt+u1h8jm+u1h8jz+u1h8mb+u1h8q0+u1h8q5+u1h8qh+u1h8qj+u1h8mv+u1h8my+u1h8mz+u1h8w2+u1h8w2+u1h8w9+u1h8wd+u1h8wg+u1h8xb+u1hb87+u1hb8k+u1hb8m+u1hb8q+u1hb8q+u1hb8r+u1hb8r+u1hb8r+u1hb8x+u1hb8x+u1hb8z+u1hb8y+u1hb8s+u1hb8g+u1hb9e+u1hbd1+u1hbdy+u1hbdw+u1hbg0+u1hbg1+u1hbg3+u1hbg6+u1hbg9+u1hbgd+u1hbgd+u1hbgf+u1hbge+u1hbgv+u1hbuj+u1hbuk+u1hbu6+u1hbu1+u1hbu2).
