### ISSUE TITLE
Handle umlauts and their resolution as equivalent

### ISSUE THREAD

**Issue by fsteeg** [hbz/nwbib#208]
Köln, Koeln should yield the same result

**Comment by acka47** [comment]
Also, "Koln"  as stakeholders required.

**Comment by fsteeg** [comment]
No, if I recall correctly, that should explicitly not be treated as equivalent, sample given was:

Münster is not equal to Munster.

**Comment by acka47** [comment]
Ok, I probably confused this with the actual implementation we once had using Jörg's plugin.

**Comment by fsteeg** [comment]
Deployed to staging (using a small test set), see:

`q`

- http://test.lobid.org/nwbib/search?q=köln
- http://test.lobid.org/nwbib/search?q=koeln

`word`

- http://test.lobid.org/nwbib/search?word=köln
- http://test.lobid.org/nwbib/search?word=koeln

`name`

- http://test.lobid.org/nwbib/search?name=Gebäude
- http://test.lobid.org/nwbib/search?name=Gebaeude

`subject`

- http://test.lobid.org/nwbib/search?subject=köln
- http://test.lobid.org/nwbib/search?subject=koeln

`topics`

- http://test.lobid.org/nwbib/topics?q=köln
- http://test.lobid.org/nwbib/topics?q=koeln

This is implemented using the snowball-German2 stemmer that is part of Elasticsearch. Besides the two normalizations from our requirements shown in the links above, it also does the common third normalization that was not part of our requirements:

- http://test.lobid.org/nwbib/search?q=koln
- http://test.lobid.org/nwbib/search?word=koln
- http://test.lobid.org/nwbib/search?subject=koln
- http://test.lobid.org/nwbib/search?name=Gebaude

I think we should still deploy it like this (and see if stakeholders complain) for these reasons:

- It's common for non German speakers to simply leave out the diacritics when searching
- Correct hits for non-diacritic words are not lost, they will also be in the result set (e.g. Munster)
- We keep it simple and reliable by using an existing Elasticsearch functionality instead of building our own or using some plugin

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
Deployed to production, closing. See:

`q`

- http://lobid.org/nwbib/search?q=köln
- http://lobid.org/nwbib/search?q=koeln

`word`

- http://lobid.org/nwbib/search?word=köln
- http://lobid.org/nwbib/search?word=koeln

`name`

- http://lobid.org/nwbib/search?name=Gebäude
- http://lobid.org/nwbib/search?name=Gebaeude

`subject`

- http://lobid.org/nwbib/search?subject=köln
- http://lobid.org/nwbib/search?subject=koeln

`topics`

- http://lobid.org/nwbib/topics?q=wärme
- http://lobid.org/nwbib/topics?q=waerme
