### ISSUE TITLE
Many subject chains are not found within "Themensuche"

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#210]
For example http://lobid.org/nwbib/topics?q=rees doesn't give back all results for http://lobid.org/nwbib/topics?q=rees+r%C3%B6merzeit.

**Comment by fsteeg** [comment]
Deployed to staging, see:

http://test.lobid.org/nwbib/topics?q=rees
http://test.lobid.org/nwbib/topics?q=rees+r%C3%B6merzeit

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
Deployed to production, closing. See:

http://lobid.org/nwbib/topics?q=rees
http://lobid.org/nwbib/topics?q=rees+r%C3%B6merzeit
