### ISSUE TITLE
Improve performance for Themensuche

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#213]
After testing #210 and looking at different examples (e.g. [searching for "Köln"](http://test.lobid.org/nwbib/topics?q=k%C3%B6ln) with > 15k results) in Themensuche, I think we should implement paging for Themensuche. What about loading more results when people scroll to the button of the page. Is it possible to implement this easily?

**Comment by fsteeg** [comment]
Not in a useful way. I've actually had this implemented as a first approach for #210, but an important feature of the current topics search is that the result is sorted alphabetically. Individual pages can be sorted, but e.g. `Rees | Römer*` will be spread across pages. The alternative of loading all and sorting that would have the same performance issue.

The root issue for the performance issue is that we don't use a proper facets call (the `subjectChain` field is analyzed by Elasticsearch for query reasons and therefore can't be used as facet field). It should be possible to change that, but not quickly, and probably not for `nwbib-launch`.

Re-naming and re-labeling.

**Comment by fsteeg** [comment]
Deployed to staging, see: http://test.lobid.org/nwbib/topics?q=köln (and similar, unchached requests).

**Comment by acka47** [comment]
+1
