### ISSUE TITLE
Always show timeline from 1983 to current year for filtering by publication year

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#219]
Currently, only the publication years which actually exist in the results are shown in the timeline for filtering a result list. this is awkward for results with only one year e.g. http://test.lobid.org/nwbib/search?name=smartphone or only two publication years, e.g. http://test.lobid.org/nwbib/search?word=smartphone.

Solution: Always show the same timeline from 1983 till current year and only show the bars where publications exist.

**Comment by acka47** [comment]
Also, this is quite confusing where I chose one year and two others are shown: http://test.lobid.org/nwbib/search?person=schmidt&issued=1991&nwbibspatial=http%3A%2F%2Fpurl.org%2Flobid%2Fnwbib-spatial%23n03&location=50.871944362297654%2C6.6961111687123775

**Comment by fsteeg** [comment]
Deployed to staging, see:

- http://test.lobid.org/nwbib/search?name=smartphone
- http://test.lobid.org/nwbib/search?word=smartphone

Also now avoids redundant labels when facet is active:

- http://test.lobid.org/nwbib/search?q=glessen&issued=2008-2016
- http://test.lobid.org/nwbib/search?person=schmidt&issued=1991&nwbibspatial=http%3A%2F%2Fpurl.org%2Flobid%2Fnwbib-spatial%23n03&location=50.871944362297654%2C6.6961111687123775

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
Deployed to production, closing. See:

- http://lobid.org/nwbib/search?name=smartphone
- http://lobid.org/nwbib/search?word=smartphone
- http://lobid.org/nwbib/search?q=glessen&issued=2008-2016
- http://lobid.org/nwbib/search?person=schmidt&issued=1991&nwbibspatial=http%3A%2F%2Fpurl.org%2Flobid%2Fnwbib-spatial%23n03&location=50.871944362297654%2C6.6961111687123775
