### ISSUE TITLE
Add facet over field "coverage"

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#221]
To meet stakeholder demands for showing list of values of property `coverage` (fields 700n, notations 96, 97, 99 in source data), we will add a facet within the "Ortsbezug" section over this field.

**Comment by fsteeg** [comment]
Deployed to staging (with test set), see: http://test.lobid.org/nwbib/search

**Comment by acka47** [comment]
I noticed some problems trying this out. Here is the first:
In the test data, there are two "Münster" elements, one for the Regierungsbezirk and one for the town. As the content in angle brackets is missing both look the same. See e.e.g http://test.lobid.org/nwbib/HT008353259 and http://test.lobid.org/nwbib/HT003160768 Thus, before deploying this on production we should fix #222 .

**Comment by acka47** [comment]
Also, there is a problem with Umlauts but it only exists in the test data on staging.

**Comment by acka47** [comment]
> Thus, before deploying this on production we should fix #222 .

This should also be fixed for the elements in the "Orte" facet.

**Comment by fsteeg** [comment]
Deployed to staging, see http://test.lobid.org/nwbib/search

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
Seem to go wrong for GND subjects, where umlauts are now escaped (but oddly not in Sachsystematik), see: http://test.lobid.org/nwbib/search

**Comment by fsteeg** [comment]
https://github.com/hbz/nwbib/issues/221#issuecomment-171918095 looks like a deployment issue. Alos it's non-critical (no broken functionality). Will open separate issue if still present after deployment to production.

**Comment by fsteeg** [comment]
Deployed to production, closing. See: http://lobid.org/nwbib/search
