### ISSUE TITLE
Content in angle brackets from nwbibspatial not shown in HTML

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#222]
Similar to #104. See e.g. http://lobid.org/nwbib/HT016180747 where the HTML reads 

```html
<tr><td>Ortsbezug</td><td><a title="Nach weiteren Titeln suchen" href="/nwbib/search?nwbibspatial=Handorf+%3CM%C3%BCnster%2C+Westfalen%3E">Handorf <Münster, Westfalen></a></td></tr>
```
 but you can only see "Handorf" in the browser.

**Comment by fsteeg** [comment]
Deployed to staging. Your sample is not in the currently deployed test set, but see:

http://test.lobid.org/nwbib/HT008353259

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
Deployed to production, closing. See: http://lobid.org/nwbib/HT016180747
