### ISSUE TITLE
Subject facet is broken after search via subject in title page

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#223]
When I initiate a subject search via GND ID, e.g. from a single resource view, the subject facet for the result kist us then broken. Example: http://lobid.org/nwbib/search?subject=http%3A%2F%2Fd-nb.info%2Fgnd%2F4076769-3 

The subject facet always looks like this:

![2060114_subject-facet-bug](https://cloud.githubusercontent.com/assets/160292/12324997/581017ee-bac7-11e5-9b8e-ab2684bdc0ea.png)

Problems:

- The chosen subject which triggered the search isn't shown.
- Always the same subject ("Nüsse, Barbara") ) for further filtering is shown.

**Comment by fsteeg** [comment]
Seems to be fixed on staging by subsequent changes, see:

http://test.lobid.org/nwbib/search?subject=http%3A%2F%2Fd-nb.info%2Fgnd%2F4076769-3

(But made me aware of different issue: https://github.com/hbz/nwbib/issues/221#issuecomment-171918095)

**Comment by acka47** [comment]
Ok. So leave this be for now and I will check whether it runs after other issues are deployed...

**Comment by fsteeg** [comment]
I'll self assign and move to deploy, will move back if still an issue with full data on staging.

**Comment by fsteeg** [comment]
Deployed to production, closing.

See: http://lobid.org/nwbib/search?subject=http%3A%2F%2Fd-nb.info%2Fgnd%2F4076769-3

And search by subjects e.g. via links from http://lobid.org/nwbib/HT018809722
