### ISSUE TITLE
Switch domain to nwbib.de

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#227]
The domain is already reserved by hbz.

**Comment by fsteeg** [comment]
@acka47 I seem to remember that you mentioned having access to the DNS management for this, reassigning.

**Comment by acka47** [comment]
The domain is registered via [DFN](https://www.dfn.de/dienstleistungen/dfninternet/domains/) and DNS entries are configured inhouse by our colleague A.D. I will contact him as soon as we have figured out what DNS entry we need. We will discuss tomorrow whether we need a reverse proxy or whether there is a better way. Please think about it, @dr0i and @fsteeg.

**Comment by fsteeg** [comment]
We will also use emphytos for nwbib.de. @dr0i and me will contact A.D.

**Comment by fsteeg** [comment]
We also need to ask A.D. for SSL certificates.

**Comment by acka47** [comment]
nwbib.de now points to emphytos. What's left is the SSL certificate. @dr0i will cover this according to https://wiki.hbz-nrw.de/display/ZIT/Zertifikate+beantragen (internal wiki).

**Comment by dr0i** [comment]
As there is no wildcard certificate - what (sub)domains we need?
www.nwbib.de , nwbib.de, test.nwbib.de - this' all ?

**Comment by acka47** [comment]
> www.nwbib.de , nwbib.de, test.nwbib.de - this' all ?

Sounds good to me.

**Comment by fsteeg** [comment]
Deployed for staging:

http://nwbib.de

`nwbib.de.conf` uses a ProxyPass:

```
ProxyPass / http://quaoar1.hbz-nrw.de:8001/ nocanon
ProxyPassReverse / http://quaoar1.hbz-nrw.de:8001/
```

http://test.lobid.org/nwbib

`test.lobid.org.conf` replaces the `/nwbib` proxy with a permanent redirect:

```
ProxyPassMatch ^/nwbib(.*) !
RedirectMatch permanent ^/nwbib(.*) http://nwbib.de$1
```

This should ensure that old URLs keep working, like:
http://test.lobid.org/nwbib/search?q=ehrenfeld&issued=2015

Assigning @acka47 for functional review.

After that, or in parallel, we'll have to:

- [ ] Set up DNS to route subdomains to emphytos: @dr0i
- [ ] Set up subdomain proxies and redirects: @fsteeg
- [ ] Set up SSL certificates on emphytos: @dr0i
- [ ] Set up HTTPS proxies and redirects: @fsteeg

**Comment by acka47** [comment]
nwbib.de works. Redirection looks good to meas well:

```
$ curl -v http://test.lobid.org/nwbib/BT000139576
* Hostname was NOT found in DNS cache
*   Trying 193.30.112.187...
* Connected to test.lobid.org (193.30.112.187) port 80 (#0)
> GET /nwbib/BT000139576 HTTP/1.1
> User-Agent: curl/7.35.0
> Host: test.lobid.org
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Date: Tue, 23 Feb 2016 15:05:39 GMT
* Server Apache/2.2.12 (Linux/SUSE) is not blacklisted
< Server: Apache/2.2.12 (Linux/SUSE)
< Location: http://nwbib.de/BT000139576
< Content-Length: 319
< Content-Type: text/html; charset=iso-8859-1
< 
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="http://nwbib.de/BT000139576">here</a>.</p>
<hr>
<address>Apache/2.2.12 (Linux/SUSE) Server at test.lobid.org Port 80</address>
</body></html>
* Connection #0 to host test.lobid.org left intact
```

+1

**Comment by dr0i** [comment]
I also configured already https://test.nwbib.de/.
