### ISSUE TITLE
Wrong map facet label when multiple spatial facets set

### ISSUE THREAD

**Issue by fsteeg** [hbz/nwbib#229]
[Sample link](http://lobid.org/nwbib/search?q=kohle&nwbibspatial=http%3A%2F%2Fpurl.org%2Flobid%2Fnwbib-spatial%23n20&location=64+Orte+aus+Kartenauswahl|51.216184076148224%2C7.632550224608195+51.21610199748479%2C7.6327055165756+51.21603923570643%2C7.6328822834927035+51.21599793769891%2C7.633074478943698+51.21597951614367%2C7.633275528770883+51.21598460118834%2C7.633478555947355+51.23311813570036%2C7.8386353590784585+51.23312301935365%2C7.838685113891687+51.23312932563618%2C7.838734458986859+51.233137041295336%2C7.838783290670354+51.23314615011675%2C7.838831506327461+51.2331566329584%2C7.8388790046379455+51.36602506885735%2C8.400388733069649+51.3660830331772%2C8.400577263947037+51.366162349315104%2C8.40074466822124+51.366260115034%2C8.400884820659655+51.36637275303333%2C8.40099259315986+51.36649614185576%2C8.401064042383876+51.649552894094455%2C8.51773074680015+51.649656589190386%2C8.517760092073003+51.6497618510264%2C8.517763352670075+51.64986616869789%2C8.517740450813465+51.649967053839376%2C8.517691932801137+51.65006209998026%2C8.517618955975593+52.04394790330753%2C8.15095226646048+52.043966308908274%2C8.150934420155686+52.04398435717634%2C8.150915633890143+52.04400202995917%2C8.150895926559055+52.04401930948187%2C8.15087531798425+52.044036178365126%2C8.150853828893784+52.37042202940625%2C7.719742709206225+52.37054590627839%2C7.719527179474444+52.37063015498949%2C7.719265305599178+52.3706686599639%2C7.718976097626968+52.37065862615438%2C7.718680549851315+52.37060078190693%2C7.718400116787184+52.28393526047628%2C7.4328447689869295+52.283934934653715%2C7.4328436979446755+52.283934608117995%2C7.432842627482956+52.28393428086945%2C7.4328415576030515+52.28393395290852%2C7.432840488306161+52.283933624235544%2C7.432839419593641+52.054770127097534%2C6.6906171998880595+52.05463950773921%2C6.690326460861167+52.054458101555454%2C6.690120015744885+52.05424539418017%2C6.690020040263351+52.054024233737%2C6.690037273487159+52.05381837667602%2C6.690169864274348+51.59964812885038%2C7.132392034806099+51.59964346606923%2C7.132396593100041+51.59963882607001%2C7.13240121125458+51.59963420914923%2C7.132405888974631+51.599629615601934%2C7.132410625961354+51.59962504572169%2C7.132415421911951+51.3999401465923%2C7.343351379641766+51.399918035534036%2C7.343375691583667+51.39989653463245%2C7.34340137111369+51.399875676792725%2C7.3434283789327095+51.399855493936016%2C7.343456673708712+51.399836016950445%2C7.343486212140332).

To reproduce: Filter by map, label is ok, add 'Regionen' filter: results are updated, label not.

**Comment by fsteeg** [comment]
Number is calculated when map is clicked, and inserted into the query parameter, resulting in wrong value when other facets are set after the map. Removing number since it's not crucial, and actually redundant (map contains cluster labels with counts).

Deployed to staging: [sample result](http://test.lobid.org/nwbib/search?q=kohle&nwbibspatial=http%3A%2F%2Fpurl.org%2Flobid%2Fnwbib-spatial%23n03&location=Orte+in+Kartenauswahl|50.63269436024214%2C7.0162284439965195+50.632664981219925%2C7.0163559155320465+50.63264578839842%2C7.016488122780914+50.632637074284936%2C7.016623050931048+50.63263897168666%2C7.016758643704417+50.63265145168633%2C7.016892834694137+50.65881845666604%2C7.2130461327145+50.65884666472984%2C7.213200552749099+50.65888885192089%2C7.21334682941416+50.658944115542965%2C7.213481832894795+50.659011273101854%2C7.21360267458337+50.65908888761043%2C7.213706768885507+51.12125968812137%2C7.749497800901785+51.12133070085842%2C7.749570351223575+51.121406742505265%2C7.749628544159286+51.12148667503121%2C7.749671508816799+51.12156930218099%2C7.749698602204251+51.121653387378785%2C7.749709418852868+51.166653323945624%2C7.7510984678464565+51.16675412678104%2C7.751089783251132+51.1668530512784%2C7.751057698629972+51.16694797325173%2C7.751002902935632+51.16703685447307%2C7.750926572795661+51.16711778643695%2C7.7508303472464135+51.48683681659895%2C7.3074970716302445+51.48683763398901%2C7.307495932426993+51.48683845025583%2C7.30749479114852+51.48683926539726%2C7.307493647797626+51.48684007941138%2C7.307492502377229+51.486840892296044%2C7.307491354890163+51.55045136271552%2C7.21749117249995+51.55050742551892%2C7.217402050773712+51.55055673092338%2C7.2173031362251985+51.55059862244575%2C7.217195745910758+51.55063254231766%2C7.217081309742537+51.55065803891114%2C7.216961351448679+51.578457727285944%2C7.056394932085657+51.57847041096357%2C7.05630817775122+51.57847868301008%2C7.056220054534776+51.57848248899196%2C7.056131142350161+51.57848180386417%2C7.05604202630326+51.57847663213519%2C7.0559532928414415+51.55897692759037%2C6.823393030757434+51.55897252995245%2C6.823347745937101+51.55896696183933%2C6.82330279555972+51.5589602329418%2C6.823258257860512+51.55895235497082%2C6.8232142103564675+51.55894334163732%2C6.823170729711343+51.53344360589503%2C6.708240755632211+51.533422938353496%2C6.70815832811412+51.533398194056176%2C6.708078855709382+51.53336953491488%2C6.7080028584585305+51.53333714845818%2C6.707930833661844+51.53330124660431%2C6.707863252625317+51.366336410259294%2C6.418697651491016+51.36626626733896%2C6.418592280293689+51.36618761290614%2C6.418503657172048+51.366101992976716%2C6.418433524129115+51.36601109048789%2C6.418383259721279+51.36591669222067%2C6.418353851961052+51.26675024107858%2C6.398909512983715+51.26669196433946%2C6.398902101318593+51.26663350423881%2C6.398902630330228+51.266575283600964%2C6.398911096192398+51.26651772351979%2C6.398927437674127+51.26646124031319%2C6.398951536582356+51.199794302179384%2C6.43228502439106+51.199776634577525%2C6.432294271709411+51.199759129902944%2C6.432304277132701+51.199741800925615%2C6.432315033361888+51.19972466028732%2C6.43232653255029+51.19970772049246%2C6.432338766309176+50.68910443253177%2C6.812335364076052+50.68901682109228%2C6.812412839352086+50.68893718483323%2C6.812509409349765+50.68886718164537%2C6.812623063700855+50.68880826888233%2C6.812751436379622+50.68876167301798%2C6.812891854958147) from following instructions from above.

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
Deployed to production, closing. [Sample result](http://lobid.org/nwbib/search?q=kohle&nwbibspatial=http%3A%2F%2Fpurl.org%2Flobid%2Fnwbib-spatial%23n65&location=Orte+in+Kartenauswahl|51.216184076148224%2C7.632550224608195+51.21610199748479%2C7.6327055165756+51.21603923570643%2C7.6328822834927035+51.21599793769891%2C7.633074478943698+51.21597951614367%2C7.633275528770883+51.21598460118834%2C7.633478555947355+51.23311813570036%2C7.8386353590784585+51.23312301935365%2C7.838685113891687+51.23312932563618%2C7.838734458986859+51.233137041295336%2C7.838783290670354+51.23314615011675%2C7.838831506327461+51.2331566329584%2C7.8388790046379455+51.36602506885735%2C8.400388733069649+51.3660830331772%2C8.400577263947037+51.366162349315104%2C8.40074466822124+51.366260115034%2C8.400884820659655+51.36637275303333%2C8.40099259315986+51.36649614185576%2C8.401064042383876+51.649552894094455%2C8.51773074680015+51.649656589190386%2C8.517760092073003+51.6497618510264%2C8.517763352670075+51.64986616869789%2C8.517740450813465+51.649967053839376%2C8.517691932801137+51.65006209998026%2C8.517618955975593+52.04394790330753%2C8.15095226646048+52.043966308908274%2C8.150934420155686+52.04398435717634%2C8.150915633890143+52.04400202995917%2C8.150895926559055+52.04401930948187%2C8.15087531798425+52.044036178365126%2C8.150853828893784+52.37042202940625%2C7.719742709206225+52.37054590627839%2C7.719527179474444+52.37063015498949%2C7.719265305599178+52.3706686599639%2C7.718976097626968+52.37065862615438%2C7.718680549851315+52.37060078190693%2C7.718400116787184+52.28393526047628%2C7.4328447689869295+52.283934934653715%2C7.4328436979446755+52.283934608117995%2C7.432842627482956+52.28393428086945%2C7.4328415576030515+52.28393395290852%2C7.432840488306161+52.283933624235544%2C7.432839419593641+52.054770127097534%2C6.6906171998880595+52.05463950773921%2C6.690326460861167+52.054458101555454%2C6.690120015744885+52.05424539418017%2C6.690020040263351+52.054024233737%2C6.690037273487159+52.05381837667602%2C6.690169864274348+51.59964812885038%2C7.132392034806099+51.59964346606923%2C7.132396593100041+51.59963882607001%2C7.13240121125458+51.59963420914923%2C7.132405888974631+51.599629615601934%2C7.132410625961354+51.59962504572169%2C7.132415421911951+51.3999401465923%2C7.343351379641766+51.399918035534036%2C7.343375691583667+51.39989653463245%2C7.34340137111369+51.399875676792725%2C7.3434283789327095+51.399855493936016%2C7.343456673708712+51.399836016950445%2C7.343486212140332) from following instructions from above.
