### ISSUE TITLE
HTML escape sequences in icon popups

### ISSUE THREAD

**Issue by fsteeg** [hbz/nwbib#233]
http://lobid.org/nwbib/search?q=*&t=http%3A%2F%2Fpurl.org%2Fontology%2Fbibo%2FMultiVolumeBook

Hover over type icon -> `Mehrb&auml;ndig`

**Comment by fsteeg** [comment]
Deployed to staging:



http://test.lobid.org/nwbib/search?q=*&t=http%3A%2F%2Fpurl.org%2Fontology%2Fbibo%2FMultiVolumeBook

Hover over type icon -> `Mehrbändig`

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
Deployed to production, closing. See:

http://lobid.org/nwbib/search?q=*&t=http%3A%2F%2Fpurl.org%2Fontology%2Fbibo%2FMultiVolumeBook

Hover over type icon -> `Mehrbändig`
