### ISSUE TITLE
Tweak detail view

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#237]
Requested by stakeholders in mail by G.C. from 2016-01-26:

>	Wir finden die gestraffte Einzeltrefferanzeige gelungen. Noch zwei
	Anmerkungen: 1. Nicht gut finden wir hier die Bezeichnung Ortsbezug, wir
	würden "Raumsystematik" aus sachlichen Gründen bevorzugen. 2. Gibt es
	zwei Schlagwortfolgen, sollten diese auch differenziert werden, z. B.
	durch ein deutliches Trennzeichen (Raute) oder jeweils eine eigene Zeile.

- [ ] Use "Raumsystematik" instead of "Raumbezug"
- [ ] Clear separation of subject chains

(The second point will be easily fixed with data structure of API 2.0.)

**Comment by fsteeg** [comment]
Deployed to staging.

Change `coverage` label to 'Raumsystematik', but append 'Orte' and 'Regionen' if both `coverage` and `nwbibspatial` exist, to avoid duplicate 'Raumsystematik' label. See:

http://test.lobid.org/nwbib/HT018832788
http://test.lobid.org/nwbib/HT018859890
http://test.lobid.org/nwbib/HT016936007

Separate individual subject chains by line breaks, see:

http://test.lobid.org/nwbib/HT018493213

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
Deployed to production, closing.

Change `coverage` label to 'Raumsystematik', but append 'Orte' and 'Regionen' if both `coverage` and `nwbibspatial` exist, to avoid duplicate 'Raumsystematik' label. See:

http://lobid.org/nwbib/HT018832788
http://lobid.org/nwbib/HT018859890
http://lobid.org/nwbib/HT016936007

Separate individual subject chains by line breaks, see:

http://lobid.org/nwbib/HT018493213
