### ISSUE TITLE
Moving all entries from result list to Merkliste

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#238]
Requested by stakeholders in mail by G.C. from 2016-01-26:
              
> Es fehlt  allerdings noch die Möglichkeit, alle Titel einer
		Trefferliste zu markieren und in die Merkliste zu übernehmen.

**Comment by fsteeg** [comment]
Deployed to staging, see arrow pointing at individual stars in a result list, e.g.:

http://test.lobid.org/nwbib/search?q=Köln-Longerich

**Comment by acka47** [comment]
The function of the arrow isn't intuitively understood. Another icon probably wouldn't make things better though. Perhaps we should use text? Anyway, we'll have to discuss this when I am back at work some day...

**Comment by fsteeg** [comment]
Added a 'Merkliste' label in front of the arrow. I like how this also explains the stars next to the individual hits. Also note the tool tip on the link in case you didn't notice it before.

Deployed to staging: http://test.lobid.org/nwbib/search?q=Köln-Longerich

**Comment by acka47** [comment]
> Added a 'Merkliste' label in front of the arrow. 

THis might be mistaken as a link to the "Merkliste". Something short for "Zur Mekrliste inzufügen" would be good...

**Comment by fsteeg** [comment]
OK, so how about this: use same icon as for starring individual results, with details in the popup (like for individual results). See: http://test.lobid.org/nwbib/search?location=&q=K%C3%B6ln-Longerich

**Comment by acka47** [comment]
\o/ Simple and very good solution. I like. +1
