### ISSUE TITLE
Star markers stay set after entries have been deleted from Merkliste

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#239]
Reported by stakeholders in mail by G.C. from 2016-01-26:

> Bei Wiederholung der gleichen Suche waren in der
		neuen=alten Trefferliste die alten gesetzten Markierungen
		immer noch vorhanden, auch als die Merkliste zwischenzeitlich gelöscht 
		worden war.

**Comment by fsteeg** [comment]
Steps to reproduce the issue:

- Open http://lobid.org/nwbib/search?q=neuehrenfeld
- Star both titles
- Click 'Merkliste'
- Unstar first title
- Click browser back button: one starred, one not: all good
- Click 'Merkliste'
- Click 'Merkliste löschen' and confirm
- Click browser back button twice: one title still starred, even after reload

Fix deployed to staging: http://test.lobid.org/nwbib/search?q=neuehrenfeld

**Comment by acka47** [comment]
Currently, I can't evebn reproduce the issue on production as starred items won't be shown in "Merkliste" at all (browser issue?).

On staging adding and deleting works fine though. Thus, +1.

**Comment by fsteeg** [comment]
Deployed to production, closing. See https://github.com/hbz/nwbib/issues/239#issuecomment-176243077 for steps to reproduce fix.
