### ISSUE TITLE
OPAC links don't work for ULBs Düsseldorf and Bonn

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#240]
Reported by stakeholders in mail by G.C. from 2016-01-26:

> Für die Düsseldorfer und die Bonner Bestände 
> 	funktioniert immer noch nicht der Sprung in den lokalen Katalog mit 
> 	sofortiger Anzeige des Titels.  Für den Düsseldorfer lokalen Katalog 
> 	erhält man nur einen Suchschlitz mit der HT-Nummer des Titels und 
> 	müsste dann noch einmal die Suche starten. Das ist sehr verwirrend für 
> 	den Benutzer, denn er kennt ja keine HT- Nummer und darüber hinaus 
	wird auch noch "keine Treffer" gemeldet.

We will have to fix this in https://github.com/hbz/link-templates/blob/master/isil2opac_hbzid.json.

**Comment by fsteeg** [comment]
Deployed to staging, see:

http://test.lobid.org/nwbib/HT017595568
http://test.lobid.org/nwbib/HT018525192
http://test.lobid.org/nwbib/HT017847194

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
Deployed to production, closing. See:

http://lobid.org/nwbib/HT017595568
http://lobid.org/nwbib/HT018525192
http://lobid.org/nwbib/HT017847194
