### ISSUE TITLE
Outer NRW border lighter than inner borders

### ISSUE THREAD

**Issue by fsteeg** [hbz/nwbib#247]
Inner borders are painted stronger than the outer border.

A possible fix would be to add an additional outer border.

This could also provide a way to incorporate this feedback (by G.C., 26.1.):

> Vielleicht wäre es auch möglich, die Umrisse der Gesamtkarte durch Schraffur plastischer hervortreten zu lassen?

**Comment by fsteeg** [comment]
Deployed to production, see: http://test.lobid.org/nwbib

**Comment by acka47** [comment]
We should give it a try with the current map and the "Gemeinden". Thus, +1.

**Comment by fsteeg** [comment]
Deployed to production, closing. See: http://lobid.org/nwbib
