### ISSUE TITLE
Black map in IE

### ISSUE THREAD

**Issue by fsteeg** [hbz/nwbib#254]
Reported by E.L., NWBib-Mail 2016-02-19

**Comment by fsteeg** [comment]
I also get the issue in Chromium (Mac, 41.0.2231.0)

**Comment by fsteeg** [comment]
Deployed to staging: http://test.lobid.org/nwbib

I've tested in Chromium, do you have an IE at hand, @acka47?

**Comment by acka47** [comment]
> I've tested in Chromium, do you have an IE at hand, @acka47?

Works in IE as well.
