### ISSUE TITLE
Error on details

### ISSUE THREAD

**Issue by fsteeg** [hbz/nwbib#255]
http://lobid.org/nwbib/HT018582218

**Comment by fsteeg** [comment]
Deployed to staging, see:

http://test.lobid.org/nwbib/HT018582218
http://test.lobid.org/nwbib/HT018596489
http://test.lobid.org/nwbib/HT018596444
http://test.lobid.org/nwbib/HT018755634
http://test.lobid.org/nwbib/HT005016197

**Comment by acka47** [comment]
+1
