### ISSUE TITLE
Additional path segment for details view?

### ISSUE THREAD

**Issue by fsteeg** [hbz/nwbib#256]
Brought up by @acka47:

http://lobid.org/nwbib/HT017903876 (will be `http://nwbib.de/HT017903876`) or
http://lobid.org/nwbib/details/HT017903876 (will be `http://nwbib.de/details/HT017903876`)

If the answer is the latter, what should we serve for:

http://lobid.org/nwbib/details (will be `http://nwbib.de/details`)
Perhaps simple instructions: "Details for titles can be acccessed directly or via search..."

**Comment by fsteeg** [comment]
I'd consider the data set name `nwbib` to be moved up from `lobid.org/nwbib` to `nwbib.de`. So `http://nwbib.de/HT017903876` is the `nwbib` entry for `HT017903876`. I think this current solution is good and this issue can be closed.

**Comment by acka47** [comment]
+1. Closing.
