### ISSUE TITLE
nwbibspatial facet checkbox not set

### ISSUE THREAD

**Issue by fsteeg** [hbz/nwbib#257]
See http://lobid.org/nwbib/search?nwbibspatial=Essen-Kettwig

**Comment by fsteeg** [comment]
To reproduce: this happens when clicking non norm data links from details view, e.g. `Ascheberg-Herbern` from http://test.nwbib.de/HT007070509, not when actually facetting over `nwbibspatial`.

**Comment by fsteeg** [comment]
Deployed to staging, see literal `Raumsystematik` links from:

http://test.nwbib.de/HT007070509
http://test.nwbib.de/HT018582218
http://test.nwbib.de/HT015518874

**Comment by acka47** [comment]
+1
