### ISSUE TITLE
No ISBN with data 2.0

### ISSUE THREAD

**Issue by fsteeg** [hbz/nwbib#260]
See: 

http://lobid.org/nwbib/HT018807238
http://gaia.hbz-nrw.de:9200/resources/resource/HT018807238

**Comment by dr0i** [comment]
But the data resides in the new data (search for `isbn` in http://gaia.hbz-nrw.de:9200/resources/resource/HT018807238 ).

**Comment by fsteeg** [comment]
Yes, this is just an nwbib/UI issue, I only added the gaia link for reference to the data to use.

**Comment by fsteeg** [comment]
Deployed to staging, see:

http://test.nwbib.de/HT018807238
http://test.nwbib.de/HT005016197

**Comment by acka47** [comment]
+1 Out of curiosity: Did we have the pipe-separated ISBNs for titles with two ISBNs before?

**Comment by fsteeg** [comment]
> Out of curiosity: Did we have the pipe-separated ISBNs for titles with two ISBNs before?

Conceptually yes, but the display is still quite new, before we had repeated table rows instead of pipe-separated values in a single row.
