### ISSUE TITLE
Repair link to journal under "Zum Bestand siehe"

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#264]
Reported by U.P.on 2016-02-25:

> Wenn ich von einem Aufsatz kommend rechts oben auf den Bestand der Quelle=Zeitschrift klicke, erhalte ich nur unverständliche Angaben. Beispiel:
> https://nwbib.de/HT017196116

Currently, the link goes to lobid.org/resource instead of lobid.org/nwbib.

**Comment by fsteeg** [comment]
Deployed to staging: http://test.nwbib.de/HT017196116

**Comment by acka47** [comment]
+1
