### ISSUE TITLE
Fix Umlauts in field "Publikationstyp"

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#265]
Reported via email by U.P. on 2016-02-25:

> Bei mehrbändigen Werken wird beim Publikationstyp "mehrbändig" der Umlaut sehr unschön dargestellt. Beispiel:
> https://nwbib.de/HT018486420

**Comment by fsteeg** [comment]
Deployed to staging: http://test.nwbib.de/HT018486420

**Comment by acka47** [comment]
+1
