### ISSUE TITLE
Detail view not working

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#266]
Example of title without working detail view: https://nwbib.de/HT006933578

Reported via email by U.P. on 2016-02-25:

> Wenn ich das Heimat-Blatt Unterrath-Lichtenbroich suche, erhalte ich zwei Treffer. Die elektr. Ausg. wird korrekt angezeigt. Bei Klick auf die gedr. Ausg. erhalte ich eine Fehlermeldung.
> https://nwbib.de/search?name=heimat-blatt+unterrath-lichtenbroich&person=&subject=

**Comment by fsteeg** [comment]
Deployed to staging, see:

http://test.nwbib.de/HT006933578
http://test.nwbib.de/HT016841615

**Comment by acka47** [comment]
+1
