### ISSUE TITLE
Errors on all details pages with data 2.0

### ISSUE THREAD

**Issue by fsteeg** [hbz/nwbib#271]
All detail pages yield errors when using data 2.0 for viewing.

Toggled production to use data 1.x, issue is reproducible on staging: http://test.nwbib.de/

Will investigate. @dr0i: Any idea about possible changes in the production data 2.0 since yesterday?

**Comment by dr0i** [comment]
Yes, new index was deployed. See hbz/lobid-rdf-to-json#29.

**Comment by fsteeg** [comment]
Updates for `@id` -> `id` and new `type` structure deployed to staging: http://test.nwbib.de
