### ISSUE TITLE
Update index page text

### ISSUE THREAD

**Issue by fsteeg** [hbz/nwbib#273]
U.P, 2016-02-26:

> Bei allen Recherchen haben Sie die Möglichkeit, die Treffer nach räumlichen und sachlichen Gesichtspunkten, nach Dokumentengruppen und Bibliotheksbestand einzugrenzen.

**Comment by fsteeg** [comment]
Deployed to staging: http://test.nwbib.de

**Comment by acka47** [comment]
+1
