### ISSUE TITLE
Unstar all hits on page

### ISSUE THREAD

**Issue by fsteeg** [hbz/nwbib#275]
U.P., 2016-02-25

> es fehlt die Möglichkeit, für alle Treffer die Markierung über das Sternchen oben zentral auch wieder zu entfernen.

**Comment by fsteeg** [comment]
Deployed to staging. See any search result, e.g. http://test.nwbib.de/search?q=longerich

**Comment by acka47** [comment]
Hmm, I liked the star icon we ha dbefore. Would be nice to have star icons with a `+` and `-`. I guess, this isn't available. (Ceterim censeo, we need a designer.)

**Comment by fsteeg** [comment]
Thanks for your persistence in finding a good solution around this functionality!

The toggle option we discussed offline was actually much easier to implement than I expected.

Deployed to staging: http://test.nwbib.de/search?q=longerich

**Comment by acka47** [comment]
+1
