### ISSUE TITLE
Don't display `nwbibspatial` `96` and `97` if `coverage` is given

### ISSUE THREAD

**Issue by fsteeg** [hbz/nwbib#276]
My interpretation of E.L., 2016-02-19:

>Dabei ist uns aufgefallen, dass sich hinter der Benennung „Raumsystematik: Orte“ die GSW bestimmter Kreise und Regierungsbezirke befinden. http://lobid.org/nwbib/HT006696859 Zusätzlich tauchen unter der Benennung  „Raumsystematik: Regionen“ die allgemeinen Begriffe  Regierungsbezirke (96) und Kreise (97) auf. Sie sollten hier aber erst gar nicht erscheinen, da es sich ja inhaltlich um bestimmte Kreise und Bezirke handelt – analog zur alten NWBib. Diese Notationen werden nur vergeben, wenn es in dem Dokument allgemein um Kreise und Regierungsbezirke geht, was relativ selten der Fall ist.

**Comment by fsteeg** [comment]
@acka47 I suspect we still didn't really understand the mapping for these fields, but given our current software and situation I think the solution from this issue's title makes sense. What do you think?

**Comment by fsteeg** [comment]
Correction: I guess this should only happen for `96` and `97` in `nwbibspatial`. Updating title.

**Comment by acka47** [comment]
> @acka47 I suspect we still didn't really understand the mapping for these fields, but given our current software and situation I think the solution from this issue's title makes sense. What do you think?

If I remember correctly, our handling of these fields dates back to a point where we didn't have/use the "coverage" field. However, I agree with the suggested solution and add as example [HT006696859](http://nwbib.de/HT006696859). It looks like this in the source:

```xml
<datafield tag="700" ind1="n" ind2="1">
  <subfield code="a">96</subfield>
  <subfield code="b">Regierungsbezirk Detmold</subfield>
</datafield>
```

The proposed solution goes like this. If subfield `b` of 700n is given, we add this to the "coverage" field – as we already do:

```json
"coverage":[
   "Bielefeld",
   "Regierungsbezirk Detmold"
],

```

But we should _not_ add `http://purl.org/lobid/nwbib-spatial#n96` to the "nwbibspatial" field (which we currently do). In short, for the given example, the following information should be **removed** from the data:

```json
nwbibspatial":[
   {
      "id":"http://purl.org/lobid/nwbib-spatial#n96"
   }
],

```

**Comment by acka47** [comment]
Just noticed that I thought about this like we would have to adjust the data transformation but @fsteeg only proposed to adjust the presentation in NWBib. As the underlying data isn't really wrong but just gives an accurate representation of the base data, it's+1 from me for only adjusting the presentation.

**Comment by fsteeg** [comment]
Deployed to staging:

http://test.nwbib.de/HT006696859 (sample from this issue, no `96`)
http://test.nwbib.de/HT018902207 (no `coverage`, is actually about `96`)
http://test.nwbib.de/HT017203152 (will have additional `coverage` when https://github.com/hbz/lobid-resources/issues/44 is done)

**Comment by fsteeg** [comment]
We just discussed offline that we'll also remove 10, 12, 14, 24, 28, 35, 36, 37, 52, 54, 72, 74 as requested by stakeholders (see also https://github.com/hbz/lobid-resources/issues/44).

**Comment by fsteeg** [comment]
Deployed to staging: http://test.nwbib.de/HT017203152

No longer has `10`, will have additional coverage instead when hbz/lobid-resources#44 is done.

**Comment by acka47** [comment]
+1
