### ISSUE TITLE
'Show less' facet links

### ISSUE THREAD

**Issue by fsteeg** [hbz/nwbib#277]
U.P., 2016-02-25

> Wäre es möglich, unter den Facetten zu dem "zeige mehr Facetten" auch einen Button zu haben "zeige weniger Facetten", sodass man stufenweise wieder zuklappen kann?

**Comment by fsteeg** [comment]
Deployed to staging, see e.g. http://test.nwbib.de/search?q=ehrenfeld

**Comment by acka47** [comment]
+1
