### ISSUE TITLE
Wrong count in holdings facet

### ISSUE THREAD

**Issue by fsteeg** [hbz/nwbib#279]
U.P., 2016-02-25

> In der Facette "Bestand" wird hinter den einzelnen Facettengliedern nicht die korrekte Zahl der in einer Bibliothek vorhandenen Medien wiedergegeben. Wenn man auf die Trefferliste selbst schaut, hat man die richtige Anzahl. Beispiel: http://nwbib.de/search?name=&person=&subject=d%C3%BCsseldorf+geschichte Nur 43 Titel in der Facette "Bestand" zur ULB Düsseldorf, klicke ich dann aber drauf, hat die Trefferliste 734 Treffer mit Bestand in der ULB Düsseldorf.

**Comment by fsteeg** [comment]
Deployed to staging, see: http://test.nwbib.de/search?subject=düsseldorf+geschichte

**Comment by acka47** [comment]
The numbers still differ a bit (750 in the facet and 740 when setting the filter). I guess this is because for some resources the library holds more then one item, isn't it?
Anyway, +1.

**Comment by fsteeg** [comment]
That sounds like a good explanation.

Also, facet counts are only estimates in general according to the Elasticsearch documentation.
