### ISSUE TITLE
Subject facet empty

### ISSUE THREAD

**Issue by fsteeg** [hbz/nwbib#286]
No subject facet content for any query, e.g. http://nwbib.de/search?q=ehrenfeld

**Comment by fsteeg** [comment]
Edit: updated description and comment. It's actually a general issue: the subject facet is gone.

@dr0i: Any production updates/changes in the last hour or so?

**Comment by dr0i** [comment]
Nope.

**Comment by fsteeg** [comment]
Deployed to staging: http://test.nwbib.de/search?q=ehrenfeld

Was caused by `@id` to `id` switch. No idea why it was still working earlier today though.

**Comment by acka47** [comment]
+1
