### ISSUE TITLE
Add main map with Gemeinden

### ISSUE THREAD

**Issue by fsteeg** [hbz/nwbib#29]

**Comment by fsteeg** [comment]
Our plans for map-based visualization and exploration of the data are now focussed on the `coverage` field (see #139). Closing.

**Comment by fsteeg** [comment]
While working on #247 it occurred to me that there's a relatively easy way to implement our early idea to provide a map with the NRW-Gemeinden as an option to the NRW-Kreise in the main map. Reopening.

**Comment by fsteeg** [comment]
Deployed to staging: http://test.lobid.org/nwbib

I had the impression that this level is actually more interesting, so I've set it up as the default.

The maps can be switched with a link from the description text on the main page.

**Comment by acka47** [comment]
As already said in another issue, we should give it a try and ask the stakeholders' opinion. +1

**Comment by fsteeg** [comment]
Deployed to production, closing. See: http://lobid.org/nwbib
