### ISSUE TITLE
Use "title" value as HTML <title>

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#291]
For detail views t would be good to have the title of the shown bibliographic resource as title of the HTML page instead of the generic `<title>NWBib - Vollanzeige</title>` for every resource. This would be nice for people with several tabs open and would probably also make sense from an SEO point of view.

**Comment by fsteeg** [comment]
Deployed to staging, see:

http://test.nwbib.de/HT017718339
http://test.nwbib.de/HT017253098
http://test.nwbib.de/HT016989920

**Comment by acka47** [comment]
This looks better but I am not sure whether we shouldn't add something more to the HTML title. Maybe a `NWBib: ` before every title. Or maybe the author name before the title. (would this be a problem to implement?). What do you think?

**Comment by fsteeg** [comment]
I actually had it deployed with "NWBib - " prepended first, but in a browser window with a few tabs all I saw was the "NWBib" part, so I changed that before assigning for review. Prepending the author should be possible, but I don't see the advantage. The resources have a clearly defined title, which I think is the ideal content for the HTML title.

**Comment by acka47** [comment]
Ok. As you tried other approaches, I say: +1
