### ISSUE TITLE
Data 2.0 subject chain links in details yield 0 hits

### ISSUE THREAD

**Issue by fsteeg** [hbz/nwbib#292]
Samples:

http://nwbib.de/HT017832548
http://nwbib.de/HT017312517

**Comment by fsteeg** [comment]
If the `subjectChain` values will be identical in 1.x and 2.0 after https://github.com/hbz/lobid-resources/issues/29 is fixed, this should be fixed automatically. @dr0i Will they be identical?

**Comment by dr0i** [comment]
yes, after fulldump deployement , which takes 13 h. (Syncing the morph was easy here.)

**Comment by fsteeg** [comment]
Fix via https://github.com/hbz/lobid-resources/issues/29 deployed to production, closing. See:

- http://nwbib.de/HT017832548 `->` http://nwbib.de/search?q=%22Heinrich-Heine-Institut%2C+Rheinisches+Literaturarchiv+|+Archivp%C3%A4dagogik+|+Jugend+|+Projekt+|+Geschichte+2009-2011%22
- http://nwbib.de/HT017312517 `->` http://nwbib.de/search?q=%22LWL-Archivamt+f%C3%BCr+Westfalen%2C+Westf%C3%A4lisches+Literaturarchiv+|+Geschichte+2001-2011%22
