### ISSUE TITLE
Performance issue on index page

### ISSUE THREAD

**Issue by fsteeg** [hbz/nwbib#296]
Reported on 2016-03-14 by U.P.:

> Das Aufrufen der Webhauptseite generell, also die Eingabe von "nwbib.de" oder der Klick nach einer Suche oder aus einer Trefferliste heraus auf die Startseite "NWBib" dauert doch etwas zu lange, zumal es ganz links oben so aussieht, als ob der Browser hängt.

See also #274

@dr0i Suspected an HTTPS issue (old lynx won't open https://nwbib.de/, reproducible e.g. on quaoar1 with `lynx https://nwbib.de/`). But this 1) would lead to not loading at all, 2) would presume entering "nwbib.de" redirects to HTTPS.

My first guess would be a Javascript/SVG performance issue with IE.

**Comment by fsteeg** [comment]
Made index page map script `async` to mitigate slow performance.

Deployed to staging: http://test.nwbib.de

@acka47 Could you give it a try in IE and check if you notice any difference?

**Comment by acka47** [comment]
I just tried it in IE and don't notice any difference. Both production and staging work fine. I will contact U.P. and ask her to try out test.nwbib.de

**Comment by acka47** [comment]
Just talked to U.P. The problem occurs in [Firefox ESR 38.4.0](https://www.mozilla.org/en-US/firefox/38.4.0/releasenotes/) _every_ time the home page is loaded. I tried to reproduce it in my Firefox (44.0.2) and actually encountered the problem twice (in about ten tries) myself. It won't occur anymore, although I tried it a lot.

U.P. will try this out on different computers/browsers and report how it works.

**Comment by acka47** [comment]
Am 17.03.2016 um 10:14 schrieb U.P.:
> 
> der Benutzer-PC, auf dem ich gerade die NWBib getestet habe, hat die 
> Firefox Version 44.0.2
> 
> Ich hatte dort aber das gleiche Phänomen. Innerhalb einer Recherche mit 
>   mehrfacher Facettierung, Einzeltrefferanzeige, Bestandsanzeige, Zoomen 
> über die Karte ging alles ganz schnell. Aber das Zurücksetzen von einer 
> Recherche oder Einzeltrefferanzeige auf „NWBib“, auf den Start, dauerte 
> 5-6 Sek., wobei das grüne Kreis-Icon ganz oben links in der Ecke des 
> Bildschirms auch stockte und sich nicht drehte, ebenso wenn ich über 
> Google „nwbib“ eingegeben hatte und dann auf den Link der 
> Google-Trefferliste geklickt habe.

**Comment by acka47** [comment]
This is really strange. As I said, I can not reproduce this with the same Firefox version on Linux. I also tried it on a Windows PC running Firefox 44.0.2 and could also _not_ reproduce the problem.

BTW, U.P. pointed out that it used to work and that the problem appeared after one of our changes to the site.

**Comment by acka47** [comment]
U.P. just pointed out via email that the fix in #297 didn't bring any improvements but instead may even have made things worse.

> also, eine Verbesserung habe ich mit http://test.nwbib.de/ nicht feststellen können. Auf meiner alten Firefox-Version an meinem Dienst-PC sind jetzt auch die Recherchen und Facettierungen  einen Hauch langsamer geworden, meinem Empfinden nach. An dem Benutzer-PC mit aktueller Firefox-Version gingen die Recherchen und Facettierungen genauso schnell wie sonst, aber der Start bei Eingabe der URL eher noch langsamer und auch der Klick auf den Start-Button auf der Homepage war eher noch langsamer, beides etwa 7-8 Sek.

**Comment by fsteeg** [comment]
> BTW, U.P. pointed out that it used to work and that the problem appeared after one of our changes to the site.

If I remember correctly, the issue came up with the switch to Gemeinden as default for the main map. That map has way more segments in the SVG, and it's created with Javascript, so maybe that's the issue. Deployed Kreise as default to staging, to pin down the issue: http://test.nwbib.de

**Comment by acka47** [comment]
+1 for making "Kreise" the default view. U.P. just confirmed the performance improvement:

Am 17.03.2016 um 13:46 schrieb U.P.:
> Volltreffer! Mit der Karte nach Kreisen statt nach Gemeinden als Default geht es wieder ganz schnell, sowohl auf meinem DienstPC also auch auf dem BenutzerPC.
