### ISSUE TITLE
Missing MAB-Source

### ISSUE THREAD

**Issue by jschnasse** [hbz/nwbib#303]
http://lobid.org/resource/HT018097995/about?format=source

**Comment by fsteeg** [comment]
```
GET HT018097995: Service Unavailable
{"error":"NoShardAvailableActionException[[hbz01][0] null]","status":503}
```

http://lobid.org/resource/HT018097995

**Comment by fsteeg** [comment]
The `hbz01` mabxml index was broken after outage of quaoar2 (see https://github.com/hbz/nwbib/issues/302). If my understanding is correct, this caused all source requests to fail. I was going to switch to a different index and delete the old hbz01 index (which had unallocated shards even after quaoar2 came back). After deleting it via the head plugin on quaoar3 it started recovering, so the shard issue was probably on one node only, and it recovered from the other.

Todays updates are still running, but your sample is there:
http://lobid.org/resource/HT018097995/about?format=source

Assiging @jschnasse for review.
