### ISSUE TITLE
Adjust tooltip for general search

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#307]
Requested by H.F. via mail on 2016-03-24:

> Bei den Booleschen Operatoren erscheint uns der Tooltip bei der übergreifenden Suche schwer verständlich.

Alternative proposed by me: "Boolesche Operatoren: AND, OR, AND NOT"

**Comment by fsteeg** [comment]
Your actual suggestion from the mail (2016-04-06):

> "Boolesche Operatoren: AND, OR, AND NOT; Phrasensuche mit "", Trunkierung mit *"

**Comment by fsteeg** [comment]
Deployed to staging: http://test.nwbib.de/

**Comment by acka47** [comment]
+1
