### ISSUE TITLE
Error for resource HT017411546

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#308]
HTTP 500 Internal Server Error for GET on http://nwbib.de/HT017411546. 

The reason is that this resource doesn't exist in API 2.0:
```
$ curl -i http://lobid.org/resources/HT017411546
HTTP/1.0 404 Not Found
```

**Comment by fsteeg** [comment]
This is not a new resource, so it's not an issue about missing updates or similar. Tried manually reindexing the missing resource, but no luck (only its items end up in the index), will need further investigation, opened https://github.com/hbz/lobid-resources/issues/69.

For nwbib, I've set up a fall back: use data 1.x if no data 2.0 is found for the requested resource. 

Deployed to staging: http://test.nwbib.de/HT017411546

**Comment by acka47** [comment]
+1
