### ISSUE TITLE
Remove beta notice

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#310]

**Comment by fsteeg** [comment]
I think this is due (since the decision of the LBK actually).

@acka47: I seem to remember you mentioned some objections by stakeholders? Are these still current? Maybe we should bring this up in our next mail to the list?

**Comment by acka47** [comment]
As there are no open issues that customers want to be dealt with before official launch, I agree that the NWBib already is out of beta and say +1 for removing the notice.

**Comment by fsteeg** [comment]
Deployed to staging, see: http://test.nwbib.de

(also updated some links, see a186b72529ea5aa916834a01177600f443ee8fe6 for details)

**Comment by acka47** [comment]
+1

**Comment by acka47** [comment]
As you pointed me again to the changed links. I tend to leave out the hbz union catalog completely and to not point to the Aleph system.
