### ISSUE TITLE
Error on some detail pages

### ISSUE THREAD

**Issue by fsteeg** [hbz/nwbib#311]
See:

http://nwbib.de/HT017955685
http://nwbib.de/HT017056117
http://nwbib.de/HT016421108
http://nwbib.de/HT015477605

**Comment by acka47** [comment]
All of these have a DDC notation under subject, e.g. from http://lobid.org/resources/HT015477605:

```json
"subject":[
   {
      "id":"http://d-nb.info/gnd/4008054-7",
      "preferredName":"Braunkohlenindustrie",
      "preferredNameForTheSubjectHeading":"Braunkohlenindustrie"
   },
   {
      "id":"http://d-nb.info/gnd/4131791-9",
      "preferredName":"Braunkohlenbergbau",
      "preferredNameForTheSubjectHeading":"Braunkohlenbergbau"
   },
   {
      "id":"http://d-nb.info/gnd/4466117-4",
      "preferredName":"Kierdorf",
      "preferredNameForThePlaceOrGeographicName":"Kierdorf"
   },
   {
      "id":"http://dewey.info/class/620/"
   }
]
```

**Comment by fsteeg** [comment]
Looks like it was a caching issue, works after restart, closing. See:

http://nwbib.de/HT017955685
http://nwbib.de/HT017056117
http://nwbib.de/HT016421108
http://nwbib.de/HT015477605
