### ISSUE TITLE
"Band Band" in subordination label

### ISSUE THREAD

**Issue by fsteeg** [hbz/nwbib#312]
See http://nwbib.de/HT018905269

**Comment by acka47** [comment]
The additional "Band" comes from the source data, field 451, see http://lobid.org/hbz01/HT018905269 and [current morph, lines 1627-1629](https://github.com/hbz/lobid-resources/blob/2823082f4879750418050e58c0679c9263cb43a0/src/main/resources/morph-hbz01-to-lobid.xml#L1627-L1629).

We might prevent such things by using the volume information from 456. I am not sure whether this won't result in other problems, though...

**Comment by acka47** [comment]
Similar problem here: http://nwbib.de/HT018906840 In both cases, the superordinated resource (http://nwbib.de/HT014160257 resp. http://nwbib.de/HT018906836) is typed as `MultiVolumeWork` but the volumes are related to it with `inSeries` which seems wrong. This doesn't seem to be the reason, though, as all other subordinated resources from http://nwbib.de/HT014160257 look fine, see [here](http://nwbib.de/search?set=*&raw=%40graph%5C.http%5C%3A%5C%2F%5C%2Fpurl%5C.org%5C%2Flobid%5C%2Flv%23series%5C.%40id%3Ahttp%5C%3A%5C%2F%5C%2Flobid%5C.org%5C%2Fresource%5C%2FHT014160257).

As said in the comment before, we should prbably best look into using field 456 for numberng of titles in a series instead.

**Comment by fsteeg** [comment]
Fixed it on the UI level: remove "Band" (if it's there) before adding it to the label.

If there were two separate fields in the source data for only the title and only the numbering that would be a cleaner solution indeed. As I understand we have to process 451 in any case, and the inconsistency is in the source data (sometimes 451 contains Band, sometimes not), so I think we can leave it like it is.

Deployed to staging, see:

http://test.nwbib.de/HT018905269
http://test.nwbib.de/HT018906840
http://test.nwbib.de/HT014101050

**Comment by acka47** [comment]
+1
