### ISSUE TITLE
Link from subjects to topics search

### ISSUE THREAD

**Issue by fsteeg** [hbz/nwbib#315]
See mail by H.F., 2016-04-19.

For instance `Rundfunkempfänger` in http://nwbib.de/HT018863397 should *additionally* link to:
http://nwbib.de/topics?q=%09Rundfunkempf%C3%A4nger

**Comment by fsteeg** [comment]
Discussed with @acka47 offline: not _additional_ links, instead replace GND links.

**Comment by fsteeg** [comment]
Deployed to staging:

http://test.nwbib.de/HT018907075
http://test.nwbib.de/HT018888782

**Comment by acka47** [comment]
I think the links into the "Themensuche" should only be shown for GND subjects, i.e. for the "Schlagwörter" field. Also the icon seems quite wide probably because it is so flat. Are there other options?

**Comment by fsteeg** [comment]
About the links from the nwbib classification: I think omitting these only makes sense from a cataloger perspective. From a user perspective, why would I get the links for one kind of subject, but not for the other. Also, the two linked examples show that these links allows topics to be discovered that wouldn't be without these links (nwbib classification with values that are not in the subjects, but part of topics).

About the icon: I tried a lot of icons, and I think the one now deployed makes most sense in two ways: as an ellipsis (...) it represents the parts of the linked topics that are not displayed in the details view, and the dots contained in a little box can also represent the topic (subject chain) itself. Finally with its low height, it's not too visually dominant (in detail views with many subjects).

**Comment by acka47** [comment]
> About the links from the nwbib classification: I think omitting these only makes sense from a cataloger perspective. From a user perspective, why would I get the links for one kind of subject, but not for the other.

1. It's librarians who currently tell us what to do. And they only asked for having this link to "Themensuche" next to subjects and not notations of a classification.
2. Having the links next to "sachsystematik" entries suggests that they are already searched for in the Themensuche which is not the case. Themensuche is only based on GND/RSWK. I find it confusing when the distinctions between the different subjects are blurred. It is hard to understand anyway. 

I suggest leaving them out for now and asking stakeholders whether they would like to have them.

**Comment by fsteeg** [comment]
Restored previous display of nwbibsubject field.

Deployed to staging:

http://test.nwbib.de/HT018907075
http://test.nwbib.de/HT018888782

**Comment by acka47** [comment]
+1
