### ISSUE TITLE
Include alternate labels in "Themensuche"

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#317]
This basically means for a Themensuche search:

- query via the subject parameter, e.g. http://nwbib.de/search?subject=m%C3%BCllentsorgungmaking
- retrieve, sort and list subject chains in all results 

Requested by H.F. – amongst others via email on 2016-02-24:

> - Ihre ursprüngliche Integration der SW-Verweisungen in die Themensuche ist ja zu Beginn des Projekts nur ausgesetzt worden, sollte doch aber insbesondere zur möglichsten Vermeidung von 0-Treffer-Anzeigen noch einmal aufgegriffen werden, zumal jetzt, da sie die Datenorganisation verbessert haben. Hier werden wir dann testen müssen.

And on 2016-04-19:

> Doch bleibt es eine Herausforderung, unseren Nutzern Titel etwa zur Abfallbeseitigung auch dann zugänglich zu machen, wenn sie eben statt mit der bibliothekarischen Vorzugsbezeichnung „Abfallbeseitigung“ mit den ebenfalls gängigen Begriffen „Müllbeseitigung“ oder „Müllentsorgung“ suchen, die wir im GND-Satz auch als Verweisungsformen vorhalten: Wir haben hier sachlich etwas zu bieten und tun weder den Suchenden noch uns Anbietern einen Gefallen, wenn wir das, was wir haben, nicht über die Rampe bringen.

**Comment by acka47** [comment]
Regarding the example "Abfallbeseitigung":

- We currently have 217 records with this subject in NWBib: http://nwbib.de/search?subject=4000100-3
- 354 results for "Abfallbeseitigung" in Themensuche
- 0 hits for "[Müllbeseitigung](http://nwbib.de/topics?q=m%C3%BCllbeseitigung)" oder "[Müllentsorgung](http://nwbib.de/topics?q=m%C3%BCllentsorgung)" in Themensuche

**Comment by fsteeg** [comment]
From its basic idea this should work. And it looks good for the two examples:

http://test.nwbib.de/topics?q=müllbeseitigung
http://test.nwbib.de/topics?q=müllentsorgung

However, we get weird results for some subject queries. Seems to be a general issue with the subject search, but the topic search exposes it very visibly.

Topic search:
http://test.nwbib.de/topics?q=römer

Subject query:
http://lobid.org/resource?subject=römer&set=NWBib&format=full

Includes:
http://lobid.org/resource?id=BT000138475&format=full

Subject search uses `subjectChain` and `subjectLabel`, but neither includes `römer` or `romer`. Could be an issue with the index profile. The issue does not seem to exist in data 2.0:

http://lobid.org/resources?q=(subjectChain:römer+OR+subjectLabel:römer)+AND+collectedBy.id:NWBib

However, data 2.0 does not have proper german anlyzers set up for these fields yet. We also have no facets support yet, so using data 2.0 for this wouldn't be trivial either. At the same time, I don't think we should work on this in API 1.x, as we're focussing on data 2.0.

This leaves us with two options as far as I see:

1) Deploy topic search with alternate labels as now on staging, and fix the issue later based on API 2.0
2) Wait until we can deploy a correct topic search with alternate labels based on API 2.0

**Comment by acka47** [comment]
I have the feeling that the number of queries where the problem you describe acutally exists is quite small. NWBib stakeholders would probably already have realized when comparing old and new NWBib when this would affect lots of queries. For your example subject search for "römer":

- new NWBib: 1552 results (http://nwbib.de/search?sort=newest&subject=r%C3%B6mer)
- old NWBib: 260 results

Thus, I tend to deploy the changes on production and to take care of the subject chains starting with a `: `. This obviously is a problem within the morph which will hopefully just disappear with our new approach to subject chains and Themensuche in the context of API 2.0.  As you said, it would be nice if the NWBib frontent just wouldn't list these results.

**Comment by fsteeg** [comment]
Deployed removal of topics starting with `:` to staging:

http://test.nwbib.de/topics?q=römer
http://test.nwbib.de/topics?q=köln

**Comment by acka47** [comment]
+1
