### ISSUE TITLE
Re-create product page on hbz website

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#324]
Before the relaunch of the hbz website there was a "product page" for NWBib. Currently, there is no such page.

**Comment by acka47** [comment]
I just wrote an email to the hbz marketing asking how to re-create the NWBib page on the new site.

**Comment by acka47** [comment]
A first version of the page is now online. I didn't put too much effort into it but just updated the last product page. We can easily adjust it if you wish, @fsteeg.

**Comment by fsteeg** [comment]
Content is fine. The name and resulting URL is rather long:

https://www.hbz-nrw.de/produkte/linked-open-data/nordrhein-westfaelische-bibliographie-nwbib

And not consistent with other pages, which seem to prefer the short version, e.g.:

https://www.hbz-nrw.de/produkte/open-access/dipp
https://www.hbz-nrw.de/produkte/digibib-loesungen/digibib

I don't really mind, but wanted to mention it, reassigning.

**Comment by acka47** [comment]
I contacted the marketing colleagues and they adjusted the URL: https://www.hbz-nrw.de/produkte/linked-open-data/nwbib. Closing.
