### ISSUE TITLE
Map quest tiles are not available anymore

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#325]
See any map on nwbib. See also hbz/lobid-organisations#234.

**Comment by fsteeg** [comment]
Deployed to staging, see:

http://test.nwbib.de/search?q=böll
http://test.nwbib.de/search?location=51.18333340622485%2C7.2000000067055225
http://test.nwbib.de/HT018950446

**Comment by dr0i** [comment]
+1

**Comment by acka47** [comment]
+1
