### ISSUE TITLE
Error on HT018833649 details

### ISSUE THREAD

**Issue by fsteeg** [hbz/nwbib#327]
Reported by @aquast.

See http://nwbib.de/HT018833649

Also:

> Die Fehler- / Kontaktinformation ist eher verwirrend: [...] 
> Ich finde keinen Kontakt, nur Links auf Webseiten

Additional offline information: 

multiple erroring details pages on search: http://nwbib.de/search?q=karten

**Comment by fsteeg** [comment]
Updated error message for actual feedback link: 27ddf10d0977f7900e6ba051ba0cbb2e008fcad9

Erroring resources work after restart, probably a caching issue.

Deployed to staging, see:

http://test.nwbib.de/HT018833649
http://test.nwbib.de/search?q=karten

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
Root cause seems to be an issue with the resource 2.0 index which was configured in nwbib.

(Not the current beta/productive index, opened https://github.com/hbz/lobid-resources/issues/92).

See: http://nwbib.de/HT018833649
