### ISSUE TITLE
Error for HT018776640

### ISSUE THREAD

**Issue by fsteeg** [hbz/nwbib#329]
https://nwbib.de/HT018776640

**Comment by fsteeg** [comment]
Works after restart: https://nwbib.de/HT018776640

Opened #330 for potential root cause.

Closing.

**Comment by acka47** [comment]
It's gone again: https://nwbib.de/HT018776640 As well as http://nwbib.de/HT018833649 from #327.

Reopening.

**Comment by fsteeg** [comment]
Root cause seems to be an issue with the resource 2.0 index which was configured in nwbib.

(Not the current beta/productive index, opened https://github.com/hbz/lobid-resources/issues/92).

See: http://nwbib.de/HT018776640
