### ISSUE TITLE
Move beacon file creation and hosting to nwbib repo

### ISSUE THREAD

**Issue by fsteeg** [hbz/nwbib#335]
See:

https://github.com/hbz/nwbib/issues/102
https://github.com/hbz/nwbib/issues/106
https://github.com/lobid/lodmill/pull/663
https://de.wikipedia.org/wiki/Wikipedia:BEACON
http://lobid.org/download/beacons/nwbibContributors.bf
http://lobid.org/download/beacons/nwbibSubjects.bf

**Comment by acka47** [comment]
It is also time to update the BEACON files. Maybe we can combine this with moving them to the NWBib repo...

**Comment by acka47** [comment]
As discussed in yesterday's NWBib meeting, we should update the BEACON files.

**Comment by acka47** [comment]
Moving this up as we still haven't updated the BEACON files.

**Comment by acka47** [comment]
When we are at it, we should fix the target. Currently, the old `http://lobid.org/nwbib/search?person={ID}` is used. (Looking at the log files, @dr0i and me were just wondering where these requests come from.)

**Comment by dr0i** [comment]
Deployed, see files at https://lobid.org/download/beacons/ beginning with 'nwbib'.

**Comment by acka47** [comment]
We should update the targets:

- in nwbibContributors.bf: `#TARGET: https://nwbib.de/search?person=https%3A%2F%2Fd-nb.info%2Fgnd%2F` 
- in nwbibSubjects.bf: `#TARGET: https://nwbib.de/search?subject=https%3A%2F%2Fd-nb.info%2Fgnd%2F`

**Comment by dr0i** [comment]
@acka47 good catch! Changed them on the server an in the code.

**Comment by acka47** [comment]
Could you please also change the base of the target URLs from ` https://lobid.org/nwbib/` to `https://nwbib.de`?

**Comment by dr0i** [comment]
Uh. Sorry didn't saw that. Please check again!

**Comment by acka47** [comment]
Looks good. But the IDs with hyphens only work for the subject query but not for the person query. Compare:

https://nwbib.de/search?person=https%3A%2F%2Fd-nb.info%2Fgnd%2F4024544-5

and

https://nwbib.de/search?subject=https%3A%2F%2Fd-nb.info%2Fgnd%2F4127794-6

This is not a beacon problem, though...

**Comment by dr0i** [comment]
I think we can use this to get persons AND corporate bodies, i.e. all contribution agents:

*coporate body*: https://nwbib.de/search?q=contribution.agent.id%3A%22https%3A%2F%2Fd-nb.info%2Fgnd%2F4024544-5%22
*person*: https://nwbib.de/search?location=&q=contribution.agent.id%3A%22https%3A%2F%2Fd-nb.info%2Fgnd%2F112012051%22

**Comment by dr0i** [comment]
Deployed to production. Closing.
