### ISSUE TITLE
Improve behaviour when classification notation is chosen

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#336]
Reported by H.F. via email on 2016-07-27:

> während der Arbeiten am Artikel fielen mir noch zwei Dinge zur
> Systematiksuche auf. Einmal bricht nach der Anwahl einer Systemstelle
> die Nutzerinformation über die ausgeführte Suche ab. Könnte man hier
> analog zu anderen Suchen oberhalb der Treffer die für die Trefferanzeige
> relevante Systemstelle anzeigen z.B. "Sachgebiet" und dann "402340
> Grundrechte"?
> 
> Das andere ist die Facette "Sachgebiete" nach Auswahl einer
> Systemstelle. Hier steht die formale Info, dass man eine Stelle
> ausgewählt hat, das ist in Ordnung. Dann werden aber stets nach jeder
> Systemstellenauswahl dieselben Sachgebiete beginnend mit "Geschichte
> (23307)" genannt. Da man nach Auswahl einer einzelnen Systemstelle die
> gefundenen Titel allerdings mit anderen Systemstellen nicht weiter
> einzugrenzen vermag, müssten der Hinweis "1 ausgewählt" eigentlich
> reichen und die weiteren Hinweise auf Systemstellen entfallen.
>

**Comment by acka47** [comment]
We probably can't implement the first suggestion But we should implement the second point, i.e. when I click on a notation under "Sachgebiete". The checked notation should be the first in the "Sachgebiete" facet. This currently works for some (e.g. [s240500](http://nwbib.de/search?nwbibsubject=http%3A%2F%2Fpurl.org%2Flobid%2Fnwbib%23s240500)) but not for all (e.g. [s402340](http://nwbib.de/search?nwbibsubject=http%3A%2F%2Fpurl.org%2Flobid%2Fnwbib%23s402340)).

Regarding the request to not show the other notations when one is chosen, I will make clear that this actually makes sense with the "or" connection of notations.

**Comment by fsteeg** [comment]
Deployed to staging, see:

http://test.nwbib.de/search?nwbibsubject=http%3A%2F%2Fpurl.org%2Flobid%2Fnwbib%23s240500

http://test.nwbib.de/search?nwbibsubject=http%3A%2F%2Fpurl.org%2Flobid%2Fnwbib%23s402340

http://test.nwbib.de/search?nwbibsubject=http%3A%2F%2Fpurl.org%2Flobid%2Fnwbib%23s402340%2Chttp%3A%2F%2Fpurl.org%2Flobid%2Fnwbib%23s240000&sort=

For details, see comment in https://github.com/hbz/nwbib/commit/6b2e9932c6feafa83dd9fb833c0c3f46eb90bae3.

**Comment by acka47** [comment]
The behaviour is strange when I select a subject directly from a single entry, e.g. for subject "Umsiedlung": http://test.nwbib.de/search?subject=http%3A%2F%2Fd-nb.info%2Fgnd%2F4061614-9: It says "0 ausgewählt" in the subject facet.

**Comment by acka47** [comment]
It works for "Sachgebiete", though, e.g. http://test.nwbib.de/search?nwbibsubject=http%3A%2F%2Fpurl.org%2Flobid%2Fnwbib%23s572030.

**Comment by fsteeg** [comment]
Fixed on staging: http://test.nwbib.de/search (click subject links from detail pages).

**Comment by fsteeg** [comment]
The changes in this issue are only consistent together with #341 (otherwise the preview numbers in the facet don't match actual results). Moving to backlog.

**Comment by fsteeg** [comment]
Deployed to staging, see: http://test.nwbib.de/search

Facets support drill down (`AND` for facet and results), except for type and owner facets (they still use `OR`).

**Comment by acka47** [comment]
Great, this makes so much mor esense for the facets. +1

**Comment by dr0i** [comment]
I don't like that a owner query works as `OR`  (using multiple values for the paramter) while others will work as `AND`. Also, it's an API break, even if the API examples site doesn't explicitly mentioned `subject` comma-separated queries. I for myself already have used the comma-separated `subject` queries as `OR`-queries .
Is there a need to break this old behaviour?

**Comment by fsteeg** [comment]
Deployed to production, closing. See facet behavior at http://nwbib.de/search
