### ISSUE TITLE
Add journal list to web site

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#337]
Requested by customers via email from I.N. on 2016-08-05:

> im Anhang finden Sie die Liste der laufend für die
> Nordrhein-Westfälische Bibliographie ausgewerteten Zeitschriften.
> 
> Diese Liste war bisher an folgender Stelle zu finden:
> 
> http://www.landesbibliothek-nrw.de/aufgaben/nrw_bibliographie/zeitschriftenliste/
> 
> Die Zeitschriftentitel enthalten noch den Link zur alten NWBib.
> 
> In Absprache mit der NWBib-Redaktion in Düsseldorf, haben wir die
> Zeitschriftenliste aktualisiert und die Links korrigiert.
> 
> Die Links führen nun zur neuen Web-Version der NWBib.
> 
> Gemeinsam mit der Redaktion in Düsseldorf haben wir überlegt, wo die
> Zeitschriftenliste in der Web-Version eingebunden werden könnte.
> 
> Wir haben uns auf folgende Position geeinigt: Die Liste sollte in der
> obersten Zeile innerhalb des Menüs mit dem Informationssymbol als
> eigener Eintrag unterhalb von „Über die NWBib“ positioniert werden (s. u.).
> 
> Der Eintrag sollte lauten: „Ausgewertete Zeitschriften“.

![nwbib-journal-list](https://cloud.githubusercontent.com/assets/160292/17664405/1c0b26e6-62f4-11e6-9650-910e4e78a1e4.jpg)

I forwarded the mail with attachment (xslx) to @fsteeg .

**Comment by fsteeg** [comment]
Deployed to staging: http://test.nwbib.de/journals

Data is stored in a CSV file in the repo:
https://github.com/hbz/nwbib/blob/337-journals/conf/nwbib-journals.csv

**Comment by acka47** [comment]
We should add in front of the list: "In der NRW-Bibliographie laufend ausgewertete Zeitschriften (Stand: 01.08.2016):"

**Comment by fsteeg** [comment]
Deployed to staging (with tweaks discussed offline): http://test.nwbib.de/journals

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
Deployed to production, closing. See: http://nwbib.de/journals
