### ISSUE TITLE
GND URI instead label shown for some entries

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#338]
Reported by NWBib stakeholder I.N. via email on 2016-08-05:

> Bei einigen Titelaufnahmen wird der Körperschaftsname noch nicht richtig
> angezeigt:
> 
> http://nwbib.de/HT007038758

**Comment by fsteeg** [comment]
Seems to have been a temporary issue, looks good: http://nwbib.de/HT007038758

**Comment by acka47** [comment]
Yes, closing.
