### ISSUE TITLE
GND URI shown when subject chosen in facet after subject search

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#339]
Reported by NWBib stakeholder I.N. via email on 2016-08-05:

> Bei einer kombinierten Schlagwortrecherche aus
> Schlagwortkategorie und Schlagwort-Facette wird das zweite Schlagwort,
> das aus der Facette angewählt wurde als URL angezeigt.
> 
> 1.       Schlagwort = Eisenbahnlinie via Erweiterte Suche
> 
> 2.       Schlagwort = Bahnhof via SW-Facette
> 
> http://nwbib.de/search?subject=Eisenbahnlinie%2Chttp%3A%2F%2Fd-nb.info%2Fgnd%2F4129465-8&sort=
> 
> 
> http://nwbib.de/search?subject=Radwandern%2Chttp%3A%2F%2Fd-nb.info%2Fgnd%2F4115388-1&sort=
> 
> http://nwbib.de/search?subject=Denkmalpflege%2Chttp%3A%2F%2Fd-nb.info%2Fgnd%2F4004973-5&sort=
>

**Comment by fsteeg** [comment]
Deployed to staging, see:

http://test.nwbib.de/search?subject=Eisenbahnlinie%2Chttp%3A%2F%2Fd-nb.info%2Fgnd%2F4129465-8

**Comment by acka47** [comment]
I found the ID more fitting than the string. It would be great if facets would be shown as a non-editable string (=a button) in the seartch window to indicate that they stand for one (controlled) value. Is this doable with not too much effort?

**Comment by acka47** [comment]
Also, if I search for subject strings "Eisenbahnlinie" and "Bahnhof" I get the exact same status in the search field but a different number of results: http://test.nwbib.de/search?subject=Eisenbahnlinie%2CBahnhof

Talking on the phone we decided to do the following:

- Don't show the subject chosen via facet at all in the search field
- Add the hint "1 ausgewählt" to the subject facet additional to the check on the chosen element.

**Comment by fsteeg** [comment]
Deployed to staging, see:

http://test.nwbib.de/search?subject=Eisenbahnlinie%2Chttp%3A%2F%2Fd-nb.info%2Fgnd%2F4129465-8

**Comment by acka47** [comment]
Now I sometime (but not always) experience unexpected behavour with the "Orte" facet. When choosing elements from multiple facets it sometimes says "0 ausgewählt" for "Orte" although an element has been chosen from the facet and is actually active e.g. [this query](http://test.nwbib.de/search?subject=http%3A%2F%2Fd-nb.info%2Fgnd%2F119252899&nwbibsubject=http%3A%2F%2Fpurl.org%2Flobid%2Fnwbib%23s841070&word=*&raw=%40graph%5C.http%5C%3A%5C%2F%5C%2Fpurl%5C.org%5C%2Fdc%5C%2Felements%5C%2F1%5C.1%5C%2Fcoverage%5C.%40value%3A%22Hamm%22). Works on [production](http://nwbib.de/search?subject=http%3A%2F%2Fd-nb.info%2Fgnd%2F119252899&nwbibsubject=http%3A%2F%2Fpurl.org%2Flobid%2Fnwbib%23s841070&word=*&raw=%40graph%5C.http%5C%3A%5C%2F%5C%2Fpurl%5C.org%5C%2Fdc%5C%2Felements%5C%2F1%5C.1%5C%2Fcoverage%5C.%40value%3A%22Hamm%22), though.

This doesn't occur often, though.

**Comment by acka47** [comment]
@fsteeg As this error doesn't occur often I would give my ok and you may work on it after deploying it. But it probably makes sense to take a look into it now as the problem obviously was introduced with the changes for this issue.

**Comment by fsteeg** [comment]
Deployed to staging:

http://test.nwbib.de/search?subject=http%3A%2F%2Fd-nb.info%2Fgnd%2F119252899&nwbibsubject=http%3A%2F%2Fpurl.org%2Flobid%2Fnwbib%23s841070&raw=%40graph%5C.http%5C%3A%5C%2F%5C%2Fpurl%5C.org%5C%2Fdc%5C%2Felements%5C%2F1%5C.1%5C%2Fcoverage%5C.%40value%3A%28%2B%22Hamm%22%29

(Issue was introduced by work on #336)

**Comment by acka47** [comment]
As I wrote above, it "says "0 ausgewählt" for "Orte" although an element has been chosen from the facet and is actually active". Thus, removing the "0 ausgewählt" isn't correct. It should rather read "1 ausgewählt". [In production]() it actually says "2 ausgewählt" because searching for coverage = Hamm results in both sowing results with "Hamm (Westf)" and "Hamm <Westfalen>". This is better than the current behaviour on staging though it might also be problematic in some cases.

**Comment by acka47** [comment]
Here is another example where the coverage search ("Köln") doesn't have two results-
- Staging not showing any element chosen in "Orte" facet (though one is chosen): http://test.nwbib.de/search?q=*&subject=http%3A%2F%2Fd-nb.info%2Fgnd%2F4045895-7&nwbibsubject=http%3A%2F%2Fpurl.org%2Flobid%2Fnwbib%23s841070&raw=%40graph%5C.http%5C%3A%5C%2F%5C%2Fpurl%5C.org%5C%2Fdc%5C%2Felements%5C%2F1%5C.1%5C%2Fcoverage%5C.%40value%3A%22K%C3%B6ln%22
- On production the behaviour is as expected ("1 ausgewählt" for "Orte" facet): http://nwbib.de/search?q=*&subject=http%3A%2F%2Fd-nb.info%2Fgnd%2F4045895-7&nwbibsubject=http%3A%2F%2Fpurl.org%2Flobid%2Fnwbib%23s841070&raw=%40graph%5C.http%5C%3A%5C%2F%5C%2Fpurl%5C.org%5C%2Fdc%5C%2Felements%5C%2F1%5C.1%5C%2Fcoverage%5C.%40value%3A%22K%C3%B6ln%22

**Comment by acka47** [comment]
Can't reproduce it, please deploy. +1

**Comment by fsteeg** [comment]
For completeness, here's the staging URL when selecting `Köln`, `Künstler`, and `Fotografie`:

http://test.nwbib.de/search?subject=http%3A%2F%2Fd-nb.info%2Fgnd%2F4045895-7&nwbibsubject=http%3A%2F%2Fpurl.org%2Flobid%2Fnwbib%23s841070&raw=%40graph%5C.http%5C%3A%5C%2F%5C%2Fpurl%5C.org%5C%2Fdc%5C%2Felements%5C%2F1%5C.1%5C%2Fcoverage%5C.%40value%3A%28%2B%22K%C3%B6ln%22%29

**Comment by fsteeg** [comment]
Deployed to production, closing. See:

http://nwbib.de/search?subject=Eisenbahnlinie%2Chttp%3A%2F%2Fd-nb.info%2Fgnd%2F4129465-8

http://nwbib.de/search?subject=http%3A%2F%2Fd-nb.info%2Fgnd%2F4045895-7&nwbibsubject=http%3A%2F%2Fpurl.org%2Flobid%2Fnwbib%23s841070&raw=%40graph%5C.http%5C%3A%5C%2F%5C%2Fpurl%5C.org%5C%2Fdc%5C%2Felements%5C%2F1%5C.1%5C%2Fcoverage%5C.%40value%3A%28%2B%22K%C3%B6ln%22%29
