### ISSUE TITLE
Add report to "Publikationstyp" facet

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#343]
With implementing https://github.com/hbz/lobid/issues/242 we now have resources with type http://purl.org/ontology/bibo/Report in lobid. We should add this to the "Publikationstyp" facet.

**Comment by acka47** [comment]
@fsteeg Is it sufficient to adjust https://github.com/hbz/nwbib/blob/master/conf/nwbib.conf? I could do this...

**Comment by fsteeg** [comment]
Yes, that should work.

**Comment by acka47** [comment]
I can't find a fitting icon in the octicon/glyphicon sets. Something like https://cdn0.iconfinder.com/data/icons/simple-seo-and-internet-icons/512/analytics-512.png would be nice...

**Comment by fsteeg** [comment]
Deployed your change to staging: http://test.nwbib.de/search

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
Deployed to production, closing.

See: http://nwbib.de/search?t=http%3A%2F%2Fpurl.org%2Fontology%2Fbibo%2FReport
