### ISSUE TITLE
Search entry via "Regionen" and "Sachgebiete" does not work anymore

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#347]
Reported by U.P. via Mail just now:

> wenn ich auf einzelne Regionen oder Sachgebiete klicke, die ich mir aus
> der oberen Menüzeile habe anzeigen lassen, erhalte ich folgende Meldung:
> 
> Ein Titel mit der ID if(t== konnte nicht gefunden werden.

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
Deployed to production, closing. See: http://nwbib.de/register?t=Raumsystematik
