### ISSUE TITLE
Show nwbibspatial and nwbibsubject labels above result list

### ISSUE THREAD

**Issue by fsteeg** [hbz/nwbib#349]
Based on Feedback by H.F., 9.9.:

> Wäre es nicht schöner, z.B. die Ergebnisanzeige „155 Treffer“ direkt mit der zugrunde liegenden Herkunft aus dem Sachgebiet „122030 Kartenauswertung“ verbunden zu finden?

This should only appear when coming from the classifications, not when (additional) values are selected via facet, i.e. only if there is only one nwbibspatial or nwbibsubject, and no other restriction.

**Comment by fsteeg** [comment]
Deployed to staging, see results linked from:

http://test.nwbib.de/register?t=Raumsystematik
http://test.nwbib.de/register?t=Sachsystematik

**Comment by acka47** [comment]
+1
