### ISSUE TITLE
URI without label shown for GND resource

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#354]
At least one GND resource makes problems: http://d-nb.info/gnd/5183585-X See https://nwbib.de/search?person=http%3A%2F%2Fd-nb.info%2Fgnd%2F5183585-X.

**Comment by acka47** [comment]
Here is another one: https://nwbib.de/HT019093814

**Comment by fsteeg** [comment]
On staging (and locally) it's even worse (all 4 labels are missing): https://test.nwbib.de/HT019093814

**Comment by fsteeg** [comment]
When I switch to using API 1.x for the details view, 3 of 4 labels reappear, behaving like on production. Production, however, seems to be using data 2.0, see nwbib.conf file in `sol@quaoar1:~/git/nwbib`.
