### ISSUE TITLE
Remove "Schlagwortfolge" and take over order from subject array

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#363]
From https://github.com/hbz/nwbib/pull/362#issuecomment-266814698:

> I realized that we also can remove the "Schlagwortfolge" line by now as the subjects already come in a sorted array. But the order is not taken for the HTML representation, see e.g. http://test.nwbib.de/HT014013953 in comparison to http://test.lobid.org/resources/HT014013953.

**Comment by fsteeg** [comment]
> I realized that we also can remove the "Schlagwortfolge" line by now as the subjects already come in a sorted array.

You mean to remove it just on the UI level, right? Because the `subjectChain` field is used for the Themensuche.

For the UI: it currently links to a search with the given `subjectChain`. Should we add a link after the subjects when we remove it? Like 'Titel mit ganzer Schlagwortfolge suchen'?

**Comment by acka47** [comment]
Perhaps I was a bit hasty here. I just remembered that we still have no way of separating two subject chains in the JSON. See for example http://test.lobid.org/resources/HT013099804. We will need this before adjusting the UI here.

I think @dr0i is currently working on this with https://github.com/hbz/lobid-resources/issues/4, aren't you @dr0i ?

**Comment by dr0i** [comment]
In  hbz/lobid-resources#4 I've ticked the issue  `list dct:subjects objects` , meaning I think it's done. As I remembered we talked about leaving the `subjectChains` as they are. If not, please make an issue and let us discuss _how_ to encode the subject chains under the `subject`-list.

**Comment by dr0i** [comment]
This is achieved long ago with `subject.componentList`.
I think this issue is done.
Closing.
