### ISSUE TITLE
Expanding facets adds checkboxes

### ISSUE THREAD

**Issue by fsteeg** [hbz/nwbib#375]
To reproduce:

1. Open http://nwbib.de/search?q=k%C3%B6ln
2. Click 'Zeige mehr Orte' repeatedly

Result:

Each expansion adds a checkbox without label to the list of values

**Comment by acka47** [comment]
I can't reproduce this on Chromium Version 53.0.2785.143 Built on Ubuntu , running on LinuxMint 17.3 (64-bit).

**Comment by acka47** [comment]
I can reproduce this in Firefox, though.

**Comment by fsteeg** [comment]
It's actually a visual/layout issue: the boxes and links are misaligned, and the misalignment increases as the list is expanded (hover over checkbox to highlight associated label).
