### ISSUE TITLE
Empty subject line for resources with DDC subjects only

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#380]
See for example http://nwbib.de/HT019196136. I think this has to do with the fact that there only is one element in the `subject` array which is a DDC notation.

Though it sounds like it is related to https://github.com/hbz/lobid-resources-web/issues/22 I doubt that that is the case.

**Comment by acka47** [comment]
If this really only holds for DDC-only records, we just should wait and fix this by switching to API 2.0.

**Comment by fsteeg** [comment]
We've had the same thing in resources-web before: https://github.com/hbz/lobid-resources-web/issues/3
