### ISSUE TITLE
Add robots.txt to production and test

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#386]
I just noticed that google gives back results from the test system, see https://www.google.de/?gws_rd=ssl#q=site:test.nwbib.de&*. Obviously, we don't have a robots.txt for NWBib. (I think we discussed this in the past but couldn't find an issue for this.) However, we should add two  robots.txt.

```
# robots.txt for nwbib.de
User-agent: *
Disallow: 
```

```
# robots.txt for test.nwbib.de
User-agent: *
Disallow: /
```

**Comment by acka47** [comment]
This can be quickly implemented I guess. @fsteeg, you might approach this, when you have half an hour left and don't want to start working on a bigger issue.

**Comment by acka47** [comment]
ping @fsteeg

**Comment by fsteeg** [comment]
Deployed to test: http://test.nwbib.de/robots.txt

**Comment by acka47** [comment]
+1 Closing.
