### ISSUE TITLE
Journals with comma in title not shown in journal list

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#388]
Reported today by NWBib stakeholder I.N.. Obviously, titles with comma make problems as the list maintained as a csv file. I suggest making it a tab-separated list.

On 11.05.17 15:48, N., I. wrote:
> uns ist aufgefallen, dass es eine Abweichung bei der Anzeige der Liste 
> der ausgewerteten NWBib-Zeitschriften gibt.
> 
> Am 11.01.2017 beinhaltete die CSV-Datei „nwbib-journals“ 582 
> Zeitschriften-Titel.
> 
> Diese 582 Titel sind auch in der hinterlegten Liste noch enthalten. 
> Siehe: 
> https://github.com/hbz/nwbib/blob/4ad26f2f9fc5d840e51497e6abee91f275543b8c/conf/nwbib-journals.csv
> 
> Aber wenn man die Liste in der Web-Version der NWBib unter dem 
> Info-Punkt aufruft bekommt man nur 472 Zeitschriftentitel angezeigt.
> 
> Es fehlen also 110 Titel in der Anzeige.

> Hier einige Beispiele:
> 
> Agrar- und Umweltrecht : Zeitschrift für das gesamte Recht der 
> Landwirtschaft, der Agrarmärkte und des ländlichen 
> Raumes,"http://nwbib.de/HT013574325"
> 
> An Bigge, Lenne und Fretter : heimatkundliche Beiträge aus der Gemeinde 
> Finnentrop,"http://nwbib.de/HT007216566"
> 
> An Möhne, Röhr und Ruhr / Heimatbund Neheim-Hüsten 
> e.V.,"http://nwbib.de/HT007066969"
> 
> An Ruhr, Valme und Elpe : heimatkundliche Beiträge aus den Dörfern der 
> Gemeinde Bestwig,"http://nwbib.de/HT015783600"
> 
> Annalen des Historischen Vereins für den Niederrhein, insbesondere das 
> Alte Erzbistum Köln,"http://nwbib.de/HT000178865"
> 
> Archäologie im Rheinland / Landschaftsverband Rheinland, Rheinisches Amt 
> für Bodendenkmalpflege,"http://nwbib.de/HT017784848"
> 
> Archäologisches Korrespondenzblatt : Urgeschichte, Römerzeit, 
> Frühmittelalter,"http://nwbib.de/HT004277812"
> 
> Archiv des Badewesens : Fachzeitschrift für Praxis, Technik, 
> Wissenschaft und Betriebswirtschaft,"http://nwbib.de/HT005077187"

**Comment by fsteeg** [comment]
Deployed to staging: http://test.nwbib.de/journals

**Comment by ChristophEwertowski** [comment]
+1
