### ISSUE TITLE
Visualize location hierarchy from Wikidata

### ISSUE THREAD

**Issue by fsteeg** [hbz/nwbib#392]
Create a page like http://nwbib.de/classification?t=Sachsystematik but for NRW locations from Wikidata.

See https://github.com/hbz/lobid-resources/issues/130 and in particular this Wikidata query: http://tinyurl.com/y8sbgcf5.

**Comment by fsteeg** [comment]
First version deployed to test: http://test.nwbib.de/classification?t=Wikidata

- Use `Regierungsbezirk` in NRW as top level elements
- Sort other top level locations in NRW into `Sonstige`
- Link items to Wikidata for editing and debugging
- Support reloading locations from Wikidata

Will continue by working on API 2.0 queries and hit previews, but I think it makes sense to review what we have in parallel. @acka47: Some entries in `Sonstige` are incorrectly set up as direct parts of NRW in Wikidata. Do we want to fix these before our meeting? Or would these be good to demonstrate how we can edit Wikidata and have that reflected in our classification (using the Wikidata reload link)?

**Comment by acka47** [comment]
This already looks quite good. I currently have not time to fix wikidata entries anyway. Demonstrating the cleanup of wikidata and reloading of the classification based on the changes seems to make sense.

For the meeting with NWBib editors it would also be great to have a csv file with all the location strings (see https://github.com/hbz/lobid-resources/issues/130#issuecomment-304867318) and the label and ID of the wikidata resource it was mapped to, @dr0i.

**Comment by fsteeg** [comment]
Added Lobid 2.0 search links and GND links (is this useful for the meeting?) if available in Wikidata:

http://test.nwbib.de/classification?t=Wikidata

@acka47 How important do you consider the search result previews for the prototype? With the current implementation this would require > 8000 request on page load, which takes quite a while. This would probably require a more complex approach like indexing the data and basically doing a facet request.

**Comment by acka47** [comment]
I think the result previews are not that important. But it would be nice to at least see where there are zero hits in NWBib.

**Comment by acka47** [comment]
@fsteeg Re. https://github.com/hbz/nwbib/issues/392#issuecomment-332176813: I think it would be great for debugging purposes and for our presentation next week to have the possibility to easily see in the classification which location strings were mapped to the respective Wikidata entry. One would have to just show the distinct `coverage` entries of the records with the respective wikidata link.

**Comment by fsteeg** [comment]
> I'm not sure I understand. Would this be based on the CSV file you asked @dr0i to create? Would you want to see in the Wikidata classification, for each Wikidata entry, the coverage string from NWBib titles?

If this is correct, I could do it in another way: since I already query Lobid for the result count previews, I could use the coverage values in the response (i.e. results for a specific Wikidata ID). Would we still need the CSV then?

**Comment by acka47** [comment]
I meant that _instead_ of the csv file we could incorporate the labels into the prototype classification by adding the distinct values of the `coverage` field of the resources that have a link to a specific wikidata location.

**Comment by acka47** [comment]
I didn't read your comment before posting. Obviously, we are on the same page. :-)

**Comment by fsteeg** [comment]
> I meant that instead of the csv file we could incorporate the labels into the prototype classification

OK great! Deployed to stage: http://test.nwbib.de/classification?t=Wikidata

As I mentioned above, the data is far from complete, but to check the format this should work. You can filter for `|` to get all entries that have a search link and details. Keep in mind that some titles have different coverage values, so sometimes some of the values don't seem to make sense.

**Comment by dr0i** [comment]
@fsteeg re: small staging-index:
Tuesday evening I started building a new staging-index when I discovered something wen t wrong, I cancelled that job. Obviously that cancelling was "clean" enough so that the index-aliases were switched and old indices were deleted (though this was not desired now). I started creating a new index shortly after that, see: http://gaia.hbz-nrw.de:9200/_plugin/head/ . It's nearly done now. You can use that unfished index already for it will reveal far more hits than the cancelled one.
Not sure what would happen if you give the staging-alias manually, though, because of the cleaning (automatically alias-renaming and old indices deleting at the end of the ETL process). Would recommend to configure the API by using the full qualified index-name instead of the alias.

Note that the phenomenon of an nearly empty staging-index is rarely to be experienced again , as a situation as described above will seldom occur.

**Comment by acka47** [comment]
As discussed, here is a query containing inception and dissolution dates if they exist (and excluding Stadtbezirke): http://tinyurl.com/y9x7fbjz

100 items have a inception date and 55 a dissolution date and 50 items have both.

**Comment by acka47** [comment]
I just realized that we need some more entries under "Sonstiges" that  are not associated with NRW in Wikidata but which @dr0i includes in lobid-resources by directly calling the Wikidata API. For example http://stage.lobid.org/resources/HT006934472.json includes:

```json
{
   "spatial":[
      {
         "type":"Location",
         "id":"http://www.wikidata.org/entity/Q2098852",
         "label":"Autobahnkreuz Düsseldorf-Nord",
         "geo":{
            "type":"GeoCoordinates",
            "lat":51.28678,
            "lon":6.80392
         }
      }
   ]
}
```

The Wikidata item http://www.wikidata.org/entity/Q2098852 doesn't have a wdt:P131 ("liegt in Verwaltungseinheit") statement at all...

**Comment by acka47** [comment]
We just discussed that we won't include into the UI the items matched by a direct wikidata API call. We do not need to confront the NWBib editors with the matching before we have improved it some more.

**Comment by fsteeg** [comment]
Deployed latest version to stage: http://test.nwbib.de/classification?t=Wikidata

(dissolution dates, Stadtbezirke and subordinate Stadtteile, Regierungsbezirk Aachen under Sonstige)

**Comment by fsteeg** [comment]
Redeployed with coverage labels as mouseover for search links, as discussed offline:

http://test.nwbib.de/classification?t=Wikidata

**Comment by acka47** [comment]
I think this looks really good by now and totally suffices as a prototype for the Thursday meeting.

**Comment by fsteeg** [comment]
Deployed two minor changes (icons like in production, link to production-resources):

http://test.nwbib.de/classification?t=Wikidata

I suggest we deploy this to production and link to the production version in the Wiki page summarizing yesterday's meeting. That will free the test instance for new tests and provide a stable setup for working on the Wikidata classification.

**Comment by acka47** [comment]
+1
