### ISSUE TITLE
Auf Biographisches Portal bei "Ergänzende Suche" verweisen

### ISSUE THREAD

**Issue by fsteeg** [hbz/nwbib#394]

**Comment by fsteeg** [comment]
Deployed to test: https://test.nwbib.de/

**Comment by acka47** [comment]
Ich meine, Herr Flachmann sagte, dass er bescheid geben würde, sobald der Link ergänzt werden soll. Die wollten noch auf eine neue Version waren, oder so. Von daher sollten wir vielleicht hiermit warten.

**Comment by acka47** [comment]
Herr Flachmann hat jetzt grünes Licht gegeben, den Link zu ergänzen.

**Comment by fsteeg** [comment]
Deployed to test: https://test.nwbib.de

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
Deployed to production, closing. See https://nwbib.de
