### ISSUE TITLE
Neue Hauptebene in Systematiken einführen

### ISSUE THREAD

**Issue by fsteeg** [hbz/nwbib#396]
**Hauptebene entsprechend Papier von H.F., S. 7:**

Nordrhein-Westfalen insgesamt. Landesteile
Landschaften in Nordrhein-Westfalen
Kirchliche Gebiete in Nordrhein-Westfalen
Historische Territorien und Gebiete
Regierungsbezirke, Kreise, Orte. Euregio

**Entsprechend Papier von H.F., S. 8:**

Landeskunde (allgemein. Geo-u. Biowissenschaften)
Landeskunde (historisch)
Staat. Politik. Verwaltung. Recht
Bevölkerung. Soziales. Wirtschaft. Raumordnung. Umweltschutz
Religion
Volkskunde. Gesellschaft. Kultur. Bildung
Künste. Medien

**Comment by fsteeg** [comment]
Deployed to test:

https://test.nwbib.de/classification?t=Raumsystematik
https://test.nwbib.de/classification?t=Sachsystematik

**Comment by fsteeg** [comment]
Wie offline besprochen, und entsprechend Notizen vom Treffen, Raumsystematik ganz ohne Systemstellen:

https://test.nwbib.de/classification?t=Raumsystematik

**Comment by acka47** [comment]
+1
