### ISSUE TITLE
Neue Ortssystematik auf Wikidata-Basis

### ISSUE THREAD

**Issue by fsteeg** [hbz/nwbib#397]
Hauptebene entsprechend Papier von H.F., S. 7, aber ohne Ziffern:

Nordrhein-Westfalen insgesamt. Landesteile
Landschaften in Nordrhein-Westfalen
Kirchliche Gebiete in Nordrhein-Westfalen
Historische Territorien und Gebiete
Regierungsbezirke, Kreise, Orte. Euregio

Unter dem letzten Punkt die experimentelle Struktur von https://test.nwbib.de/classification?t=Wikidata.

Erfordert https://github.com/hbz/lobid-resources/issues/585

Zu klären: was wird aus den bisherigen Werten der Raumsystematik [1], die es nicht in Wikidata gibt? Die sollen ja in die Gliederung oben einsortiert werden. Was wird aus den IDs der Raumsystematik (z.B. `http://purl.org/lobid/nwbib-spatial#n01`)?

[1] https://nwbib.de/classification?t=Raumsystematik

**Comment by acka47** [comment]
> Zu klären: was wird aus den bisherigen Werten der Raumsystematik [1], die es nicht in Wikidata gibt? Die sollen ja in die Gliederung oben einsortiert werden. Was wird aus den IDs der Raumsystematik (z.B. `http://purl.org/lobid/nwbib-spatial#n01`)?

Meines Erachtens müssen wir hier nichts ändern, wir sollten aber auch für diese Systematikstellen die entsprechenden Wikidata-IDs (mit der property `http://xmlns.com/foaf/0.1/focus`) ergänzen.

Als erstes sollten die zusätzlichen Ebenen in der SKOS-Datei (https://github.com/hbz/lobid-vocabs/blob/master/nwbib/nwbib-spatial.ttl) ergänzt werden, siehe https://github.com/hbz/lobid-vocabs/issues/72. Auf der Basis wird doch gerade schon die HTML-Sicht generiert, oder? Eventuell läuft das ja nach der SKOS-Anpassung direkt, zumindest ohne die Ensortierung der Wikidata-Systematik.

**Comment by fsteeg** [comment]
Collecting some next steps here (I suggest I check when deployed, @acka47 strikes out as review):

- [x] Fix sorting of Stadtbezirke of Düsseldorf and Essen at (email U.P. 23.11.18). Deployed: https://test.nwbib.de/classification?t=Wikidata 
- [ ] Add content of https://test.nwbib.de/classification?t=Wikidata to "Regierungsbezirke, Kreise, Orte. Euregio" at https://nwbib.de/classification?t=Raumsystematik

**Comment by fsteeg** [comment]
Inhalt von https://test.nwbib.de/classification?t=Wikidata ist jetzt auch unter "Regierungsbezirke, Kreise, Orte. Euregio" in https://test.nwbib.de/classification?t=Raumsystematik eingebettet.

Das verhält sich da wie die klassische Raumsystematik: Links gehen auf Suchen, sonst gibts nichts (keine Trefferzahlen, Wikidata- und GND-Links). Geplant ist ja auch noch der Link zum Kopieren der QID+Label. Aber vielleicht sollten Teile davon in eine andere (die alte?) Admin-Oberfläche?

**Comment by acka47** [comment]
Die Inhalte unter https://test.nwbib.de/classification?t=Wikidata betreffen ja nur die Notationen 96, 97, 99 (Bezirke, Kreise, Orte). Wir haben allerdings auch aus GSW der folgenden Notationen Wikidata-Links generiert: 10, 12, 14, 23, 28, 52, 54, 72, 74. Diese sollten auch unter den entsprechenden Notationen eingehängt werden.

Hier ein paar relevante Informationen für die Umsetzung:
- Betroffen sind insgesamt gut 7700 Titel, siehe [hier](http://lobid.org/resources/search?q=inCollection.id%3A%22http%3A%2F%2Flobid.org%2Fresources%2FHT014176012%23%21%22+AND+coverage%3A%2810+OR+12+OR+14+OR+23+OR+28+OR+52+OR+54+OR+72+OR+74%29+AND+_exists_%3Aspatial). 
- Hier eine Liste der darin enthaltenen uniquen QIDs inklusive Notation: https://gist.github.com/acka47/f5eb6747ba73ece928498a4d92fac7d6 (Konnte das leider nicht komplett automatisch machen, ist also vieles manuel nachprozessiert. Der erste Schritt war `$ curl "http://lobid.org/resources/search?q=inCollection.id%3A%22http%3A%2F%2Flobid.org%2Fresources%2FHT014176012%23%21%22+AND+coverage%3A%2810+OR+12+OR+14+OR+23+OR+28+OR+52+OR+54+OR+72+OR+74%29+AND+_exists_%3Aspatial&format=bulk" | jq  -r '{ qid: .spatial[].id, notation: .coverage[] }'`)

**Comment by fsteeg** [comment]
Updated the list at https://github.com/hbz/nwbib/issues/397#issuecomment-451184837 based on our offline discussion.

**Comment by acka47** [comment]
We created the `non-90s-qids.json` file like this:

1. `http://lobid.org/resources/search?q=inCollection.id%3A%22http%3A%2F%2Flobid.org%2Fresources%2FHT014176012%23%21%22+AND+coverage%3A%2810+OR+12+OR+14+OR+23+OR+28+OR+52+OR+54+OR+72+OR+74%29+AND+_exists_%3Aspatial&format=bulk" | | jq -r '. | "\({ qid: .spatial[].id, notation: (.coverage[] / "| ") | last, label: .spatial[].label }),"' > ids-and-notations.json`
2. Adding the outer array and deleting the last comma by hand
3. `cat ids-and-notations.json | jq 'unique_by(.qid) | sort_by(.notation)' > ids-and-notations_sorted.json`
4. Removing the last entries with 90s notations by hand
5. Saving as `non-90s-qids.json`

**Comment by acka47** [comment]
This didn't work as expected, see `curl http://lobid.org/resources/HT018243227.json | jq -r '. | "\({ qid: .spatial[].id, notation: (.coverage[] / "| ") | last, label: .spatial[].label }),"'`

**Comment by acka47** [comment]
We decided to add the non-90s entries by using the manual mapping file at https://github.com/hbz/lobid-resources/blob/master/src/main/resources/string2wikidata.tsv plus the clerical regions via the three respective types, see the sparql query at https://github.com/hbz/lobid-resources/blob/e5e806b4806d0da4f9badd7d00219812db19d636/src/main/resources/getNwbibSubjectLocationsAsWikidataEntities.sparql#L39-L43

**Comment by fsteeg** [comment]
After talking with @dr0i I continued to look into the original approach by @acka47 and I think this is a good solution for now:

1. `curl "http://lobid.org/resources/search?q=inCollection.id%3A%22http%3A%2F%2Flobid.org%2Fresources%2FHT014176012%23%21%22+AND+NOT+coverage%3A%2896+OR+97+OR+99%29+AND+_exists_%3Aspatial&format=bulk" | jq -r '.spatial as $spatial | .coverage as $coverage | foreach .spatial[] as $i (0;.+1;"\({qid: $spatial[.-1].id, notation: ($coverage[.-1] / " | ") | last, label: $spatial[.-1].label}),")' > ids-and-notations.json`

2. Add the outer array and delete the last comma by hand

3. `cat ids-and-notations.json | jq 'unique_by(.qid)' > non-90s-qids.json`

To check if this result is good:

4. Get a list of all QIDs get got: `cat non-90s-qids.json | jq -r '(.[].qid / "/") | last' | sort -u > qids-actual.txt`

5. Get the QIDs in the TSV mapping: `wget https://raw.githubusercontent.com/hbz/lobid-resources/master/src/main/resources/string2wikidata.tsv ; cut -f 2 string2wikidata.tsv | sort -u > qids-temp.txt`

6. Add the QIDs from the geo index: `curl "http://weywot4.hbz-nrw.de:9200/geo_nwbib/wikidata-geo/_search?q=Q3146899%20OR%20Q2072238%20OR%20Q897303&size=9999" | jq -r '.hits.hits[]._id' | sort -u  >> qids-temp.txt ; cat qids-temp.txt | sort -u >> qids-expected.txt`

We can now compare `qids-expected.txt` and `qids-actual.txt`. (I used Eclipse: select both files, right-click, Compare with -> Each other, CLI option: `diff qids-expected.txt qids-actual.txt`)

There were 4 IDs missing in `qids-actual.txt`. 3 of these had 0 hits, the one remaining seems to be the only case where an item has a 99 notation and a non-99 notation that only appears in this resource (see the query in step 1). I added it manually to `non-90s-qids.json`:

```
{
  "qid": "http://www.wikidata.org/entity/Q55888099",
  "notation": "74",
  "label": "Herrschaft Horstmar"
}
```

Deployed to test: http://test.nwbib.de/classification?t=Raumsystematik

**Comment by acka47** [comment]
Was ist mit der Ordnung der Orte unter einer Notation, z.b. die Liste unter "Niederrhein-Gebiet"? Das scheint ja derzeit ungeordnet zu sein. ich glaube, es wäre sinnvoll, für das Treffen eine alphabetische Ordnung umzusetzen, oder?

**Comment by fsteeg** [comment]
Sortierung deployed: http://test.nwbib.de/classification?t=Raumsystematik

**Comment by fsteeg** [comment]
Einträge mit 0 Treffern entfernen und Trefferzahlen auf test deployed:

https://test.nwbib.de/classification?t=Raumsystematik

**Comment by fsteeg** [comment]
Fälschlicherweise automatisch durch https://github.com/hbz/lobid-resources/pull/950 geschlossen, öffne wieder.

**Comment by fsteeg** [comment]
Fix für fehlende Zwischenknoten auf test deployed (Email I.N., 17.1.):

https://test.nwbib.de/classification?t=Raumsystematik

**Comment by acka47** [comment]
+1 Kann wie beim NWBib-Treffen besprochen auf Production deployt werden.
