### ISSUE TITLE
Verortung von Einzeltreffern in Systematiken zeigen

### ISSUE THREAD

**Issue by fsteeg** [hbz/nwbib#398]
Im Gegensatz zur Verschlagwortung verorten die Raum- und die Sachsystematik Titel in einem System aus über- unter- und nebengeordneten Kategorien. Statt der scheinbar redundanten Darstellung von Schlagwörtern und Systematiken in den Einzeltrefferanzeigen sollten wir versuchen, die Verortung der Titel in den Systematiken darzustellen, z.B. über Ausschnitte der Baumdarstellung.

Dies hätte zudem den Effekt, Nutzer, die über Google auf Einzeltreffer stoßen, auf die Systematiken und die damit verbundenen Suchmöglichkeiten hinzuweisen.

Erfordert https://github.com/hbz/nwbib/issues/397.

**Comment by acka47** [comment]
Im Januartreffen wurde dies als gute Lösung gesehen, um Eindeutigkeit der Notationsstellen ohne Homonymzusätze (und damit Aänderungen in Wikidata) zu erreichen.

**Comment by fsteeg** [comment]
Vorschlag: wir setzen das um, indem wir die Breadcrumbs von den Systematiksuchen verbessern.

Hier schonmal mit den neuen Links auf die Systemstelle für die unterste Stelle:

https://test.nwbib.de/search?nwbibsubject=http%3A%2F%2Fpurl.org%2Flobid%2Fnwbib%23s102000

Das prinzipiell dann eingesetzt in die Detailseiten, in der Art:

https://test.nwbib.de/HT019749164

Aber statt `Regionen / Raumsystematik / Q2103 Bochum` den echten Weg dahin.

Also für das verlinkte Beispiel:

`9 Regierungsbezirke, Kreise, Orte. Euregio / Regierungsbezirk Arnsberg / Q2103 Bochum`
`1-2 Landschaften in Nordrhein-Westfalen / 20 Ruhrgebiet`
`1 Landeskunde (allgemein. Geo-u. Biowissenschaften) / 100000 Allgemeine Landeskunde / 102000 Landesbeschreibungen`

Oder verkürzt (Label nur beim letzten oder wenn keine Notation vorhanden):

`9 / Regierungsbezirk Arnsberg / Q2103 Bochum`
`1-2 / 20 Ruhrgebiet`
`1 / 100000 / 102000 Landesbeschreibungen`

Die Elemente würde jeweils auf die Stelle in der Systematik linken. Und das Gleiche hätten wir oben bei den Systematiksuchen (erster Link in diesem Kommentar).

**Comment by acka47** [comment]
+1 für den Ansatz

**Comment by fsteeg** [comment]
Nach einigem Experimentieren und Besprechungen vor Ort auf Test deployed.

Einzeltreffer:

https://test.nwbib.de/HT017403860
https://test.nwbib.de/HT016885624
https://test.nwbib.de/HT016061518
https://test.nwbib.de/HT015767786

Suchliste:

https://test.nwbib.de/search?nwbibsubject=http://purl.org/lobid/nwbib%23s613043
https://test.nwbib.de/search?nwbibspatial=http://purl.org/lobid/nwbib-spatial%23n01
https://test.nwbib.de/search?nwbibspatial=http://www.wikidata.org/entity/Q2264182

**Comment by acka47** [comment]
+1 Finde ich super als ersten Aufschlag. Können wir der Redaktion so zur Begutachtung geben.

**Comment by fsteeg** [comment]
Wieder geöffnet nach Feedback durch H.F. und U.P. (Emails vom 25.02.19).

- [ ] Sachsystematik: nur Notation und Name, z.B. `651030 Buddhismus`
- [ ] Raumsystematik, nicht-QID: wie Sachsystematik, z.B. `68 Grafschaft Mark`
- [ ] Raumsystematik, QID: max. zwei Ebenen, von unten bis zur ersten Notation, bei Bedarf Auslassung z.B. `9 > Kreis Lippe > Schlangen` oder `10 Westfälische Bucht > Senne`
- [ ] In Trefferliste ergänzt durch `Sachgebiete` bzw. `Regionen`

**Comment by fsteeg** [comment]
Auf Test deployed:

https://test.nwbib.de/HT019462868
https://test.nwbib.de/HT019721936
https://test.nwbib.de/HT019813722
https://test.nwbib.de/HT019697315

https://test.nwbib.de/search?nwbibsubject=http%3A%2F%2Fpurl.org%2Flobid%2Fnwbib%23s651030
https://test.nwbib.de/search?nwbibspatial=http%3A%2F%2Fpurl.org%2Flobid%2Fnwbib-spatial%23n68

**Comment by acka47** [comment]
Ich schicke dann mal eine E-Mail an die Liste wegen der Begutachtung.

**Comment by fsteeg** [comment]
Alle QID-Einträge bis zu ersten Notation anzeigen, auf test (Punkt 2 Email H.F., 2019-03-06):

https://test.nwbib.de/HT019462868
https://test.nwbib.de/HT019697315

**Comment by acka47** [comment]
+1
