### ISSUE TITLE
Knopf zum Kopieren von QID/Notation und Label in Systematiken

### ISSUE THREAD

**Issue by fsteeg** [hbz/nwbib#399]
Einzelne Einträge in ~~https://test.nwbib.de/classification?t=Wikidata~~ http://nwbib.de/spatial und http://nwbib.de/subjects sollten einen Knopf bekommen, über den QID/Notation und Label in die Zwischenablage kopiert werden können (von wo sie beim Katalogisieren im Aleph-Client eingefügt werden können).

z.B. für Köln: `Q365 Köln`

**Comment by fsteeg** [comment]
Deployed to test: https://test.nwbib.de/spatial

**Comment by acka47** [comment]
I suggest to leave this on test and deploy an "invisible" button (three spaces after the closing parentheses) on production and then let the editors decide which way to go.

**Comment by fsteeg** [comment]
Blank space with tooltips seems odd, just blank space is very bare-bones (no UI feedback on copy).

Another suggestion: use the icon and tooltips, place it after of the hit counts, but only show it on hover.

https://test.nwbib.de/spatial

**Comment by acka47** [comment]
+1
