### ISSUE TITLE
Enable export of Merkliste

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#40]
Currently, there only exists the possibility to create a "Merkliste" for one session. It should be possible to somehow save this list. 

Easiest solution: Get a list of lobid/NWBib URLs for the listed resources. We might offer this in a first step.

Later, we should offer a way to export list using different citation styles. This means, we should utilize [Citation Style Language (CSL)](http://citationstyles.org/) to enable export of a "Merkliste" in different citation styles.

**Comment by acka47** [comment]
This is another issue ranked with high priority by stakeholders. A rough estimate of implementation time for tomorrow's meeting would be nice, @fsteeg.

**Comment by fsteeg** [comment]
I've looked into CSL and after being a bit confused I now understand what this is about (different *presentations* of the Merkliste).

Stakeholders mentioned printing and saving as their use cases. For the printing, I'd expect they want the same format as in our details views. This is what we have in the old NWBib, and we can easily implement this based on existing templates.

This HTML export can also be saved, but for the saving, what I had in mind (and what CSL is *not* about, hence my confusion), was a data export so the Merkliste can be imported into citation management software. For that, the open, wide-spread option would probably be BibTeX.

So, CSL: not really what we need, I think. Perhaps a simple, printable, saveable HTML version is all we need here for now? Plus a new ticket, post-launch, for BibTeX export?

**Comment by acka47** [comment]
> Stakeholders mentioned printing and saving as their use cases. For the printing, I'd expect they want the same format as in our details views. This is what we have in the old NWBib, and we can easily implement this based on existing templates.

This would be the minimum. Ideally, we would support export of a list in different styles and formats (including BibTeX).

> This HTML export can also be saved, but for the saving, what I had in mind (and what CSL is *not* about, hence my confusion), was a data export so the Merkliste can be imported into citation management software. For that, the open, wide-spread option would probably be BibTeX.

Yes, BibTeX should be supported but also other formats. As far as I can see CSL supports BibTeX (see https://github.com/citation-style-language/styles/blob/7116881001d4e494c7f56140b177b99492255517/bibtex.csl) and [hundreds of styles and other formats](https://github.com/citation-style-language/styles).That is why I thought we should use it as base format to map lobid data on. I am not sure whether it is the right way to go, though. I think, @hatorikibble is quite knowledgeable about this and he can probably tell us how to best implement this. (I also just found [bibutils](http://bibutils.refbase.org/) which be a good fit for this but it doesn't look like it is maintained anymore).

> So, CSL: not really what we need, I think. 

As said above, I am not sure whether this is right.

> Perhaps a simple, printable, saveable HTML version is all we need here for now? Plus a new ticket, post-launch, for BibTeX export?

NWBib stakeholders will probably be content for the launch with a printable and downloadable version of the HTML. So please go ahead working on this. But we will also think about how to enable export in different citation styles _and_ bibliographic formats used by reference management software. As different formats and styles should better be offered on API level, the corresponding ticket should be opened at https://github.com/hbz/lobid.

**Comment by hatorikibble** [comment]
no sorry, I don't have any special BibTeX knowledge, talk to @heikojansen he implemented the bibliographic exports in the DigiBib

**Comment by acka47** [comment]
I have just started reading [Philipp Zumstein und Matti Stöhr (2015): Zur Nachnutzung von bibliographischen Katalog- und Normdaten für die persönliche Literaturverwaltung und Wissensorganisation](http://ub-madoc.bib.uni-mannheim.de/39937/1/abitech-2015-0037.pdf). It seems highly relevant for our discussion.

**Comment by fsteeg** [comment]
Deployed to staging, see: http://test.lobid.org/nwbib/stars

The link above now redirects to a URL with the IDs as query parameters, making the resulting URL shareable and bookmarkable, e.g. see: http://test.lobid.org/nwbib/stars?format=details&ids=HT015539122%2CHT015448633%2CHT017127240

I agree that CSL and BibTeX support make sense as part of the API and should get issues at https://github.com/hbz/lobid.

**Comment by acka47** [comment]
I think this solution is fine for the launch. I wonder whether we could shorten the URLs in any way. As the URL is for sharing a list with other people via email, twitter etc. it should be as short as possible. Having a list of ten titles already makes the URL quite long, e.g. http://test.lobid.org/nwbib/stars?ids=HT018843259%2CHT018774232%2CHT018843269%2CHT018807238%2CHT018544772%2CHT018652670%2CHT018495341%2CHT017823207%2CHT017386615%2CHT016708644.

@fsteeg Is there an easy option for shortening the links? 

Setting up a NWBib-specific URL shortener probably would be too much overhead, wouldn't it? On the other side a hbz-owned URL shortener could be used for other projects as well. (See also [this blog post](http://blog.sbb.berlin/urlshortener/) by Staatsbibliothek Berlin describing how they set up their own URL shortener with https://yourls.org/.)

**Comment by acka47** [comment]
> Setting up a NWBib-specific URL shortener probably would be too much overhead, wouldn't it? On the other side a hbz-owned URL shortener could be used for other projects as well.

This is right but we won't do this now and rather think about if, how and when to implement it in https://github.com/hbz/lobid/issues/278.

+1 for this then

**Comment by fsteeg** [comment]
Deployed to production, closing. See:

- http://lobid.org/nwbib/stars
- http://lobid.org/nwbib/stars?format=details&ids=HT015539122%2CHT015448633%2CHT017127240
