### ISSUE TITLE
Suchlink funktioniert nicht bei einer Ortssystematikstelle

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#400]
Gemeldet per E-Mail von I.N. am 2017-10-10:

> Bei der "Grafschaft Ravensberg" (69) gibt es keine Treffer. Mit der Systemstelle 69 sind aber 92 Titel verknüpft.
> 
> Merkwürdigerweise ist der Link immer gleich und führt auch zu Treffern, nur bei "69" nicht?
> 
> https://nwbib.de/search?nwbibspatial=http%3A%2F%2Fpurl.org%2Flobid%2Fnwbib-spatial%23n67
> 
> https://nwbib.de/search?nwbibspatial=http%3A%2F%2Fpurl.org%2Flobid%2Fnwbib-spatial%23n68
> 
> https://nwbib.de/search?nwbibspatial=http%3A%2F%2Fpurl.org%2Flobid%2Fnwbib-spatial%23n69
> 
> https://nwbib.de/search?nwbibspatial=http%3A%2F%2Fpurl.org%2Flobid%2Fnwbib-spatial%23n70

**Comment by acka47** [comment]
Das Problem muss beim der Transformation liegen. Ein Beispiel-Titel mit der Notation `69` in 700n.1a ist HT018107777, siehe [MAB XML](http://lobid.org/hbz01/HT018107777) im JSON taucht `http://purl.org/lobid/nwbib-spatial#n69` aber nicht auf.

Vgl. als funktionierendes Gegenbeispiel HT013358158 ([MABD XML](https://lobid.org/hbz01/HT013358158)) mit Notation `67` in 700n.1a, wo `http://purl.org/lobid/nwbib-spatial#n67` enstprechend im [JSON-LD](https://lobid.org/resources/HT013358158.json) auftaucht.

**Comment by acka47** [comment]
Offensichtlich deckt die regular expression in der [Morph, Zeile 2635](https://github.com/hbz/lobid-resources/blob/7d5a8083e6bf681e6a7952a371aefe65df819eb4/src/main/resources/morph-hbz01-to-lobid.xml#L2635) nicht die "69" mit ab. Statt `^([0-8][0-8]\b|91\b|96|97)\b` muss es `^([0-8][0-9]\b|91\b|96|97)\b` heißen.

**Comment by fsteeg** [comment]
67 und 69 geben wieder/weiter keine Treffer:

https://nwbib.de/search?nwbibspatial=http%3A%2F%2Fpurl.org%2Flobid%2Fnwbib-spatial%23n67
https://nwbib.de/search?nwbibspatial=http%3A%2F%2Fpurl.org%2Flobid%2Fnwbib-spatial%23n69

**Comment by acka47** [comment]
67 wurde entfernt (siehe https://github.com/hbz/lobid-vocabs/commit/da826952faa175593379af6da461d3e3891b8093) und 69 funktioniert: https://nwbib.de/search?nwbibspatial=http%3A%2F%2Fpurl.org%2Flobid%2Fnwbib-spatial%23n69

Mache zu.
