### ISSUE TITLE
Fragen zur Ortssystematik & Wikidata-Matching

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#405]
- http://lobid.org/resources/HT017470198.json: "Wülfrath-Rohdenhaus" wird momentan auf [Q161729](wikidata.org/entity/Q161729) (Wülfrath") gematcht, weil es Rohdenhaus in Wikidata nicht gibt. Was tun? - Ungenaues Matching akzeptieren oder Rohdenhaus anlegen?
-

**Comment by dr0i** [comment]
Die mit einem MINIMU_SCORE von <4 sind hier: https://gist.github.com/dr0i/162c8ef05def3058d69b5d0762e40c50.

**Comment by acka47** [comment]
Wie gesagt, hätte ich am liebsten eine csv-Datei mit folgenden Infos:

coverage_count, coverage_string, qid, score

**Comment by acka47** [comment]
Ich mach das Issue mal zu. Die konkrete Frage hat sich erledigt und die csv-Datei gibt es ja auch schon lange
