### ISSUE TITLE
lobid.org/nwbib URLs updaten

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#406]
Links auf eine übergeordnete Ressource sind noch nach dem Muster `lobid.org/nwbib/{hbzId}`, siehe z.B. https://nwbib.de/HT019480074. Für Endnutzer ist das nicht auffällig und kein Problem, weil auf nwbib.de weitergeleitet wird. Es ist allerdings unnötig und für manche verwirrend. Zudem werden diese URLs auch in Google indexiert, siehe https://www.google.de/search?q=site%3Alobid.org%2Fnwbib.

Auf der Startseite findet sich auch noch die alte URL im eingebetteten JSON-LD:

```json
{
  "@context":"http://schema.org",
  "@type":"WebSite",
  "url":"https://lobid.org/nwbib",
  "potentialAction":{
    "@type":"SearchAction",
    "target":"https://lobid.org/nwbib/search?q={search_term_string}",
    "query-input":"required name=search_term_string"
  }
}
```

**Comment by fsteeg** [comment]
Deployed to test:

https://test.nwbib.de/HT019480074
https://test.nwbib.de (see source)

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
Deployed to production, closing.

https://nwbib.de/HT019480074
https://nwbib.de (see source)
