### ISSUE TITLE
In Zeitschriftenliste fehlt jeweils erste Wort des Titels fehlt

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#407]
Heute gemeldet aus der NWBib-Redaktion:

> die Liste der laufend ausgewerteten NWBib-Zeitschriften sieht auf GitHub 
> völlig korrekt aus.
> 
> Aber auf unserer NWBib-Homepage (https://nwbib.de/journals) fehlt 
> jeweils das erste Wort des Titels.

**Comment by fsteeg** [comment]
Deployed to test: https://test.nwbib.de/journals

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
Deployed to production, closing. See https://nwbib.de/journals
