### ISSUE TITLE
Notationen auf oberster Ebene der Sachsystematik ergänzen

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#412]
Wie von H.F. am 2017-11-08 geschrieben:

> > Zur neuen ersten Ebene hätte ich allerdings noch eine Bitte. Anders als 
> bei der Raumsystematik wollen wir ja bei der umfangreicheren und tiefer 
> gestaffelten Sachsystematik die Notationen beibehalten. Nun erscheint es 
> ein wenig befremdlich, wenn auf erster Ebene der Sachsystematik die 
> Notationen fehlen, während ab der zweiten Ebene vollständige 
> Systemstellen aus Notation und Klassenbezeichnung verwandt werden. Von 
> daher sollten wir die einstellig-dezimalen Notationen zur obersten Ebene 
> auch ergänzen; diese Alternative hatten wir wie ich meine auch besprochen.

Unter https://nwbib.de/classification?t=Sachsystematik sollte es also wie folgt aussehen (vgl. auch das [Dokument aus Münster](https://app.syncwerk.de/f/d1af5e02cc/?raw=1), S.8:

```
1 Landeskunde (allgemein. Geo-u. Biowissenschaften)
2 Landeskunde (historisch)
4 Staat. Politik. Verwaltung. Recht
5 Bevölkerung. Soziales. Wirtschaft. Raumordnung. Umweltschutz
6 Religion
7 Volkskunde. Gesellschaft. Kultur. Bildung
8 Künste. Medien
```

**Comment by fsteeg** [comment]
Deployed to test: https://test.nwbib.de/classification?t=Sachsystematik

**Comment by acka47** [comment]
+1
