### ISSUE TITLE
Nwbib index for spatial lookups errors on stage

### ISSUE THREAD

**Issue by dr0i** [hbz/nwbib#414]
This works fine at quaoar1, but not on weywot2 `curl 'localhost:8010/nwbib/_search?q=*'`. No clue why.

**Comment by dr0i** [comment]
Also, why index the spatial turtle? The label of the id's are part of the data, enriched via ETL and the sidecar-approach via labels see e.g. http://lobid.org/resources/HT019307689.json.

**Comment by acka47** [comment]
Indexing spatial turtles.

![3390756279_e958124c8f_o](https://user-images.githubusercontent.com/160292/34522375-95a2ad9e-f092-11e7-8dac-abd805fcfd9c.jpg)

Source: "Space turtles" by [Parée](https://www.flickr.com/photos/pareeerica) on [Flickr](https://flic.kr/p/6aCvHa), licensed CC-BY.

**Comment by fsteeg** [comment]
Removed the old index in `target/universal/stage/data` and restarted nwbib, works fine now:

```
sol@weywot2:[~/git/nwbib] master
$ curl 'localhost:8010/nwbib/_search?q=*'
{"took":56,"timed_out":false,"_shards":{"total":5,"successful":5,"failed":0},"hits": [...]
```

I guess something went wrong when building the index previously, fetching the *.ttl from GitHub etc.

> Also, why index the spatial turtle?

@dr0i: the *.ttl files contain the classification hierarchy data for https://nwbib.de/classification?t=Raumsystematik and https://nwbib.de/classification?t=Sachsystematik

**Comment by dr0i** [comment]
Ok then. Thx.
The cause was probably that the old index was of `ES 2.6.3` rather than the now used `ES 5.6.3`. Discovered such effects myself locally when building ES-internal tests after upgrading to the new version.
Closing.
