### ISSUE TITLE
NWBib-Zeitschriftenliste aktualisieren

### ISSUE THREAD

**Issue by fsteeg** [hbz/nwbib#417]
Auf Basis der aktuellen CSV-Datei von I.N. vom 9.1.

**Comment by fsteeg** [comment]
Deployed to test: https://test.nwbib.de/journals

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
Deployed to production, closing. See https://nwbib.de/journals

**Comment by acka47** [comment]
I.N. hat heute eine neue csv mit der aktuellen Liste geschickt.

**Comment by fsteeg** [comment]
Auf test deployed, s. https://test.nwbib.de/journals & https://github.com/hbz/nwbib/commit/7bde2ff2a3664855f63a11b93cfff8c17b20148e

Beim nächsten Update sollten wir die manuellen Schritte aus https://github.com/hbz/nwbib/commit/7bde2ff2a3664855f63a11b93cfff8c17b20148e automatisieren (mit Metafacture oder OpenRefine).

Schon diesmal sollten wir die von uns vorgenommenen Korrekturen für HT019777111, HT017504290, HT020467258, HT019369585, HT020315604 (entferntes Sonderzeichen `�`), in HT007006464, HT004491517 (`fü` -> `für`) und HT017230962 (`[` ergänzt) zurückmelden.

**Comment by acka47** [comment]
+1
