### ISSUE TITLE
Falsche Facetten nach ISBN/ISSN-Suche

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#418]
Nach einer ISBN/ISSN-Suche sehen die Facetten aus als wäre die Ergebnisliste sehr groß, obwohl nur ein Titel drin ist. Siehe zum Beispiel https://nwbib.de/search?sort=newest&id=978-3658189129 wie auch https://test.nwbib.de/search?sort=newest&id=978-3658189129

(Ein kleiner Bug, den Nutzer/innen bzw. Kunden noch nicht bemerkt haben.)

**Comment by fsteeg** [comment]
Auf test deployed: https://test.nwbib.de/search?sort=newest&id=978-3658189129

**Comment by acka47** [comment]
Hmm, also looks good on production, see https://nwbib.de/search?sort=newest&id=978-3658189129. Did you already deploy to production. However, +1.

**Comment by fsteeg** [comment]
> Hmm, also looks good on production, see https://nwbib.de/search?sort=newest&id=978-3658189129.

Must have been a temporary fallback to staging, now/still not OK in production.

**Comment by acka47** [comment]
I think I didn't look correctly, so no falback. However, again +1 for the fix.
