### ISSUE TITLE
Ergebnisliste der Themensuche verbessern

### ISSUE THREAD

**Issue by fsteeg** [hbz/nwbib#422]
Anforderung aus Email von H.F. vom 16.3.2018: Ergebnisse der Themensuche sollen nur Themen enthalten, die einen der Suchbegriffe oder eine Verweisungsform eines Suchbegriffs enthalten.

Kurzfristig:

- [x] ~~Nur Themen anzeigen, die  in den Ansetzungsformen einen der Suchbegriffe enthalten~~

Mittelfristig, Verweisungsformen sauber unterstüzen, könnte 2. Hälfte 2018 bearbeitet werden:

- [ ] 1. In Transformation direkte Zuordnung Ansetzungs- und Verweisungsformen herstellen und im JSON abbilden, z.B. als Unterfeld `altLabels`:

```
"componentList": [{
    "gndIdentifier": "4012788-6",
    "id": "http://d-nb.info/gnd/4012788-6",
    "label": "Dormagen",
    "altLabels" : ["Durnomagus", "Stadt Dormagen"],
    "source": {
        "id": "http://d-nb.info/gnd/7749153-1",
        "label": "Gemeinsame Normdatei (GND)"
    },
    "type": ["PlaceOrGeographicName"]
}]
```

Siehe hierzu https://github.com/hbz/lobid-resources/issues/116.

- [ ] 2. Auf Basis dieser Daten separaten Hilfsindex für Themen aufbauen (z.B. embedded, wie die Systematik-Indexe) mit Inhalt in dieser Art:

```
{
    "label": "Dormagen | Bronzezeit | Vorrömische Eisenzeit | Keramik | Funde",
    "altLabels": [
        "Jungbronzezeit",
        "Frühe Bronzezeit",
        "Mittlere Bronzezeit",
        "Bodenfund",
        "Frühbronzezeit",
        "Spätbronzezeit",
        "Jüngere Bronzezeit",
        "Bodenfunde",
        "Späte Bronzezeit",
        "Archäologische Funde",
        "Durnomagus",
        "Ältere Bronzezeit",
        "Stadt Dormagen"
    ]
}
```

- [ ] 3. Themensuche auf diesen Index umstellen, in Trefferliste `label` anzeigen, bei Klick eine Suche wie bisher auslösen

**Comment by fsteeg** [comment]
Nur Themen anzeigen, die einen der Suchbegriffe enthalten: https://test.nwbib.de/topics?q=glessen

**Comment by acka47** [comment]
+1 von mir und H.F.

**Comment by acka47** [comment]
Hier der rlevante Teil der E-Mail.

On 23.03.2018 13:03, Flachmann, Holger wrote:
> Natürlich ist es schade, wenn bei Suche etwa mit der Verweisungsform "Müllbeseitigung" dann die Meldung kommt, keine Themen zur Anfrage gefunden zu haben, nur weil die Vorzugsbezeichnung nicht getroffen wurde. Dem könnte man ja durch die allgemein gefasste Aufforderung begegnen, andere Suchbegriffe zu versuchen. Keine Lösung fiel uns aber für den Fall ein, dass die Themensuche nach "Kindertageseinrichtung" sieben Treffer erzielt, weil es Einrichtungen gibt, die diese Wendung  im Namen führen. Dass es aber mit dem "richtigen", nämlich dem angesetzten Schlagwortbegriff "Kindertagesstätte" dann 268 Treffer gibt, dem könnte man natürlich durch Einrichtung einer "Keine-Treffer-Meldung" nicht beikommen.
> 
> Wir hatten nur überlegt, ob nicht eine generelle Sensibilisierung für das Vokabular weiter helfen könnte, wenn etwa im Zuge der Sucheingabe  angezeigt würde, bis zu welchem Buchstaben Treffer vorhanden sind (kennt man von Volltextsuchen). Noch besser könnte sein, mit dem Fortschritt der Sucheingabe eine Suchbegriffsliste zu generieren. Das haben wir für die Texteingaben bei der Erweiterten Suche im Biographischen Portal NRW so eingerichtet:
>      https://biographie-nrw.uni-muenster.de/advancedsearch
> 
> Eigentlich müsste man so etwas wieder einmal sehen? Ist das mit vertretbarem Aufwand möglich?

H.F.'s Anregungen haben mich dazu gebracht, mal darüber nachzudenken, die GND-API für Vorschläge (bei Eingabe einer Verweisungsform wird die Ansetzungsform als Suchterm vorgeschlagen) oder auch für Query Term Expansion zu benutzen. Da sollten wir uns auch mal Gedanlen drüber machen. (Die erste Variante hat den Vorteil, dass die Suchergebnisse transparent sind, ohne dass wir die Verweisungsformen anzeigen müssen.)

**Comment by fsteeg** [comment]
Themensuche nur für Ansetzungsformen ist produktiv: https://nwbib.de/topics?q=glessen

**Comment by fsteeg** [comment]
Suchvorschläge auf test deployed:

https://test.nwbib.de/topics?q=Müllbeseitigung
https://test.nwbib.de/topics?q=Theaterautor

**Comment by ChristophEwertowski** [comment]
+1 für die Suchvorschläge

**Comment by acka47** [comment]
Das sieht doch sehr gut aus. Da wird H.F. sich ja freuen. Ich denke, es wäre hilfreich, beim Suchvorschlag in Klammern die Anzahl der damit veknüpften Themen zu nennen, z.B. "Abfallbeseitigung (378 Themen)".

**Comment by fsteeg** [comment]
> Ich denke, es wäre hilfreich, beim Suchvorschlag in Klammern die Anzahl der damit veknüpften Themen zu nennen, z.B. "Abfallbeseitigung (378 Themen)".

Das geht an der Stelle nicht so ohne Weiteres, weil die Abfrage selbst ja gegen die GND-API geht und die Themenliste zudem nicht nur auf einer einfachen Anfrage basiert, sondern gefiltert wird (im Gegensatz zu den anderen Zahlen an der Stelle, die Anzahl der Treffer zu einem Thema).

**Comment by acka47** [comment]
Ah, ok. Dann lassen wir das. Zur Platzierung der Suchvorschläge: Ich glaube, es wäre besser, die Vorschläge immer direkt unter dem Eingabefenster anzuzeigen. So ist der Kontext gegeben.

**Comment by fsteeg** [comment]
Moved suggestions up: https://test.nwbib.de/topics?q=Kindertageseinrichtung

**Comment by acka47** [comment]
Das ist viel besser finde ich. +1

**Comment by ChristophEwertowski** [comment]
+1 auch von mir.

**Comment by fsteeg** [comment]
Opened corresponding pull request https://github.com/hbz/nwbib/pull/423 and assigned @dr0i.

@acka47: I think this resolves one of 3 aspects of this issue, the remaining being:

1. connection between preferred and variant names in the JSON data
2. enable auto-suggest for topic search (and advanced search?)

We should probably open separate issues for these if we want to pursue them.

**Comment by acka47** [comment]
For 1.) we have https://github.com/hbz/lobid-resources/issues/116 and I don't think we should push 2.) ourselves so I am happy with just closing this when deployed.
