### ISSUE TITLE
Bei Klick auf Körperschaft wird Personensuche gestartet

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#426]
... und es gibt null Ergebnisse. Siehe z.B "Düsseldorfer Schauspielhaus" ind https://nwbib.de/HT019622162.

**Comment by fsteeg** [comment]
Deployed to test, see:

https://test.nwbib.de/HT018582218
https://test.nwbib.de/HT019622162

**Comment by acka47** [comment]
+1
