### ISSUE TITLE
Suchvorschläge in Themensuche verbessern

### ISSUE THREAD

**Issue by fsteeg** [hbz/nwbib#428]
H.F., 6.4.:

> - [x] Suche nach "kita", [...] warum wir dort auch den japanischen Ort finden?

`Kita` als Token in `variantName`: `Kita Kyūshū` http://lobid.org/gnd/4110289-7.json

> - [x] Sucheingabe der Verweisungsform  "NRW" -> Suchvorschlag "Nordrhein-Westfalen"

Auf test deployed: https://test.nwbib.de/topics?q=NRW

E.L., 13.4.:

> - [x] Wie werden [Suchvorschläge] generiert? Nach welchen Auswahlkriterien gehen Sie vor? Welche GND-Kategorien werden durchsucht? Gibt man „Abfallbeseitigung“ in der lobid-GND ein und facettiert man dann nach Schlagwort erhält man 9 Treffer, aber nur die letzten 4 davon werden vorgeschlagen. Wir vermuten, dass Sie in allen (?) Feldern der Schlagwörter nach dem Begriff „Abfallbeseitigung“ suchen, unabhängig davon, ob es sich um ein Verweisungsfeld (4XXer abweichende Namensform) und Unterfeld oder Beziehungsfeld (5XXer Oberbegriffe etc.) handelt. Ist das so? Und wie begrenzen Sie die Anzahl der Vorschläge bzw. welche nehmen Sie nicht?

Aktueller Algorithmus für Suchvorschläge am Beispiel https://test.nwbib.de/topics?q=Kita

- Suche Eingabe in Verweisungsformen der GND: http://lobid.org/gnd/search?q=variantName:Kita
- Sammle alle Ansetzungformen der Ergebnisse
- Entferne alle Ansetzungformen-Dubletten und Ansetzungformen mit Leerstellen
- Sortiere aufsteigend nach Längendifferenz der Ansetzungformen zur Anfrage
- Wähle davon erste 10 Ansetzungsformen
- Ermittle Trefferzahl für Ansetzungsform in NWBib, z.B. https://nwbib.de/search?subject=Kitakyūshū
- Entferne Ansetzungformen mit 0 Treffern
- Sortieren Ansetzungformen absteigend nach Anzahl der Treffer der Ansetzungsform in NWBib

D.h. am Ende haben wir max. 10 Vorschläge, sortiert nach Trefferzahl der Ansetzungsform in NWBib.

Hier noch ein paar Beispiele:

https://test.nwbib.de/topics?q=Müllentsorgung
https://test.nwbib.de/topics?q=Kita
https://test.nwbib.de/topics?q=Abfallbeseitigung
https://test.nwbib.de/topics?q=Kunst
https://test.nwbib.de/topics?q=Geschichte

**Comment by ChristophEwertowski** [comment]
+1 In der Antwortmail kann die erste Frage ja gleich bei der Erklärung des Algorithmus für Suchvorschläge mitbeantwortet werden.

**Comment by fsteeg** [comment]
Auf production, s. https://nwbib.de/topics?q=NRW

Ich mache nochmal auf wegen Antwort an die NWBib-Redaktionen.

**Comment by fsteeg** [comment]
Nach Diskussion und Anpassungen mit @acka47 neu auf test deployed.

Aktueller Algorithmus für Suchvorschläge am Beispiel https://test.nwbib.de/topics?q=Kita

- Suche Eingabe in Verweisungsformen `variantName` der GND unter Ausschluss der Typen Körperschaft und Werk, eingeschränkt auf 500 Treffer: `https://lobid.org/gnd/search?q=variantName:Kita&filter=type:(NOT (ConferenceOrEvent Work))&size=500`
- Ermittle Trefferzahl in NWBib-Schlagwortsuche für GND-IDs im Ergebnis, z.B. https://nwbib.de/search?subject=http://d-nb.info/gnd/4372740-2
- Wähle davon alle GND-IDs mit mehr als 5 Treffern in NWBib-Schlagwortsuche
- Sortiere alle GND-IDs absteigend nach Trefferzahl in NWBib-Schlagwortsuche
- Zeige Ansetzungsform der ersten 3 Treffer

D.h. am Ende haben wir max. 3 Vorschläge, sortiert nach Trefferzahl der GND-ID in NWBib.

Hier noch ein paar Beispiele:

https://test.nwbib.de/topics?q=Müllentsorgung
https://test.nwbib.de/topics?q=LVR
https://test.nwbib.de/topics?q=NRW
https://test.nwbib.de/topics?q=Abfallbeseitigung
https://test.nwbib.de/topics?q=Kunst
https://test.nwbib.de/topics?q=Geschichte
https://test.nwbib.de/topics?q=Haynrix

**Comment by acka47** [comment]
+1

**Comment by acka47** [comment]
Sobald wir https://github.com/hbz/lobid-gnd/issues/80 umgesetzt haben, könne wir die Anzahl der aus lobid-gnd abgefragten Treffer (derzeit 500) wahrscheinlich deutlich reduzieren.

**Comment by fsteeg** [comment]
Deployed to production, closing. See:

https://nwbib.de/topics?q=Müllentsorgung
https://nwbib.de/topics?q=LVR
https://nwbib.de/topics?q=NRW
https://nwbib.de/topics?q=Abfallbeseitigung
https://nwbib.de/topics?q=Kunst
https://nwbib.de/topics?q=Geschichte
https://nwbib.de/topics?q=Haynrix
