### ISSUE TITLE
Add information on licensing, lobid as source and API querying

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#430]
There is no information about the license for NWBib data on nwbib.de. Also, people can not find out easily how to query the data over an API. (A link to lobid with the `inCollection` parameter should be provided.)

**Comment by acka47** [comment]
Mein Vorschlag: Wir ergänzen eine statische Seite unter 🛈. Hier ein Titel- und Textentwurf:

# Open Data

Die Daten der Nordrhein-Westfälischen Bibliographie sind unter einer offenen Lizenz ([CC0](https://creativecommons.org/publicdomain/zero/1.0/deed.de)) zur freien Nachnutzung verfügbar. Das Hochschulbibliothekszentrum des Landes Nordrhein-Westfalen (hbz) bietet die Daten als Bestandteil des hbz-Verbundkatalogs über [lobid-resources](http://lobid.org/resources) an. Die API-Dokumentation findet sich unter [https://lobid.org/resources/api](https://lobid.org/resources/api).

Für eine Einschränkung von lobid-API-Abfragen auf NWBib-Titel ist die Abfrage auf einfache Weise anzupassen, siehe dazu [https://hyp.is/v3CaLlqyEem7TlM93gt0sA/lobid.org/resources/api](https://hyp.is/v3CaLlqyEem7TlM93gt0sA/lobid.org/resources/api).

**Comment by fsteeg** [comment]
Deployed to test: https://test.nwbib.de/

**Comment by acka47** [comment]
+1
