### ISSUE TITLE
SPARQL-Query aktualisieren

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#431]
Die SPARQL-Abfrage wurde für lobid-resources angepasst, siehe https://github.com/hbz/lobid-resources/pull/805. Einige Anpassungen sollten auch für die NWBib-Sicht übernommen werden, vorerst aber nicht die Kirchenkreise und Diözesen, weil sie an anderer Stelle in die Ortssystematik "eingehängt" werden müssen.

**Comment by fsteeg** [comment]
Deployed to test: https://test.nwbib.de/classification?t=Wikidata

**Comment by acka47** [comment]
Sieht gut aus. +1

**Comment by acka47** [comment]
Es haben wieder einige Anpassungen der SPARQL-Query in lobid-resources stattgefunden. Reopening.

**Comment by acka47** [comment]
Die aktualisierte Query gibt 120 Einträge mehr als Ergebnis.
