### ISSUE TITLE
Changes in link templates should be effective without reload

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#434]
As in lobid-resources, when I adjust https://github.com/hbz/link-templates/blob/master/isil2opac_hbzid.json the OPAC links in NWBib should be directly adjusted.

**Comment by TobiasNx** [comment]
Wird unnötig durch #628 . Kann ich schließen @fsteeg

**Comment by TobiasNx** [comment]
Wir nutzen die linktemplates nicht mehr durch https://github.com/hbz/nwbib/issues/628, könnte eigentlich geschlossen werden @acka47

**Comment by acka47** [comment]
Closing
