### ISSUE TITLE
Manche Orte werden doppelt angezeigt in der Ortssystematik

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#441]
Siehe https://test.nwbib.de/classification?t=Wikidata.

Aus der Mailingliste:

>> Mir ist nur aufgefallen, dass bei Essen die Stadtteile einmal unter 
>> den jeweiligen Stadtbezirken auftauchen und einmal unter Essen selbst 
>> im Testsystem. Bei Düsseldorf stehen die Stadtteile dagegen entweder 
>> unter Düsseldorf direkt oder unter dem Stadtbezirk.
> 
> Alle Stadteile werden momentan doppelt angezeigt, wenn in Wikidata ein 
> doppelter Eintrag bei "liegt in der Werwaltungseinheit" ist, siehe z.B. 
> Essen-Bochold: https://www.wikidata.org/wiki/Q257616 Das werden wir auf 
> jeden Fall im System anpassen, dass ein Ort nur an der jeweils untersten 
> Hierarchieebene angezeigt wird.

Aber:

>> Unter dem ehemaligen Landkreis Düsseldorf hängen fälschlich etwa 19000 
>> Titel, die richtig auch bei der Stadt Düsseldorf auftauchen.
> 
> Auch hier ist das Problem, dass in Wikidata Düsseldorf auch zwei 
> Einträge unter "liegt in der Verwaltungseinheit" hat, siehe 
> https://www.wikidata.org/wiki/Q1718. Allerdings wäre es hier nicht 
> richtig, nur den Eintrag der untersten Hierarchiebene zu zeigen. Wir 
> werden uns etwas überlegen.

**Comment by acka47** [comment]
Da mit dem Landkreis Düsseldorf (Q1803134) eh keine Titel verknüpft sind, werde ich die SPARQL Query updaten, so dass der alte Landkreis gar nicht mehr als Teil ders Ergebnis zurückkommt.

**Comment by acka47** [comment]
> Da mit dem Landkreis Düsseldorf (Q1803134) eh keine Titel verknüpft sind, werde ich die SPARQL Query updaten, so dass der alte Landkreis gar nicht mehr als Teil des Ergebnis zurückkommt.

Done, siehe https://github.com/hbz/nwbib/pull/443/commits/6c98f9f11fc69539f8d32ed4addb2ea4502b6781

Das heißt, jetzt muss nur dafür gesorgt werden, dass alle Wikidata-Entitäten nur einmal in der Systematik auftauchen und zwar an der jeweils untersten möglichen Ebene der Hierarchie.

**Comment by fsteeg** [comment]
Deployed to test: https://test.nwbib.de/classification?t=Wikidata

**Comment by acka47** [comment]
+1
