### ISSUE TITLE
Einige Notationen werden nicht in der Sachsystematik angezeigt

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#442]
Aus einer Mail von U.P. vom 2018-10-31 an die NWBib-Liste:

> eine Kollegin in Bonn hat festgestellt, dass in der Sachsystematik 
> (Sachgebiete) auf der nwbib.de-Seite einige Kategorien fehlen, z.B. 
> 865020 Bibliotheksgeschichte, 865070 Schulbibliotheken, 880100 
> Publizistik. Information und Dokumentation - Allgemeines und 882000 
> Publizistik mit diversen Untergliederungen. Könnten Sie sich das bitte 
> anschauen.

Ich habe keine Ahnung, ob und wieviele weitere Notationen außer den genannten betroffen sind. Alle genannten Notationen sind im [SKOS-Schema](http://purl.org/lobid/nwbib) und sollten also auch angezeigt werden. Von daher liegt das Problem wahrscheinlich bei der Generierung der Systematik-Seite.

Übrigens gbt es zu allen Notationen Treffer in der NWBib ([865020](https://nwbib.de/search?nwbibsubject=http%3A%2F%2Fpurl.org%2Flobid%2Fnwbib%23s865020), [865070](https://nwbib.de/search?nwbibsubject=http%3A%2F%2Fpurl.org%2Flobid%2Fnwbib%23s865070), [880100](https://nwbib.de/search?nwbibsubject=http%3A%2F%2Fpurl.org%2Flobid%2Fnwbib%23s880100), [882000](https://nwbib.de/search?nwbibsubject=http%3A%2F%2Fpurl.org%2Flobid%2Fnwbib%23s882000)), wo dann auch das richtige Label angezeigt wird.

**Comment by fsteeg** [comment]
Deployed to test: https://test.nwbib.de/classification?t=Sachsystematik
