### ISSUE TITLE
ss für ß im Systematikfilter

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#447]
I.N. schrieb am 2019-01-25 via Mailingliste in Bezug auf den Filter unter https://test.nwbib.de/classification?t=Raumsystematik:

> Die Orte 
> „Schloß Holte- Stukenbrock“ und „Schloß Neuhaus“ werden nur bei der 
> Eingabe von „Schloß“ mit „ß“  gefunden. Auch bei Eingabe von „Schloss“ 
> sollten sie angezeigt werden.

**Comment by fsteeg** [comment]
Deployed to test: https://test.nwbib.de/classification?t=Raumsystematik

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
Closing, will be deployed with https://github.com/hbz/nwbib/issues/397 as discussed yesterday.
