### ISSUE TITLE
Recherche mit der Sachgruppe 841040 funktioniert nicht

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#449]
Soeben gemeldet via E-Mail von I.N.:

> Recherche mit der Sachgruppe *841040 
> https://nwbib.de/search?nwbibsubject=http%3A%2F%2Fpurl.org%2Flobid%2Fnwbib%23s841040

**Comment by fsteeg** [comment]
Deployed to test:
https://test.nwbib.de/search?nwbibsubject=http%3A%2F%2Fpurl.org%2Flobid%2Fnwbib%23s841040

Caused by https://github.com/hbz/lobid-resources/issues/953

**Comment by acka47** [comment]
+1
