### ISSUE TITLE
Identify unmatched "coverage"

### ISSUE THREAD

**Issue by dr0i** [hbz/nwbib#451]
This comes from https://wiki1.hbz-nrw.de/display/SEM/NWBib-Raumsystematik-Treffen+2019:
How many "coverage" entries couldn't be matched? The API search @acka47 used is not sufficient if there are more than one "coverage" where one is without a hit.

**Comment by dr0i** [comment]
hduser@weywot1:log$ grep ' No hit' 20190123-0100-stage.startHbz02ToLobidResources.sh | cut -d \( -f2 |cut -d ',' -f1 | sort -u
Aachen Eilendorf
Aachen Orsbach
Aachen Schmithof
Aachen Sief
Aachen Soers
Aachen Vaalserquartier
Ahaus Ober Ortwick
Alsdorf  Broicher Siedlung
Altenbrock
Altersloh
Altninnentrop
Ammath
Arnsberg Bergheim
ArnsbergNeheim
Artelshofen
Astenberg
Bad Berleburg  Kühhude
Bad Berleburg  Müsse
Bad Salzuflen  Knetterheide
Beek  Xanten
Bembüren
Bensberg Immekeppel
Berenbrock  Lüdinghausen
Berge  Hamm  Westfalen
Bergheim  Steinheim  Höxter
Bergisch Gladbach  Dürscheiderhütte
Bergisch Gladbach  Oberlückerath
Bielefeld Hoberge
Bippen
Bochum Rechen
Bockum  Hamm  Westfalen
Bonn Bad Godsberg
Bonnenbroich Geneicken
Bonn Geislar
Bonn Großenbusch
Bonn Limperich
Bonn Schweinheim
Bremke  Menden  Sauerland
Bruchhausen  Leverkusen
Brühl Geildorf
Brüningsen
Buchholz  Hattingen
Buchholz  Paderborn
Buir  Kerpen  Rhein Erft Kreis
Burtscheid  Kreis Aachen
Coesfeld Stockum
Dinxperlo
Diözese Köln
Dissen  Teutoburger Wald
Domagen Straberg
Dortmund Hohensyburg
Dortmund Mitte
Dreisbach  Siegen
Drolshagen Germinghausen
Duisburg Essenberg
Duisburg Kaldenhausen
Duisburg Obermarxloh
Duisburg Vierlinden
Eichen  Freudenberg  Siegen Wittgenstein
Eiden
Eilendorf  Aachen
Eitorf Probach
Ermgassen
Erzdiözese Köln
Everswinkel Müssingen
Friedrichsthal  Olpe
Frielinghausen  Hamm  Westfalen
Geildorf
Gladbach Rheydt Odenkirchen
Glandorf
Grafschaft Schanze
Grevenbroich Königshoven
Grevenhagen  Steinheim  Höxter
Grotenrath
Gummerbach
Hackhausen  Jüchen
Hadamar
Haffen Mehr
Hagedorn  Steinheim  Kreis Höxter
Hagen am Teutoburger Wald
Handorf Dorbaum
Harth  Büren  Paderborn
Häverstedt
Heeren  Rees
Heide  Altena
Heide  Brühl  Rhein Erft Kreis
Heinsberg Kirchoven
Herkensiefen
Herscheid Hüinghausen
Herten Bertlich
Hickengrund
Höllinghofen
Holthusen
Holzminden
Hombroich
Horster Schelsen
Hörstgen
Hüffe  Preußisch Oldendorf
Idensen
Jüchen Kamphausen
Jüchen Mürmeln
Jüchen Schaan
Kappellen  Moers
Kekerdom
Kerpen  Eifel
Kerpen Loogh
Kesten
Kevelar Winnekendonk
Keylaer
Kitzenhaus
Koblenz
Köln  Diözese
Köln  Erzdiözese
Köln Kasselberg
Köln Langel  Merkenich
Kourl
Krauthausen  Aachen
Krefeld  Kempener Feld
Kreis Mülheim an der Ruhr
Kreuztal Osthelden
Kronenburg  Dahlem Kr  Euskirchen
Landkreis Gummersbach
Landkreis Waldbröl
Langern  Werne
Lengerich Wechte
Leopoldshöhe Dahlhausen
Leveringhausen  Waltrop
Lüdinghausen Borkenberge
Lüdinghausen  Region
Marialinden Schlingenthal
Mark  Hamm  Westfalen
Maubach  Herzogenrath
Meerbusch  Meerer Busch
Meinersen
Meinerzhagen Schürfelde
Melaten  Köln
Melle
Menzerath
Merbusch Büderich
Merrbusch Langst Kirst
Merten Bourauel
Meyerhöfen
Mönchengladbach Heyden
Mönchengladbach Rheindalen
Monheim Hitdorf
Monschauer Land
Monschau  Region
Mülheim Eppinghofen
Müllen
Müsse  Berleburg
Neuenrade Kesberg
Neuss Eppinghoven
Niederbreitbach
Niedermenden  Honschaft
Nonnenwerth
Nordinker
Nordlünern
Oberbonsfeld
Oberndorf  Westfalen
Oberriefenrath
Oberrieferath
Oberzündorf
Olfen Vinnum
Pattern b  Aldenhoven
Perm
Petternich
Raeren
Raesfeld Homer
Rahden Varlheide
Rennekoven
Rheidt  Bergheim  Erft
Rodenwalde
Rothenfelde
Salchendorf  Neunkirchen  Siegen Wittgenstein
Schaan  Jüchen
Schagern
Schöneshof
Schwalmtal Hostert
Seelbach Marienthal
Siegburg Seligental
Sohl  Berleburg
Spädinghausen
Speelberg
Stadthagen
Stadtkyll
Stadtlohn Büren
Steinhelle
Stemshorn
Stieldorf Birlinghoven
Stockem  Stolberg  Rheinland
Venne  Senden  Kreis Coesfeld
Vinnum
Vossenack Simonskall
Waasenberg
Waat
Wahlscheid Dahlhaus
Waldbröl Benroth
Wardhausen
Warendorf Klauenberg
Warmel
Wechte
Wegholm
Weilerswist  Groß Vernicht
Welver Hangfort
Westkapelle
Wickeder Holz
Wilberhofen  Sieg
Winterberg Mollenseifen
Wissel  Kalkar  Kreis Kleve
Witten Bommerholz
Wollseifen
Würselen Schweilbach
=>212

**Comment by dr0i** [comment]
Aachen Niederforstbach
Aachen Sief
Aachen Soers
Aachen Vaalserquartier
Bad Berleburg  Müsse
Beek  Xanten
Bensberg Immekeppel
Bergisch Gladbach  Dürscheiderhütte
Bergisch Gladbach  Oberlückerath
Bonn Bad Godsberg
Bonnenbroich Geneicken
Bonn Geislar
Bonn Großenbusch
Bonn Limperich
Bonn Schweinheim
Bruchhausen  Leverkusen
Brühl Geildorf
Buir  Kerpen  Rhein Erft Kreis
Burtscheid  Kreis Aachen
Coesfeld Stockum
Dinxperlo
Duisburg Alsum
Duisburg Essenberg
Duisburg Kaldenhausen
Duisburg Obermarxloh
Duisburg Vierlinden
Eitorf Probach
Friedewald
Friedrichsthal  Olpe
Geildorf
Gladbach Rheydt Odenkirchen
Grevenbroich Königshoven
Grotenrath
Gummerbach
Hackhausen  Jüchen
Hadamar
Haffen Mehr
Hagedorn  Steinheim  Kreis Höxter
Heeren  Rees
Heide  Brühl  Rhein Erft Kreis
Heinsberg Kirchoven
Herkensiefen
Hombroich
Horster Schelsen
Hörstgen
Jüchen Kamphausen
Jüchen Mürmeln
Jüchen Schaan
Kappellen  Moers
Katholische Kirche  Erzdiözese Paderborn
Kekerdom
Kerpen  Eifel
Kerpen Loogh
Kevelar Winnekendonk
Keylaer
Kitzenhaus
Köln Kasselberg
Köln Langel  Merkenich
Königswinter Heisterbach
Kourl
Krauthausen  Aachen
Krefeld  Kempener Feld
Kreis Mülheim an der Ruhr
Kronenburg  Dahlem Kr  Euskirchen
Landkreis Gummersbach
Landkreis Waldbröl
Marialinden Schlingenthal
Maubach  Herzogenrath
Meerbusch Langst Kirst
Meerbusch  Meerer Busch
Melaten  Köln
Menzerath
Merten Bourauel
Mönchengladbach Heyden
Mönchengladbach Rheindalen
Monheim Hitdorf
Monschauer Heckenland
Monschau  Region
Mühlheim an der Ruhr
Mülheim Eppinghofen
Müsse  Berleburg
Neuss Eppinghoven
Niedermenden  Honschaft
Oberbonsfeld
Oberriefenrath
Oberrieferath
Pattern b  Aldenhoven
Perm
Petternich
Raeren
Rennekoven
Rheidt  Bergheim  Erft
Rodenwalde
Schaan  Jüchen
Schöneshof
Schwalmtal Hostert
Seelbach Marienthal
Speelberg
Steinhelle
Stemmer  Minden  Westfalen
Stieldorf Birlinghoven
Stockem  Stolberg  Rheinland
Vossenack Simonskall
Waasenberg
Waat
Wahlscheid Dahlhaus
Waldbröl Benroth
Wardhausen
Wechte
Weilerswist  Groß Vernicht
Westkapelle
Wilberhofen  Sieg
Wissel  Kalkar  Kreis Kleve
Witten Wengern
Wollseifen
Wuppertal Hohenhagen
Wuppertal Sandfeld
Würselen Schweilbach
=> 118

**Comment by acka47** [comment]
@dr0i Can you please provide the current list of unmatched strings?

**Comment by dr0i** [comment]
Aachen Niederforstbach
Beek  Xanten
Bensberg Immekeppel
Bergisch Gladbach  Dürscheiderhütte
Bergisch Gladbach  Oberlückerath
Bonn Bad Godsberg
Bonnenbroich Geneicken
Bonn Geislar
Bonn Großenbusch
Bonn Limperich
Bonn Schweinheim
Bruchhausen  Leverkusen
Brühl Geildorf
Buir  Kerpen  Rhein Erft Kreis
Burtscheid  Kreis Aachen
Duisburg Alsum
Duisburg Essenberg
Duisburg Kaldenhausen
Duisburg Obermarxloh
Duisburg Vierlinden
Düsseldorf Kaiserwserth
Düsselodrf
Eitorf Probach
Geildorf
Gladbach Rheydt Odenkirchen
Grevenbroich Königshoven
Grotenrath
Gummerbach
Hackhausen  Jüchen
Hadamar
Haffen Mehr
Heeren  Rees
Heide  Brühl  Rhein Erft Kreis
Heinsberg Kirchoven
Herkensiefen
Hombroich
Horster Schelsen
Jüchen Kamphausen
Jüchen Mürmeln
Jüchen Schaan
Kappellen  Moers
Katholische Kirche  Erzdiözese Paderborn
Kekerdom
Kerpen  Eifel
Kerpen Loogh
Kevelar Winnekendonk
Keylaer
Kitzenhaus
Königswinter Heisterbach
Krefeld  Kempener Feld
Kreis Mülheim an der Ruhr
Kronenburg  Dahlem Kr  Euskirchen
Landkreis Gummersbach
Landkreis Waldbröl
Maubach  Herzogenrath
Meerbusch Langst Kirst
Meerbusch  Meerer Busch
Melaten  Köln
Menzerath
Mönchengladbach Heyden
Mönchengladbach Rheindalen
Monheim Hitdorf
Monschau  Region
Mühlheim an der Ruhr
Mülheim Eppinghofen
Neuenkirchen  Sankt Arnold
Neuss Eppinghoven
Niedermenden  Honschaft
Oberbonsfeld
Oberriefenrath
Oberrieferath
Pattern b  Aldenhoven
Perm
Petternich
Raeren
Rennekoven
Rodenwalde
Schaan  Jüchen
Schöneshof
Schwalmtal Hostert
Speelberg
Stockem  Stolberg  Rheinland
Waasenberg
Waat
Wahlscheid Dahlhaus
Waldbröl Benroth
Wardhausen
Weilerswist  Groß Vernicht
Westkapelle
Wilberhofen  Sieg
Wissel  Kalkar  Kreis Kleve
Witten Wengern
Wollseifen
Würselen Schweilbach
=> 94

**Comment by dr0i** [comment]
$ grep ' No hit' 20190218-1103-stage.startHbz02ToLobidResources.sh  | cut -d \( -f2 |cut -d ',' -f1 | sort -u 
Duisburg Beek
Gladbach Rheydt
Kreis Westel
Mülheim Eppinghofen
Rennekoven
Stockem  Stolberg  Rheinland
Wahlscheid Dahlhaus

**Comment by acka47** [comment]
@dr0i, what's the current status? According to the NWBib editors there shouldn't exist any not-matched strings  anymore.

**Comment by dr0i** [comment]
NWBib editors are correct indeed.

**Comment by acka47** [comment]
Closing for now but we will have to check the matching in the coming weeks sporadically.
