### ISSUE TITLE
Direkte Links auf Einträge mit Kontext in Systematiken

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#452]
Todos aus dem Januartreffen: 
- [x]  ~Euregio ganz unten anzeigen~
- [x] ~Klick auf Systematikstelle führt zu Sicht der jeweiligen Stelle im Kontext, Klick auf Trefferanzahl führt zur Trefferliste. Dies auch symmetrisch für die Sachsystematik.~

**Comment by acka47** [comment]
DFer erste Punkt muss auch im SKOS umgesetzt werden.

**Comment by fsteeg** [comment]
Euregio ganz unten anzeigen deployed: https://test.nwbib.de/classification?t=Raumsystematik

**Comment by acka47** [comment]
Ich werde das am [SKOS]() anpassen. Du nutzt ja sicher die `skos:broader`-Angaben für die Darstellung der Hierarchie, oder?

**Comment by acka47** [comment]
Ach ne, geht ja gar nicht. Dafür müssen wir erst https://github.com/hbz/lobid-vocabs/issues/85 umsetzen. Dann können wir das aus diesem Ticket einfach rausnehmen, oder? Wenn die Hierarchie eh aus dem SKOS übernommen wird, reicht ja die Anpassung da.

**Comment by fsteeg** [comment]
> Du nutzt ja sicher die skos:broader-Angaben für die Darstellung der Hierarchie, oder?

Genau, aber die neuen Untereinträge sind ja Wikidata-Einträge, d.h. die sind ja (noch) gar nicht im SKOS und können daher auch keine skos:broader Angaben bekommen.

Kommt grad rein:

> Ach ne, geht ja gar nicht. Dafür müssen wir erst hbz/lobid-vocabs#85 umsetzen. Dann können wir das aus diesem Ticket einfach rausnehmen, oder?

Klingt gut!

**Comment by fsteeg** [comment]
Deployed to test:

https://test.nwbib.de/classification?t=Raumsystematik#n10
https://test.nwbib.de/classification?t=Raumsystematik#Q3069
https://test.nwbib.de/classification?t=Sachsystematik#s500000

**Comment by acka47** [comment]
Das sieht sehr gut aus, genauso habe ich mir das vorgestellt! Eine Sache ist mir noch bei der URL aufgefallen. Ich finde  den Parameter für die Raumsystematik (immer noch) ungewöhnlich. Wäre nicht `nwbib.de/classification/raumsystematik#Q325202` netter oder direkt `nwbib.de/raumsystematik#Q325202`?

**Comment by fsteeg** [comment]
> Eine Sache ist mir noch bei der URL aufgefallen. Ich finde den Parameter für die Raumsystematik (immer noch) ungewöhnlich. Wäre nicht nwbib.de/classification/raumsystematik#Q325202 netter oder direkt nwbib.de/raumsystematik#Q325202?

Wir haben ja Klassifikationen und Register:

http://nwbib.de/classification
http://nwbib.de/register

Das plus Typ als Pfad wäre dann sowas:
```
http://nwbib.de/classification/sachsystematik
http://nwbib.de/classification/raumsystematik
http://nwbib.de/register/sachsystematik
http://nwbib.de/register/raumsystematik
```
Man könnte es konzeptuell auch umdrehen:
```
http://nwbib.de/sachsystematik/classification
http://nwbib.de/sachsystematik/register
http://nwbib.de/raumsystematik/classification
http://nwbib.de/raumsystematik/register
```
Und dann vielleicht statt Sach/Raum im Parameter classification/register:
```
http://nwbib.de/sachsystematik?t=classification
http://nwbib.de/sachsystematik?t=register
http://nwbib.de/raumsystematik?t=classification
http://nwbib.de/raumsystematik?t=register
```
Dazu classification als default und, weil alle Pfade bisher englisch sind, vielleicht `classes` statt Sachsystematik und `spatial` statt Raumsystematik:
```
http://nwbib.de/classes
http://nwbib.de/classes?t=register
http://nwbib.de/spatial
http://nwbib.de/spatial?t=register
```

Was wir dann (konzeptuell) nicht mehr hätten wären die Übersichtsseiten:

http://nwbib.de/classification
http://nwbib.de/register

**Comment by acka47** [comment]
As discussed on the phone, we will do it like this with `?classification` as default parameter not being shown in the URL:

```
http://nwbib.de/subjects
http://nwbib.de/subjects?t=register
http://nwbib.de/spatial
http://nwbib.de/spatial?t=register
```

**Comment by fsteeg** [comment]
Auf test deployed:

http://test.nwbib.de/subjects
http://test.nwbib.de/subjects?t=register
http://test.nwbib.de/spatial
http://test.nwbib.de/spatial?t=register

Wo ich das Register zur Raumsystematik sehe: da sind die neuen Sachen ja noch nicht drin. Sollen die da rein? Wäre extrem lang die Liste mit über 8000. Aber so machts ja irgendwie keinen Sinn. Sollen vielleicht nur die nicht-9er rein?

**Comment by acka47** [comment]
+1

(kurzer Einwurf: Mir ist jetzt aufgefallen, dass im Raumsystematik-Register die neuen Orte aus Wikidata noch nicht auftauchen. Das wird sich dann ja mit https://github.com/hbz/lobid-vocabs/issues/85 ändern.)
