### ISSUE TITLE
Verhältnis distinkte_QID/Geo_nwbib-index

### ISSUE THREAD

**Issue by dr0i** [hbz/nwbib#455]
Todo aus dem Januar-Treffen.: 
Setze distinkte QIds ins Verhältnis des Geo-Nwbib-Index (der auf Grund der SPARQL und der manuellen Liste ermittelt wurde).

**Comment by dr0i** [comment]
> $ grep Hit  20190127-0100-stage.startHbz02ToLobidResources.sh |sed 's#.*id":"http://www.wikidata.org/entity/\([^"]*\).*#\1#g' |sort -u > distinctQids_20190127-0100.txt
$ wc -l distinctQids_20190127-0100.txt
4221`

Der `geo_nwbib`-Index hält 8768 Einträge. => Verhältnis ca. 1/2 (ganz genau: 0.48).

**Comment by acka47** [comment]
Danke.
