### ISSUE TITLE
Notationen in Raumsystematik anzeigen

### ISSUE THREAD

**Issue by fsteeg** [hbz/nwbib#456]
s. https://wiki1.hbz-nrw.de/display/SEM/NWBib-Raumsystematik-Treffen+2019 (zugriffsbeschränkt)

**Comment by fsteeg** [comment]
Auf test deployed:

https://test.nwbib.de/classification?t=Raumsystematik
https://test.nwbib.de/classification?t=Sachsystematik

**Comment by acka47** [comment]
+1
