### ISSUE TITLE
Räumliche Erschließung auf QIDs anstatt Strings umstellen

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#470]

**Comment by acka47** [comment]
Momentan läuft noch die Abstimmung per Mailingliste, wie die Werte im Detail in 700n gespeichert werden sollen, siehe den Thread mit Betreff "NWBib-Systemstellen: Anzeige in der Webausgabe und Katalogisierung im hbz-Verbundkatalog".

**Comment by acka47** [comment]
Wir haben nun grünes Licht. Die Werte in 700n sollen wie in den folgenden Beispielen aussehen:

- https://nwbib.de/spatial#Q767106 Senne
- https://nwbib.de/spatial#Q20826977 Uentrop

Das heißt, wir werden auch den Namensraum des SKOS-Vokabulars ändern von `http://purl.org/lobid/nwbib-spatial#` zu `https://nwbib.de/spatial#`.

Ich werde als nächstes eine Test-Update-Datei für die Verbundgruppe erstellen.

**Comment by acka47** [comment]
Die Copy-Paste-Funktion muss in beiden Systematiken angepasst werden. @fsteeg, wie besprochen setzen wir das innerhalb dieses Issues um.

**Comment by fsteeg** [comment]
Deployed to test:

https://test.nwbib.de/spatial
https://test.nwbib.de/subjects

**Comment by acka47** [comment]
+1 Da wir die URIs ja eh anpassen, könnten wir nun natürlich auch die verwirrende Inkonsistenz bei den Buchstaben vor den Notationen ("n" bei spatial, "s" bei subjects) anpassen. Wir können es aber meinetwegen auch einfach so lassen.

**Comment by acka47** [comment]
Nach dem Deployen das Ticket bitte nicht schließen, sondern in Ready zurückschieben.

**Comment by fsteeg** [comment]
> Da wir die URIs ja eh anpassen, könnten wir nun natürlich auch die verwirrende Inkonsistenz bei den Buchstaben vor den Notationen ("n" bei spatial, "s" bei subjects) anpassen.

Oh ja, das ist eine gute Idee. Auf test deployed:

https://test.nwbib.de/spatial
https://test.nwbib.de/subjects

**Comment by acka47** [comment]
So war das nicht gemeint. Nach dem Namespace darf keine Nummer kommen, weil es sonst in RDF/XML Probleme gibt. Das heißt, wir müssen einen Buchstaben voranstellen, können aber für beide Systematiken denselben nehmen. Mein Vorschlag wäre "n" für "Notation".

**Comment by fsteeg** [comment]
Auf test deployed (wie eben besprochen mit großem N für Konsistenz mit Q-IDs):

https://test.nwbib.de/spatial
https://test.nwbib.de/subjects

**Comment by acka47** [comment]
+1

**Comment by acka47** [comment]
Die Art der Speicherung von URI plus String in 700n wird ja nun anders ablaufen als in .https://github.com/hbz/nwbib/issues/470#issuecomment-483588151 dargestellt. Die endgültige Fassung mit Ablage von String und URI in unterschiedlichen Unterfeldern ist im [Wiki](https://service-wiki.hbz-nrw.de/pages/viewpage.action?pageId=339607588#URIsstattGSWundNotationeninhbz01&Lokalsystemen-Nachher) dokumentiert, hier das Beispiel:

```xml
<datafield tag="700" ind1="n" ind2="1">
    <subfield code="a">Ruhrgebiet</subfield>
    <subfield code="0">https://nwbib.de/spatial#N20</subfield>
</datafield>
<datafield tag="700" ind1="n" ind2="1">
    <subfield code="a">Duisburg</subfield>
    <subfield code="0">https://nwbib.de/spatial#Q2100</subfield>
</datafield>
<datafield tag="700" ind1="n" ind2="1">
    <subfield code="a">Essen</subfield>
    <subfield code="0">https://nwbib.de/spatial#Q2066</subfield>
</datafield>
<datafield tag="700" ind1="n" ind2="1">
    <subfield code="a">Einzelne Autoren (Primärliteratur)</subfield>
    <subfield code="0">https://nwbib.de/subjects#N768010</subfield>
</datafield>
```

**Comment by fsteeg** [comment]
Entsprechend der neuen Speicherung der Unterfelder müssen auch die Copy-Knöpfe in den Systematiken angepasst werden und z.B. sowas in die Zwischenablage kopieren (korrekt, @acka47?):

`Niederrheinische Herzogtümer$$0https://nwbib.de/spatial#N43`

**Comment by acka47** [comment]
> Entsprechend der neuen Speicherung der Unterfelder müssen auch die Copy-Knöpfe in den Systematiken angepasst werden und z.B. sowas in die Zwischenablage kopieren (korrekt, @acka47?):
> 
> `Niederrheinische Herzogtümer$$0https://nwbib.de/spatial#N43`

Ja, der Katalogisierungsumstieg erfolgt Ende November.

**Comment by fsteeg** [comment]
Copy-Knöpfe sind aktualisiert: https://nwbib.de/spatial

**Comment by acka47** [comment]
Die Katalogisierung ist seit Donnerstag, 5.12.2019 umgestellt. Nach ein paar Schwierigkeiten mit dem Kpier-Knopf für die Sachsystematik (der auch spatial-URIs lieferte) scheitn das Verfahren zu funktionieren. Closing.
