### ISSUE TITLE
Anpassung der nwbib.de App

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#474]
Depends on #468 bzw. sollte gemeinsam deployt werden. Mit der Anpassung der lobid-resources Datenstruktur für räumliche Inhaltserschließung (und der URIs für die Sachklassifikation) müssen auch die entsprechenden Funktionen in nwbib.de angepasst werden. Dies sind alle Funktionen, die bisher auf Daten mit `subject.source.id: "http://purl.org/lobid/nwbib-spatial"` oder `spatial` zugreifen:

- [x] ~Anzeige der hierarchischen Raumsystematik~
- [x] ~Suche über Karte auf der Startseite~
- [x] ~Interaktive Karte bei der Suchergebnisliste~
- [x] ~Regionen- und Sachgebiete-Facetten bei der Suchergebnisliste~
- [x] ~Anzeige der Raumverschlagwortung in Einzeltrefferanzeige (labels, breadcrumb)~ ~~(muss auch in lobid-resources angepasst werden)~~ gibts da gar nicht, s. z.B. http://lobid.org/resources/HT018612706 vs. http://nwbib.de/HT018612706
- [x] ~Suchfunktion (Lupe) bei "Raumsystematik" in Einzeltreffersicht~
- [x] ~Die Änderung der Sachsystematik-URIs könnte auch Anpassungen erfordern~

**Comment by acka47** [comment]
Hier sind die gemachten Anpassungen im Überblick:

I just reviewed it:

- `subject.id` für die Sachsystematikstellen ist jetzt `https://nwbib.de/subjects#N{notation}` anstatt `http://purl.org/lobid/nwbib#s{notation}`
- `subject.source.id` ist jetzt `https://nwbib.de/subjects` für die Sachsystematik anstatt `http://purl.org/lobid/nwbib`
- *All* spatial subjects are moved to `spatial` 
- `spatial.id` uses `https://nwbib.de/spatial#` as namespace instead of `http://purl.org/lobid/nwbib-spatial#`
-  The `spatial.source` is `https://nwbib.de/spatial` accordingly.

For reference, here an example from HT017150239:
```json
{
   "id":"http://lobid.org/resources/HT017150239#!",
   "subject":[
      {
         "type":[
            "ComplexSubject"
         ],
         "componentList":[
            {
               "id":"http://d-nb.info/gnd/7856688-5",
               "type":[
                  "CorporateBody"
               ],
               "gndIdentifier":"7856688-5",
               "source":{
                  "id":"http://d-nb.info/gnd/7749153-1",
                  "label":"Gemeinsame Normdatei (GND)"
               },
               "label":"Westfalen-Lippe. Amt für Denkmalpflege in Westfalen, Fachbereich Praktische Denkmalpflege und Baukultur"
            }
         ],
         "label":"Westfalen-Lippe, Amt für Denkmalpflege in Westfalen, Fachbereich Praktische Denkmalpflege und Baukultur"
      },
      {
         "id":"https://nwbib.de/subjects#N844200",
         "source":{
            "id":"https://nwbib.de/subjects",
            "label":"Sachsystematik der Nordrhein-Westfälischen Bibliographie"
         },
         "notation":"844200",
         "label":"Denkmalpflege. Denkmalschutz"
      }
   ],
   "spatial":[
      {
         "id":"https://nwbib.de/spatial#N05",
         "type":[
            "Concept"
         ],
         "source":{
            "id":"https://nwbib.de/spatial",
            "label":"Raumsystematik der Nordrhein-Westfälischen Bibliographie"
         },
         "notation":"05",
         "label":"Westfalen"
      },
      {
         "focus":{
            "id":"http://www.wikidata.org/entity/Q2742",
            "geo":{
               "lat":51.9625,
               "lon":7.6255555555556
            },
            "type":[
               "http://www.wikidata.org/entity/Q22865",
               "http://www.wikidata.org/entity/Q262166",
               "http://www.wikidata.org/entity/Q707813",
               "http://www.wikidata.org/entity/Q1549591",
               "http://www.wikidata.org/entity/Q42744322"
            ]
         },
         "id":"https://nwbib.de/spatial#Q2742",
         "type":[
            "Concept"
         ],
         "label":"Münster",
         "source":{
            "id":"https://nwbib.de/spatial",
            "label":"Raumsystematik der Nordrhein-Westfälischen Bibliographie"
         }
      }
   ]
}
```

**Comment by acka47** [comment]
Wie besprochen kann die Umsetzung nun mit dem small-testset-Index implementiert und getestet werden.

**Comment by fsteeg** [comment]
Deployed to test (with small test set): https://test.nwbib.de/

**Comment by acka47** [comment]
+1 für die kleine Testmenge. @dr0i, bitte für staging-Index umsetzen, für 2. Testphase.

**Comment by dr0i** [comment]
Indexed to resources-staging. Switched https://test.nwbib.de/ to use this new index. @acka47 die 2. Testphase kann beginnen.

**Comment by fsteeg** [comment]
Enabled filtering of zero hit entries in classifications, deployed https://github.com/hbz/lobid-resources/pull/996 to http://stage.lobid.org/resources, switched https://test.nwbib.de to use http://stage.lobid.org/resources

**Comment by acka47** [comment]
The "Regionen" filter does not work. Example:

1. Search for "kohle" you get 1779 hits and it says "237" hits for Ruhrgebiet in the "Regionen" filter
3. Clicking on it will change the header ("1770 Treffer in Regionen > 20 Ruhrgebiet") but the results are not filtered at all.

**Comment by fsteeg** [comment]
Redeployed, see https://test.nwbib.de/search?q=kohle

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
To be deployed on Monday (2019-06-03).
