### ISSUE TITLE
New SSL Certificates

### ISSUE THREAD

**Issue by dr0i** [hbz/nwbib#476]
As in hbz/lobid#383.

- [x] nwbib.de
- [x] www.nwbib.de
~- [ ] beta.nwbib.de~
- [x] test.nwbib.de

@fsteeg @acka47 do we really need certificates for test-servers?

**Comment by dr0i** [comment]
As discussed with @fsteeg we need not beta.nwbib.de but test.nwbib.de to be able for real tests like openrefine which may depend on ssl.

**Comment by dr0i** [comment]
Got a call from IT: it's possible to cover several domainnames using one certificate ("Subject Alternative Name (SAN)") if these remain on the same machine. How cool is this? So we **just need one certificate for all nwbib domains**.
(It also would be possible to cover other domains like lobid.org, but considering security it would be better to have more certificates, so we will restrict it to a hostname with it's subdomains.)

**Comment by dr0i** [comment]
Deployed, please review.

**Comment by acka47** [comment]
+1. Closing
