### ISSUE TITLE
UI der Ortsklassifikation aktualisieren

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#477]
Z.B. gibt es keine Treffer mehr für "Monschauer Heckenland", es wird aber immer noch angezeigt, siehe https://nwbib.de/spatial#Q993449

**Comment by fsteeg** [comment]
Fixed by restarting the app (fresh cache), see https://nwbib.de/spatial#Q993449

**Comment by acka47** [comment]
This removed the one with zero results but did not add new ones, eg. "Monschauer Land" ([Q63191391](http://lobid.org/resources/search?q=spatial.id%3A%22http%3A%2F%2Fwww.wikidata.org%2Fentity%2FQ63191391%22)).

**Comment by fsteeg** [comment]
Deployed to test: https://test.nwbib.de/spatial#Q63191391

**Comment by acka47** [comment]
+1
