### ISSUE TITLE
Adjust detail view to added notations

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#480]
Depends on https://github.com/hbz/lobid-vocabs/issues/89, depends on https://github.com/hbz/lobid-resources/issues/1017.

 Quote from email by H.F. posted to list 2019-05-01:

> Die Übernahme der Raumsystematik-Einträge in die Titelaufnahmen (TA) der NWBib wird sich mit der Verschiebung der Verwaltungsgliederung von "9" nach "0" auch ändern. Unserer Grundidee folgend würden unnotierte Stellen (Stadtbezirke, Stadt- und Ortsteile in der Ortssystematik) in der TA in einem Hierarchiestrang bis zur ersten notierten Stelle dargestellt werden. Von hier aus gelangten die Nutzenden per Link zur Raumklasse im Kontext der Raumsystematik.

Maybe, we won't have to adjust anything if the code already shows the path until the next notated concept.

**Comment by acka47** [comment]
Wir müssen das noch anpassen. Derzeit wird bei den Systematikeinträgen, die neuerdings eine Notation haben, keine Notation angezeigt und stattdessen wie bisher der ganze Hierarchiestrang. Siehe z.B. https://nwbib.de/HT020034847, wo es einfach heißen sollte " 05754 Kreis Gütersloh".

Gleiches gilt für die Anzeige über der Trefferliste (hier: https://nwbib.de/search?nwbibspatial=https%3A%2F%2Fnwbib.de%2Fspatial%23Q6218).

**Comment by fsteeg** [comment]
Deployed to test:

https://test.nwbib.de/HT020034847
https://test.nwbib.de/search?nwbibspatial=https://nwbib.de/spatial%23Q6218

We still have breadcrumbs for entries without notations:

https://test.nwbib.de/BT000160271
https://test.nwbib.de/search?nwbibspatial=https://nwbib.de/spatial%23Q683292

**Comment by acka47** [comment]
Looks good. +1
