### ISSUE TITLE
Provide RDF download link for classifications

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#484]
Both for https://nwbib.de/spatial and https://nwbib.de/subjects. We should at least provide a link to the turtle file as it is on GitHub. Even better would be additional content negotiation for Accept header "text/turtle" and – ideally – for other RDF serializations.

**Comment by fsteeg** [comment]
Deployed to test:

https://test.nwbib.de/spatial
https://test.nwbib.de/subjects

**Comment by acka47** [comment]
+1
