### ISSUE TITLE
Add P4900 qualifier to NWBib ID

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#487]
https://www.wikidata.org/wiki/Property:P4900

**Comment by acka47** [comment]
We will do this. This will make it easier to generate the SKOS file as we will have only one `broader` statement to add (for those that have different P131 statements). Also, we will be able to move a lot of the config file https://github.com/hbz/nwbib/blob/master/conf/non-90s-qids.json to wikidata.

**Comment by acka47** [comment]
Adding a statement with qualifiers via Quickstatements is easy, see https://www.wikidata.org/wiki/Help:QuickStatements#CSV_file_syntax:

> A lowercase "qal" followed by a property number (without "P") adds a qualifier to the current statement. The column value specifies the value of the qualifier, in QuickStatements version 1 syntax. There must be some "P" column before a "qal" column to specify which statement the qualifier is added to.

For our case, this would look like this:

```
qid,P6814,qal4900
Q151243,""""Q151243",Q3898
Q181825,""""Q181825",Q54803599
Q249710,""""Q249710",Q54803600
```
Note that no quotes around the QIDs are needed as they are not strings in this case (unlike in the case of P6814).

I ran a test batch and it worked, see https://tools.wmflabs.org/quickstatements/#/batch/17983.

**Comment by acka47** [comment]
I think this should be the right SPARQL query to also get the broader QID:
 
```sparql
SELECT DISTINCT
?item
?itemLabel
?broader
?dissolutionDate
?ags
?ks
# (group_concat(distinct ?partOf; separator = ", ") as ?partOf)
# (group_concat(distinct ?hasPart; separator = ", ") as ?parts)
WHERE {
  ?item p:P6814 [ pq:4900 ?broader ] .
  SERVICE wikibase:label {  bd:serviceParam wikibase:language "de" }
  OPTIONAL { ?item wdt:P576 ?dissolutionDate }
#  OPTIONAL { ?item wdt:P150 ?hasPart . }
#  OPTIONAL { ?item wdt:P131 ?partOf }
  OPTIONAL { ?item wdt:P439 ?ags }
  OPTIONAL { ?item wdt:P440 ?ks }
}

# GROUP BY ?item ?itemLabel ?dissolutionDate ?ags ?ks ?broader
```
[Try it!](https://w.wiki/7sX)
Currently, there are no results, although the three entries with the qualifier should come back. Maybe it is a problem with the SPARQL index not being updated yet. Will try again later.

**Comment by acka47** [comment]
Re. replacing https://github.com/hbz/nwbib/blob/master/conf/non-90s-qids.json, here is a first overview.

These broader relations are handled in the file:

```
$ curl https://raw.githubusercontent.com/hbz/nwbib/master/conf/non-90s-qids.json | jq .[].notation | sort | uniq -c | sort -nr
     31 "74"
     27 "33"
     12 "Q253765"
     11 "Q769380"
     11 "32"
     11 "24"
     10 "12"
      8 "14"
      7 "36"
      6 "54"
      6 "28"
      6 "10"
      4 "Q1700"
      4 "52"
      2 "72"
      1 "Q702291"
      1 "Q109773"
```

The ones with a qid can easily be handled via P4900. The question is how many of the others have a `foaf:focus` statement linking them to a Wikidata entry. These are:

- N10 ("Westfälische Bucht") -> Q462011
- N12 ("Weserbergland") -> Q72931
- N14 ("Sauerland") -> Q4194
- N24 ("Niederrhein-Gebiet") -> Q445609
- N28 ("Eifel") -> Q152356
- N32 ("Evangelische Kirche im Rheinland") -> Q1380992
- N33 ("Evangelische Kirche von Westfalen") -> Q1381014

A focus statement is missing for:

- N52 ("Kleinere geistliche Territorien im Rheinland")
- N54 ("Kleinere weltliche Territorien im Rheinland")
- N72 ("Kleinere geistliche Territorien in Westfalen")
- N74 ("Kleinere weltliche Territorien in Westfalen")

There are 43 classification entries with `broader` statements to those four.

**Comment by acka47** [comment]
For adding data to the third column (`qal4900`) as written in https://github.com/hbz/nwbib/issues/487#issuecomment-527794281, we have to retrieve the QID as follows:

1. Get the `broader` URI, e.g. `nwbib-spatial:N14` for the following example:
```
nwbib-spatial:Q56042007
        a               skos:Concept ;
        skos:broader    nwbib-spatial:N14 ;
        skos:inScheme   <https://nwbib.de/spatial> ;
        skos:prefLabel  "Westsauerland"@de ;
        foaf:focus      wd:Q56042007 .
```
2. Lookup the `foaf:focus` of broader entity. For (`nwbib-spatial:N14`) in our example, this is `wd:Q4194`.
```
nwbib-spatial:N14  a    skos:Concept ;
        skos:broader    nwbib-spatial:N1-2 ;
        skos:inScheme   <https://nwbib.de/spatial> ;
        skos:notation   "14" ;
        skos:prefLabel  "Sauerland"@de ;
        foaf:focus      wd:Q4194 .
```

3. Add the QID to the respetive line: 
```
qid,P6814,qal4900
Q56042007,""""Q56042007",Q4194
```

**Comment by fsteeg** [comment]
Single `broader`: 
[qid-p6814-qal4900-single.csv.txt](https://github.com/hbz/nwbib/files/3590507/qid-p6814-qal4900-single.csv.txt)

Multiple `broader` (but some with only 1 `focus`?):
[qid-p6814-qal4900-multi.csv.txt](https://github.com/hbz/nwbib/files/3590486/qid-p6814-qal4900-multi.csv.txt)

**Comment by fsteeg** [comment]
Batch process started by @acka47 at https://tools.wmflabs.org/quickstatements/#/batch/18263

Assigning myself to start work on using the P4900 information to build the hierarchy.

**Comment by fsteeg** [comment]
@acka47 Not sure what is happening with the batch job, but it seems stuck or something? There are 1686 items with status `INIT`, but the job is `DONE`? https://tools.wmflabs.org/quickstatements/#/batch/18263

**Comment by acka47** [comment]
We might have to run another batch with the remaining entries. However, I just added two entries to Wikidata (https://www.wikidata.org/wiki/Q67206648 & https://www.wikidata.org/wiki/Q67206680) and will add `focus` statements to nwbib-spatial for them. Then we will have around 40 additional `broader` statements to load. (Which will finally fix https://www.wikidata.org/wiki/Q457468)

**Comment by fsteeg** [comment]
> Then we will have around 40 additional broader statements to load.

[qid-p6814-qal4900-new.csv.txt](https://github.com/hbz/nwbib/files/3595514/qid-p6814-qal4900-new.csv.txt)

**Comment by acka47** [comment]
The additional 39 statements have also been added, see https://tools.wmflabs.org/quickstatements/#/batch/18264. In #489 I checked whether any Wikidata entry with NWBi ID is missing the qualifier although it should have one. Everything is fine for now. Closing.
