### ISSUE TITLE
Improve accessibility

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#488]
This testing tool might be good to work with as we can run it locally: https://github.com/paypal/AATT

**Comment by acka47** [comment]
Here is one result of running an accessibility checker  (powermapper) on nwbib.de: https://try.powermapper.com/demo/Report/85c0b47b-bef3-4fe7-98c4-cbbd4eb08339

**Comment by acka47** [comment]
Hintergrund ist u.a. die  [Richtlinie (EU) 2016/2012](https://eur-lex.europa.eu/legal-content/DE/TXT/?uri=CELEX%3A32016L2102) und deren Umsetzung in nationales Recht. Die gesetzlichen Umsetzungfristen:

- ab 23.09.2019 – alle neuen digitalen Anwendungen
- ab 23.09.2020 – alle vor dem 23.09.2019 bereits
bestehenden Anwendungen
- ab 23.06.2021 – alle mobilen Anwendungen

Für die Überwachung ist das [https://www.mags.nrw/ueberwachungsstelle-barrierefreie-informationstechnik](https://www.mags.nrw/ueberwachungsstelle-barrierefreie-informationstechnik) zuständig. Die erste Überwchungsperiode beginnt laut deren Angaben am 2021-01-01.

**Comment by fsteeg** [comment]
Habe ein nützliches Tool gefunden um eine paar grundlegende Sachen zu fixen, vgl. `https://nwbib.de/` und `https://test.nwbib.de/` in https://www.experte.de/barrierefreiheit

**Comment by acka47** [comment]
Sieht gut aus. +1 Kann gerne deployt werden.

**Comment by dr0i** [comment]
Deployed, closing.

**Comment by fsteeg** [comment]
Reopening: https://nwbib.de/search needs some work. Tool above is based on Lighthouse, which is available in Chromium: go to https://nwbib.de/search, open Developer Tools (CTRL+SHIFT+I), select 'Lighthouse' tab, select only 'Accessibility' check box under 'Categories', then click 'Generate report'.

**Comment by fsteeg** [comment]
Deployed to test, see https://test.nwbib.de/search and its Lighthouse report (as described above).

**Comment by acka47** [comment]
+1
