### ISSUE TITLE
Fragen an die NWBib-Redaktion

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#491]
Dies ist ein Sammelticket für offene Fragen, die in Abstimmung mit der NWBib-Redaktion geklärt werden müssen.

- [x] ~Drei~ Zwei Einträge haben denselben KS ("05334"), d.h. dieselbe Notation:  Städteregion Aachen ([Q6272](https://www.wikidata.org/wiki/Q6272))~, ehemaliger Kreis Aachen ([Q7379734](https://www.wikidata.org/wiki/Q7379734))~ und ehemaliger Landkreis Köln ([Q1803277](https://www.wikidata.org/wiki/Q1803277)) (siehe #490 )
- [x] Auf welchen Wikidata-Eintrag soll "Euregio" (derzeit 91) gematcht werden: [Q153026, "Europaregion"](https://www.wikidata.org/wiki/Q153026) oder [Q1374337, "Euregio"](https://www.wikidata.org/wiki/Q1374337)?
- Sind folgende von @acka47 vorgenommenen Einordnungen in Ordnung?
  - [x] Rureifel (Q1406857) -> Eifel (Q152356) (oder doch besser: Nordeifel oder Westeifel?)
  - [x] Homert (Q1487002) -> Südsauerland (Q56042224)
  - [x] Arnsberger Wald (Q31553414) -> Nordsauerland (Q31553414)
  - [x] Monschauer Land (Q63191391) -> Eifel (Q152356)
  - [x] Senne (Q767106) -> Ostwestfalen (Q2036208)
  - [x] Selfkant (Q981347) -> Niederrheinisches Tiefland (Q212520)
- [x] Bei den unterrgeordneten Einträgen von Kleineren geistlichen Territorien im Rheinland/in Westfalen (52 & 72) handelt es sich ausschließlich um Kloster. Sollten die Systemstellen 52 & 72 nicht umbenannt oder sogar zusammengelegt werden?
- [x] ["Kloster Werden"](https://nwbib.de/spatial#Q688373) ist gerade unter  "Essen" einsortiert, was nicht wünschenswert ist. Wo soll es stattdessen hin?
- [x] Es gibt zwei Tüschenbroichs: [Q1283532](https://www.wikidata.org/wiki/Q1283532) & [Q2465162](https://www.wikidata.org/wiki/Q2465162). Auf welches solle der Eintrag [99 Tüschenbroich](https://lobid.org/resources/search?q=coverage%3At%C3%BCschenbroich) gematcht werden (bisher Q1283532)?
- [x] Kann die Systematikstelle "4-7 Historische Territorien und Gebiete" sinnvollerweise auf [Q26830017](https://www.wikidata.org/wiki/Q26830017) gematcht werden?

**Comment by acka47** [comment]
Bezüglich "Kloster Werden": Es soll eigentlich allein unter https://nwbib.de/spatial#N52 einsortiert werden, in Wikidata wurde aber als Überordnung "Essen" angelegt, was ich gerade entfernt habe, siehe https://www.wikidata.org/w/index.php?title=Q688373&type=revision&diff=1029121004&oldid=1010965646. 

Das Problem mit zwei `broader`-Einträgen gibt es auch bei anderen Einträgen unter `52`. Ich habe bei allen Wikidata-Einträgen die fehlerhafte Überordnung entfernt und die Einträge in der nwbib-spatial-conf.ttl ergänzt, siehe https://github.com/hbz/nwbib/pull/493/commits/cf14f70615099591e6878fa211f478549077b07d.

**Comment by acka47** [comment]
> Das Problem mit zwei `broader`-Einträgen gibt es auch bei anderen Einträgen unter `52`. Ich habe bei allen Wikidata-Einträgen die fehlerhafte Überordnung entfernt und die Einträge in der nwbib-spatial-conf.ttl ergänzt,

Das gleiche gilt für die Einträge mit `broader`  N72. Habe das auch in Wikidata und der conf-Datei angepasst.

**Comment by fsteeg** [comment]
Aktueller Stand auf Test: https://test.nwbib.de/spatial (z.B. https://test.nwbib.de/spatial#Q688373)

**Comment by acka47** [comment]
Die Fragen sind alle geklärt, wenn auch nicht unbeding tumgesetzt. Für die Umsetzung gibt es aber separate Ticket. Ich schließe daher das Ticket.
