### ISSUE TITLE
No hit when using two (or more) spaces consecutively in a query

### ISSUE THREAD

**Issue by dr0i** [hbz/nwbib#495]
This is not working:
https://nwbib.de/search?location=&q=hiddenhausen++schule
while this is:
https://nwbib.de/search?location=&q=hiddenhausen+schule
and this also works:
http://www.lobid.org/resources/search?q=hiddenhausen++schule

**Comment by TobiasNx** [comment]
@dr0i this seems to be not true anymore, can you test and close?

**Comment by dr0i** [comment]
Yep - right, it works now.
Closing.
