### ISSUE TITLE
Suchen mit "an", "in" und Sonderzeichen funktionieren nicht

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#506]
On 14.11.19 15:29, I.N. wrote:
> Uns ist aufgefallen, dass es einen Unterschied zwischen der Recherche im 
> Suchschlitz auf der Startseite und der „Erweiterten Suche“ gibt .
> 
> Gibt man Titel, die die Präpositionen  „an“ und „in“ oder Sonderzeichen 
> „+“ „-„  „:“  „&“ enthalten *vollständig *ein, bekommt man bei der 
> Recherche im Suchschlitz keine Treffer.
> 
> Andere kleine Wörter im Titel wie z.B. aus, im, um, über, für, und, zur, 
> der, den, des, die und der Bindestrich ergeben keinen Unterschied.
> 
> Hier einige Beispiel-Titel:
> 
> 1)*An* Möhne, Röhr und Ruhr
> 
> 2)*An* Bigge, Lenne und  Fretter
> 
> 3)Archivpflege i*n* Westfalen-Lippe
> 
> 4)Natur und Umwelt *in* Siegen-Wittgenstein
> 
> Bei den Sonderzeichen würden die Nutzer vermutlich auf die Idee kommen, 
> das Zeichen bei der Recherche herauszunehmen oder den Titel in 
> Anführungszeichen zu setzen.
> 
> Aber bei einem negativen Ergebnis aufgrund der Präpositionen „an“ und 
> „in“ würde vielleicht nicht jeder Nutzer auf den Gedanken kommen nochmal 
> anders zu recherchieren.
> 
> Könnte man in diesen beiden Fällen (an, in) noch etwas nachbessern?
>

**Comment by fsteeg** [comment]
Deployed to production, see:

https://nwbib.de/search?q=Natur+und+Umwelt+in+Siegen-Wittgenstein
https://nwbib.de/search?q=An+Bigge%2C+Lenne+und+Fretter
https://nwbib.de/search?q=Archivpflege+in+Westfalen-Lippe
https://nwbib.de/search?q=An+M%C3%B6hne%2C+R%C3%B6hr+und+Ruhr

**Comment by acka47** [comment]
+1 Closing. Ich werde eine kurze Nachricht an die Mailingliste schreiben.

**Comment by acka47** [comment]
Ich sehe gerade, dass nur die Stoppwort-Problematik gelöst ist. Sonderzeichen gehen nach wie vor nicht, siehe z.B. https://nwbib.de/search?location=&q=jacke+%2B+hose (vs https://nwbib.de/search?sort=newest&name=jacke+%2B+hose in der erweiterten Suche) oder https://nwbib.de/search?q=Facts+%26+figures vs. https://nwbib.de/search?name=Facts+%26+figures. Reopening.

**Comment by fsteeg** [comment]
Ich habe es so verstanden, dass es bei Sonderzeichen ok ist:

> Bei den Sonderzeichen würden die Nutzer vermutlich auf die Idee kommen,
das Zeichen bei der Recherche herauszunehmen oder den Titel in
Anführungszeichen zu setzen.
> 
> Aber bei einem negativen Ergebnis aufgrund der Präpositionen „an“ und
„in“ würde vielleicht nicht jeder Nutzer auf den Gedanken kommen nochmal
anders zu recherchieren.
> 
> Könnte man in diesen beiden Fällen (an, in) noch etwas nachbessern?

**Comment by acka47** [comment]
Ah, ok. Hätte ich doch noch mal besser die gesamt eE-Mail gelesen. Sorry. Closing.
