### ISSUE TITLE
Siebengebirge fehlt

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#507]
On 05.12.19 10:02, U.P. wrote:

> in der neuen Systematik fehlt das Siebengebirge. Es ist in der alten 
> Systematik ein GSW zu Rheinland = N03. Deshalb macht es wohl auch keinen 
> Sinn, wenn ich im WD-Eintrag zum Siebengebirge die NWBib-ID eintrage, da 
> ja nicht mit der QID von „Rheinland“ verknüpft wird, nicht wahr? Müssten 
> Sie da händisch die Unterordnung in der Raumsystematik einrichten? 

### Beispiel [HT020015895](http://lobid.org/resources/HT020015895)

[Source](http://lobid.org/hbz01/HT020015895): 

```xml
<datafield tag="700" ind1="n" ind2="1">
  <subfield code="a">03</subfield>
  <subfield code="b">Siebengebirge</subfield>
</datafield>
<datafield tag="700" ind1="n" ind2="1">
  <subfield code="a">102070</subfield>
</datafield>
```

In the JSON, there is no mention of `03` or `Siebengebirge`, neither in `coverage` nor in `spatial`. Why?

**Comment by acka47** [comment]
Eigentlich müsste das doch abgedeckt sein, wenn ich mir diese RegEx anschaue:


Anstatt

**Comment by dr0i** [comment]
Die wichtige Zeile it 7273, da wo `coverage` definiert ist. Und das verweist auf https://github.com/hbz/lobid-resources/blob/5cc1c15d9ffd9cb5bc6db5ed38450f2f6ac8cca6/src/main/resources/morph-hbz01-to-lobid.xml#L7262 , und da fehlt die `03`.

**Comment by dr0i** [comment]
@acka47 muss die Schildkröte noch fertig machen!

**Comment by fsteeg** [comment]
Deployed to test:

https://test.nwbib.de/spatial
https://github.com/hbz/lobid-vocabs/pull/105

**Comment by acka47** [comment]
When viewing the [result list](https://test.nwbib.de/search?nwbibspatial=https%3A%2F%2Fnwbib.de%2Fspatial%23Q4236) for "Siebengebirge", the URI is shown instead of the label in the breadcrumb path: "322 Treffer in Regionen > 1-2 Landschaften in Nordrhein-Westfalen > https://nwbib.de/spatial#Q4236"

**Comment by fsteeg** [comment]
Deployed to test:

https://test.nwbib.de/spatial
https://github.com/hbz/lobid-vocabs/pull/105/files

**Comment by acka47** [comment]
+1
