### ISSUE TITLE
Copy-und-Paste-Knopf der Sachsystematik liefert falsche URIs

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#508]
Bitte möglichst schnell korrigieren.

Am 06.12.19 um 09:24 schrieb I.N.:
> beim Ausprobieren des Copy- und Paste-Verfahrens ist uns aufgefallen, 
> dass bei den NWBib-Sachnotationen der Link, der in die Zwischenablage 
> kopiert wird immer mit https://nwbib.de/spatial#N...... beginnt und 
> nicht mit „https://nwbib.de/subjects#N......“?
> 
> Dementsprechend werden die Sachnotationen in der Titelanzeige auch bei 
> den Raumnotationen angezeigt und der Link führt natürlich zur 
> Raumsystematik und nicht zur Sachsystematik.
> 
> Hier ein Beispiel:
> 
> Können Sie die im Klemmbrett hinterlegten Links z.B. 
> „Bibliographien$$0https://nwbib.de/spatial#N101000“ austauschen?
> 
> Sollen wir in der Zwischenzeit die Links für die Sachnotationen manuell 
> eintragen (https://nwbib.de/subjects#N......), damit wir im Januar nicht 
> so viele Titelaufnahmen korrigieren müssen?
>

**Comment by fsteeg** [comment]
Deployed to test:

http://test.nwbib.de/subjects
http://test.nwbib.de/spatial

**Comment by acka47** [comment]
+1
