### ISSUE TITLE
Zeige Notationen aus `notation`-Feld an

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#511]
Bisher werden die in https://nwbib.de/spatial angezeigten Notationen wohl aus der URI generiert. Mit #501 können wir auch alle anderen Notationen anzeigen, die im Feld `notation` sind. Beispiel:

```
nwbib-spatial:Q365  a   skos:Concept ;
        skos:broader    nwbib-spatial:Q7927 ;
        skos:inScheme   <https://nwbib.de/spatial> ;
        skos:notation   "05315000" ;
        skos:prefLabel  "Köln"@de ;
        foaf:focus      wd:Q365 .
```

**Comment by fsteeg** [comment]
Deployed to test: e.g. https://test.nwbib.de/spatial#Q6275

**Comment by fsteeg** [comment]
Redeployed as discussed offline: https://test.nwbib.de/spatial#N05

**Comment by fsteeg** [comment]
And redeployed once more to test, preferring `ks` over `ags` for uniform notation length under the Regierungsbezirk level: https://test.nwbib.de/spatial#Q7927

**Comment by acka47** [comment]
+1. Looks great. Please deploy together with #107.
