### ISSUE TITLE
Falsche Verknüpfung für Kreis Mettmann

### ISSUE THREAD

**Issue by fsteeg** [hbz/nwbib#514]
Basiert auf Fehlerbericht von U.P. am 20.12.19, 13:55.

Offenbar wurden Einträge mit `coverage`:`Mettmann <Kreis> | 97` fälschlicherweise mit dem alten Kreis Düsseldorf-Mettmann verknüpft, s. https://nwbib.de/search?nwbibspatial=https%3A%2F%2Fnwbib.de%2Fspatial%23Q1787267 z.B. http://lobid.org/resources/HT020141133.json

**Comment by acka47** [comment]
Es handelt sich um 339 Titel, die Kreis und Mettmann enthalten, siehe das gist unter , das ich mit dem unter #467 entstandenen Dienst wie folgt erstellt habe: `$ curl "http://nwbibsnapshot.lobid.org/resources/search?q=%22Mettmann+%3CKreis%3E%22&size=400" | jq -r .member[].hbzId` (und dann Ergänzung von `- [ ] `am Zeilenanfang um eine abhakbare Liste zu haben).

**Comment by acka47** [comment]
Wir werden eine hbz01-Update-Datei an die Verbundgruppe geben, um dieses Ticket und #516 zu erledigen.

Hier ist die korrekte Query, umm alle betroffenen Titel zu bekommen:


Für die 339 Titel müssen wir dann die csv-Datei (im gleichen Format wie in #464) auf Basis der hbz-IDs (siehe [gist](https://gist.github.com/acka47/7a7fd80195e1e2a8b6f82c709fdb396c)) und des jetzigen lobid-resources-Standes erstellen und dann folgende regex durchführen:

 `s/foo/bar/g`

**Comment by fsteeg** [comment]
Import file for review: [700n-import-20200115-1400.txt](https://github.com/hbz/nwbib/files/4064966/700n-import-20200115-1400.txt)

**Comment by acka47** [comment]
+1

**Comment by acka47** [comment]
Erledigt. Closing.
