### ISSUE TITLE
Fehlende Titel bei Bistum Münster

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#516]
On 07.01.20 17:20, I.N. wrote:
> bei der Raumnotation Bistum Münster (36  | Diözese Münster (Westf)) 
> fehlen die verknüpften NWBib-Titel.

Siehe https://nwbib.de/spatial#Q769380 & https://lobid.org/resources/search?q=spatial.id%3A%22https%3A%2F%2Fnwbib.de%2Fspatial%23Q769380%22

Wir werden das beheben, sobald #467 umgesetzt ist.

**Comment by acka47** [comment]
Es handelt sich um 660 Titel, siehe http://nwbibsnapshot.lobid.org/resources/search?q=di%C3%B6zese+AND+m%C3%BCnster. Mir ist schleicherhaft, warum das Matching nicht funktioniert hat, da die Strings in der string2wikidata.tsv alle auftauchen, siehe https://github.com/hbz/lobid-resources/blob/master/src/main/resources/string2wikidata.tsv#L134-L136 (Zeilen 134 bis 136):

```tsv
Münster <Westfalen, Diözese> | 36	Q769380
Diözese Münster (Westf) | 36	Q769380
Münster (Diözese) | 36	Q769380
```

**Comment by acka47** [comment]
Wir werden eine hbz01-Update-Datei an die Verbundgruppe geben, um dieses Ticket und #514 zu erledigen.

Für die 660 Titel müssen wir dann die csv-Datei (im gleichen Format wie in #464) auf Basis der hbz-IDs (siehe [gist](https://gist.github.com/acka47/e8b2a55354faa5266a86101b23a886ae)) und des jetzigen Standes erstellen und in jeder Zeile in Spalte 2 folgendes voranstellen: `"Bistum Münster$$0https://nwbib.de/spatial#Q769380", `. (Dann sollten wir noch schauen, ob irgendeine Zeile mit `, ` endet, falls dies das einzige Schlagwort sein soltle.

**Comment by fsteeg** [comment]
Import file for review: [700n-import-20200115-1415.txt](https://github.com/hbz/nwbib/files/4065044/700n-import-20200115-1415.txt)

**Comment by acka47** [comment]
> Import file for review: [700n-import-20200115-1415.txt](https://github.com/hbz/nwbib/files/4065044/700n-import-20200115-1415.txt)

+1

**Comment by acka47** [comment]
Die Titel sind aktualisiert, siehe https://lobid.org/resources/search?q=spatial.id%3A%22https%3A%2F%2Fnwbib.de%2Fspatial%23Q769380%22. Unter https://nwbib.de/spatial#Q769380 wird die Anzahl aber noch nicht angezeigt. Kommt dann mit der nächsten Aktualisierung der Web-Raumsystematik. Closing.
