### ISSUE TITLE
Ergänze Enddatum bei Alt-Regierungsbezirken

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#518]
Von der NBWib-Mailingliste:

On 09.01.20 15:25, I.N. wrote:
> hier noch ein kleiner Änderungswunsch: Könnten Sie bei den beiden 
> Alt-Regierungsbezirken noch das Enddatum des Bestehens ergänzen (analog 
> zu den Alt-Kreisen).
> 
> Regierungsbezirk Aachen (bis 1972]
> 
> Regierungsbezirk Minden (bis 1947)

**Comment by fsteeg** [comment]
Note to self: https://github.com/hbz/nwbib/blob/7d2060e4ef1b550b503a8ecea1d16e2ea5a3ed0c/app/controllers/nwbib/Classification.java#L339

**Comment by fsteeg** [comment]
Deployed to test:

https://test.nwbib.de/spatial#N05
https://github.com/hbz/lobid-vocabs/pull/108/files

**Comment by acka47** [comment]
+1 Wir sollten auch die ganze Systematik auf Basis der Wikidata-Daten aktualisieren, damit der Kreis Bielefeld auch – wie von Frau N. gewünscht – im Regierungsbezirk Detmold angesiedelt ist. Aus ihrer E-Mail: 

> Anmerkung: Der Kreis Bielefeld gehörte ab 1947 zum Regierungsbezirk 
> Detmold, daher habe ich den Wikidata-Eintrag „broader concept“ auf den 
> Regierungsbezirk Detmold verändert.
> 
> Nach der Aktualisierung der Raumsystematik gäbe es somit keinen 
> logischen Widerspruch. Die verbleibenden Alt-Kreise unter dem 
> Regierungsbezirk Minden Bünde und Rahden existieren nur bis 1831 bzw. 1832.

**Comment by fsteeg** [comment]
Redeployed to test:

https://test.nwbib.de/spatial#N05
https://github.com/hbz/lobid-vocabs/pull/108/files

**Comment by acka47** [comment]
+1 Wie besprochen, deployen wir das jetzt so auf Production.
