### ISSUE TITLE
Orte mit null Treffern in Systematik anzeigen

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#520]
Wie gerade offline besprochen sollten wir alle Orte mit einer NWbib-ID in Wikidata in die nwbib-spatial.ttl übernehmen und unter https://nwbib.de/spatial anzeigen.

Begründung:

- Ursprünglich wurden die ohne Treffer unterdrückt, weil ansonsten tausende Orte ohne Treffer angezeigt worden wären.
- Wenn Katalogisierer\*innen einen neuen Ort in Wikidata mit der NWBib-ID versehen, kann gar nicht das MARC-Snippet für die Erfassung kopiert werden, wenn noch kein Titel mit dem Ort erfasst ist und der Ort deshalb nicht in der Systematik angezeigt wird.

**Comment by acka47** [comment]
Momentan bauen sich die Katalogisierer\*innen bei neuen Orten die URIs wohl selbst zusammen, weil sie den Copy/Paste-Button ja nicht benutzen können. Siehe z.B. die vier Einträge mit "Eckum" (https://nwbib.de/spatial#Q1281908), das momentan noch gar nicht Teil der Systematik ist.

**Comment by fsteeg** [comment]
Deployed to test:

https://test.nwbib.de/spatial#Q3708105
https://github.com/hbz/lobid-vocabs/pull/109/files

**Comment by acka47** [comment]
+1
