### ISSUE TITLE
Liste aller nicht-nummerischen Snapshot-Einträge in 700n1a

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#521]
Aus https://github.com/hbz/nwbib/issues/467#issuecomment-571547415:

> Ein weiterer Use Case aus eine E-Mail von U.P.  vom 2019-12-05:

>> wir sind jetzt über das Register der Notationen in hbz01 auf einige 
>> Fehler aus der Vergangenheit gestoßen, als z.B. der Ort in 700n ohne das 
>> einleitende $a 99 oder ein GSW ohne die einleitende Notation eingegeben 
>> wurde, z.B.
>> 
>> HT019001149
>> 
>> HT004542399

Ein gutes Beispiel ist das erste. Dort findet sich in 700n1a anstatt einer Notation ein Textstring, siehe http://nwbibsnapshot.lobid.org/resources/HT019001149?format=json:

```json
{
    "spatial":[
        {
            "700n1a":[
                "572060",
                "617030",
                "Düsseldorf-Derendorf"
            ]
        }
    ]
}
```

Um eine Liste alle solcher Fehleintragungen zu bekommen, müssten wir mittels einer Regular Expression abfragen nach allen Werten in 700n1a, die keine Reihung von digits sind. Für Regexp queries siehe https://www.elastic.co/guide/en/elasticsearch/reference/5.6/query-dsl-regexp-query.html. Meine Frage ist, wie ich die Query abschicken muss.

**Comment by fsteeg** [comment]
Regular expressions [gehen auch in queryString queries](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/query-dsl-query-string-query.html#_regular_expressions):

http://nwbibsnapshot.lobid.org/resources/search?q=spatial.700n1a%3A%2F%5B%5E0-9%5D%2B%2F

**Comment by acka47** [comment]
Danke, ich habe die Liste per Mailingliste an die NWBib-Redaktion weitergeleitet. Closing.
