### ISSUE TITLE
Ehemalige Notation 52 wird noch genutzt

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#522]
On 15.01.20 13:51, U.P. wrote:
> Durch einen Hinweis von 
> Frau Niemann bin ich dazu gekommen, mir die Einverleibung der Notation 
> 52 „Kleinere geistliche Territorien im Rheinland“ in die Notation 54 
> anzusehen. Dabei ist mir aufgefallen, dass bei den geistlichen 
> Territorien sowohl im NWBib-Portal wie auch in hbz01 noch die alte 
> Notation 52 mit „Kleinere geistliche Territorien im Rheinland 
> https://nwbib.de/spatial#N52“ ( z.B. BT000097744   / 
> https://nwbib.de/BT000097744 <https://nwbib.de/BT000097744>  ) mit 
> angezeigt wird.

Ich habe geantwortet, dass wir die Titel zusammen mit #514 und #516 korrigieren werden.

**Comment by acka47** [comment]
To Do: Für die Titel der Abfrage http://lobid.org/resources/search?q=spatial.id%3A%22https%3A%2F%2Fnwbib.de%2Fspatial%23N52%22 müssen wir eine csv-Datei (im gleichen Format wie in #464)  auf Basis des jetzigen Datenstandes erstellen und `https://nwbib.de/spatial#N52` mit `https://nwbib.de/spatial#N52` ersetzen.

**Comment by fsteeg** [comment]
Import file for review: [700n-import-20200115-1430.txt](https://github.com/hbz/nwbib/files/4065104/700n-import-20200115-1430.txt)

(When concatting the files from #514, #516, and here we should consider the order to avoid overwriting)

**Comment by acka47** [comment]
> Import file for review: [700n-import-20200115-1430.txt](https://github.com/hbz/nwbib/files/4065104/700n-import-20200115-1430.txt)

+1
> (When concatting the files from #514, #516, and here we should consider the order to avoid overwriting)

+1

**Comment by acka47** [comment]
Hier die komplette Import-Datei, mit der in folgender Reihenfolge abgearbeitet wird:

1. #522 (Notation 52)
2.  #516 (Bistum Münster)
3. #514 (Kreis Mettmann)

[20200116-import.txt](https://github.com/hbz/nwbib/files/4071337/20200116-import.txt)

**Comment by acka47** [comment]
Erledigt, die Raumsystematik muss aber neu gebaut werden, damit diew Zahlen korrekt sind. Closing.
