### ISSUE TITLE
Veraltete Notationen 96 & 97 sind noch in hbz01

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#523]
ca. 17.000 Titel sind betroffen, siehe http://lobid.org/resources/search?q=spatial.id%3A%22https%3A%2F%2Fnwbib.de%2Fspatial%23N96%22+OR+spatial.id%3A%22https%3A%2F%2Fnwbib.de%2Fspatial%23N97%22. Die sollten wir glaube ich auch noch aktualisieren...

**Comment by acka47** [comment]
Im Zuge dieser Aktualisierung sollen auch die fehlenden Einträge zum  Stadtbezirk Hamm-Bockum-Hövel ergänzt werden: http://nwbibsnapshot.lobid.org/resources/search?q=Bockum+AND+H%C3%B6vel&size=100

**Comment by acka47** [comment]
> Im Zuge dieser Aktualisierung sollen auch die fehlenden Einträge zum Stadtbezirk Hamm-Bockum-Hövel ergänzt werden: http://nwbibsnapshot.lobid.org/resources/search?q=Bockum+AND+H%C3%B6vel&size=100

Eine Liste der hbzIds lässt sich so abfragen: `$ curl "http://nwbibsnapshot.lobid.org/resources/search?q=Bockum+AND+H%C3%B6vel&size=100" | jq -r .member[].hbzId

**Comment by fsteeg** [comment]
Import file for review: [700n-import-20200123-1450.txt.zip](https://github.com/hbz/nwbib/files/4103368/700n-import-20200123-1450.txt.zip)

**Comment by acka47** [comment]
Das hbz01 Update wurde am Wochenende durchgeführt, siehe http://lobid.org/resources/search?q=spatial.id%3A%22https%3A%2F%2Fnwbib.de%2Fspatial%23N96%22+OR+spatial.id%3A%22https%3A%2F%2Fnwbib.de%2Fspatial%23N97%22. Closing.

**Comment by acka47** [comment]
Zu berücksichtigen in #465.
