### ISSUE TITLE
Ergänze Klammerzusatz "(Stadtbezirk)", wenn Angabe im Label fehlt

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#524]
Bei der Ergänzung der Enddaten für Alt-Regierungsbezirke sind unerwünschte Änderungen in die Systematik gelangt. Und zwar wurde in Wikidata bei einigen Stadtbezirken der Klammerzusatz "(Stadtbezirk") entfernt, siehe https://github.com/hbz/lobid-vocabs/pull/108/files. Wir haben diese Änderungen jetzt erstmal auf dem Produktionssystem eingespielt. Da wir es nicht für sinnvoll halten, auf Wikidata einen Edit-War zu starten, um den Klammerzusatz zu behalten, gehen wir wie folgt vor: Wir ergänzen eine Regel, die während der Generierung der SKOS-Systematik bei allen Stadtbezirken den Klammerzusatz ergänzt, wenn das Wort "Stadtbezirk" nicht bereits im Namen vorkommen sollte.

**Comment by fsteeg** [comment]
Deployed to test:

https://test.nwbib.de/spatial#Q151287
https://github.com/hbz/lobid-vocabs/pull/112/files

**Comment by acka47** [comment]
In der Ergebnisliste ist es noch nicht umgesetzt, siehe z.B. https://test.nwbib.de/search?nwbibspatial=https%3A%2F%2Fnwbib.de%2Fspatial%23Q151287. Die basiert doch auf auch nwbib-spatial.ttl, oder? Auch nicht bei den Einzeltreffern, siehe z.B. https://test.nwbib.de/HT020288485.

**Comment by fsteeg** [comment]
Redeployed to test:

https://test.nwbib.de/search?nwbibspatial=https://nwbib.de/spatial%23Q151287
https://test.nwbib.de/HT020288485

**Comment by acka47** [comment]
+1
