### ISSUE TITLE
36 | Diözese Minden und Corvey wurden nicht migriert

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#527]
Ähnlich wie #516 . Es handelt sich um neun Treffer: http://nwbibsnapshot.lobid.org/resources/search?q=di%C3%B6zese++AND+minden

**Comment by acka47** [comment]
Vgl. http://nwbibsnapshot.lobid.org/resources/search?q=di%C3%B6zese+AND+corvey & https://nwbib.de/spatial#Q3708105 für Corvey. (Ähnlich wie https://github.com/hbz/nwbib/issues/516#issuecomment-574120953 ist das Mapping eigentlich in der `string2wikidata.tsv`: `Diözese Corvey | 36	Q3708105`. Aus irgendwelchen Gründen wurde das nicht in den Daten ergänzt und dann migriert. Gilt auch für Diözese Minden.)

**Comment by fsteeg** [comment]
Grad besprochen: machen wir manuell.

**Comment by acka47** [comment]
Mail an die Redaktion ging gerade raus. Closing.
