### ISSUE TITLE
Zeige Copy-Paste-Button auch bei Orten mit null verlinkten Titeln an 

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#529]
Siehe z.B. https://nwbib.de/spatial#Q1377265 oder https://nwbib.de/spatial#Q883257.

Auf der obersten Ebene (im Web bold dargestellt) sollte aber weiterhin kein Button angezeigt werden.

**Comment by fsteeg** [comment]
Deployed to test:

https://test.nwbib.de/spatial#Q1377265
https://test.nwbib.de/spatial#Q883257

**Comment by acka47** [comment]
+1
