### ISSUE TITLE
Ergänze fehlende Ortsverlinkung zu Bockum-Hövel

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#530]
Hier die Liste der Titel, bei denen das ergänzt werden muss:

http://nwbibsnapshot.lobid.org/resources/search?q=Bockum+AND+H%C3%B6vel&size=100

Eingetragen werden muss https://nwbib.de/spatial#Q1573603, wieder als erstes in der zweiten Spalte.

**Comment by fsteeg** [comment]
Import file for review: [700n-import-20200123-1445.txt](https://github.com/hbz/nwbib/files/4103351/700n-import-20200123-1445.txt)

**Comment by acka47** [comment]
Der Import wurde durchgeführt, siehe https://nwbib.de/search?nwbibspatial=https%3A%2F%2Fnwbib.de%2Fspatial%23Q1573603. Closing.
