### ISSUE TITLE
Deployment-Fehler auschließen

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#536]
Als ich heute https://nwbib.de/spatial aufgerufen hat, war die Wartezeit wieder sehr lang. Offensichtlich war der Cache noch "kalt" (siehe https://www.section.io/blog/what-is-cache-warming/). Falls es einfach umzusetzen ist, sollten wir den Cache automatisch aufwärmen, so dass keine Nutzer*in so so eine lange Wartezeit erleben muss.

**Comment by acka47** [comment]
Es handelte sich nicht um ein Caching-Problem, sondern um ein Problem beim Deployment, das in Zukunft ausgeschlossen werden sollte.

**Comment by fsteeg** [comment]
Die `nwbib.conf` war so konfiguriert, dass die große SKOS-Datei eingelesen wurde, und zusätzlich die Systematik aus Wikidata aufgebaut wurde. Der Code sollte so umgebaut werden, dass die UI immer nur die Datei verwendet, und das Bauen der Systeamtik aus Wikidata nur über `SpatialToSkos`.

**Comment by acka47** [comment]
Kann das geschlossen werden, @fsteeg ?

**Comment by fsteeg** [comment]
Also entsprechend umgebaut habe ich nichts, d.h. das Problem könnte bei falscher Konfiguration wieder auftauchen. Ist es aber seitdem nicht, und bei falscher Konfiguration könnte alles Mögliche passieren, d.h. ich würde sagen ja, kann geschlossen werden.
