### ISSUE TITLE
Add Körperschaft / Corporate Body in advanced search

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#54]
For DigiBib integration we need the following fields to be searched seperately (striked though are those we already have:

1. ~~Freitext~~: ?q parameter
2. ~~Wörter aus dem Titel~~: `dct:title` and `http://rdvocab.info/Elements/otherTitleInformation`
3. Autor (Name, Vorname): `dct:creator` + `a gnd:Person`
4. Körperschaft: dct:creator + `a gnd:CorporateBody`
5. ~~Verlag: `dc:publisher`~~
6. ~~Schlagwörter~~
7. ISBN: tbd
8. ISSN: tbd
9. ~~Erscheinungsjahr: `dct:issued`~~

"Autor" and "Körperschaft" are only queryable via one "field" in lobid.

**Comment by acka47** [comment]
We will now enable search for corporate body by creating a separate API parameter, see https://github.com/hbz/lobid/issues/121.

**Comment by fsteeg** [comment]
Deployed to staging, see: http://test.lobid.org/nwbib/search?corporation=hbz

**Comment by acka47** [comment]
+1
