### ISSUE TITLE
Titel über "Stadt Werne" mit "Bochum-Werne" verlinkt

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#541]
Am 06.02.20 um 11:35 schrieb I.N.:
> wir haben noch ein Problem beim geographischen Namen „Werne“ entdeckt.
> 
> Die Titel zur Stadt Werne im Kreis Unna (Q10936) wurden unter den 
> heutigen Stadtteil Bochum-Werne (Q881204) gehängt.
> 
> Die meisten Titel beziehen sich auf die Stadt Werne und nicht auf den 
> heutigen Ortsteil Werne im Stadtbezirk Bochum-Ost.

Im Snapshot gibt es [424 Titel zur Stadt Werne](http://nwbibsnapshot.lobid.org/resources/search?q=spatial.700n1b%3A%28%22Werne%22+AND+NOT+%22Bochuum%22%29), während es [in der aktuellen NWBib nur 56](https://nwbib.de/search?nwbibspatial=https://nwbib.de/spatial%23Q10936) sind.

Wir werden sämtliche 424 Titel aus dem Snapshot aktualisieren.

**Comment by acka47** [comment]
To Do:

- Update file für de 424 Titel erstellen
- `https://nwbib.de/spatial#Q881204` durch `https://nwbib.de/spatial#Q10936` ersetzen

**Comment by fsteeg** [comment]
Import-Datei: [700n-import-20200401-1130.txt](https://github.com/hbz/nwbib/files/4414156/700n-import-20200401-1130.txt) (423 Einträge, [verwendeter query](http://nwbibsnapshot.lobid.org/resources/search?q=spatial.700n1b%3A%28%22Werne%22+AND+NOT+*Bochum*%29)).

**Comment by acka47** [comment]
+1 (Mit der [verwendeten Query]( http://nwbibsnapshot.lobid.org/resources/search?q=spatial.700n1b%3A%28%22Werne%22+AND+NOT+*Bochum*%29 ) ist es ein Titel weniger ist als mit der [Query im Originalkommentar](http://nwbibsnapshot.lobid.org/resources/search?q=spatial.700n1b%3A%28%22Werne%22+AND+NOT+%22Bochum%22%29). Da fällt ja nicht ins Gewicht...)

**Comment by fsteeg** [comment]
Import-Datei ohne ZDB (s. https://github.com/hbz/nwbib/issues/540#issuecomment-607698311): [700n-import-20200402-1145.txt](https://github.com/hbz/nwbib/files/4420177/700n-import-20200402-1145.txt)

**Comment by acka47** [comment]
The update worked well, see https://nwbib.de/search?nwbibspatial=https://nwbib.de/spatial%23Q10936 (ZDB titles are missing so we will need to take this into account in #465 .
