### ISSUE TITLE
Raumsystematik neu aufbauen

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#542]
Es ist mal wieder Zeit, https://nwbib.de/spatial auf basis der [config-Datei](https://github.com/hbz/nwbib/blob/master/conf/nwbib-spatial-conf.ttl) und Wikidata neu zu bauen.

**[Anleitung für den Neuaufbau der Systematik](https://github.com/hbz/nwbib/wiki/Aktualisierungsprozess-f%C3%BCr-die-NWBib-Raumsystematik#technischer-workflow-zur-aktualisierung)**

**Comment by fsteeg** [comment]
Deployed to test, see https://github.com/hbz/lobid-vocabs/pull/115 & e.g. https://test.nwbib.de/spatial#Q1283656

**Comment by acka47** [comment]
+1 Let's deploy this and see whether the alert stops showing up (I guess so).

**Comment by fsteeg** [comment]
Deployed to production, closing. See e.g. https://nwbib.de/spatial#Q1283656

**Comment by acka47** [comment]
@fsteeg, please rebuild as there have been several changes.

**Comment by fsteeg** [comment]
Deployed to test, see https://github.com/hbz/lobid-vocabs/pull/116 & e.g. https://test.nwbib.de/spatial#Q2166105

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
Deployed to production, closing. See e.g. https://nwbib.de/spatial#Q2166105

**Comment by fsteeg** [comment]
Deployed to test, see https://github.com/hbz/lobid-vocabs/pull/118 & https://test.nwbib.de/spatial#Q65415375

**Comment by fsteeg** [comment]
Deployed to production, closing. See https://nwbib.de/spatial#Q65415375

**Comment by acka47** [comment]
Reopening as new entries were added, e.g. https://test.nwbib.de/spatial#Q2128453

**Comment by acka47** [comment]
Please deploy after merging #552 .

**Comment by acka47** [comment]
Die Ortssystematik muss wieder neu geladen werden, https://nwbib.de/spatial#Q1775208 soll durch http://www.wikidata.org/entity/Q95350780 ersetzt werden.

**Comment by fsteeg** [comment]
Auf test deployed: https://test.nwbib.de/spatial#Q95350780

Aber durch die Änderung der ID aktuell ohne verknüpfte Titel:

https://test.nwbib.de/search?nwbibspatial=https://nwbib.de/spatial%23Q95350780
https://test.nwbib.de/search?nwbibspatial=https://nwbib.de/spatial%23Q1775208

**Comment by acka47** [comment]
Sieht gut aus. Ich sag dann nach dem Deployen auf der Liste bescheid, dass die fünf Titel angepasst werden müssen.

**Comment by fsteeg** [comment]
Deployed to production, closing. See https://nwbib.de/spatial#Q95350780

**Comment by acka47** [comment]
Reopening because of Oberbilk.

**Comment by acka47** [comment]
Heute kam eine E-Mail von S. G.-H. Die Systematik muss erneut neu gebaut werden, "Wey" ist neu im Testsystem: https://test.nwbib.de/spatial#Q2299820

**Comment by acka47** [comment]
S. G.-H. hat einen weiteren Ort ergänzt: https://test.nwbib.de/spatial#Q731895

Bitte neu aufbauen, @fsteeg .

**Comment by fsteeg** [comment]
Deployed to production, closing: https://nwbib.de/spatial#Q731895

**Comment by acka47** [comment]
Wegen https://github.com/hbz/nwbib/issues/565#issuecomment-762072910 bitte neu aufbauen, @fsteeg.

**Comment by fsteeg** [comment]
Deployed to test, see:

https://test.nwbib.de/spatial#Q876515
https://github.com/hbz/lobid-vocabs/pull/130/files

**Comment by fsteeg** [comment]
Reviewed in https://github.com/hbz/lobid-vocabs/pull/130.

Deployed to production, closing. See https://nwbib.de/spatial#Q876515

**Comment by acka47** [comment]
We need to rebuild NWBib spatial classification as  are least two new places have been added:

- Amtmannscherf, [Q39695707](https://www.wikidata.org/wiki/Q39695707)
- Holterhöfe, [Q1625196](https://www.wikidata.org/wiki/Q1625196)

**Comment by fsteeg** [comment]
Deployed:

https://nwbib.de/spatial#Q39695707
https://test.nwbib.de/spatial#Q39695707

**Comment by acka47** [comment]
+1 Mail is sent, closing.

**Comment by acka47** [comment]
Es wurde wieder ein neuer Ort ergänzt: https://www.wikidata.org/w/index.php?title=Q1946283&type=revision&diff=1443492085&oldid=1443490833

In der Testsystematik ist er bereits: https://www.wikidata.org/w/index.php?title=Q1946283&type=revision&diff=1443492085&oldid=1443490833

**Comment by fsteeg** [comment]
Deployed to production, see e.g. https://nwbib.de/spatial#Q47446722

**Comment by acka47** [comment]
Email is sent. Closing.

**Comment by acka47** [comment]
Erneuter Aufbau nötig, da neuer NWBib-ID-Eintrag in Wikidata in https://www.wikidata.org/w/index.php?title=Q40719211&type=revision&diff=1448399447&oldid=1448398042. Deshalb gibt es auch eine tägliche Monitoring-E-Mail.

**Comment by acka47** [comment]
nwbib-spatial was updated, see https://github.com/hbz/lobid-vocabs/commit/2c238f383219e35d006db67159196caf83e93956. Please deploy, @fsteeg .

**Comment by fsteeg** [comment]
Deployed to production, closing. See: https://nwbib.de/spatial#Q40719211

**Comment by acka47** [comment]
Reopening. email from U.P. to list:
 
> in die Testsystematik habe ich eine neue Systemstelle eingebracht. Sieht 
> gut aus und kann übernommen werden. Zwei Titel habe ich schon händisch 
> damit verknüpft.

**Comment by acka47** [comment]
nwbib-spatial ist updated, please deploy, @fsteeg .

**Comment by fsteeg** [comment]
Deployed to production, closing. See: https://nwbib.de/spatial#Q107451916

**Comment by acka47** [comment]
S. G.-H. wrote via email on 2021-07-16:

> in der Test-Raumsystematik habe ich den Ortsteil "Gut Unterdickt" 
> (gehörig zu Bad Münstereifel im Kreis Euskirchen, Regierungsbezirk Köln) erfasst. 
> Würden Sie das Produktionssystem bitte bei Gelegenheit (wir wissen, dass Sie 
> viel zu tun haben) entsprechend aktualisieren?

**Comment by acka47** [comment]
I updated the nwbib-spatial.ttl file from Wikidata, see https://github.com/hbz/lobid-vocabs/commit/83243f7f1334dfbf1972c1f6d83e712e9ccec874. Please deploy, @fsteeg.

**Comment by fsteeg** [comment]
Deployed, closing. See:

https://test.nwbib.de/spatial#Q1557059
https://nwbib.de/spatial#Q1557059

**Comment by acka47** [comment]
On 01.12.21 09:19, S. K.-L. wrote:

> wir haben 2 neue Ortsteile erfasst.
> 
> Gipperich und Niedersetzen

Siehe  https://www.wikidata.org/wiki/Q109703178 & https://www.wikidata.org/w/index.php?title=Q1988468&type=revision&diff=1530507565&oldid=1530506787

On 01.12.21 14:10, C.T. wrote:

> ich habe (Kürten) Bornen neu in die Systematik eingebracht.

Siehe https://www.wikidata.org/w/index.php?title=Q26836855&type=revision&diff=1536603560&oldid=1418147628

**Comment by fsteeg** [comment]
Pushed new nwbib-spatial to https://github.com/hbz/lobid-vocabs/pull/140.

(I forgot that by our new process this is done by @acka47.)

**Comment by acka47** [comment]
Thanks! I forgot it myself.

**Comment by fsteeg** [comment]
Deployed to production, see e.g. https://nwbib.de/spatial#Q29514553

**Comment by acka47** [comment]
Closing

**Comment by acka47** [comment]
Mit [Büren](https://www.wikidata.org/w/index.php?title=Q63860001&type=revision&diff=1551828626&oldid=1551824317) hat ein weiterer Ort die NWBib-ID in Wikidata bekommen und muss nun in die NWBib-Raumsystematik übernommen werden.

**Comment by fsteeg** [comment]
Deployed to production, closing. See https://nwbib.de/spatial#Q63860001.

**Comment by acka47** [comment]
Es gibt einen weiteen neuen Ortsteil:  (Hennef)- Striefen, Q2356192

**Comment by fsteeg** [comment]
Deployed to production, closing. See:

https://nwbib.de/spatial#Q63860001
https://nwbib.de/spatial#Q2356192

**Comment by acka47** [comment]
Einen habe ich noch: Queckenberg (Q15059086).

**Comment by fsteeg** [comment]
Deployed to production, closing. See https://nwbib.de/spatial#Q15059086.

**Comment by acka47** [comment]
@fsteeg, please deploy the changes pushed in https://github.com/hbz/lobid-vocabs/commit/251ed3d8a78050bba52459f947dbbe37e09eeaf7

**Comment by fsteeg** [comment]
Deployed to test and production, see:

https://nwbib.de/spatial#Q19687919
https://nwbib.de/spatial#Q50388833

**Comment by acka47** [comment]
E-Mails hatte ich gestern rausgeschickt. Closing.

**Comment by fsteeg** [comment]
Deployed to production, closing. See https://nwbib.de/spatial#Q857181

**Comment by acka47** [comment]
Am 22.03.22 um 18:43 schrieb G-H, S.:
> in der Test-Raumsystematik habe ich die Ortsteile „Bärbroich“ (gehörig 
> zu Bergisch Gladbach, Rheinisch-Bergischer Kreis, Regierungsbezirk Köln) 
> sowie „Scheid“ (gehörig zu Lohmar im Rhein-Sieg-Kreis, ebenfalls 
> Regierungsbezirk Köln) erfasst. Würden Sie das Produktionssystem bitte 
> entsprechend aktualisieren?

**Comment by fsteeg** [comment]
Deployed to production, see:

https://nwbib.de/spatial#Q1019064
https://nwbib.de/spatial#Q1289090

**Comment by fsteeg** [comment]
Deployed to production: https://nwbib.de/spatial#Q1017276

**Comment by acka47** [comment]
C.T. wurde über Deployment informiert. Closing.

**Comment by acka47** [comment]
On 06.04.22 08:42, C.T. wrote:
> ich habe den Ortsteil Groin von Rees eingebracht: 
> Groin$$0https://nwbib.de/spatial#Q65182530

Reopening.

**Comment by acka47** [comment]
I updated the SKOS file with [c20666e](https://github.com/hbz/lobid-vocabs/commit/c20666efbd3d6793c126dab37cdd36a723fa2bf2), @fsteeg please deploy to production.

**Comment by fsteeg** [comment]
Deployed to production, see:

https://nwbib.de/spatial#Q1417419
https://nwbib.de/spatial#Q65182530

**Comment by acka47** [comment]
Gerade kam eine weitere Ergänzung bon C.T. rein:

> ich habe den Ortsteil Lückert von Hennef eingebracht: 
>   Lückert$$0https://nwbib.de/spatial#Q1880210

**Comment by acka47** [comment]
SKOS-Datei ist aktualisiert, siehe https://github.com/hbz/lobid-vocabs/commit/6164fd726cbb29034cd96eaf335049350609dce3 . Kann auf Production deployt werden.

**Comment by fsteeg** [comment]
Deployed: https://nwbib.de/spatial#Q1880210

**Comment by acka47** [comment]
Am 04.05.22 um 10:15 schrieb C.T.:
> ich habe den Ortseil „Dorp“ von Wegberg in Wikidata neu angelegt und 
> versucht ihn durch aktualisieren in die Systematik einzubringen, was mir 
> aber nicht gelungen ist.

**Comment by acka47** [comment]
@fsteeg, please deploy.

**Comment by fsteeg** [comment]
Deployed to production: https://nwbib.de/spatial#Q111827768

**Comment by acka47** [comment]
E-Mail ist verschickt. Closing

**Comment by acka47** [comment]
Am 09.06.22 um 09:31 schrieb S. K.-L.:
> ich habe 2 neue Orte in die Raumsystematik eingebracht.
> 
> Lohauserholz
> 
> Wamge
> 
> Könnten Sie bitte die Raumsystematik aktualisieren?

**Comment by acka47** [comment]
Added changes in https://github.com/hbz/lobid-vocabs/commit/a45868a266c2439e78552c4aa506f09b26313997. Please deploy, @fsteeg .

**Comment by fsteeg** [comment]
Deployed to production, see:

https://nwbib.de/spatial#Q112078933
https://nwbib.de/spatial#Q32945246
https://nwbib.de/spatial#Q65945133

**Comment by acka47** [comment]
Mail an NWBib-Liste ist raus. Closing.

**Comment by acka47** [comment]
Am 27.07.22 um 11:02 schrieb D. R.-W.:
> heute habe ich in die Test-Version
> 
>   Emmericher Eyland Q2546591
> 
> eingebracht. Bitte die NWBib aktualisieren.
> 
> Danke sehr!

**Comment by fsteeg** [comment]
Deployed to production: https://nwbib.de/spatial#Q2546591

**Comment by acka47** [comment]
Mail ist nun raus. Closing

**Comment by acka47** [comment]
U.P. hat Gevenich (Linnich), [Q1520246](https://www.wikidata.org/wiki/Q1520246) ergänzt.

**Comment by acka47** [comment]
Bitte auf dem produktionssystem deployen, @fsteeg .

**Comment by fsteeg** [comment]
Deployed: https://nwbib.de/spatial#Q1520246

**Comment by acka47** [comment]
Mail ist verschickt. Closing.

**Comment by acka47** [comment]
U.P. meldet heute die Ergänzung von Mönchengladbachs Ortsteil "Ueding", [Q105455560](https://www.wikidata.org/wiki/Q105455560).

**Comment by acka47** [comment]
lobid-vocabs ist aktualisiert, bitte deployen, @fseeg. Eine Mail an die Liste habe ich schon im Entwurfsordner.

**Comment by fsteeg** [comment]
Deployed: https://nwbib.de/spatial#Q105455560

**Comment by acka47** [comment]
On 13.09.22 10:28, C.T. wrote (via private mail, not the list):
> Hallo Herr Pohl,
> 
> ich habe folgenden Ortsteil neu eingebracht:
> 
> Vetschau nwbib.de/spatial#Q2521301

**Comment by fsteeg** [comment]
Deployed: https://nwbib.de/spatial#Q2521301

**Comment by acka47** [comment]
Mail ist raus. Closing

**Comment by acka47** [comment]
Please deploy to prdo, @fsteeg .

**Comment by fsteeg** [comment]
Deployed: https://nwbib.de/spatial#Q2380724

**Comment by acka47** [comment]
Am 03.11.22 um 10:51 schrieb U.P.:
> Werthhoven$$0https://nwbib.de/spatial#Q2563512
> 
> Bitte in Produktivsystem übernehmen, danke und Grüße,

**Comment by acka47** [comment]
Please deploy to prod, @fsteeg

**Comment by fsteeg** [comment]
Deployed: https://nwbib.de/spatial#Q2563512

**Comment by acka47** [comment]
Mail an Liste ist raus. Closing.

**Comment by acka47** [comment]
Am 08.11.22 um 12:55 schrieb D.F.:
> Bitte neuen Ortsteil ins Produktiv-System übernehmen:
> 
> Lengenbeck $$0https://nwbib.de/spatial#Q1817623
>

**Comment by acka47** [comment]
Please deploy to prod, @fsteeg .

**Comment by fsteeg** [comment]
Deployed: https://nwbib.de/spatial#Q1817623

**Comment by acka47** [comment]
Mail versendet. Closing.

**Comment by acka47** [comment]
Wurde von @fsteeg im Kontext von #593 ergänzt. Mail ist raus. Closing.

**Comment by acka47** [comment]
Please deploy, @fsteeg

**Comment by fsteeg** [comment]
Deployed: https://nwbib.de/spatial#Q114559747

**Comment by acka47** [comment]
Mail ist raus. Closing.

**Comment by acka47** [comment]
This time, the generation of the rpb-spatial.ttl does not work, although I didn't change anything in my local setup. Here is the out put of `$ rm -rf ./data ; rm conf/wikidata.json ; sbt "runMain SpatialToSkos" ; cp conf/nwbib-spatial.ttl ../lobid-vocabs/nwbib/`

```
downloading sbt launcher 1.8.2
[info] Loading project definition from /home/acka47/git/nwbib/project
[info] Set current project to nwbib (in build file:/home/acka47/git/nwbib/)
[info] Compiling 1 Scala source and 1 Java source to /home/acka47/git/nwbib/target/scala-2.11/classes...
[info] Running SpatialToSkos 
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/acka47/.ivy2/cache/ch.qos.logback/logback-classic/jars/logback-classic-1.1.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/acka47/.ivy2/cache/org.slf4j/slf4j-log4j12/jars/slf4j-log4j12-1.7.12.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
log4j:WARN No appenders could be found for logger (org.elasticsearch.node).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
org.jboss.netty.channel.ChannelException: Failed to bind to: /0.0.0.0:3333
	at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:272)
	at play.core.server.NettyServer$$anonfun$1.apply(NettyServer.scala:147)
	at play.core.server.NettyServer$$anonfun$1.apply(NettyServer.scala:144)
	at scala.Option.map(Option.scala:146)
	at play.core.server.NettyServer.<init>(NettyServer.scala:144)
	at play.core.server.NettyServerProvider.createServer(NettyServer.scala:215)
	at play.core.server.NettyServerProvider.createServer(NettyServer.scala:214)
	at play.core.server.ServerProvider$class.createServer(ServerProvider.scala:24)
	at play.core.server.NettyServerProvider.createServer(NettyServer.scala:214)
	at play.api.test.TestServer$.start(TestServer.scala:80)
	at play.api.test.TestServer.start(TestServer.scala:42)
	at play.test.Helpers.start(Helpers.java:507)
	at play.test.Helpers.running(Helpers.java:523)
	at SpatialToSkos.main(SpatialToSkos.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.Run.invokeMain(Run.scala:67)
	at sbt.Run.run0(Run.scala:61)
	at sbt.Run.sbt$Run$$execute$1(Run.scala:51)
	at sbt.Run.directExecute$1(Run.scala:53)
	at sbt.Run.run(Run.scala:55)
	at sbt.Defaults$$anonfun$runMainTask$1$$anonfun$apply$44$$anonfun$apply$45.apply(Defaults.scala:793)
	at sbt.Defaults$$anonfun$runMainTask$1$$anonfun$apply$44$$anonfun$apply$45.apply(Defaults.scala:791)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:461)
	at sun.nio.ch.Net.bind(Net.java:453)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:222)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:85)
	at org.jboss.netty.channel.socket.nio.NioServerBoss$RegisterTask.run(NioServerBoss.java:193)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.processTaskQueue(AbstractNioSelector.java:391)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:315)
	at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	... 3 more
java.lang.RuntimeException: org.jboss.netty.channel.ChannelException: Failed to bind to: /0.0.0.0:3333
	at play.api.test.TestServer.start(TestServer.scala:46)
	at play.test.Helpers.start(Helpers.java:507)
	at play.test.Helpers.running(Helpers.java:523)
	at SpatialToSkos.main(SpatialToSkos.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
Caused by: org.jboss.netty.channel.ChannelException: Failed to bind to: /0.0.0.0:3333
	at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:272)
	at play.core.server.NettyServer$$anonfun$1.apply(NettyServer.scala:147)
	at play.core.server.NettyServer$$anonfun$1.apply(NettyServer.scala:144)
	at scala.Option.map(Option.scala:146)
	at play.core.server.NettyServer.<init>(NettyServer.scala:144)
	at play.core.server.NettyServerProvider.createServer(NettyServer.scala:215)
	at play.core.server.NettyServerProvider.createServer(NettyServer.scala:214)
	at play.core.server.ServerProvider$class.createServer(ServerProvider.scala:24)
	at play.core.server.NettyServerProvider.createServer(NettyServer.scala:214)
	at play.api.test.TestServer$.start(TestServer.scala:80)
	at play.api.test.TestServer.start(TestServer.scala:42)
	at play.test.Helpers.start(Helpers.java:507)
	at play.test.Helpers.running(Helpers.java:523)
	at SpatialToSkos.main(SpatialToSkos.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:461)
	at sun.nio.ch.Net.bind(Net.java:453)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:222)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:85)
	at org.jboss.netty.channel.socket.nio.NioServerBoss$RegisterTask.run(NioServerBoss.java:193)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.processTaskQueue(AbstractNioSelector.java:391)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:315)
	at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
[trace] Stack trace suppressed: run last compile:runMain for the full output.
java.lang.RuntimeException: java.lang.RuntimeException: org.jboss.netty.channel.ChannelException: Failed to bind to: /0.0.0.0:3333
	at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last compile:runMain for the full output.
[error] (compile:runMain) java.lang.RuntimeException: org.jboss.netty.channel.ChannelException: Failed to bind to: /0.0.0.0:3333
[error] Total time: 15 s, completed 20-Jan-2023 14:14:59
```

**Comment by dr0i** [comment]
> Failed to bind to: /0.0.0.0:3333

This usually means that there is already some daemon running at your localhost at port 3333. Check this with "$ lsof -i 3333" and kill it, if you dare, before starting `sbt` again.

**Comment by acka47** [comment]
Ah, thanks. OpenRefine was the culprit.

**Comment by acka47** [comment]
Ok, pushed changes to lobid-vocabs and deployed it by myself for the first time. \o/ Closing

**Comment by acka47** [comment]
Reopening because of today's email by U.P. with subject "neuer Ortsteil Scheuren in der Gemeinde Odenthal im Rheinisch-Bergischen Kreis im Regierungsbezirk Köln" -> https://test.nwbib.de/spatial#Q59594697

**Comment by acka47** [comment]
Erledigt

**Comment by acka47** [comment]
Reopening. Es gab einige Anpassungen in Wikdiata, die nachgezogen werden müssen. Zum Kontext hier meine E-Mail an C.T.:

Am 26.04.23 um 15:47 schrieb Adrian Pohl:
>  Ich habe mir gerade mal die Geschichte des 
> Eintrags Q1978684 angeschaut.
> 
> Als wir die NWBib-ID ergänzt haben, war der Eintrag bereits 
> problematisch. Die meisten Aussagen bezogen sich auf den Ortsteil, 
> allerdings verwiesen der Link auf Wikipedia und Wikimedia Commons auf 
> Einträge zu der Kirche:
> 
> https://www.wikidata.org/w/index.php?title=Q1978684&oldid=1010927391
> 
> Der Nutzer Chri06 hat dann am 19. September 2021 den Eintrag aufgeräumt 
> zugunsten der Kirche, siehe 
> https://www.wikidata.org/w/index.php?title=Q1978684&action=history
> 
> Erst anderthalb Jahre später ist Ihnen das nun aufgefallen. Ich gebe 
> Ihrer Analyse recht, dass wir nun nicht die Änderungen an Q1978684 
> rückgängig machen sollten, weil es dann den Ortsteil zweimal gibt. Ihre 
> vorgeschlagene Lösung scheint mir die einzig sinnvolle:
> 
> On 26.04.23 14:07, Tetzlaff, Cordula wrote:
>> Ich lösche die NWBib-ID aus dem Satz 1. Damit müsste die Verknüpfung 
>> mit der Raumsystematik gelöst werden?
>>
>> Ich verknüpfe die 17 Sätze unter 2. Mit der richtigen NW-Bib-ID?
>>
> 
> Ja, genau. Und wie ich sehe haben Sie die NWBib-ID beim zweiten Satz 
> (Q59168726) bereits ergänzt, so dass er in der NWbib nutzbar wird.
> 
>> Eigentlich hatten wir gedacht, dass die von uns genutzten 
>> Wikidata-Sätze irgendwie vor Fremdeingriff geschützt würden, was aber 
>> in diesem Fall wohl nicht funktioniert hat. Aber es ist auch der erste 
>> Fall, den wir bemerkt haben in dieser Art.
> 
> Schützen können wir das nicht. Wir können nur aufpassen, dass wir 
> unerwünschte Änderungen nicht in die – von Wikidata als "Puffer" 
> entkoppelte – NWBib Raumsystematik übernehmen. Das hat wohl auch eine 
> Weile geklappt, die Änderung ist erst am 22.11. 2022 in die NWBib 
> gerutscht: 
> https://github.com/hbz/lobid-vocabs/commit/3ffff2ad24e0074b8f432ff32d5ace5a14aa4330
> 
> Ich nehme an, dass ich manuell die Anpassung bis dahin nicht übernommen 
> habe, Herr Steeg das dann aber getan hat. Ich hätte mich wohl besser 
> vorher um eine langfristige Lösung kümmern müssen – so wie Sie es gerade 
> vorgeschlagen haben. Das werde ich mir für die Zukunft merken.

**Comment by acka47** [comment]
Erledigt.

**Comment by acka47** [comment]
Mail ist geschrieben. Closing

**Comment by acka47** [comment]
Am 24.05.23 um 11:23 schrieb D.F:
> Bitte neuen Ortsteil ins Produktiv-System übernehmen:
> 
> Nierentrop $$0https://nwbib.de/spatial#Q1524435

**Comment by acka47** [comment]
@fsteeg Der [hier](https://github.com/hbz/nwbib/wiki/Aktualisierungsprozess-f%C3%BCr-die-NWBib-Raumsystematik#technischer-workflow-zur-aktualisierung) dokumentierte Update-Prozess funktioniert nicht mehr wie gewohnt, vermutlich als FOlge des Switches von Aleph zu Alma. 

Ich habe den resultierenden Commit in den Branch [wrongSpatialUpdate](https://github.com/hbz/lobid-vocabs/tree/wrongSpatialUpdate) gepusht, siehe https://github.com/hbz/lobid-vocabs/commit/75a8328c5493253c67070f307414920edd363b55 .Fast alle Änderungen sind inkorrekt. Erst hatte ich befürchtet, dass sich tatsächlich so viel in Wikidata geändert hat, die Einträge, die ich mir angeschaut habe, waren aber ok. Beispiele:

* https://github.com/hbz/lobid-vocabs/commit/75a8328c5493253c67070f307414920edd363b55#diff-5a4025dc904d3edd63d0adfa5597cb54cdb49f0d19d301126c866df31d9bfcc9L252-L258
-> [Dorp (Q111827768)](https://www.wikidata.org/wiki/Q111827768) hat noch eine NWBib ID und wurde seit Oktober 2022 nicht geändert.
* https://github.com/hbz/lobid-vocabs/commit/75a8328c5493253c67070f307414920edd363b55#diff-5a4025dc904d3edd63d0adfa5597cb54cdb49f0d19d301126c866df31d9bfcc9L5848-L5850
-> [Q446857](https://www.wikidata.org/wiki/Q446857) heißt korrekt immer noch "Innenstadt" und nicht "Köln-Innenstadt".

Kannst du bei Gelegenheit mal schauen, was da schiefläuft?

**Comment by fsteeg** [comment]
Hm, wenn ich [das mache](https://github.com/hbz/nwbib/wiki/Aktualisierungsprozess-f%C3%BCr-die-NWBib-Raumsystematik#technischer-workflow-zur-aktualisierung) sieht es so aus: https://github.com/hbz/lobid-vocabs/commit/0cf0ae5c6818d581d2be06bbe7ba6809c71ba9a0.

Klappt vielleicht das Löschen der Daten irgendwie nicht (`rm -rf ./data ; rm conf/wikidata.json`)?

**Comment by acka47** [comment]
Ja, bei dir sieht es gut aus. Habe es mal in den master gemergt.

> Klappt vielleicht das Löschen der Daten irgendwie nicht (`rm -rf ./data ; rm conf/wikidata.json`)?

Ja, genau. Ich bekomme das am Anfang gemeldet:

> rm: das Entfernen von 'conf/wikidata.json' ist nicht möglich: Datei oder Verzeichnis nicht gefunden

Die Datei gibt es tatsächlich nicht.

**Comment by acka47** [comment]
Die beiden Orte sind nun produktiv, Mail ist geschrieben:

Am 31.05.23 um 09:38 schrieb Adrian Pohl:
> Lieber Herr F.,
> 
> die beiden Orte sind nun in der Produktiv-NWBib:
> 
> https://nwbib.de/spatial#Q1524435
> https://nwbib.de/spatial#Q908119
> 
> Viele Grüße
> Adrian Pohl

Ich lasse das Ticket nochmal offen, bis das Problem auf meiner Seite behoben ist.

**Comment by fsteeg** [comment]
> Die Datei gibt es tatsächlich nicht.

Hm, dann verwendet er zumindest keine alten Daten, aber dann klappt ev. was anderes nicht, bei der Wikidata-SPARQL-Abfrage vielleicht? Da wird die wikidata.json erzeugt. Oder du bist im falschen Ordner oder sowas? Lokale Änderungen im Repo wären auch noch eine mögliche Fehlerquelle.

**Comment by acka47** [comment]
Ich war auf Java 11, mit 8 geht es wieder. Danke fürs Zuhören, @fsteeg . ;-) Closing.

**Comment by acka47** [comment]
Eledigt: https://nwbib.de/spatial#Q818997 Mail ist abgeschickt. Closing.

**Comment by acka47** [comment]
Am 06.07.23 um 11:38 schrieb D R.-W.:
> 
> Lieber Herr Pohl,
> heute habe ich in die Test-Version
> 
>    Grötzenberg  Q1551698
> 
>   eingebracht. Bitte die NWBib aktualisieren.

Am 06.07.23 um 12:55 schrieb C.T.:
> Hallo Herr Pohl,
> 
> ich habe den Ortsteil Ohmbach (von Windeck) neu eingebracht, kann ihn 
> allerdings noch nicht in der NW-Bib-Systematik finden.

**Comment by acka47** [comment]
On 03.11.23 14:58, U.P. wrote:
> der Stadtteil Rosellerheide ist neu angelegt im Testsystem und kann 
> übernommen werden. Dabei ist mir aufgefallen, dass der Stadtteil 
> Röckrath von Neuss auch noch nicht an der richtigen Stelle im Alphabet 
> der Stadtteile steht.

&

**Comment by acka47** [comment]
> Dabei ist mir aufgefallen, dass der Stadtteil
Röckrath von Neuss auch noch nicht an der richtigen Stelle im Alphabet
der Stadtteile steht.

Sieht für mich gerade gut aus:
![image](https://github.com/hbz/nwbib/assets/160292/752218e8-a42d-4477-8e8a-74595b033fae)

**Comment by acka47** [comment]
Erledigt, see https://nwbib.de/spatial#Q2166852 & https://nwbib.de/spatial#Q1021743 Closing
