### ISSUE TITLE
Ergänze Anfangsdatum bei Landkreis Grevenbroich-Neuß

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#545]
Am 01.04.20 um 13:59 schrieb U.P.:

> Hier wäre es noch gut, wenn dem Landkreis Grevenbroich-Neuß in unserer 
> Raumsystematik noch der Beginn hinzugefügt würde, nämlich 1929, sonst 
> gibt es keine Abgrenzung zum Kreis Grevenbroich, der von 1816 bis 1929 
> und 1946 bis 1974 bestand.

**Comment by fsteeg** [comment]
Deployed to test, see:

https://test.nwbib.de/spatial#Q1110953
https://github.com/hbz/lobid-vocabs/pull/117
https://github.com/hbz/nwbib/pull/546

**Comment by acka47** [comment]
+1
