### ISSUE TITLE
Neuen Aktualisierungsprozess umsetzen

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#547]
Setzt #515 voraus.

Anfang April haben wir den [hier](https://github.com/hbz/nwbib/wiki/Aktualisierungsprozess-f%C3%BCr-die-NWBib-Raumsystematik#alternativvorschlag-f%C3%BCr-den-update-prozess) beschriebenen Alternativvorschlag für den Update-Prozess der NWBib- Raumsystematik gemacht und die NWBib-Redaktion hat zugestimmt, dass es so umgesetzt werden soll. Hier die Beschreibung des Verfahrens aus dem Wiki:

> 1. NWBib-Redakteur\*in entscheidet sich für die Ergänzung eines Ortes und ergänzt eine Aussage mit [NWBib ID (P6814)](https://www.wikidata.org/wiki/Property:P6814) bei dem entsprechenden Wikidata-Eintrag.
> 2. Redakteur\*in stößt einen Neuaufbau der Systematik im Testsystem an: https://test.nwbib.de/spatial (Da die Wikidata-Schnittstelle erst mit zeitlichem Verzug aktualisiert wird, werden die Änderungen teilweise erst am nächsten Tag sichtbar.)
> 3. Redakteur\*in kopiert Feldinhalt aus der Test-Systematik nach Aleph.
> 4. Ein automatischer Test benachrichtigt das lobid-Team, dass die Systematik erweitert wurde.
> 5. lobid-Team aktualisiert die Systematik im Produktionssystem. Bei möglicherweise unerwünschten Auswirkungen wird vorher die NWBib-Redaktion konsultiert.

Für 4.) müssen wir #515 umsetzen.

**Comment by fsteeg** [comment]
Reload-Link für Schritt 2. oben ist verfügbar: https://test.nwbib.de/spatial

Die aktuelle Problematik mit Hamborn als Stadtteil und Stadtbezirk könnten wir zum Testen verwenden (aus Wikidata aktualisieren wenn Hamborn als Stadtteil wiederhergestellt ist).

**Comment by acka47** [comment]
Sehr schön, hab das direkt mal in dem Hambor-Kontext auf der Mailingliste erwähnt.

**Comment by acka47** [comment]
Mit "Schuttdorf" funktioniert es schon. Ist auf Produktion nicht drin aber auf Test.

**Comment by acka47** [comment]
> Die aktuelle Problematik mit Hamborn als Stadtteil und Stadtbezirk könnten wir zum Testen verwenden 

Der Test ist erfolgreich: im Test-System sind beide da, auf Produktion nicht.

**Comment by acka47** [comment]
Damit dieses Ticket geschlossen werden kann, muss noch #515 erledigt werden, was wir zu einem späteren Zeitpunkt tun weden. Verschiebe es zurück nach "Ready".

**Comment by acka47** [comment]
Was wir nicht bedacht haben, ist, dass es natürlich einige Aktualisierungen gibt, die nicht gleich aus der Ergänzung eines neuen Eintrags bestehen, z.B. hier die Entfernung des Stadtbezirk-Typ: https://www.wikidata.org/w/index.php?title=Q1677185&type=revision&diff=1209489576&oldid=1010922703

Über so eine Änderung müssen wir also von der Redaktion benachrichtigt werden. Eine Alternative wäre: Alle Änderungen in Wikidata daraufhin überprüfen, ob sie von einem NWBib-Redaktionsmitglied gemacht wurde, und wenn ja, die Änderungen in die NWbib-Systematik zu übernehmen...

**Comment by acka47** [comment]
Clsoing, weil #515 derzeit nicht benötigt wird-
