### ISSUE TITLE
Disallow crawlers for test.nwbib.de

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#549]
When implementing #386, we disallowed crawlers for the test system:

```
# robots.txt for test.nwbib.de
User-agent: *
Disallow: /
```

However, currently nothing is disallowed on test, see https://test.nwbib.de/robots.txt. (That's why a user sent us feedback to a document on test.)

**Comment by acka47** [comment]
Heute kam eine Fehlermeldung rein mit Verweis auf das Testsystem. Die Crawler sind dort immer noch erlaubt.

**Comment by fsteeg** [comment]
Deployed to https://test.nwbib.de/robots.txt, closing.
