### ISSUE TITLE
Zeige "abstract" & "note" im HTML

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#556]
Am 05.11.20 um 10:14 schrieb U.P.:

> wie hier in den Beispielen
> 
> https://nwbib.de/HT020583841
> 
> https://nwbib.de/HT018394360
> 
> zu sehen, wird das Feld 750c nicht im NWBib-Portal angezeigt. Es enthält 
> in der Regel wichtige Hinweise zum „Verständnis“ der Publikation in 
> formaler oder inhaltlicher Hinsicht. Würden Sie bitte prüfen, ob eine 
> Anzeige im Portal möglich ist?

Das Feld 750 wird auf `dct:abstract` gemappt, siehe https://github.com/hbz/lobid-resources/blob/f93201bec043cc732b27814a6ab4aea390d1aa9e/src/main/resources/morph-hbz01-to-lobid.xml#L7549-L7551 

Wir müssen es nur noch im HTML anzeigen. (Eventuell dann auch direkt in lobid-resources?)

**Comment by acka47** [comment]
Auch das Feld `note` sollte angezeigt werden, ich habe den Titel angepasst. U.P schrieb am 2020-11-05:

 > das gleiche gilt für Feld 501. Das wird auch nicht angezeigt. Hier ein Bespiel:
> https://nwbib.de/HT020632104
> 
> Außerdem wird noch Feld 434 "andere Details zur physischen Beschreibung" nicht angezeigt:
> https://nwbib.de/HT020583841
> 
> Vorschlag: Unserer Meinung nach sollten diese Felder auch in der TA im NWBib-Portal angezeigt werden, und zwar nach Feld 425 "Jahr" in der Reihenfolge, wie die Feldnummern das vorgeben. Bei Feld 750c würden wir allerdings eine Position zwischen den 400er und 500er Feldern vorziehen. Wir würden aber in Zukunft auf die Belegung des Feldes 750c ganz verzichten und immer das Feld 501 verwenden. Dann erübrigt sich das Problem mit Feld 750c.

434 wird momentan noch nicht transformiert wie es aussieht, von daher ist das aufwändiger und wird hier nicht bearbeitet. Reihenfolge der Anzeige: Jahr, `abstract`, `note`

**Comment by fsteeg** [comment]
Deployed to test, see:

- [ ] https://test.nwbib.de/HT018394360 (750/abstract)
- [ ] https://test.nwbib.de/HT020632104 (501/note)

**Comment by acka47** [comment]
+1 von mir aus. Ich schick das mal an die Liste, damit die sich wegen der Labels beraten können.
