### ISSUE TITLE
Filtern von Ergebnislisten funktioniert teilweise nicht

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#557]
Kam gerade über die Mailingliste.

Am 10.11.20 um 13:02 schrieb I.N.:

> die Recherche nach Schlagwörtern und anschließender Einschränkung auf 
> eine NWBib-Sachnotation funktioniert z.Z. nicht.
> 
> Hier einige Beispiele:
> 
>  1. Schlagwort-Recherche „Bocholt“ ergibt 1.261 Treffer:
>     https://nwbib.de/search?name=&person=&subject=Bocholt
> 
> Unter den Sachgebieten werden z.B. 17 Treffer mit der Notation 
> „Schulgeschichte“ angezeigt. Wenn man diese 17 Titel auswählt, wird 
> keine Einschränkung vorgenommen.
> 
> https://nwbib.de/search?subject=Bocholt&nwbibsubject=https%3A%2F%2Fnwbib.de%2Fsubjects%23N783000&format=
> 
> Außerdem zieht die Anzeige unter der Facette „Schlagwörter“ merkwürdig aus?
> 
> ![image](https://user-images.githubusercontent.com/160292/98676036-57627b00-235b-11eb-93a2-b4afd946314c.png)
>
>  2. Schlagwort-Recherche „Telgte“ ergibt 452 Treffer:
>     https://nwbib.de/search?name=&person=&subject=Telgte
> 
> Unter den Sachgebieten werden z.B. 43 Treffer mit der Notation 
> „Wallfahrten“ angezeigt. Nach Auswahl der Titel wird keine reduzierte 
> Treffermenge angezeigt.
> 
> https://nwbib.de/search?subject=Telgte&nwbibsubject=https%3A%2F%2Fnwbib.de%2Fsubjects%23N611085&format=
> 
> Die Einschränkung mit einer NWB-Raumnotation funktioniert:
> 
> https://nwbib.de/search?subject=Telgte&nwbibspatial=https%3A%2F%2Fnwbib.de%2Fspatial%23Q44172870&format=

Es ist aber nicht alles kaputt, z.B. funktioniert nach einer Suche nach "bocholt" und dann filtern nach "Karten": https://nwbib.de/search?q=bocholt&nwbibsubject=https%3A%2F%2Fnwbib.de%2Fsubjects%23N126000

**Comment by acka47** [comment]
1.) "bocholt" -> "Schulgeschichte" funktioniert bei mir jetzt (es ging eben nicht), 2.) klappt immer noch nicht. Seltsam.

Wegen der Schlagwörter habe ich noch die Vermutung, dass das evtl. seit der Umstellung auf HTTPS-URIs bei der GND nicht mehr funktioniert. Im Code findet sich die HTTP-Variante einmal:

https://github.com/hbz/nwbib/blob/277da0e363b56998c58d7f5596d81ac42c0f692b/app/controllers/nwbib/Lobid.java#L170-L178

**Comment by fsteeg** [comment]
Habe Kombination von `subject` und `nwbibsubject` sowie die Schlagwörter-Facette gefixt.

Deployed auf test:

https://test.nwbib.de/search?subject=bocholt&nwbibsubject=https%3A%2F%2Fnwbib.de%2Fsubjects%23N783000&format=

**Comment by acka47** [comment]
+1 Sieht sehr gut aus. Bitte deployen und danke für die schnelle Umsetzung.

**Comment by fsteeg** [comment]
Auf production deployed:

https://nwbib.de/search?subject=bocholt&nwbibsubject=https%3A%2F%2Fnwbib.de%2Fsubjects%23N783000

Issue wird nach merge von #572 geschlossen.
