### ISSUE TITLE
Enddatum im Systematikeintrag "Minden-Revensberg" entfernen

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#565]
Siehe https://www.wikidata.org/wiki/Q876515 und https://nwbib.de/spatial#Q876515

H.F. schrieb heute per E-Mail:

> in der Raumsystematik steht Minden-Ravensberg nicht unter 4-7 Historische Territorien und Gebiete, sondern unter 1-2 Landschaften. Hintergrund dafür ist, dass das preußische Verwaltungsgebiet nicht einmal ein Jahrhundert lang existierte (1719-1807), man aber danach noch weiterhin von der Region sprach und auch heute noch spricht, nicht nur in kirchlichen Kontexten, wie unsere NWBib-Titel auch zeigen
> 
Von daher müssen wir den zeitlichen Zusatz tatsächlich entfernen. Tatsächlich stimmt dann die Verlinkung zum Wikadata-Satz nicht mehr

Vorschlag:

1. Eintrag in die config-Datei umziehen und Enddatum entfernen
2. `foaf:focus`-Link zu Wikidata entfernen
3. URI ändern (`N123` anstatt `Q876515`)

@fsteeg, was denkst du zu 3.)? Ich würde eigentlich gerne auch in der URI ausdrücken, dass hier keine Wikidata-Verknüpfung existiert, dafür müssten wir die aber ändern, was wir ja eigentlich nicht machen sollten.

**Comment by fsteeg** [comment]
Was spricht denn dagegen, nur das Jahr rauszunehmen? Passt [`foaf:focus`](http://xmlns.com/foaf/spec/#term_focus) nicht trotzdem?

**Comment by acka47** [comment]
> Was spricht denn dagegen, nur das Jahr rauszunehmen? Passt [`foaf:focus`](http://xmlns.com/foaf/spec/#term_focus) nicht trotzdem?

Es geht halt um zwei verschiedene Dinge: Der Wikidata-Eintrag handelt von der preußischen Verwaltungseinheit, die 1719 bis 1807 existierte und der NWBib-Eintrag von der Landschaft, die es bis heute gibt. Wir sollten den Eindruck vermeiden, dass die NWBib unter https://nwbib.de/spatial#Q876515 Einträge über `wd:Q876515sammelt.

**Comment by fsteeg** [comment]
> Der Wikidata-Eintrag handelt von der preußischen Verwaltungseinheit, die 1719 bis 1807 existierte und der NWBib-Eintrag von der Landschaft, die es bis heute gibt.

OK, aber wenn diese Landschaft eine Sache ist, die es wirklich gibt, wäre es dann nicht sinnvoll, einen Wikidata-Eintrag dafür anzulegen, wie Herr Flachmann vorgeschlagen hat? Wenn die aber nur ein NWBib-Konzept ist, dann kann man doch sagen, dass die Verwaltungseinheit die reale Sache ist, auf die sich das NWBib-Konzept bezieht.

Die URL-Änderung fände ich in dem Fall OK, ich könnte aber auch einen Redirect einrichten.

**Comment by acka47** [comment]
Ich habe nochmal drüber nachgedacht und das nun anders gelöst, siehe https://www.wikidata.org/wiki/Q876515.

Da auch im Wikipedia-Artikel steht, dass es sowohl eine preußische Verrwaltungseinheit ist als auch "Regionalbezeichnung für das nördliche Ostwestfalen", habe ich den Typ "Region" in Wikidata ergänzt und Start- und Enddatum als Qualifikator beim Typ "Verwaltungsgliederung Preußens" ergänzt. Mit einem erneuten Einspielen aus Wikidata sollte das Enddatum nicht mehr angezeigt werden.

**Comment by fsteeg** [comment]
Ah, sehr schön, das klingt super.

**Comment by acka47** [comment]
Ja, gut, dass du hartnäckig gebliueben bist. ;-)

**Comment by acka47** [comment]
Ist erledigt. Closing
