### ISSUE TITLE
Update der Ortsklassifikation im Testsystem funktioniert nicht

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#569]
Am 31.05.21 um 14:20 schrieb U.P. an die NWBib-Mailingliste:

> am 25. Mai hat Frau v. G. den o.g. Eintrag \[[Amtmannscherf (Q39695707)](https://www.wikidata.org/wiki/Q39695707)\], A.P. aufgearbeitet, 
> gespeichert und in der Testsystematik auf den Button „aus WD 
> aktualisieren“ geklickt. Dann müsste doch dort nach etwa einem Tag der 
> WD-Eintrag als Ortsteil auch unter der Gemeinde Odenthal im 
> Rhein.-Bergischen Kreis zu finden sein. Dies ist aber nicht der Fall. 
> Ich meine, der Eintrag in WD ist korrekt und vollständig. Oder gibt es 
> zz Probleme mit der Testsystematik?

Ich habe es auch getestet und gehe davon aus, dass die Automatisierung derzeit nicht funktioniert.

**Comment by fsteeg** [comment]
> in der Testsystematik auf den Button „aus WD aktualisieren“ geklickt. Dann müsste doch dort nach etwa einem Tag der WD-Eintrag als Ortsteil auch unter der Gemeinde Odenthal im Rhein.-Bergischen Kreis zu finden sein

So funktioniert das ja nicht, habe das Wiki zum Thema [Verzögerung/Neuaufbau präzisiert](https://github.com/hbz/nwbib/wiki/Aktualisierungsprozess-f%C3%BCr-die-NWBib-Raumsystematik/_compare/3e2d5f3722a941906eddc8f7a2d88d682a1debd7...b14099236cddf4a9ea468d34e13cbb3036547cf0).

> Ich habe es auch getestet und gehe davon aus, dass die Automatisierung derzeit nicht funktioniert.

Ja, konnte ich reproduzieren: auch nach dem Aktualisieren gab es kein 'Amtmannscherf' in https://test.nwbib.de/spatial. War ein Konfigurationsfehler auf test.nwbib.org (wo wir zum Testen was verstellt hatten, vielleicht brauchen wir doch eine separate Instanz, oder z.B. einen einfachen Passwort-Schutz für den Aktualisierungslink im Produktivsystem).

Jedenfalls ist Amtmannscherf jetzt da: https://test.nwbib.de/spatial#Q39695707

**Comment by acka47** [comment]
+1, Mail ist raus. Closing
