### ISSUE TITLE
Discard geo_nwbib index

### ISSUE THREAD

**Issue by dr0i** [hbz/nwbib#570]
We used the `geo_nwbib` index to enrich geo labels with wikidata spatial data.
I think we don't need this enrichment anymore. It is described in https://github.com/hbz/lobid-resources/issues/998 as "the old way".
Discovered that the `geo_nwbib` is broken atm, too (it has 0 docs), but without any effect. Nonetheless, please ACK this @acka47.

The code should also be cleansed of this no more needed enrichment.

**Comment by dr0i** [comment]
"Fun" fact: the morph uses `wd_itemLabelTypesCoordinates.tsv` for enrichment. I have no idea how this file was build. Timestamp says " 31  May 2019". Must be related in https://github.com/hbz/lobid-resources/issues/998#issuecomment-493932913.

**Comment by dr0i** [comment]
Ah, one has to execute the shell curl defined in `getTypeAndCoordinatesFromWikidata.sparql`, see https://github.com/hbz/nwbib/issues/468#issuecomment-493189871. But doing this result in a file with only 164 lines , whilest `wd_itemLabelTypesCoordinates.tsv` has around 9k.
Should we update `wd_itemLabelTypesCoordinates` by fixing and running  `getTypeAndCoordinatesFromWikidata.sparql`?

**Comment by acka47** [comment]
AFAIK, we still need this for the ZDB data where we have still labels instead of URIs, see #465.

**Comment by acka47** [comment]
> AFAIK, we still need this for the ZDB data where we have still labels instead of URIs, see #465.

Yes, we still need the lookup for the ZDB data. However, the current NWBib entries from ZDB look fine, they all seem to have `spatial` entries as needed, see 
[`inCollection.id:"http://lobid.org/resources/HT014846970#!" AND inCollection.id:"http://lobid.org/resources/HT014176012#!" AND _exists_:spatial`](http://lobid.org/resources/search?q=inCollection.id%3A%22http%3A%2F%2Flobid.org%2Fresources%2FHT014846970%23%21%22+AND+inCollection.id%3A%22http%3A%2F%2Flobid.org%2Fresources%2FHT014176012%23%21%22+AND+_exists_%3Aspatial). Maybe the geo_nwbib index went down after the last ETL process?

**Comment by acka47** [comment]
Sorry, I just now read you other comments, @dr0i.

> Fun" fact: the morph uses wd_itemLabelTypesCoordinates.tsv for enrichment.

So we don't need the index at all.

> Should we update wd_itemLabelTypesCoordinates by fixing and running getTypeAndCoordinatesFromWikidata.sparql?

As things are fine as is and we are only talking about ~15k entries from ZDB, we can leave it like this and discard the geo_nwbib index. Please do so, @dr0i and then close the issue.

**Comment by dr0i** [comment]
Have this already deployed. You may want to have a look @acka47 .

**Comment by acka47** [comment]
> You may want to have a look @acka47 .

I did and I think something went wrong. I did not write the number down above but I think there were thousands more results for this query before deployment: [`inCollection.id:"http://lobid.org/resources/HT014846970#!" AND inCollection.id:"http://lobid.org/resources/HT014176012#!" AND _exists_:spatial`](http://lobid.org/resources/search?q=inCollection.id%3A%22http%3A%2F%2Flobid.org%2Fresources%2FHT014846970%23%21%22+AND+inCollection.id%3A%22http%3A%2F%2Flobid.org%2Fresources%2FHT014176012%23%21%22+AND+_exists_%3Aspatial). Checking for [ZDB resources in NWBib _without_ `spatial` information](https://lobid.org/resources/search?q=inCollection.id%3A%22http%3A%2F%2Flobid.org%2Fresources%2FHT014846970%23!%22+AND+inCollection.id%3A%22http%3A%2F%2Flobid.org%2Fresources%2FHT014176012%23!%22+AND+NOT+_exists_%3Aspatial) I get **11418** results. 

Here is an example that confirms my thoughts: https://lobid.org/resources/HT015720046 It has no `spatial` object although a spatial entry in `700n` exists in the [source](http://lobid.org/hbz01/HT015720046):

```xml
<datafield tag="700" ind1="n" ind2="1">
  <subfield code="a">99</subfield>
  <subfield code="b">Oberhausen (Rheinland)</subfield>
</datafield>
```

**Comment by acka47** [comment]
I just checked it out again as we will have to create an update file for https://github.com/hbz/nwbib/issues/465. It looks good again. I assume you set this upa again, @dr0i ?

**Comment by dr0i** [comment]
Correct. So this is fine then? I would revert master then.

**Comment by acka47** [comment]
> Correct. So this is fine then? I would revert master then.

+1

**Comment by dr0i** [comment]
Reverted. Closing.
