### ISSUE TITLE
Zeige Inhalt des Feldes 434 an

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#571]
Diese Anforderung wurde in #556 gefordert aber dort nicht umgesetzt:

> U.P schrieb am 2020-11-05:
>
>> das gleiche gilt für Feld 501. Das wird auch nicht angezeigt. Hier ein Bespiel:
>> https://nwbib.de/HT020632104
>> 
>> Außerdem wird noch Feld 434 "andere Details zur physischen Beschreibung" nicht angezeigt:
>> https://nwbib.de/HT020583841
>> 
>> Vorschlag: Unserer Meinung nach sollten diese Felder auch in der TA im NWBib-Portal angezeigt werden, und zwar nach Feld 425 "Jahr" in der Reihenfolge, wie die Feldnummern das vorgeben. Bei Feld 750c würden wir allerdings eine Position zwischen den 400er und 500er Feldern vorziehen. Wir würden aber in Zukunft auf die Belegung des Feldes 750c ganz verzichten und immer das Feld 501 verwenden. Dann erübrigt sich das Problem mit Feld 750c.

Ich schrieb in https://github.com/hbz/nwbib/issues/556#issuecomment-724719514:

> 434 wird momentan noch nicht transformiert wie es aussieht, von daher ist das aufwändiger und wird hier nicht bearbeitet.

**Comment by TobiasNx** [comment]
Sind das MAB oder MARC felder?

**Comment by acka47** [comment]
> Sind das MAB oder MARC felder?

MAB/Aleph XML

**Comment by TobiasNx** [comment]
MAB 434 # $$a -> MARC 300 ## $$b ([300 - Physical Description (R) $b - Other physical details (NR)](https://www.loc.gov/marc/bibliographic/bd300.html))
aus der [Konkordanz](https://service-wiki.hbz-nrw.de/pages/viewpage.action?pageId=483000321): 

> Illustrierender Inhalt
> (300 nicht wiederholbar, alle Angaben in einem Feld)
> 
> 300 ## $$a 201 Seiten $$b Illustrationen $$c 30cm $$e 1 DVD-ROM

Element 300 $b scheint unspezifischerzu sein, als 434: Other physical details vs. Illustrierender Inhalt

**Comment by TobiasNx** [comment]
@acka47 300 is part of `extend` is that enough?

**Comment by TobiasNx** [comment]
Ping @acka47

**Comment by acka47** [comment]
Ja, passt. Closing.
