### ISSUE TITLE
AND-Verknüpfung bei Kombination von Schlagwort- und Sachgebietsfilter

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#573]
Am 20.08.21 um 13:34 schrieb U.P.:

> wenn ich mit einer Sachgruppe suche, z.B. „Alltag“, erhalte ich 1104 
> Treffer. Facettiere ich dann mit dem SW „Alltagskultur“, erhalte ich 
> aber nicht weniger Treffer, sondern mehr, nämlich 1153. D.h. wohl, dass 
> die Treffer addiert werden, sofern sie sich nicht überlappen. Mit 
> anderen Facetten wie Medientyp oder Publikationstyp funktioniert die 
> Facettierung aber einwandfrei.

Da die Filterung nach verschiedenen Schlagwörtern oder verschiedener Sachgebiete mit einer `AND`-Verknüpfung stattfindet, sollte auch die Kombination der beiden Filter mit `AND` erfolgen.

**Comment by fsteeg** [comment]
Deployed to test:

https://test.nwbib.de/search?subject=https%3A%2F%2Fd-nb.info%2Fgnd%2F4001307-8&nwbibsubject=https%3A%2F%2Fnwbib.de%2Fsubjects%23N702000

**Comment by acka47** [comment]
+1 That was quick.

**Comment by fsteeg** [comment]
Deployed to production (will be reviewed and merged in https://github.com/hbz/nwbib/pull/572), see:

https://nwbib.de/search?subject=https%3A%2F%2Fd-nb.info%2Fgnd%2F4001307-8&nwbibsubject=https%3A%2F%2Fnwbib.de%2Fsubjects%23N702000
