### ISSUE TITLE
Anpassung des Favicons

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#577]
U.P. hat heute folgende Bitte per E-Mail an die Liste weitergeleitet:

> Vielleicht können wir uns wünschen, dass die Symbole der NWBib in den 
> Landesfarben grün, rot, weiß abgebildet wird.
> 
> Lässt sich einfacher finden wenn man mehrere Fenster geöffnet hat.

**Comment by acka47** [comment]
Das Landeswappen wäre – nach Nachfrage und Antwort aus Düsseldorf – auch gut: https://www.land.nrw/sites/default/files/styles/asset_image_halfwidth/public/assets/images/nrw_w_rgb.png

**Comment by fsteeg** [comment]
Deployed to test (use Ctrl-F5 to refresh cache): https://test.nwbib.de

**Comment by acka47** [comment]
+1
