### ISSUE TITLE
Aufsetzen einer auf der lobid-Alma-API basierenden NWBib-Testversion

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#578]
In 2022 werden wir die NWBib auf die lobid-Alma-API (https://alma.lobid.org/resources) umstellen müssen. Um die Anwendung frühzeitig testen zu können, sollten wir schon jetzt eine NWBib-Variante aufsetzen, die auf der lobid-Alma-API basiert.

Laufen könnte die entsprechend unter http://alma.nwbib.de

**Comment by fsteeg** [comment]
Die Testinstanz läuft jetzt auf Basis von Alma-Daten: http://test.nwbib.de/.

Grundsätzlich funktioniert es auch mit den neuen Daten, größere Komplexe die noch nicht gehen sind vor allem die Geodaten/Raumbezug/Coverage (noch nicht in den Titeldaten, da dachte ich auch noch: gehört das nicht eigentlich in die Raumsystematik?) und Bestand/item/hasItem (hat sich technisch geändert, items sind nicht mehr als eigene Dokumente im Index, und die Item-URLs haben ein neues Format / Integration von lobid-organisations muss angepasst werden).

Das Issue hier ist ja das Aufsetzen selbst, für weitere nötige Anpassungen sollten wir eigene Issues machen (z.B. zwei: Raumbezug & Bestandsinformationenen).

**Comment by acka47** [comment]
Sieht gut aus. +1 Closing
