### ISSUE TITLE
Fälschlicherweise Anzeige von Lokalinformation unter "Anmerkungen"

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#579]
Am 15.09.21 um 15:09 schrieb I.N.:

> bei der Titelaufnahme https://nwbib.de/HT018611577 
>  gibt es im Feld Anmerkungen eine 
> merkwürdige Eintragung (11_Mo).
> 
> Wenn man den Titel in Aleph aufruft, stellt man fest, dass _kein_ 
> Anmerkungsfeld 501 vorhanden ist.
> 
> Ein Blick in Lobid zeigt, dass der Eintrag aus einem _Bielefelder 
> Lokalsatz_  (Standort: 11_Mono) stammt.

![grafik](https://user-images.githubusercontent.com/160292/133569308-8b058cad-db02-40a0-8d6e-58e4ac5e187f.png)

Unter "Anmerkungen" soll nur der Inhalt des `note`-Feldes auf der Wurzelebene angezeigt werden. Offenbar werden dort gerade auch `note`-Angaben auf anderen Ebenen (hier `hasItem.note`) angezeigt.

**Comment by fsteeg** [comment]
Auf test deployed, siehe:

https://test.nwbib.de/HT018611577 (`hasItem.note`, wird nicht mehr angezeigt)
https://test.nwbib.de/HT016585703 (top-level `note`, wird weiterhin angezeigt)

**Comment by acka47** [comment]
+1
