### ISSUE TITLE
Zeige Links zu Parallelausgaben aus Feld "related" an

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#581]
On 01.09.21 17:21, I.N. wrote:
> Der Hinweis auf parallele Ausgaben ist besonders wichtig, wenn beide 
> Ausgaben in der HBZ-Titeldatei vorhanden sind, und somit eine Verlinkung 
> zur jeweils anderen Ausgabe angeboten werden könnte.
> 
> Beispiel-Titel mit Verlinkungsmöglichkeit: https://nwbib.de/HT020163372 
> und https://nwbib.de/HT020163348 
> 
> In diesem Fall sollte einfach der Text „Druck-Ausgabe …“  bzw. 
> „Online-Ausgabe, PDF“ mit dem Link zur anderen Ausgabe unterlegt werden.
> 
> Die Fußnotenfelder sollten unmittelbar *_vor_* dem 
> Sacherschließungsbereich d.h. vor dem Feld „Raumsystematik“ angezeigt 
> werden.

Die nötigen Informationen stehen im `related`-Feld, im genannten Beispiel HT020163372 sieht das so aus:

```json
	"related": [
		{
			"id": "http://lobid.org/resources/HT020163348#!",
			"note": [
				"Druck-Ausgabe"
			],
			"label": "Hübner, Carina: Der Prozess der Berufsorientierung aus der Perspektive der Schülerschaft mit sonderpädagogischem Unterstützungsbedarf im Bereich Lernen an Förderschulen im Land Nordrhein-Westfalen"
		}
	],
```

Manchmal gibt es auch mehr als einen Eintrag im `related`-Feld. Ich habe aber das Gefühl, dass dann häufig die "note"-Angabe fehlt, weshalb wir für die Anzeige vielleicht nur die erste Angabe berücksichtigen sollten.

**Comment by fsteeg** [comment]
Deployed to test, see:

https://test.nwbib.de/HT020163348
[https://test.nwbib.de/search?q=related:*](https://test.nwbib.de/search?q=related:*)

(Beim Such-Link gibts einige Parallelausgaben, die nicht zurücklinken oder nicht Teil der NWBib sind.)

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Deployed, closed.
