### ISSUE TITLE
Suche mit Klick auf Körperschaft funktioniert nicht

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#590]
Das ist ebenfalls in RPB zu fixen.

Beispiel: https://nwbib.de/HT016774863
-> Klick auf [Sommer, Thomas](https://nwbib.de/search?person=Sommer%2C+Thomas) gibt Ergebnis. Klick auf [Regierungsbezirk Arnsberg](https://nwbib.de/search?person=https%3A%2F%2Fd-nb.info%2Fgnd%2F4003008-8) startet Personen-, nicht Körperschaftssuche, weshalb kein Ergebnis zurückkommt.

**Comment by TobiasNx** [comment]
@acka47 https://nwbib.de/search?corporation=https%3A%2F%2Fd-nb.info%2Fgnd%2F4003008-8 this seems to be fixed, can you check and close?

**Comment by acka47** [comment]
Ja, es funktioniert jetzt. Closing
