### ISSUE TITLE
Abweichung von der bisherigen `publication`-Anzeige

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#591]
Bei der Alma-Testinstanz werden Verlag und Verlagsort nicht angezeigt, obwohl die Daten – wenn ich das richtig sehe, genauso aussehen wie beim Aleph-lobid. Unten der Vergleich für eine Ressource in beiden Systemen

https://nwbib.de/HT021250308: 

![image](https://user-images.githubusercontent.com/160292/188646782-920f1d2c-1819-4b5a-9738-e20a74d038a2.png)

[JSON]():
```json
"publication": [

    {
        "type": [
            "PublicationEvent"
        ],
        "location": "Düsseldorf",
        "publishedBy": "Droste Verlag",
        "startDate": "2022"
    }

]
```

https:/test./nwbib.de/HT021250308:

![image](https://user-images.githubusercontent.com/160292/188647303-c782c479-75b0-4eb4-bc36-bf6e8a57b829.png)

[JSON](https://alma.lobid.org/resources/search?q=hbzId:HT021250308&format=json):

```json
"publication": [

    {
        "publishedBy": "Droste Verlag",
        "location": "Düsseldorf",
        "type": [
            "PublicationEvent"
        ],
        "publicationHistory": "[2022]",
        "startDate": "2022"
    }

]
```

Der einzige Unterschied ist  das Feld `publication.publicationHistory`, das momentan bei zu vielen Alma-lobid-Ressourcen existiert (siehe https://github.com/hbz/lobid-resources/issues/1419) aber in der aktuellen NWBib keine Probleme macht, wenn es vorkommt, siehe z.B. https://nwbib.de/HT014055185, das noch weitaus mehr Felder im `publication`-Objekt hat, [JSON](http://lobid.org/resources/HT014055185.json):

```json
"publication": [

    {
        "type": [
            "PublicationEvent"
        ],
        "frequency": [
            {
                "id": "http://marc21rdf.info/terms/continuingfre#m",
                "label": "monatlich"
            }
        ],
        "note": [
            "Periodizität: monatl."
        ],
        "publicationHistory": "2003,Okt. - 2010,März",
        "endDate": "2010",
        "location": "Bonn",
        "publishedBy": "Köllen",
        "startDate": "2003"
    }

]
```

**Comment by acka47** [comment]
Eine andere interessante Sache ist, dass der Verlag bei den lobid-Alma-Daten im genannten beispiel auch im `contribution` Array auftaucht, was dann – sollte die Anzeige repariert werden und wie bei der produktiven NWBib aussehen – zur doppelten Anzeige des Verlags führt. Aus dem [JSON](https://alma.lobid.org/resources/search?q=hbzId:HT021250308&format=json).

```json
"contribution": [

    {
        "agent": {
            "label": "Köhler, Dorothee",
            "gndIdentifier": "130862886",
            "id": ["https://d-nb.info/gnd/130862886"](https://d-nb.info/gnd/130862886),
            "type": [
                "Person"
            ]
        },
        "role": {
            "id": ["http://id.loc.gov/vocabulary/relators/aut"](http://id.loc.gov/vocabulary/relators/aut),
            "label": "Autor/in"
        },
        "type": [
            "Contribution"
        ]
    },
    {
        "agent": {
            "gndIdentifier": "2009258-1",
            "id": ["https://d-nb.info/gnd/2009258-1"](https://d-nb.info/gnd/2009258-1),
            "label": "Droste Verlag",
            "type": [
                "CorporateBody"
            ]
        },
        "role": {
            "id": ["http://id.loc.gov/vocabulary/relators/pbl"](http://id.loc.gov/vocabulary/relators/pbl),
            "label": "Verlag"
        },
        "type": [
            "Contribution"
        ]
    }

]
```

**Comment by TobiasNx** [comment]
@acka47 this seems to be no problem anymore, can you check: https://nwbib.de/HT021250308 and close if true.

**Comment by acka47** [comment]
Ja, sieht jetzt gut aus. Closing
