### ISSUE TITLE
In der NWBib genutzter Wikidata-Ort wurde mit anderem WD-Item gemergt

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#593]
Da es sich hier um einen Präzedenzfall handelt, lege ich das Zicket an, damit wir die Diskussion und Entscheidung für kommende Fälle dokumentiert haben. Heute kam folgende Meldung rein:

On 31.10.22 01:00, sol wrote:
> Missing in NWBib:
> qid,P6814
> 
> Missing in Wikidata:
> qid,P6814
> Q47443308,""""Q47443308"
> Q1934754,""""Q1934754"

Seltsam ist, dass Q1934754 gar nicht in der [momentan Version der nwbib-spatial.ttl ](https://github.com/hbz/lobid-vocabs/blob/810a294d580d8e725134e9b5a314fbcc1446f4b5/nwbib/nwbib-spatial.ttl) auftaucht, Q47443308 allerdings schon.

Der Grund für die Meldung ist, dass Q47443308 eine Dublette war und deshalb mit der Wikidata-Ressource Q1934754 gemergt wurde. Als ID wird bei einem Merge in der Regel die ältere benutzt (hier: Q1934754). Im Ergebnis haben wir nun nur einen Eintrag: Q1934754. 

![image](https://user-images.githubusercontent.com/160292/198953101-db43b099-35f3-4f9d-a582-a64d24e3aad5.png)

Dieser Eintrag hat allerdings nun die von der Wikidata-QID abwiechende NWBib ID Q47443308:

![198953188-4954e816-c48c-4018-beae-3004efd44e62](https://user-images.githubusercontent.com/160292/198956455-bcc07f12-20c6-424f-ba78-b84d00e08b2f.png)

### Wie gehen wir damit um?

Ich sammle mal ein paar Fragen, deren Beanwortung unsere Entscheidung erleichtern sollte.

#### Ist es in irgendeiner Weise problematisch, wenn Wikidata Item ID und NWBib ID nicht dieselbe QID sind?

- Für die technische Funktionalität der NWBib spielt das keine Rolle.
- Es könnte allerdings immer mal wieder zu Verwirrungen führen.

#### Mit welchem Aufwand wäre eine Anpassung der NWBib ID verbunden?

1. Anpassung des Wikidata-Eintrags
2. Anpassung der 24 NWBib-Titel (hier wäre wohl noch eine manuelle Anpassung zumutbar)
3. Ergänzung eines `sameAs` und/oder `deprecatedUri` Statements, damit die alte URI nicht ganz aus den Daten verschwindet.
4. Neugenerierung und Deploy der Systematik

#### Was spricht gegen ein Anpassung?

- Der Aufwand, wenn die hier gewählte Lösung auch für zukünftige ähnlich geartete Fälle benutzt wird: Sollte so ein Fall in der Zukunft mit einem Ort passieren, an dem deutlich mehr Titel hängen, wäre der Aktualisierungsaufwand hoch, weil ein Batch-Update in Alma durchzuführen wäre. Allerdings scheint es mir nicht sehr wahrscheinlich, dass wir bei Orten mit vielen zugehörigen Titeln eine Wikidata-Dublette verwenden.
- Cool URIs: Die URIs der NWBib-Systematikeinträge sollten stabil bleiben

#### Was ist zu tun, wenn wir in nwbib-spatial nichts anpassen?

Damit hätten wir den ersten Fall in den Daten, wo NWBib-QID und Wikidat QID dauerhaft nicht identisch sind und müssten entsprechende Vorkehrungen treffen. Es wäre dazu lediglich die `foaf:focus`-Angabe zu aktualiseren:

1. In den Instanzdaten
2. In nwbib-spatial.ttl

Zu 1.): In den Instanzdaten wird die `foaf:focus`-Angabe generiert auf Basis einer Lookup Datei, siehe die [Fix](https://github.com/hbz/lobid-resources/blob/d741e1a79b3678caf1c6a2ff5bfe01a6e5b1abad/src/main/resources/alma/fix/subjects.fix#L226).

Diese [`nwbib-spatial.tsv`](https://github.com/hbz/lobid-resources/blob/master/src/main/resources/nwbib-spatial.tsv) wird – soweit ich weiß – aus Wikidata generiert. Die Frage ist, ob bei der Generierung bisher davon ausgegangen wird, dass die QIDs in Wikidata und NWBib identisch sind oder ob die tatsächliche Wikidata ID ausgelesen wird. @TobiasNx,  kannst du da etwas zu sagen? Wenn ja, müsste die Generierung der Datei angepasst werden.

Zu 2.) Auch im Kontext der Generierung der nwbib-spatial.ttl stellt sich die Frage, ob bei der Generierung bisher der Umstand genutzt wird, dass die QIDs in WIkidata und NWBib übereinstimmen oder ob die tatsächliche Wikidata QID für das`foaf:focus` statement nachgeschlagen wir. Ich kann das durch Inspektion der [`SpatialToSkos.java`](https://github.com/hbz/nwbib/blob/master/app/SpatialToSkos.java) nicht erkennen aber @fsteeg kann da bestimmt leicht etwas zu sagen.

Was die Entscheidung für oder gegen eine Anpassung der URI angeht, bin ich noch unschlüssig. Was meinst du, @fsteeg ?

**Comment by fsteeg** [comment]
> ob die tatsächliche Wikidata QID für das `foaf:focus` statement nachgeschlagen wir. Ich kann das durch Inspektion der [SpatialToSkos.java](https://github.com/hbz/nwbib/blob/master/app/SpatialToSkos.java) nicht erkennen aber @fsteeg kann da bestimmt leicht etwas zu sagen.

Mir scheint die QID der NWBib-ID verwendet zu werden, um das Focus-Statement zu bauen (das meinst du, oder?): https://github.com/hbz/nwbib/blob/master/app/SpatialToSkos.java#L272

> Was die Entscheidung für oder gegen eine Anpassung der URI angeht, bin ich noch unschlüssig. Was meinst du, @fsteeg ?

Bin mir nicht sicher ob ich die Abwägung wirklich durchdringe, aber tendenziell würde ich sagen das ist OK dass die ID abweicht, ist quasi unsere Entkopplung, so dass wir eben nicht immer unsere Daten ändern müssen wenn sich eine externe ID ändert, sondern wir nur den Link dahin ändern müssen.

**Comment by acka47** [comment]
> Bin mir nicht sicher ob ich die Abwägung wirklich durchdringe, aber tendenziell würde ich sagen das ist OK dass die ID abweicht, ist quasi unsere Entkopplung, so dass wir eben nicht immer unsere Daten ändern müssen wenn sich eine externe ID ändert, sondern wir nur den Link dahin ändern müssen.

Ich sehe das eigentlich auch so. Dann müssen wir allerdings die Generierung von `spatial.focus.id` anpassen:

> Mir scheint die QID der NWBib-ID verwendet zu werden, um das Focus-Statement zu bauen (das meinst du, oder?): https://github.com/hbz/nwbib/blob/master/app/SpatialToSkos.java#L272

Das müsste dann angepasst werden. Mit der SPARQL Query ([wikidata.sparql](https://github.com/hbz/nwbib/blob/master/conf/wikidata.sparql)) bekommen wir ja alle nötigen Informationen. Ich habe die mal in query.wikdata.org eingegeben ([link](https://w.wiki/5ude)), dann haben wir folgendes:

![image](https://user-images.githubusercontent.com/160292/199927628-e548e0a3-2bd2-4c9f-814d-b80f28846d75.png)

Wir müssten für `spatial.focus.id` dann halt die Item URI nehmen, à la `http://www.wikidata.org/entity/{ItemQid}`.

**Comment by TobiasNx** [comment]
> Diese [`nwbib-spatial.tsv`](https://github.com/hbz/lobid-resources/blob/master/src/main/resources/nwbib-spatial.tsv) wird – soweit ich weiß – aus Wikidata generiert. Die Frage ist, ob bei der Generierung bisher davon ausgegangen wird, dass die QIDs in Wikidata und NWBib identisch sind oder ob die tatsächliche Wikidata ID ausgelesen wird. @TobiasNx, kannst du da etwas zu sagen? Wenn ja, müsste die Generierung der Datei angepasst werden.

hier kann pascal besser was zu sagen. wie wird die nwbib-spatial.tsv generiert?

Wir wollen den prozess ja anpassen, sobald ein mehr zeilen lookup möglich ist:
https://github.com/hbz/lobid-resources/pull/1474

**Comment by dr0i** [comment]
Seit  https://github.com/hbz/lobid-resources/issues/1017 wird die `nwbib-spatial.tsv` generiert auf Grundlage der [nwbib-spatial.ttl](https://github.com/hbz/lobid-vocabs/blob/master/nwbib/nwbib-spatial.ttl) (mittels [CreateWikidataNwbibMaps.java](https://github.com/hbz/lobid-resources/blob/master/src/main/java/de/hbz/lobid/helper/CreateWikidataNwbibMaps.java)).

**Comment by TobiasNx** [comment]
DIe neue Datei wird dann nur noch auf Grundlage von wikidata erstellt: https://github.com/hbz/lobid-resources/pull/1474#issuecomment-1303226581

inkl. nwbibId und itemId

**Comment by fsteeg** [comment]
@dr0i schrieb:
> Seit https://github.com/hbz/lobid-resources/issues/1017 wird die nwbib-spatial.tsv generiert auf Grundlage der [nwbib-spatial.ttl](https://github.com/hbz/lobid-vocabs/blob/master/nwbib/nwbib-spatial.ttl) (mittels [CreateWikidataNwbibMaps.java](https://github.com/hbz/lobid-resources/blob/master/src/main/java/de/hbz/lobid/helper/CreateWikidataNwbibMaps.java)).

@TobiasNx schrieb:
> DIe neue Datei für den Mehrspalten-Lookup wird dann nur noch auf Grundlage von wikidata erstellt: https://github.com/hbz/lobid-resources/pull/1474#issuecomment-1303226581

d.h. dann nicht mehr aus der TTL, sondern mit eigenem Wikidata-Lookup? Ich hatte in Erinnerung dass wir die Geodaten eigentlich in die Systematik / TTL holen wollten. Zumal wenn die TTL eh schon die Basis war zuletzt. Oder bringe ich da was durcheinander?

**Comment by TobiasNx** [comment]
Es gibt eine Vielzahl von Informationen die in Wikidata liegen, die auch nicht in der TTL liegen. Wir hätten eine Lookup-Datei auf deren Basis wir die Werte aus Wikidata auslesen. Aktuell gehe ich nur von einem Wikidata-Lookup aus.

**Comment by fsteeg** [comment]
@acka47 schrieb:
> Ich dachte, dass eine Lösung vielleicht bereits erreicht werden könnte, wenn ich in den korrigierten Eintrag in die nwbib-spatial-conf übernehme (siehe https://github.com/hbz/nwbib/commit/768229a99f1b10dc2cf417ef35d9f324369e0322). Bei einer erneuten Generierung der nwbib-spatial wird aber immer noch ein zusätzlicher Eintrag für Herrschaft Homburg generiert, den ich dann heute manuell entfernt habe.

Ich glaube, mit dem aktuell [dokumentierten Update-Prozess](https://github.com/hbz/nwbib/wiki/Aktualisierungsprozess-f%C3%BCr-die-NWBib-Raumsystematik#technischer-workflow-zur-aktualisierung) kannst du keine [Änderungen an der nwbib-spatial-conf](https://github.com/hbz/nwbib/pull/594) testen, weil du die noch explizit in der nwbib.conf einstellen müsstest. So nimmt der die aktuelle komplette Klassifikation, und updated nur die Wikidata-Einträge. Wenn ich mit deiner Änderung komplett neu baue, bekomme ich auch zwei Einträge, aber so (erst deine neue aus der nwbib-spatial-conf, dann die neue aus Wikidata):

```
nwbib-spatial:Q47443308
        a               skos:Concept ;
        skos:broader    nwbib-spatial:N54 ;
        skos:inScheme   <https://nwbib.de/spatial> ;
        skos:prefLabel  "Herrschaft Homburg, Nümbrecht (bis 1806)"@de ;
        foaf:focus      wd:Q1934754 .

nwbib-spatial:Q1934754
        a               skos:Concept ;
        skos:broader    nwbib-spatial:N54 ;
        skos:inScheme   <https://nwbib.de/spatial> ;
        skos:prefLabel  "Reichsherrschaft Homburg (bis 1806)"@de ;
        foaf:focus      wd:Q1934754 .
```

Das ist aber auch nicht richtig, oder? Wir wollen nur die erste, nicht die zweite?

**Comment by fsteeg** [comment]
@acka47: Da wir beim nwbib-spatial-conf-Ansatz dann ja wieder schauen müssten, wie wir entscheiden, dass wir den 'echten' Wikidata-Eintrag nicht wollen, habe ich jetzt mal deinen Ansatz aus https://github.com/hbz/nwbib/issues/593#issuecomment-1303115080 umgesetzt, d.h. wir nehmen generell die Wikidata-nwbibId als ID für unsere concepts, und die Wikidata-item-ID als focus: https://github.com/hbz/nwbib/commit/cd73342bd975e2d4be4a6706c310496f3081d9db.

Das Ganze ergibt dann das hier: https://github.com/hbz/lobid-vocabs/commit/3ffff2ad24e0074b8f432ff32d5ace5a14aa4330. Die weiteren Änderungen kommen daher, dass wir zuletzt nicht sauber aus  nwbib-spatial-conf + Wikidata, sondern aus kompletter nwbib-spatial + Wikidata generiert haben, s. https://github.com/hbz/nwbib/issues/593#issuecomment-1323759790. Ich habe das in der nwbib.conf angepasst, so dass es wie dokumentiert und von dir gemacht jetzt stimmt.

**Comment by acka47** [comment]
+1
