### ISSUE TITLE
Knittkuhl (Q44023866) wurde mit Q17351610 gemergt

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#598]
Wir wurden erfolgreich durch unser Monitoring ("Alert nwbib-spatial") darauf aufmerksam gemacht, erstmals am 2023-01-22.

Hier die Änderung: https://www.wikidata.org/w/index.php?title=Q17351610&oldid=1815944157

Wir müssen das analog zu #593 anpassen.

**Comment by acka47** [comment]
@fsteeg schrieb in https://github.com/hbz/nwbib/issues/593#issuecomment-1323990833:

> Da wir beim nwbib-spatial-conf-Ansatz dann ja wieder schauen müssten, wie wir entscheiden, dass wir den 'echten' Wikidata-Eintrag nicht wollen, habe ich jetzt mal deinen Ansatz aus https://github.com/hbz/nwbib/issues/593#issuecomment-1303115080 umgesetzt, d.h. wir nehmen generell die Wikidata-nwbibId als ID für unsere concepts, und die Wikidata-item-ID als focus: https://github.com/hbz/nwbib/commit/cd73342bd975e2d4be4a6706c310496f3081d9db.

Wenn ich das richtig verstehe, dürfte – vorausgesetzt wir hätten das wie dort beschrieben umgesetzt – eigentlich gar keine Fehlermeldung kommen, weil uns die SPARQL Query( [code](https://github.com/hbz/nwbib/blob/master/conf/wikidata.sparql), [Wikidata Query Service](https://w.wiki/6Fay)) eigentlich die richtigen Daten zum korrekten Bau der SKOS-Datei liefert:

![image](https://user-images.githubusercontent.com/160292/213996500-2abbbd89-6ac6-41a5-b704-1f6c82a4a81b.png)

Irgendetwas scheint da noch nicht ganz rund zu laufen, oder @fsteeg ?

**Comment by acka47** [comment]
> Irgendetwas scheint da noch nicht ganz rund zu laufen, oder @fsteeg ?

Ich habe falsch gedacht. Das Alert-Skript hat uns korrekterweise auf den Merge hingewiesen. Wir müssen das nun bei uns umsetzen. Deshalb habe ich gerade einmal den [Aktualisierungsprozess](https://github.com/hbz/nwbib/wiki/Aktualisierungsprozess-f%C3%BCr-die-NWBib-Raumsystematik#technischer-workflow-zur-aktualisierung) laufen lassen und die Änderungen commited: https://github.com/hbz/lobid-vocabs/commit/eb23a4e6e0570f0417975687ac01a9fea3aa2fdc

Reicht das jetzt bereits aus, damit die Alert-Mail nicht mehr getriggert wird? Wir werden sehen.

**Comment by fsteeg** [comment]
> Reicht das jetzt bereits aus, damit die Alert-Mail nicht mehr getriggert wird? Wir werden sehen.

Sieht so aus, und ergibt auch Sinn, das Skript baut die Klassifikation selbst (`sbt "runMain SpatialToSkos"`): https://github.com/hbz/nwbib/blob/master/cron.sh

**Comment by acka47** [comment]
> Sieht so aus, und ergibt auch Sinn, das Skript baut die Klassifikation selbst (sbt "runMain SpatialToSkos"): https://github.com/hbz/nwbib/blob/master/cron.sh

Hmm, dann wundert es mich aber, warum überhaupt eine Alert-Mail rausgeschickt wurde. irgendwie muss doch auch mit der aktuellen nwbib-spatial.ttl verglichen werden, oder wie wurde die Mail dann getriggert?

**Comment by fsteeg** [comment]
Das Alert kam doch bevor du die Klassifikation gestern neu gebaut und deployed hattest oder?

**Comment by acka47** [comment]
> Das Alert kam doch bevor du die Klassifikation gestern neu gebaut und deployed hattest oder?

Ja, ich hatte allerdings nur neu gebaut, nicht deployt. (Die [SKOS-Datei auf der Webseite](https://nwbib.de/spatial.ttl) ist allerdings aktuell. 🤔 ) Wenn das Vergleichsskript aber selbst baut, sollte es ja irrelevant, was im lobid-vocabs-Repo liegt.

**Comment by fsteeg** [comment]
> Wenn das Vergleichsskript aber selbst baut, sollte es ja irrelevant, was im lobid-vocabs-Repo liegt.

Aso, ne, der triggert das Bauen, aber die Production-Instanz nutzt ja den lobid-vocabs-master, d.h. der baut dann den statischen Stand von https://raw.githubusercontent.com/hbz/lobid-vocabs/master/nwbib/nwbib-spatial.ttl (beim Bauen erzeugt er die Dateien, die dann  ausgewertet werden um das Alert zu schicken).

**Comment by acka47** [comment]
Zusammenfassend, um sicherzugehen, dass ich es richrtig verstanden habe: Wenn das nächste Mal eine Altert-Mail kommt wegen eines Merges von Wikidata-Items, dann reicht es erstmal aus https://github.com/hbz/lobid-vocabs/blob/master/nwbib/nwbib-spatial.ttl zu aktualisieren, damit zumindest die E-Mail nicht mehr kommt. Das Deployment können wir dann ja auch zusammen mit den nächsten größeren Änderungen machen. Ja?

**Comment by fsteeg** [comment]
Ja, klingt  gut, wenn du damit meinst dass du https://github.com/hbz/lobid-vocabs/blob/master/nwbib/nwbib-spatial.ttl per `sbt "runMain SpatialToSkos"` aktualisiert hast (nicht manuell editiert).

**Comment by acka47** [comment]
> Ja, klingt gut, wenn du damit meinst dass du https://github.com/hbz/lobid-vocabs/blob/master/nwbib/nwbib-spatial.ttl per sbt "runMain SpatialToSkos" aktualisiert hast (nicht manuell editiert).

Ich habe das per git push aktualisiert.
