### ISSUE TITLE
Mix up of GND and NWBib classifications in ZDB data

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#599]
Reported by @TobiasNx in https://github.com/hbz/lobid-resources/pull/1609#discussion_r1084141204:

> This seems to have an error in the ZDB-transformation from old coverage to spatial uri: http://lobid.org/resources/HT014078228
http://test.lobid.org/resources/990132101160206441
>
> MAB
```
<datafield tag="359" ind1="-" ind2="1">
<subfield code="a">Euregio Rhein-Waal ; Euregio Rhein-Maas-Nord</subfield>
</datafield>
```
> MARC
> 
```
<datafield tag="084" ind1=" " ind2=" ">
<subfield code="a">Euregio Rhein-Waal</subfield>
<subfield code="2">nwbib</subfield>
<subfield code="0">
https://portal.dnb.de/opac.htm?method=simpleSearch&cqlMode=true&query=idn=946322201
</subfield>
<subfield code="0">http://viaf.org/viaf/sourceID/DNB|946322201</subfield>
</datafield>
<datafield tag="084" ind1=" " ind2=" ">
<subfield code="a">Regionalplanung</subfield>
<subfield code="2">nwbib</subfield>
</datafield>
```
> 
> The ZDB change might have been done wrong here.

We will have to check whether and how many more resoruces are affected.

**Comment by dr0i** [comment]
Unclear for me what's the issue here and if it is solved.

**Comment by acka47** [comment]
The source of the original issue might be the problem described in https://service-wiki.hbz-nrw.de/x/ZwDsNg and tracked in https://github.com/hbz/nwbib/issues/595  . Thus, closing.
