### ISSUE TITLE
Anpassung der BEACON-Datei

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#600]
Gemeldet von W.F. via E-Mail am 2023-02-21:

> Ich schreibe Ihnen, da Ihre Mailadresse in der sogenannten 
> BEACON-Dateien eingetragen ist.
> https://lobid.org/download/beacons/nwbibContributors.bf
> 
> So wie ich das verstanden habe, sollte eine URL wie zum Beispiel
> https://nwbib.de/search?q=contribution.agent.id%3Ahttps%3A%2F%2Fd-nb.info%2Fgnd%2F120981459
> zu Norbert Scheuer führen, leider führen aber alle URLs die aus der 
> Header-Zeile "TARGET" und den IDs gebildet werden, zum unbefriedigenden 
> Ergebnis "Keine Ergebnisse."

Es funktioniet mit Anführungszeichen:

https://nwbib.de/search?location=&q=contribution.agent.id%3A%22https%3A%2F%2Fd-nb.info%2Fgnd%2F120981459%22

In der BEACON-Datei steht momentan das: `TARGET: https://nwbib.de/search?q=contribution.agent.id%3Ahttps%3A%2F%2Fd-nb.info%2Fgnd%2F{ID}`

Ich denke, das müssten wir einfach mit dem hier ersetzen, oder?

`https://nwbib.de/search?location=&q=contribution.agent.id%3A%22https%3A%2F%2Fd-nb.info%2Fgnd%2F{ID}%22`

**Comment by acka47** [comment]
Hmm, apparently the build script for the BEACOn file already has it right:

https://github.com/hbz/nwbib/blob/83a4e787175d767ca51c589d243b8174827ac86b/scripts/beacon/makeContributorsBeacon.sh#L15

Then why is it not published like that, @fsteeg?

**Comment by fsteeg** [comment]
> `#TARGET: https://nwbib.de/search?q=contribution.agent.id%3A"https%3A%2F%2Fd-nb.info%2Fgnd%2F{ID}"`

Ja genau, so sollte es gehen. Ich glaube man müsste auch nur die Anführungszeichen encoden:

`https://nwbib.de/search?q=contribution.agent.id:%22https://d-nb.info/gnd/{ID}%22`

Warum da offenbar was falsch auf dem Server liegt und was das überhaupt für eine `sh`-Datei ist weiss ich nicht. Da kann bestimmt @dr0i weiterhelfen.

**Comment by acka47** [comment]
Ah, ja, das ist was für @dr0i . Er hatte damals auch die Skripte in dieses Repo umgezogen und dabei aktualisiert, siehe https://github.com/hbz/nwbib/issues/335.

**Comment by dr0i** [comment]
> Ich glaube man müsste auch nur die Anführungszeichen encoden:

Genau - da war das bash script kaputt.
Ist jetzt repariert.
