### ISSUE TITLE
GND-Schlagwörter vor freien Schlagwörtern anzeigen

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#602]
On 02.03.23 09:57, I.N. wrote:
> wir hätten noch einen kleinen Verbesserungswunsch.
> 
> Wenn es in einer Titelaufnahme sehr viele freie Schlagworte (MARC Feld 
> 650) gibt, gehen die GND-Schlagwörter (MARC Feld 689) in der Menge der 
> Schlagwörter unter.
> 
> Hier ein Beispiel: https://nwbib.de/HT021461644 
> und im Testsystem: https://test.nwbib.de/HT021461644
> 
> Wäre es vielleicht möglich, die GND-Schlagwörter an der ersten Position 
> _vor_ den freien Schlagwörtern anzeigen zu lassen?

**Comment by fsteeg** [comment]
Auf test deployed: https://test.nwbib.de/HT021461644

**Comment by acka47** [comment]
We have received the go to deploy this on prod, via email both from Münster & Düsseldorf.

**Comment by fsteeg** [comment]
Deployed to production: https://nwbib.de/HT021461644
