### ISSUE TITLE
Keine Treffer mit Leerzeichen am Anfang der Kategorie "Alle Wörter"

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#603]
Gemeldet von I.N. über die Mailingliste am 2023-03-28:

> wenn durch Zufall z.B. beim Kopieren eines Titels aus einer anderen Quelle am Anfang der Kategorie Leerzeichen stehen,
> wird bei der Recherche in der Kategorie „Alle Wörter“ bzw. bei der Recherche über den Suchschlitz kein Treffer erzielt.

![image](https://user-images.githubusercontent.com/160292/228820912-d85d41ee-226b-4652-9f0b-e0a631ecce50.png)

![image](https://user-images.githubusercontent.com/160292/228820962-5095c788-92fc-413d-a5a7-d77cbeb626b2.png)

**Comment by fsteeg** [comment]
Auf dem Testsystem deployed:

https://test.nwbib.de/search?q=+Stimmungsvolle+Erinnerungen+an+die+Eisenbahn+in+Bocholt
https://test.nwbib.de/search?word=+Stimmungsvolle+Erinnerungen+an+die+Eisenbahn+in+Bocholt

**Comment by acka47** [comment]
+1
