### ISSUE TITLE
Error on searches with Alma instance

### ISSUE THREAD

**Issue by fsteeg** [hbz/nwbib#604]
Searches that include entries without `hbzId`:

- [x] https://test.nwbib.de/search
- [x] https://test.nwbib.de/search?q=köln

Links to other resources via hbzIds will still have to work:

- [x] https://test.nwbib.de/HT003772460

**Comment by fsteeg** [comment]
NWbib is expecting the `hbzId` field, which is no longer found in all entries for Alma data, which causes these errors. I will look into extracting the field into the config file, and replacing all usages with that config value, so we can set something like `id_field=almaMmsId` for the Alma instance.

**Comment by fsteeg** [comment]
Instead of making the specific field configurable, I've changed the implementation to use the actual `id` field in https://github.com/hbz/nwbib/commit/2c94f3de4bfff2d83c7d1954810ec5456b4dd397. Deployed to test:

https://test.nwbib.de/search
https://test.nwbib.de/search?q=köln

**Comment by fsteeg** [comment]
Added support for direct access via `hbzId` in an Alma-based system, for links via `hbzId`, e.g. https://test.nwbib.de/HT003772460.

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
Assigning @dr0i for remaining code review in PR https://github.com/hbz/nwbib/pull/606.
