### ISSUE TITLE
OPAC links don't work

### ISSUE THREAD

**Issue by fsteeg** [hbz/nwbib#605]
E.g. for https://nwbib.de/HT003772460, all OPAC links don't seem to work (right hand side, "Details zum Bestand als Liste anzeigen" -> "Lokalen Katalog abfragen"). I was testing with Alma data, but these seem broken for the Aleph data already. For Alma/almaMmsId we should do additional testing.

**Comment by TobiasNx** [comment]
Wird gelöst durch #628

**Comment by dr0i** [comment]
It's fixed. Closing.
