### ISSUE TITLE
Anpassungen für Alma-Instanz

### ISSUE THREAD

**Issue by fsteeg** [hbz/nwbib#607]
- [x] Siehe https://test.nwbib.de/search (rechts unten, "Bestand in Bibliotheken").
- [x] Auch  in lobid-resources, s. https://test.lobid.org/resources/search (vgl. https://github.com/hbz/lobid-resources/issues/1618, eine owner-aggregation gibts jetzt für `hasItem.heldBy.id`)
- [x] Details zum Bestand in Einzeltreffern, z.B. Signatur in https://test.nwbib.de/99371524738506441, auch elektronische Ressourcen, s. https://test.nwbib.de/99371288694506441 vs. https://nwbib.de/HT021318225 (aber anders gehandhabt, weil [99371288694506441](http://test.lobid.org/resources/99371288694506441.json) kein `fulltextOnline` hat)
- [x] Raumsystematik und Labels, s. https://test.nwbib.de/99371524738506441 vs. https://nwbib.de/HT021461532

**Comment by fsteeg** [comment]
Für die 4 Punkte oben machen wir hier vielleicht mal einen Cut, grundsätzlich scheint es mit Alma-Daten so zu funktionieren (s. auch https://github.com/hbz/nwbib/issues/604). Probleme mit eigenen Tickets gibts noch rund um OPAC-Links (https://github.com/hbz/nwbib/issues/605) und Überordnungen (https://github.com/hbz/lobid-resources/issues/1705).

Letzteres zeigt eine Schwierigkeit beim Testen des zukünftigen Alma-only-Zustandes: die Daten linken auf Produktiv-URIs, die ja noch auf Aleph-Basis laufen. D.h. wenn man sich so durchklickt landet man immer wieder auf Produktiv-Varianten. Wir könnten in einem separaten Ticket ev. versuchen, das überall zu ersetzen, sollten uns aber dennoch darauf einstellen, dass wir manches erst nach dem echten Switch sehen.

Ich denke so könnten wir das schonmal zur Begutachtung an die Redaktion geben, ev. mit Hinweisen auf bekannte Probleme (wie die oben erwähnten OPAC-Links und Überordnungen bzw. das beschriebene Rausspringen vom Test- ins Produktivsystem).

**Comment by acka47** [comment]
Sieht gut aus und kann meinetwegen deployt werden.

Eine Sache werden wir noch anpassen müssen (gerne in einem anderen Ticket):

- Momentan wird der Publikationsort nicht angezeigt
- Ich habe Zweifel, ob die NWBib-Redaktionen es für sinnvoll halten, dass mit Klick auf den Verlag eine Körpderschaftssuche gestartet werden kann.
- Am einfachsten wäre es, wenn wir die gleiche Darstellung wie in der aktuellen NWBib wählten:
![image](https://user-images.githubusercontent.com/160292/232437280-54a51de2-3304-4ff9-b918-d6441453a1e7.png)

**Comment by acka47** [comment]
+1
