### ISSUE TITLE
Liste der laufend ausgewerteten NWBib-Zeitschriften dynamisch generieren

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#611]
On 08.05.23 17:20, I.N. wrote:
> Seit dem Cutover können wir auch bei Zeitschriften-Titelaufnahmen das 
> NWBib-Selektionsfeld (Feld 960) in Alma einfügen und korrigieren. Da in 
> Alma nun unterschiedliche Kennungen für Zeitschriften hinterlegt wurden 
> (NWBib-Zeitschrift, NWBib-Zeitschrift-6 usw.), konnten wir einen 
> langgehegten Wunsch in die Praxis umsetzen. Wir haben unsere laufend 
> ausgewerteten Zeitschriften mit dem Selektionskennzeichen 
> „NWBib-Zeitschrift-6“ gekennzeichnet. Die NWBib-Zeitschriften, die 
> aktuell nicht mehr ausgewertet werden (z.B. Erscheinen eingestellt, 
> Titeländerungen, Erwerbung eingestellt, Auswertung auf Online-Ausgabe 
> umgestellt) haben das Selektionskennzeichen „NWBib-Zeitschrift“ 
> behalten. Dadurch ist nun eine Differenzierung nach laufend 
> ausgewerteten und ehemals ausgewerteten NWBib-Zeitschriften möglich.
> 
> Wenn die Kolleginnen in der ULB Düsseldorf diese Differenzierung auch 
> vornehmen würden, wäre die NWBib-Zeitschriftenliste auf Github, die wir 
> für unsere Homepage (https://nwbib.de/journals) 
>  verwendet haben, überflüssig. Man könnte 
> diese Zeitschriftenliste durch eine ODER-Recherche in Alma tagesaktuell 
> erzeugen.

**Comment by acka47** [comment]
Die Vorarbeiten in lobid sind erledigt, siehe https://github.com/hbz/lobid-resources/issues/1781.

Die Liste der laufend ausgewerteten NWBib-Zeitschriften kann nun mittels dieser Abfrage geholt werden: http://lobid.org/resources/search?q=inCollection.id:%22https://nwbib.de/journals%22

Wir sollten diese Lösung nun umsetzen, anstatt wieder eine csv-Liste einzuspielen.

**Comment by fsteeg** [comment]
Auf test deployed, die bisherige Liste wird vom Inhalt der Abfrage gefüllt:

https://test.nwbib.de/journals

Vielleicht wäre es aber auch besser, die tatsächliche Suchanfrage zu verlinken, dann hätte man z.B. die Facetten zum weiter einschränken:

[https://nwbib.de/search?q=inCollection.id:"https://nwbib.de/journals"](https://nwbib.de/search?q=inCollection.id:"https://nwbib.de/journals")

Generell wäre ev. eine `inCollection`-Facette schön, auch für lobid-resources.

(So oder so sind es ein paar weniger als bisher: https://nwbib.de/journals)

**Comment by fsteeg** [comment]
Feedback von I.N. 2024-01-22:

> Es wäre schön, wenn die Artikel (`<<Der>>`, `<<Die>>`, `<<Das>>`) am Titelanfang für die Sortierung übergangen werden könnten. 
Im MARC datafield 245 sind die Artikel durch Nichtsortierzeichen gekennzeichnet. 
Bei der ersten Zeitschrift mit den drei Punkten am Anfang stehen diese Punkte ohne Kennzeichnung direkt vor dem Titel. Aber möglicherweise, könnten die Punkt am Anfang der Kategorie auch übergangen werden?

Anpassungen auf Test deployed:

https://test.nwbib.de/journals

**Comment by fsteeg** [comment]
Feedback von I.N. 2024-01-23:

> Die Präposition "An" sortiert zusammen mit dem folgenden Substantiv wie ein Wort, obwohl ein Leerzeichen zwischen den Wörten steht: "An Bigge, Lenne und Fretter" usw.

Feedback von U.P. 2024-01-24:

> Könnten Sie uns denn eine Liste der Titel geben, die im Produktionssystem in der Liste enthalten sind, aber nicht im Testsystem?

**Comment by fsteeg** [comment]
> [...] "An Bigge, Lenne und Fretter" usw.

Stehen im Testsystem jetzt zusammen: https://test.nwbib.de/journals

**Comment by acka47** [comment]
> Möglicherweise ist der Ansatz korrekt, aber stolpert hier über unerwartete Dubletten? Konkret für dieses Beispiel in lobid-resources: [99370698631806441](https://lobid.org/resources/99370698631806441) und [990171221570206441](https://lobid.org/resources/990171221570206441). Brauchen wir dafür ev. ein Issue in lobid-resources?

Das hört sich ganz nach diesem Problem an, wofür wir z.B. schon #613 haben und auch https://github.com/hbz/lobid-resources/issues/1778 sowie eine komplette Wikiseite zur Analyse des Problems: https://service-wiki.hbz-nrw.de/x/ZwDsNg

Können ja gleich mal drüber reden, wie wir im konkreten Fall am besten damit umgehen.

**Comment by fsteeg** [comment]
Ich habe nochmal mit den Emails abgeglichen und das hier fehlte noch:

> 3) Der plattdeutsche Artikel `<<De>>` bei den beiden Zeitschriften `<<De>> Fitterkiste` und `<<De>> Rammuthe` sollte ebenfalls beim Sortieren übergangen [...] werden.
> 4) Die drei Punkte am Anfang der Zeitschrift "Bericht des Naturwissenschaftlichen Vereins für Bielefeld ..." sollten nicht angezeigt werden.

Im Testsystem umgesetzt: https://test.nwbib.de/journals

Damit ist in der neuen Liste soweit ich das sehe alles umgesetzt.

Offen ist noch die genauere Analyse der Unterschiede von alter und neuer Liste, ich weiss aber nicht ob das ein Blocker für das Deployment ist, die alte Liste ist ja als CSV in der history. Ich schreibe mal an die Liste.

**Comment by TobiasNx** [comment]
> Ich dachte erstmal, das liegt vielleicht an den Parallelausgaben, aber schon das erste Beispiel, ABU-Info, ist noch komischer: über die neue Query-basierte Liste bekommt man [990171221570206441](https://test.nwbib.de/990171221570206441), in der alten Liste stand [HT015679368](https://nwbib.de/HT015679368), beides ist die Online-Ausgabe. Die alte HT-Nummer geht in lobid-resources auf [99370698631806441](https://lobid.org/resources/99370698631806441) (auch Online-Ausgabe), was es aber [in der NWBib](https://nwbib.de/99370698631806441) nicht gibt.
> 
> Möglicherweise ist der Ansatz korrekt, aber stolpert hier über unerwartete Dubletten? Konkret für dieses Beispiel in lobid-resources: [99370698631806441](https://lobid.org/resources/99370698631806441) und [990171221570206441](https://lobid.org/resources/990171221570206441). Brauchen wir dafür ev. ein Issue in lobid-resources? So oder so: ist leider nicht ganz straight-forward, die Liste zu erstellen.

Das ist leider keine unerwartete Dublette.
**Die HT-Nummer und die zugehörige `deprecatedUrl`** kommt in beiden Einträgen vor, der redirect von lobid verweist aber NUR auf den CZ-Titel in lobid.:

CZ/Consors Titel, der in der NWBib ausgefiltert wird und keine nwbib subjects hat: https://lobid.org/resources/99370698631806441
```JSON
{
  "@context": "http://lobid.org/resources/context.jsonld",
  "almaMmsId": "99370698631806441",
  "urn": [
    "urn:nbn:de:hbz:6:2-69622"
  ],
  "oclcNumber": [
    "644257601"
  ],
  "dnbId": "990456757",
  "zdbId": "2451605-3",
  "deprecatedUri": "http://lobid.org/resources/HT015679368#!",
  "hbzId": "HT015679368",
  "title": "ABU-Info",
...
  "inCollection": [
    {
      "id": "http://lobid.org/resources/HT014846970#!",
      "label": "Zeitschriftendatenbank (ZDB)",
      "type": [
        "Collection"
      ]
    }
  ],
```

NZ/ZDB mit den inCollection-statements für hbz NZ, nwbib und nwbib-journals und nwbib subjects
```JSON
{
  "@context": "http://lobid.org/resources/context.jsonld",
  "almaMmsId": "990171221570206441",
  "urn": [
    "urn:nbn:de:hbz:6:2-69622"
  ],
  "oclcNumber": [
    "984935842"
  ],
  "zdbId": "2451605-3",
  "dnbId": "990456757",
  "deprecatedUri": "http://lobid.org/resources/HT015679368#!",
  "hbzId": "HT015679368",
  "title": "ABU-Info",
...
 "inCollection": [
    {
      "id": "http://lobid.org/organisations/DE-655#!",
      "label": "hbz - Hochschulbibliothekszentrum des Landes Nordrhein-Westfalen, Netzwerkzone",
      "type": [
        "Collection"
      ]
    },
    {
      "id": "http://lobid.org/resources/HT014846970#!",
      "label": "Zeitschriftendatenbank (ZDB)",
      "type": [
        "Collection"
      ]
    },
    {
      "id": "http://lobid.org/resources/HT016356466#!",
      "label": "Elektronische Zeitschriftenbibliothek (EZB)",
      "type": [
        "Collection"
      ]
    },
    {
      "id": "http://lobid.org/resources/HT014176012#!",
      "label": "Nordrhein-Westfälische Bibliographie (NWBib)",
      "type": [
        "Collection"
      ]
    },
    {
      "id": "https://nwbib.de/journals",
      "label": "Laufend ausgewertete NWBib-Zeitschriften",
      "type": [
        "Collection"
      ]
    }
  ],
```

Wir haben es hier mit einem Problem des Redirects von lobid.org zu tun!
