### ISSUE TITLE
Rückmeldungen aus der NWBib-Redaktion

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#614]
Gestern, am 8.5. um 17:20 hat I.N. verschiedene Punkte in einer E-Mail angeführt mit dem Betreff "NWBib-Zeitschriften, Suchschlitz-Recherche, Schlagwort-Anzeige". In #611 und #613 habe ich schonmal zwei Sachen ausgelagert. Für eine Umsetzung von Punkt 5.) aus der E-Mail ("Anzeige der Schlagwörter") müssen sich die NWBib-Redaktion erst absprechen und dann können wir ein Ticket anlegen. Die restlichen Punkte packe ich in dieses Ticket. Es scheint mir, dass si

- [x] Bei den laufend ausgewerteten NWBib-Zeitschriften werden die verknüpften Aufsätze noch nicht angezeigt und 
- [x] der Link zwischen den Parallelausgaben funktioniert noch nicht. 

> Hier einige Beispiele:
> https://nwbib.de/990209863170206441
> https://nwbib.de/990223805560206441

Recherche im  Suchschlitz bzw. Recherche über alle Felder funktioniert noch nicht:

- [x]  Keine Treffer wegen des Bindestriches: https://nwbib.de/search?location=&q=Erinnerungen+an+einen+%22Lump%22+und+%22Weltbegl%C3%BCcker%22+-+das+Peter-Hille-Haus+in+Erwitzen
- [ ] Bei Trunkierung mit * nur 2 Treffer: [https://nwbib.de/search?location=&q=M%C3%BCnster*](https://nwbib.de/search?location=&q=M%C3%BCnster*)

**Comment by fsteeg** [comment]
Die ersten drei Punkte habe ich behoben und auf Test deployed: [Periodikum 1](https://test.nwbib.de/990209863170206441), [Periodikum 2](https://test.nwbib.de/990223805560206441), [Bindestrich-Suche](https://test.nwbib.de/search?location=&q=Erinnerungen+an+einen+%22Lump%22+und+%22Weltbegl%C3%BCcker%22+-+das+Peter-Hille-Haus+in+Erwitzen).

Der vierte Punkt ist etwas unklar und offenbar eher ein Issue in lobid-resources (`word=` / [WordQuery](https://github.com/hbz/lobid-resources/blob/03536d9e66a7988675a20b599c92178912be714e/web/app/controllers/resources/Queries.java#L597)):

- in lobid-resources bekommen wir auch nur 67 Treffer für [word=Münster*](https://lobid.org/resources/search?word=M%C3%BCnster*), und in der Aleph-Instanz sogar [nichts](https://aleph.lobid.org/resources/search?word=M%C3%BCnster*), d.h. ich vermute das ging schon lange nicht (mehr?)
- die Trunkierung scheint generell nur für `keyword`-Felder zu funktionieren, z.B. nicht für [subject.label](https://lobid.org/resources/search?q=subject.label:M%C3%BCnster*), aber für [subject.label.raw](https://lobid.org/resources/search?q=subject.label.raw:M%C3%BCnster*) (was ev. den Aleph-Alma-Unterschied erklärt, weil da ev. neue Keyword-Felder dazugekommen sind)
- wir könnten die existierenden Felder `subject.label.raw` und `subject.componentList.label.raw` im [WordQuery](https://github.com/hbz/lobid-resources/blob/03536d9e66a7988675a20b599c92178912be714e/web/app/controllers/resources/Queries.java#L609) ergänzen, dann bekämen wir schonmal mehr Treffer. Das erwartete Verhalten, nämlich mehr als für [word=Münster](https://lobid.org/resources/search?word=M%C3%BCnster), wäre das aber nicht, da die meisten Felder eben offenbar keine Wildcards unterstützen

Zusammenfassend kann ich also nicht recht nachvollziehen warum Wildcards mal gingen, wir könnten das aber wohl unterstützen indem wir `keyword`-Unterfelder in der Index-Config definieren und die im WordQuery ergänzen (z.B. `title.raw`, etc., welche genau? es müssten dann wohl alle sein, in denen `word=` generell sucht). Wenn wir das wollen, sollten wir dazu wohl ein Issue in lobid-resources aufmachen.

(Ping @dr0i für den Fall dass ich hier irgendwas übersehe oder falsch verstehe).

**Comment by acka47** [comment]
+1

**Comment by acka47** [comment]
Meine Vermutung in Bezug der nicht funktionierenden Wildcards ist, dass hier eine Änderung (wegen der DigiBib?) im Hinblick auf die Behandlung von Umlauten hintersteckt. Ohne Umlaut funktionieren Wildcards, mit nicht, vgl.:

- https://lobid.org/resources/search?q=Munsterl* (10904 Treffer)
- https://lobid.org/resources/search?q=M%C3%BCnsterl* (0 Treffer)

@dr0i kann da wahrscheinlich mehr zu sagen.

**Comment by dr0i** [comment]
Didnt' analyze this, but noted that's the behaviour like before with Aleph: https://aleph.lobid.org/resources/search?q=M%C3%BCnsterl*.

**Comment by acka47** [comment]
Ok, my interpretation was wrong. Good to know.
