### ISSUE TITLE
Fehlende Volltext-Links

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#616]
On 11.05.23 13:37, I.N. wrote:
> Leider werden im Moment bei einigen Online-Zeitschriften und Online-Aufsätzen die Links zum Volltext (Alma-Feld 856) noch nicht angezeigt.
> 
> Hier einige Beispiele:
> https://nwbib.de/990209863170206441
> https://nwbib.de/990171539830206441
> https://nwbib.de/990171221570206441 (hier fehlen noch zwei weitere Links aus Feld 856 Unterfeld x: Resolving-System sowie Unterfeld x: EZB )
> 
> Bei den Aufsätzen aus diesen Zeitschriften wird der Link nicht angezeigt.
> https://nwbib.de/99372423770306441
> https://nwbib.de/99370718147006441
> 
> 
> Bei diesem Jahrbuch wird der Link angezeigt:
> https://nwbib.de/990366229600206441
> Bei einem Aufsatz aus diesen Jahrbuch wird der Link nicht angezeigt.
> https://nwbib.de/99371883990606441

**Comment by acka47** [comment]
Die Angaben fehlen derzeit in lobid, muss also da gelöst werden. Aus den MARC-Daten:

[990209863170206441](https://alma.lobid.org/marcxml/990209863170206441):
```xml
<datafield tag="856" ind1="4" ind2=" ">
` <subfield code="u">
http://journals.ub.uni-heidelberg.de/index.php/aiw/issue/archive
  </subfield>
  <subfield code="x">Verlag</subfield>
</datafield>
```

[990171539830206441](https://alma.lobid.org/marcxml/990171539830206441): 
```xml
<datafield tag="856" ind1="4" ind2=" ">
  <subfield code="u">
http://www.bibliothek.uni-regensburg.de/ezeit/?2458761
  </subfield>
  <subfield code="x">EZB</subfield>
</datafield>
```

[990171221570206441](https://alma.lobid.org/marcxml/990171221570206441):
```xml
<datafield tag="856" ind1="4" ind2="0">
  <subfield code="u">https://nbn-resolving.org/urn:nbn:de:hbz:6:2-69622</subfield>
  <subfield code="x">Resolving-System</subfield>
</datafield>
<datafield tag="856" ind1="4" ind2=" ">
  <subfield code="u">
https://www.abu-naturschutz.de/veroeffentlichungen/abu-info
  </subfield>
  <subfield code="x">Verlag</subfield>
  <subfield code="z">kostenfrei</subfield>
</datafield>
<datafield tag="856" ind1="4" ind2=" ">
  <subfield code="u">
http://www.bibliothek.uni-regensburg.de/ezeit/?2451605
</subfield>
  <subfield code="x">EZB</subfield>
</datafield>
```

**Comment by TobiasNx** [comment]
> Die Angaben fehlen derzeit in lobid, muss also da gelöst werden. Aus den MARC-Daten:
> 
> [990209863170206441](https://alma.lobid.org/marcxml/990209863170206441):
> 
> ```
> <datafield tag="856" ind1="4" ind2=" ">
> ` <subfield code="u">
> http://journals.ub.uni-heidelberg.de/index.php/aiw/issue/archive
>   </subfield>
>   <subfield code="x">Verlag</subfield>
> </datafield>
> ```

sollen auch verlagslinks gelistet werden, wenn diese nicht kostenfrei sind?  Siehe dazu auch: https://github.com/hbz/lobid-resources/issues/1044

**Comment by acka47** [comment]
https://github.com/hbz/lobid-resources/pull/1759 sieht erstmal gut aus. Das vollständige funktionale Review mache ich dann, wenn das deployt ist – sei es auf stage oder direkt production.

**Comment by TobiasNx** [comment]
Links zur EZB, werden mit 

Link:	[www.bibliothek.uni-regensburg.de](http://www.bibliothek.uni-regensburg.de/ezeit/?2840976) gelabelt

**Comment by acka47** [comment]
Das sieht gut aus, bis auf eine Sache, siehe https://nwbib.de/99371883990606441

Dort gibt es einen HT-Nummern-Link ohne Label, der nicht funktioniert:

![image](https://github.com/hbz/nwbib/assets/160292/d0cfe807-95f0-4a60-b7c8-f0b2015912f6)

Im lobid JSON sieht es wie folgt aus:

```json
"containedIn": [

        {
              "id": "http://lobid.org/resources/HT020430169#!",
              "label": "Grabbe-Jahrbuch"
        },
        {
              "id": "http://lobid.org/resources/ZDB-3016659-7#!",
              "label": "Grabbe-Jahrbuch"
        }

  ]
```

Am sinnvollsten wäre es, wenn die Transformation das erste Objekt mit `"id": "http://lobid.org/resources/HT020430169#!"` gar nicht uasgeben würde, oder?

**Comment by acka47** [comment]
Das in https://github.com/hbz/nwbib/issues/616#issuecomment-1557019983 genannte Problem ist nun behoben. Closing

**Comment by acka47** [comment]
Reopning after request from I.N. via NWbib mailing list.

On 01.06.23 15:53, I.N. wrote:
> bei den Aufsätzen aus dem Grabbe-Jahrbuch (letztes Beispiel) fehlen noch die Links, die direkt zum Repositorium der Lippischen Landesbibliothek führen:
> https://nbn-resolving.org/urn:nbn:de:hbz:51:1-18482 |x Resolving-System

This snippet from the [MARC source]() is not taken over to lobid:

```xml
<datafield tag="856" ind1="4" ind2="0">
  <subfield code="u">
https://nbn-resolving.org/urn:nbn:de:hbz:51:1-18482
  </subfield>
  <subfield code="x">Resolving-System</subfield>
</datafield>
```

nbn-resolving is handled in the fix but I assume there is something going wrong:

https://github.com/hbz/lobid-resources/blob/3b18e00b71fde18be933f875a4b55821268a60cb/src/main/resources/alma/fix/relatedRessourcesAndLinks.fix#L262-L299

**Comment by dr0i** [comment]
I think this is fixed. Can you confirm  @acka47 ? It's linked ok as :

> Online-Ressource:</dt>
Link |[nbn-resolving.de](https://nbn-resolving.de/urn:nbn:de:hbz:51:1-18482)

**Comment by acka47** [comment]
Yes, this is fixed. Closing
