### ISSUE TITLE
Fehlende Links auf Zeitschrift/Bestand

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#618]
Am 06.06.23 um 17:23 schrieb I.N.:
> Bei einigen Aufsätzen fehlt die Zeile „Bestandsangaben“
> 
> https://nwbib.de/990366703940206441

Siehe das alte Aleph-basierte lobid zum Vergleich: http://aleph.lobid.org/resources/HT020477469

**Comment by TobiasNx** [comment]
@acka47 Das könnte hiermit zusammenhängen: https://github.com/hbz/lobid-resources/issues/1865

**Comment by TobiasNx** [comment]
@acka47 und ich hatten rausgefunden, dass Artikel ja nicht mehr eindeutig in den ALMA Daten zu identifizieren sind. Zudem gibt es containedIn auch für nicht `article` wie Map, Report, etc.

Eine Möglichkeit wäre es:   `"bibliographicLevel.id"` = `"https://www.loc.gov/marc/bibliographic/bdleader.html#Monographic_component_part"` als Indikator einer Überordnung zu nehmen?

```
"bibliographicLevel": {
    "label": "Monographic component part",
    "id": ["https://www.loc.gov/marc/bibliographic/bdleader.html#Monographic_component_part"](https://www.loc.gov/marc/bibliographic/bdleader.html#Monographic_component_part)
  },
```

**Comment by acka47** [comment]
I.N. schob am 2023-09-11 noch ein paar Beispiele hinterher:

On 11.09.23 09:10, I.N. wrote:
> Lieber Herr Pohl,
> 
> bei einigen Aufsatz-Titelaufnahmen wird am rechten Rand nicht die Zeile 
> „Bestandsangaben“ angezeigt.
> 
> Bei Titelaufnahmen, die das Form-Schlagwort „Bericht“ enthalten, scheint 
> das Phänomen häufiger vorzukommen.
> 
> Hier einige Beispiele:
> 
> https://nwbib.de/99372715348206441 
>    (Überordnung mit Bestandsangaben, andere Aufsätze mit „Bestandsangaben“)
> 
> https://nwbib.de/99372918320206441
>    (Überordnung mit Bestandsangaben, andere Aufsätze mit „Bestandsangaben“)
> 
> https://nwbib.de/990366703940206441 
>  (Überordnung in eine Online-Zeitschrift, andere Aufsätze mit Anzeige „Bestandsangaben“)

Dann noch diese Anmerkung, die ich nicht verstehe, vor allem auch, weil ein Beispiel fehlt:

> Anmerkung:  Beim Form-Schlagwort (Alma-Feld 655) wird nicht zwischen dem 
> Form-Schlagwort „Erfahrungsbericht“ (GND-ID 4133254-4) und dem 
> Form-Schlagwort „Bericht“ (GND-ID 4128022-2) unterschieden. Beide werden 
> mit dem Buchstaben „i“ als Bericht wiedergegeben. Vielleicht könnte man 
> das bei Gelegenheit noch ändern?

**Comment by acka47** [comment]
> Aktuell werden die Bestandsangaben der Überordnung nur bei Article angezeigt ([src](https://github.com/hbz/nwbib/blob/9e8d17b5216fb7b3be010fc61a0caec790a1504b/app/views/details.scala.html#L63)).

Was spricht dagegen, das zu ändern und bei allen `containedIn` die Bestandsangaben der Überordnung anzuzeigen?

> @acka47 und ich hatten rausgefunden, dass Artikel ja nicht mehr eindeutig in den ALMA Daten zu identifizieren sind. Zudem gibt es containedIn auch für nicht article wie Map, Report, etc.

Das unterstützt den genannten Ansatz denke ich.

> Eine Möglichkeit wäre es: "bibliographicLevel.id" = "https://www.loc.gov/marc/bibliographic/bdleader.html#Monographic_component_part" als Indikator einer Überordnung zu nehmen?

Ich verstehe nicht, was das mit diesem Ticket zu tun hat. Für die Anzeige der Bestandsangaben brauchen wir doch lediglich die `containedIn`-Information, oder nicht?

**Comment by fsteeg** [comment]
> Was spricht dagegen, das zu ändern und bei allen `containedIn` die Bestandsangaben der Überordnung anzuzeigen?

Weiss ich auch nicht, die Einschränkung war offenbar von Anfang an drin (s. https://github.com/hbz/nwbib/commit/a10d822). Und es geht ja auch nicht um die eigentlichen Bestandsangaben der Überordnung, sondern den Link zur Überordnung im Bereich rechts (statt nur über das `In`-Feld), so ist es ja auch im verlinkten Aleph-Beispiel: http://aleph.lobid.org/resources/HT020477469.

Habe es ohne `type`-Einschränkung auf Test deployed.

Beispiele, bei denen die `containedIn`-Verlinkung bei den Bestandsangaben fehlte:

https://test.nwbib.de/99372715348206441
https://test.nwbib.de/99372918320206441
https://test.nwbib.de/990366703940206441

Hier käme die `containedIn`-Verlinkung bei den Bestandsangaben dazu:

https://test.nwbib.de/search?q=containedIn:*+AND+NOT+type:Article

**Comment by acka47** [comment]
+1
