### ISSUE TITLE
Fehlerhafte Integrationtest und alte lobid-Abfragen mit @graph

### ISSUE THREAD

**Issue by TobiasNx** [hbz/nwbib#622]
Diese erzeugen Errormeldungen in den Logs von Lobid-Resources:

https://github.com/hbz/nwbib/blob/b3e5960800244176dd960727ca2d2c5ec9362afb/test/tests/ExternalIntegrationTest.java#L84-L104

https://github.com/hbz/nwbib/blob/b3e5960800244176dd960727ca2d2c5ec9362afb/app/controllers/nwbib/Classification.java#L237-L238
https://github.com/hbz/nwbib/blob/b3e5960800244176dd960727ca2d2c5ec9362afb/app/views/TableRow.java#L184-L185
https://github.com/hbz/nwbib/blob/b3e5960800244176dd960727ca2d2c5ec9362afb/app/views/tags/result_short.scala.html#L21-L22

Auch gibt es multiVolumeWork nicht mehr in lobid.

**Comment by dr0i** [comment]
Both issues (`@graph` and `multiVolumeWork`) are solved. Closing.
