### ISSUE TITLE
NWBib-Zugriffstatistik

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#625]
On 18.08.23 09:06, U.P. wrote:
>  Können Sie schon sagen, 
> welche Möglichkeiten wir oder Sie im hbz haben werden, für das Jahr 2023 
> statistische Daten zu erheben? Könnten Sie auch die Möglichkeit prüfen, 
> dass wir selbst vielleicht monatlich Daten erheben könnten?
> 
> Interessant wären für uns in Düsseldorf zumindest folgende Erhebungen, 
> weil wir das in ähnlicher Weise auch für andere Portale bei uns im Haus 
> so machen:
> 
> -Zahl der Zugriffe: die Anzahl der Abrufe einer einzelnen Webseite mit 
> einem Webbrowser
> 
> -Zahl der Besuche: die Anzahl der Sessions bzw. mehrere /page views /von 
> der gleichen IP mit mindestens 2 Seitenzugriffen
> 
> Ich vermute mal, die Erhebung von Weiterleitungen der Nutzer vom 
> NWBib-Portal auf die E-Pflicht-Portale (oder Digitalen Sammlungen) der 
> drei Landesbibliotheken durch Klicken auf die URN in der Titelaufnahme 
> durch die Nutzer ist nicht möglich, oder? Es wäre ja schon auch 
> interessant zu erfahren, ob die Nutzung der E-Pflicht-Portale durch das 
> NWBib-Portal bedeutend erhöht wird.

**Comment by dr0i** [comment]
Das nächste Admin-Treffen ist am 1. September , Freitag 9:00. Einladung ist raus.

**Comment by acka47** [comment]
Implementiert wird das mit GoAccess und es ist auch schon recht weit fortgeschritten, siehe https://github.com/hbz/lobid/issues/512.

**Comment by acka47** [comment]
Mail an Liste ging raus, NWBib-Redaktion ist zufrieden. Closing.
