### ISSUE TITLE
Informationen zu Parallelausgaben mit ISBN anzeigen

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#636]
Auslöser dieses Tickets ist diese E-Mail and die nwbib-Liste von I.N.:

On 28.12.23 13:23, I.N. wrote:
> immer mehr Publikationen erscheinen als Print- und als Online-Ausgabe, 
> aber nicht alle Parallelausgaben (insbesondere EBA’s) können erworben 
> werden. Da wir unsere Nutzer und Nutzerinnen möglichst umfänglich 
> informieren möchten, thematisieren wir nochmal die Anzeige der Fußnoten 
> für Parallelausgaben im *Alma Feld 776, Unterfeld i Erscheint auch als, 
> Unterfeld n Online-Ausgabe ….*
> 
> Seit einiger Zeit werden die Fußnoten der Parallelausgaben anzeigt und 
> verlinkt, wenn es für beide Parallelausgaben Titelaufnahmen gibt, die 
> miteinander durch eine ID-Nr. im Unterfeld w (DE-605)HT…. in Beziehung 
> gesetzt wurden.
> 
> Hier ein Beispiel:
> 
> https://nwbib.de/HT020665576
> 
> In sehr vielen Fällen existiert aber nur eine einzige Titelaufnahme in 
> der Alma NZ. Folglich gibt es in Feld 776 kein Unterfeld w. Sehr häufig 
> ist aber das Unterfeld z mit der ISBN der Parallelausgabe vorhanden. Mit 
> dieser ISBN können die Nutzer in Bibliothekskatalogen oder im Netz nach 
> der Parallelausgabe recherchieren. Das Feld 776 ist ja in lobid 
> vorhanden (s. XML-Format und JSON-Feld related), wird aber z.Z. in der 
> Kategorie ISBN angezeigt. Hier würde man eigentlich die ISBN der 
> vorliegenden Ausgabe aus Feld 020 erwarten. Daher die Frage: Könnten Sie 
> die Fußnote aus Feld 776 anzeigen lassen? Oder, falls man auf die 
> Anzeige der ISBN aus Feld 020 verzichten möchte, könnte man vielleicht 
> die Kategorie ISBN umbenennen in „ISBN andere Ausgabe(n)“.
> 
> Hier einige Beispiel:
> 
> https://nwbib.de/99372715276006441
> (Hier gibt es zwei weitere Ausgaben, PDF und EPUB)
> 
> https://nwbib.de/99373311675806441 
> 
> https://nwbib.de/990191290020206441 
>  (Für Nutzer mit einem 
> Bibliotheksausweis ist die Parallelausgabe (EBA) via ULB-OPAC im 
> Volltext bis 31.12.2026 verfügbar).

~~N.B., diese in der E-Mail enthaltene Aussage ist nicht korrekt. Wahrscheinlich entstand der Irrtum, weil wir immer ISBN10 und ISBN13 generieren und auch anzeigen:~~

> ~~Das Feld 776 ist ja in lobid 
> vorhanden (s. XML-Format und JSON-Feld related), wird aber z.Z. in der 
> Kategorie ISBN angezeigt. Hier würde man eigentlich die ISBN der 
> vorliegenden Ausgabe aus Feld 020 erwarten.~~ (Edit wegen Falschaussage)

Wir haben also bereits alles korrekt in den Daten, inklusive der Informationen zu den Parallelausgaben, wir müssen sie nur noch korrekt anzeigen ([Beispiel 99372715276006441](http://lobid.org/resources/99372715276006441.json)): 

```json
"related": [

        {
              "note": [
                    "Online-Ausgabe (EPUB, Mobi)"
              ],
              "isbn": [
                    "9783969052389",
                    "3969052386"
              ]
        },
        {
              "note": [
                    "Online-Ausgabe (PDF)"
              ],
              "isbn": [
                    "9783969052396",
                    "3969052394"
              ]
        }

  ]
```

**Comment by acka47** [comment]
> N.B., diese in der E-Mail enthaltene Aussage ist nicht korrekt. Wahrscheinlich entstand der Irrtum, weil wir immer ISBN10 und ISBN13 generieren und auch anzeigen:
>> Das Feld 776 ist ja in lobid
    vorhanden (s. XML-Format und JSON-Feld related), wird aber z.Z. in der
    Kategorie ISBN angezeigt. Hier würde man eigentlich die ISBN der
    vorliegenden Ausgabe aus Feld 020 erwarten.

Nein, *meine* Aussage war nicht korrekt. In der Anzeige wird tatsächlich die ISBN der Parallelausgabe angezeigt. Das oben genannte Beispiel zeigt im UI die ISBN der Parallelausgabe unter "ISBN" an, siehe https://nwbib.de/99372715276006441 :

![image](https://github.com/hbz/nwbib/assets/160292/9675aac5-9f18-4c0f-98e1-1c8c200eb95d)

Hier die eigentlich anzuzeigende ISBN:

```json
"isbn": [

        "9783969052372",
        "3969052378"

  ],
```

**Comment by acka47** [comment]
> Nein, meine Aussage war nicht korrekt. In der Anzeige wird tatsächlich die ISBN der Parallelausgabe angezeigt. 

Es gibt dazu auch bereits ein lobid-resources-Ticket, weil im dortigen UI dasselbe Problem besteht: https://github.com/hbz/lobid-resources/issues/1951

**Comment by fsteeg** [comment]
Auf Test deployed.

Hier das Beispiel von oben, mehrere `related`, ohne `id`. Hier werden jetzt für den Titel selbst die korrekten ISBNs angezeigt, und dazu die Parallelausgaben (die hier vorher gar nicht auftauchten) mit ihren ISBNs:

https://test.nwbib.de/99372715276006441

Hier ein Beispiel, wo auch vorher eine Parallelausgabe erschien (hat `related.id`):

https://test.nwbib.de/HT020665576

**Comment by acka47** [comment]
Bei der Parallelausgabe steht nicht dabei, dass es sich bei der Nummer um eine ISBN handelt. Bin mir unsicher, oib wir das nicht erwähnen sollten, bevor wir es deployen. Können es aber auch erstmal so machen und das Feedback der Redaktion abwarten.

**Comment by fsteeg** [comment]
> Bei der Parallelausgabe steht nicht dabei, dass es sich bei der Nummer um eine ISBN handelt.

Auf Test ergänzt: https://test.nwbib.de/99372715276006441

**Comment by acka47** [comment]
+1
