### ISSUE TITLE
Map-Marker laden nicht

### ISSUE THREAD

**Issue by fsteeg** [hbz/nwbib#637]
s. z.B. https://nwbib.de/HT002161484

**Comment by fsteeg** [comment]
Die alten Marker kamen aus Mapbox, was inzwischen einen Account erfordert. 

Habe das Icon durch ein lokales Icon ersetzt. Auf Test deployed, s. z.B.:

https://test.nwbib.de/HT002161484

**Comment by acka47** [comment]
Ich würde für ein einfacheres Marker-Icon plädieren, so in der Art:

![image](https://github.com/hbz/nwbib/assets/160292/ad8d4f30-2d4d-487d-8e8a-bb9d2137ff98)

Die Karte ist ja schon unruhig genug, z.B. durch die physische Ansicht, die weiße Hinterlegung von Schrift.

**Comment by fsteeg** [comment]
Neue Marker auf Test (und Zoom-Level eins tiefer beim Klick):

https://test.nwbib.de/HT002161484

**Comment by acka47** [comment]
+1
