### ISSUE TITLE
Suche mit ALMA-MMS Id nicht möglich

### ISSUE THREAD

**Issue by TobiasNx** [hbz/nwbib#651]
https://nwbib.de/search?location=&q=99373223572006441

gibt keinen Treffer zurück:
https://nwbib.de/99373223572006441

**Comment by fsteeg** [comment]
Ist inkonsistent, aber was funktioniert ist eine explizite Feldsuche:

https://nwbib.de/search?q=almaMmsId:99373223572006441

**Comment by acka47** [comment]
Jetzt geht es: https://nwbib.de/search?q=99373223572006441 Wurde wahrscheinlich mit https://github.com/hbz/lobid-resources/issues/2085 gelöst. Closing.
