### ISSUE TITLE
Link zur Landesbibliotheken-Seite aktualisieren, Logo ergänzen

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#652]
Am 05.09.24 um 09:44 schrieb @HMetzner:

> die Landesbibliotheken NRW haben eine neue Homepage erhalten: 
> https://www.landesbibliotheken.nrw/ . Daher müsste ein Link angepasst 
> werden und wir würden gerne das Logo der LB einbauen.
> 
> Kannst du diesen Link bitte dort einbauen, wo bisher auf die alte Seite 
> der LB verlinkt wurde (s. Screenshot)? Der Linktext sollte dann heißen 
> „Über die Landesbibliotheken“.
> 
> Mit den neuen Seiten der LB ging auch einher ein gemeinsames Logo zu 
> entwickeln, um die Produkte der LB auszuweisen. Das Logo würden wir 
> gerne unten auf der Startseite der NWBib präsentieren (s. Anhang).
> 
> Da ist die Frage, ob man es unten mittig unter den Kasten oder in den 
> Kasten einbauen kann (inkl. Verlinkung auf die Startseite 
> https://www.landesbibliotheken.nrw/ 
> <https://www.landesbibliotheken.nrw/>)? Mock-up siehe Anhang.

![Logo_LB_NWBib_Entwurf](https://github.com/user-attachments/assets/a8e04541-8f61-4e26-8536-09efcb023970)

![Landesbibliotheken_NRW](https://github.com/user-attachments/assets/421a038c-89b5-4494-a68b-b445a8c6a312)

**Comment by acka47** [comment]
Mein Vorschlag wäre:

- Das NRW-Wappen unten aus dem Kasten entfernen, es ist ja schon oben rechts sehr exponiert.
- Landesbibliotheken-NRW-Logo in den Kasten unter den Text und daneben das hbz Logo (ansttat wie jetzt rechts neben dem Text.

Wenn du Zeit hast, kannst du das gerne mal auf Test umsetzen, @fsteeg , und wir geben es zur Diskussion in die Mailingliste zurück.

**Comment by fsteeg** [comment]
Auf dem Testsystem: https://test.nwbib.de

**Comment by HMetzner** [comment]
Lieber Fabian, vielen Dank! Kann man die Logos LB & hbz so groß machen, wie die Schrift im Kasten? Das wäre schön. Ansonsten sind die Logos dort doch gut aufgehoben. :) Lieben Gruß, Hannah

**Comment by acka47** [comment]
Ich hatte gedacht, die Logos in den Kasten zu packen. Hast du das auch ausprobiert,  @fsteeg ?

**Comment by fsteeg** [comment]
> Kann man die Logos LB & hbz so groß machen, wie die Schrift im Kasten?

> Ich hatte gedacht, die Logos in den Kasten zu packen. Hast du das auch ausprobiert

Ja, im Kasten sah es nicht so gut aus fand ich, und in größer wird es durch den fetten Text schnell sehr dominant.

Hier zum Vergleich in größer, ausserhalb des Kastens:

![logos-groesser](https://github.com/user-attachments/assets/6964a86d-ab52-4225-9a7c-b1e2ebba1fff)

Und die kleinere Größe, aber innerhalb des Kastens:

![im-kasten](https://github.com/user-attachments/assets/3e0c7bac-f2f2-405a-a8d5-a773154168bd)

**Comment by HMetzner** [comment]
Das größere ist ausgewogen mit dem Gesamtlayout, denke ich. Daher wäre es mir lieb, wenn es die "große" Variante wird. Dann gerne innerhalb des Kastens. Da stimme ich @acka47 zu. VG

**Comment by acka47** [comment]
Groß finde ich auch ok und würde auch gerne noch die Variante "groß im Kasten" sehen.

**Comment by fsteeg** [comment]
Groß im Kasten:

![gross-im-kasten](https://github.com/user-attachments/assets/f1374002-2c2e-495d-83d3-02aba62c4f14)

**Comment by fsteeg** [comment]
Vielleicht wäre auch der ursprüngliche Vorschlag besser? Mit den kleinen Logos an den Seiten, und unten nur das neue?

**Comment by HMetzner** [comment]
Nach kurzer Absprache mit Andrea Ammendola ist unser Favorit "groß, außerhalb des Kastens". Dann ist es im Kasten übersichtlicher und die Logos sind abgesetzt vom Kasten.
Kann man die Logos ein Stück weiter auseinanderziehen?

**Comment by fsteeg** [comment]
Hier die Variante mit den kleinen Logos wie bisher und dem neuen mittig:

![mit-kleinen-logos](https://github.com/user-attachments/assets/6dc3b182-cb92-4c32-9497-0110c54f729d)

**Comment by HMetzner** [comment]
Vielen Dank! Das sieht gut aus.
