### ISSUE TITLE
Show labels for "700n = 96|97|99"

### ISSUE THREAD

**Issue by dr0i** [hbz/nwbib#66]
See also #17 and #53.

It [is agreed](https://wiki1.hbz-nrw.de/display/SEM/NWBib-Treffen+10.9.2014) to show the labels for the literals denoting spatial areas (field 700, ... 99). As agreed with @fsteeg , the easiest (and most correct way) is to use what was originally catalogued - not what was somehow heuristically generated by linking to OSM. 
Fall back to @acka47's mention of taking `dc:coverage` as property to do this, see #17.

**Comment by fsteeg** [comment]
If my understanding from re-reading this issue is correct, the remaining work is a data issue with the automatic addition of "Kreis", so I'm assigning this to @dr0i and moving to `ready`.

**Comment by dr0i** [comment]
Deployed to staging.

**Comment by dr0i** [comment]
(Interesting. Some samples shows indeed: now getting more data as before.)

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Deployed to production, closing.
