### ISSUE TITLE
Add query links to literal values from Raumsystematik

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#72]
We have a lot of literal values from 700n=96|97|99 in `lv:nwbibspatial`, see https://github.com/hbz/nwbib/issues/53, https://github.com/hbz/nwbib/issues/17 and https://github.com/hbz/nwbib/issues/66. 

In the NWBib HTML, we should add to each label an underlying query link that GETs a list of all resources with the place as spatial subject.
Example: "Hilden" in http://lobid.org/nwbib/BT000084171 should point to http://lobid.org/nwbib/search?nwbibspatial=Hilden.

See also https://github.com/hbz/nwbib/issues/66#issuecomment-58899917.

**Comment by fsteeg** [comment]
Deployed to staging: http://test.lobid.org/nwbib/BT000084171

**Comment by acka47** [comment]
+1
