### ISSUE TITLE
Link to superordinated resource for holdings

### ISSUE THREAD

**Issue by fsteeg** [hbz/nwbib#76]
"Zum Bestand siehe Überordnung"

**Comment by acka47** [comment]
Can't find this in the current version. The corresponding commit is https://github.com/hbz/nwbib/commit/a10d822c36e52e9131d367c3f0011947198321d1.

**Comment by fsteeg** [comment]
I think this is due to the API change of moving `http://lobid.org/resource/NWBib` from `isPartOf` to `collectedBy`. If I remember correctly we decided to retain it in `isPartOf`, and only *add* it in `collectedBy` (to avoid this kind of issues). I'd prefer that fix. The other option would be to change the condition for `superordination` in [this line](https://github.com/hbz/nwbib/blob/master/app/views/details.scala.html#L19), but other places may well depend on that API too.

Existing sample: http://lobid.org/resource?id=HT018286356&format=full

**Comment by acka47** [comment]
> If I remember correctly we decided to retain it in `isPartOf`, and only *add* it in `collectedBy` (to avoid this kind of issues). 

Re-reading https://github.com/lobid/lodmill/issues/359 I'd say we didn't decide to retain `isPartOf` and we in fact didn't do it. Also, I think that having both links would create problems elsewhere. Thus, someone will have to fix https://github.com/hbz/nwbib/blob/master/app/views/details.scala.html#L19. Assigning to @dr0i – but perhaps @fsteeg will do it as he is obviously taking a look at GitHub now and then. :wave:

**Comment by fsteeg** [comment]
Even if we didn't decide to retain it, I think this issue (if my assumption about its cause is even correct) shows that we should have. It's an API change that breaks client applications, as it did here for our own. We can't do these kind of changes and claim to be stable and compatible. I'm aware we did this before, but we should learn from it and don't make these kind of changes (at least for the future version 2 API).

As for applying the change, while I can access GitHub, I can't test the fix so that wouldn't make sense.

**Comment by acka47** [comment]
You are right that this breaks our application. But the other API user who relies on links to a collection (edoweb) actually made the feature request and seems to be happy with our change. (Maybe another change would break their application...) As I am quite sure that nobody else relies on it, we can leave it this way. I totally agree with you that we shouldn't make this kind of changes in API 2.0.

Assigning to @dr0i as he is able to test the fix.

**Comment by acka47** [comment]
Please only write "Zum Bestand: {title of superordinated resource}. Customer feedback, see https://wiki1.hbz-nrw.de/pages/diffpagesbyversion.action?pageId=42401798&selectedPageVersions=60&selectedPageVersions=59

**Comment by dr0i** [comment]
Deployed to staging.

**Comment by dr0i** [comment]
(Note: this issue has nothing to do with `collectedBy`)

**Comment by dr0i** [comment]
You can test with e.g. http://test.lobid.org/nwbib/HT018286356.

**Comment by fsteeg** [comment]
I think the empty first column looks odd. Also `Zum Bestand` suggests the links go to the `Bestand`, not to the superordinated resource. How about `Zum Bestand siehe:` as the caption, and `Überordnung` as the labels in the first column?

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
I seem to remember that when we chatted about this recently, you both liked my suggestion.

I really think the indented variant with an empty first column that's now being deployed looks broken.

**Comment by acka47** [comment]
@fsteeg I can't recall the details of your suggestion. Can you say it again?

**Comment by fsteeg** [comment]
@acka47 What I described in https://github.com/hbz/nwbib/issues/76#issuecomment-72364481.

**Comment by dr0i** [comment]
@fsteeg We should better wait upon customer feedback for now, as we agreed once.

**Comment by dr0i** [comment]
Deployed to production, closing.

**Comment by fsteeg** [comment]
I'm not so happy with how we're handling this issue. Originally this is a regression of a feature that was already deployed to production. But then we mixed two things that I think we should instead handle separately:

1. Fix the issue that breaks a deployed feature with highest priority
2. Implement and review the label change requested by stakeholders

I think this would give both us and them a valid baseline for comparison: the working old way vs the working new way. Instead the option was: the feature is gone vs the feature is there. Given that option I understand your desire to deploy and resolve without any discussion.

But I think the solution that's now in production is both hard to understand (https://github.com/hbz/nwbib/issues/76#issuecomment-72364481) and visually inconsistent (https://github.com/hbz/nwbib/issues/76#issuecomment-75316711). To check if it's just me I did a quick usability test on http://lobid.org/nwbib/HT018286356 with our number one usability tester Linda :-) and asked her what the thing above the map is about, and she assumed that that's where you can get the resource ("Wos das gibt") — 'Zum Bestand' eben.

And even if we really want (or must have) "Zum Bestand: Kreis Unna", it has to be in one row, which is obvious for me from the request mentioned in https://github.com/hbz/nwbib/issues/76#issuecomment-71667063.

So here's what I'd suggest: we revert to just the fix in production, then deploy a one-row solution for "Zum Bestand: Kreis Unna" to test, and make that available to stakeholders, with feedback about the potential — no, scientifically proven ;-) semantic issue.

**Comment by acka47** [comment]
I am Ok with writing it in one row with "Zum Bestand siehe:" and can only agree with @fsteeg that this would be a better solution.

**Comment by fsteeg** [comment]
Deployed to staging, with "Zum Bestand siehe:" and the superordination title in one row, using "Bestandsangaben" as the caption if the resource has no items itself, and "Ergänzende Bestandsangaben" if it does. See:

http://test.lobid.org/nwbib/HT018689626
http://test.lobid.org/nwbib/HT018286356

**Comment by acka47** [comment]
> Deployed to staging, with "Zum Bestand siehe:" and the superordination title in one row, using "Bestandsangaben" as the caption if the resource has no items itself, and "Ergänzende Bestandsangaben" if it does

We should always write "Bestandsangaben" and never "Ergänzende Bestandsangaben". As the example shows this holding information is the result of incorrect cataloging, just take a look at the "call number" (Signatur).

**Comment by acka47** [comment]
> Deployed to staging, with "Zum Bestand siehe:" and the superordination title in one row, using "Bestandsangaben" as the caption if the resource has no items itself, and "Ergänzende Bestandsangaben" if it does

We should always write "Bestandsangaben" and never "Ergänzende Bestandsangaben". As the example shows this holding information is the result of incorrect cataloging, just take a look at the "call number" (Signatur).

**Comment by fsteeg** [comment]
Deployed fix to staging, see:

http://test.lobid.org/nwbib/HT018689626
http://test.lobid.org/nwbib/HT018286356

**Comment by acka47** [comment]
+1
