### ISSUE TITLE
Missing owner details

### ISSUE THREAD

**Issue by fsteeg** [hbz/nwbib#77]
Some owners (Untersigel) are not present in our organisations data.

Two appoaches possible:
- Add missing owners (we did that for some)
- Subsume the owners under their main Sigel

**Comment by acka47** [comment]
Not all hbz-internal sub"sigels" will be added to the official Sigelverzeichnis. We will thus have to implement a solution to not present these pseudo sigels/ISILs in lobid.

@dr0i suggested a solution that seems to be very sensible:
- Implement the solution on the metafacture/data transformation level.
- Check all appearing sub-sigels, i.e. ISILs of the form `DE-[0-9]{1,4}\w{0,1}-[0-9]{0,3}\w{0,3}` against a list of all official ISIls.
If these don't exist as official ISILs remove the part beginning with the last dash: DE-[0-9]{1,4}\w{0,1}~~-[0-9]{0,3}\w{0,3}~~
