### ISSUE TITLE
Improve automatic mapping of NWBib classification to wikidata

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#83]
See these comments:
- https://github.com/hbz/nwbib/issues/42#issuecomment-63775578: 47,357 resources with 700_96|97|99 aren't linked to wikidata yet.
- An incorrect mapping is documented at: https://github.com/hbz/nwbib/issues/42#issuecomment-63790251

**Comment by acka47** [comment]
After having improved the wikidata linking we will send a list of locations by district (Landkreis) to NWBib editors as well as a list of locations not linked to wikidata.

**Comment by acka47** [comment]
We might also take a look at the Getty Thesaurus of Geographic Names (TGN) for getting geo coordinates. It includes more than 15k places in North Rhine-Westphalia, see http://www.getty.edu/vow/TGNHierarchy?find=&place=&nation=&english=Y&subjectid=7003677. A lot of them have geo coordinates – at least the one I looked into. On the [TGN about page](http://www.getty.edu/research/tools/vocabularies/tgn/about.html) it reads (my emphasis):

> The TGN is not currently linked to maps, although the coordinates should allow users to find the places on a map. TGN is not a GIS. **While many records in TGN include coordinates, these coordinates are approximate and are intended for reference ("finding purposes") only.** TGN is intended to aid cataloging, research, and discovery of art historical, archaeological, and other scholarly information. However, its unique thesaural structure and emphasis on historical places make it useful for other disciplines in the broader Linked Open Data cloud. For GIS information, TGN may be linked to existing major, general-purpose, geographic databases.

**Comment by acka47** [comment]
@dr0i Please ignore my coment above and this one I just wanted to document this somewhere. It looks like the wikidata geo coordinates might probably be better than TGN. 
- Example Burgoldinghausen:
[wikidata](https://www.openstreetmap.org/?mlat=51.0158&mlon=7.98056&zoom=11#map=15/51.0148/7.9803) vs. [TGN](https://www.openstreetmap.org/?mlat=51.0167&mlon=7.9833&zoom=11#map=17/51.01580/7.98060)
- Example Rötzum: [TGN](https://www.openstreetmap.org/?mlat=52.2833&mlon=10.0667#map=15/52.2833/10.0667) vs. not existing

**Comment by acka47** [comment]
UP suggested on 2015-10-16:

> Zum Schluss möchte ich noch auf den Fall hinweisen, dass bei der Suche mit Wandern und anschl. Zoomen auf Düsseldorf ein Titel nicht gefunden wurde (HT018613966  , Ab ins Grüne),  vermutlich weil in der Raumnotation "99; Düsseldorf, Region" noch ein Komma direkt an den Ort anschließt. Könnte man die Orte in den Raumnotationen vielleicht auch grundsätzlich  trunkiert auswerten?

**Comment by philboeselager** [comment]
@dr0i 
A) Can you please provide an example of the data format used in NWBib?
B) Which fields will be used? Only latitude and longitude?
C) Is it feasible to pull these field's data via single requests?

**Comment by dr0i** [comment]
A) see e.g. http://lobid.org/resource/BT000084171/about 
B) -> `subjectLocation` and `spatial`
C) You mean: one record, one request? Yeah thats the way to go. I did this using the SQL lookup function in metafacture, wich uses JDBC. If you make elasticsearch lookups , that should be fast enough, as long as you don't make these lookups via http of course. Shouldn't be too slow (lookups you need: > 300k ).

**Comment by fsteeg** [comment]
Based on https://github.com/hbz/geodata/issues/21, I think the next step is that @dr0i should test switching the way the locations are looked up during transformation, to see if this is already an improvement.

**Comment by acka47** [comment]
Also, the response doesn't look correct for the entries we need an imporvement for: part sof a town like "Köln-Ehrenfeld". [Köln](http://gaia.hbz-nrw.de:7400/geodata?q=K%C3%B6ln) ([wikidata entity](http://www.wikidata.org/entity/Q365)), [Köln-Ehrenfeld](http://gaia.hbz-nrw.de:7400/geodata?q=K%C3%B6ln-Ehrenfeld) ([wikidata entity](http://www.wikidata.org/entity/Q897382)), and [Köln-Mülheim](http://gaia.hbz-nrw.de:7400/geodata?q=K%C3%B6ln-Mülheim) ([wikidata entity](http://www.wikidata.org/entity/Q327896)) all deliver the same geo coordinates though they have different ones in wikidata.

**Comment by acka47** [comment]
Is the query template I provided in https://github.com/hbz/nwbib/issues/83#issuecomment-65620502 actually used here: `https://www.wikidata.org/w/api.php?action=query&list=search&format=json&srsearch=$place_name` ?

**Comment by acka47** [comment]
> Based on https://github.com/hbz/geodata/issues/21, I think the next step is that @dr0i should test switching the way the locations are looked up during transformation, to see if this is already an improvement.

@droi can go for this now.

**Comment by acka47** [comment]
Unassigning @dr0i because he has a lot of other stuff to do until his parental leave. @fsteeg, can you take care of this,?

**Comment by fsteeg** [comment]
This is actually a `lobid-resources` issue, data 2.0 contains no locations yet.

**Comment by acka47** [comment]
> Here is an example query on how to lookup compound names via the wikidata API:

> https://www.wikidata.org/w/api.php?action=query&list=search&format=json&srsearch=Schmallenberg-Westernb%C3%B6defeld

This doesn't work as expected anymore. We will have to take a look into at it.

**Comment by acka47** [comment]
ping @SBRitter. this is relevant for hbz/geodata rework. See also https://github.com/hbz/nwbib/wiki/Raumnotationen-und-Ortsangaben#probleme

**Comment by fsteeg** [comment]
Since we'll implement a new location lookup for 2.0 (https://github.com/hbz/lobid-resources/issues/130) I think we can close this.

**Comment by acka47** [comment]
Ok, closing.
