### ISSUE TITLE
For anthologies, add link to list of included articles

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#89]
If in NWBib existant we should have a link to articles included in an anthology labeled "Enthaltene Beiträge anzeigen".

Example: http://test.lobid.org/nwbib/HT018295975

This should be implmented analoguous to journals, see e.g. http://test.lobid.org/nwbib/HT006919326.

(Note: A special case are multivolume works where currently all parts are listed within the description of the work, see e.g. http://lobid.org/nwbib/HT018138615.)

**Comment by acka47** [comment]
Customers also asked for adjusting the links from multivolume works to subordinated resources to the pattern for journals and – to be implemented – for anthologies. This would be good for us, to only have one pattern. So we might just implement it for all resources that actually have at least one other resoruce pointing at it with `isPartOf`.

**Comment by acka47** [comment]
As we don't have any type information about anthologies we should at this first, see lobid/lodmill#271. After this, we will just have to add the type to https://github.com/hbz/nwbib/blob/3041f0c1fab1ac598a290533c130262ff9bb4995/app/views/tags/result_doc.scala.html#L88 and everything is fine.

**Comment by dr0i** [comment]
Deployed to staging. (Can't say that it works, though).

**Comment by acka47** [comment]
It works, see http://test.lobid.org/nwbib/HT003873178 or http://test.lobid.org/nwbib/HT004489607 compared to http://lobid.org/nwbib/HT003873178 and http://lobid.org/nwbib/HT004489607.

The problem with the test resource provided in the issue description – http://test.lobid.org/nwbib/HT018295975 – is that it isn't typed as `EditedVolume` although the [source](http://test.lobid.org/resource?id=HT018295975&format=source) contains "Aufsatzsammlung" in 902. (Will probably open another issue for this.)

This one can be closed after deployment to production.

**Comment by dr0i** [comment]
Deployed to production. Closing.
