### ISSUE TITLE
Don't list volumes of MutlVolumeWorks but only show link to list of volumes

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#90]
See #89. We should add MultiVolumeWork to https://github.com/hbz/nwbib/blob/3041f0c1fab1ac598a290533c130262ff9bb4995/app/views/tags/result_doc.scala.html#L88 (see also https://github.com/hbz/nwbib/issues/89#issuecomment-73509613) and delete https://github.com/hbz/nwbib/blob/d3097afd5d7ccef24833d49822a5d5fb09caa610/app/views/tags/result_doc.scala.html#L77-79.

**Comment by dr0i** [comment]
Deployed to staging. Looks great! E.g. http://test.lobid.org/nwbib/HT018138615.

**Comment by acka47** [comment]
+1 Works like a charm. :v:

**Comment by dr0i** [comment]
Good staff work there at hbz :)
Deployed to production, closing.

**Comment by acka47** [comment]
This is not exactly as customers have asked for, though. They would like to have another wording for multivolume works instead of "Enthaltene Beiträge anzeigen" it should read "Enthaltene Bänder anzeigen".
