### ISSUE TITLE
Install web log analyzer

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#91]
For http://lobid.org/nwbib. See http://piwik.org/log-analytics/.

**Comment by acka47** [comment]
@dr0i chose [AWStats](http://www.awstats.org/) instead of Piwik.

**Comment by dr0i** [comment]
Me choose now [goaccess.io](http://goaccess.io). It's really fast and easy to configure. It fits very well into the linux environment. Will build you nwbib stats and show how to do that for your own or automize reports. Meanwhile have a look at the whole [lobid web access](http://stats.lobid.org/web-access/) stats.

**Comment by acka47** [comment]
I like goaccess. Looks much slicker than awstats and is morge intuitive. As soon as we have a UI only for /nwbib I will close this ticket.

**Comment by dr0i** [comment]
You'll find nwbib filtered in http://stats.lobid.org/web-access/nwbib .

**Comment by acka47** [comment]
Looks good for now. Closing.

**Comment by fsteeg** [comment]
Nice!

**Comment by dr0i** [comment]
Since our nfs, i.a. destination of the logs, crashed the second time in two months we choose to mount weywot4 as nfs and store the logs there.
Should the newest stats not be build correctly consider this the cause.
