### ISSUE TITLE
Don't show holding information for online resources

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#92]
If something is an online resource, there should be no map + information on an institution that holds this item.

Examples:
- http://test.lobid.org/nwbib/HT018544173
- http://test.lobid.org/nwbib/HT018541136

**Comment by acka47** [comment]
Requirement derived from 8.b) of https://wiki1.hbz-nrw.de/x/CoCDAw.

**Comment by fsteeg** [comment]
I seem to remember that @dr0i objected that we have resources that are both online and print resources.

**Comment by dr0i** [comment]
@fsteeg If I am not misleaded @acka47 said a `book` can also be an ebook, thus a resource typed as `book` doesn't implicit to be printed.
Anyway, @acka47 are you sure that anything we typed as `lv:fulltextOnline` is indead free to be viewed by everyone so that removing the `exemplar` property with the owning isil is fine? Otherwise, the ownership indicates from which IP you can view the resource.

**Comment by acka47** [comment]
After solving lobid/lodmill#700 we should remove the holding information from all online resources as customers requested. We will see whether this generates problems with some resources...

BTW, I just saw that there is another indicator in the data to identify online resources: There is the "Formschlagwort" "Online-Publikation" in field 902 resp. `v:subjectChain`.

**Comment by fsteeg** [comment]
So if I understand correctly this depends on https://github.com/lobid/lodmill/issues/700, therefore removing `ready` label.

**Comment by fsteeg** [comment]
https://github.com/lobid/lodmill/issues/700 is closed, adding `ready` label.

**Comment by fsteeg** [comment]
Deployed to staging, see:

- http://test.lobid.org/nwbib/HT018544173
- http://test.lobid.org/nwbib/HT018541136
- http://test.lobid.org/nwbib/ZDB2830721-5

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
Deployed to production, closing. See:

http://lobid.org/nwbib/HT018544173
http://lobid.org/nwbib/HT018541136
http://lobid.org/nwbib/ZDB2830721-5
