### ISSUE TITLE
Statistics on usage of different seach/browsing entries

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#93]
For the NWBib meeting on 13 April we should prepare some usage statistics about:
- [x] "Erweiterte Suche": http://lobid.org/nwbib/advanced
- [x] "Themensuche": http://lobid.org/nwbib/topics
- [x] Browsing of spatial classification: http://lobid.org/nwbib/classification?t=Raumsystematik & http://lobid.org/nwbib/register?t=Raumsystematik
- [x] Browsing onf subject classification: http://lobid.org/nwbib/classification?t=Sachsystematik, http://lobid.org/nwbib/register?t=Sachsystematik

**Comment by acka47** [comment]
To know about usage of Themensuche and classifications, we will have to check some more URL requests:

- *Themensuche*: We will have to check the referrer of queries like http://lobid.org/nwbib/search?q=%22M%C3%BCnster+%28Westf%29+|+Stadtentwicklung+|+Karte%22` whether it is some URL of the form `http://lobid.org/nwbib/topics?q={query}` (e.g. http://lobid.org/nwbib/topics?q=m%C3%BCnster+karte)
- *spatial classification*: Queries of the form `http://lobid.org/nwbib/search?nwbibspatial={conceptURI}` (e.g. http://lobid.org/nwbib/search?nwbibspatial=http%3A%2F%2Fpurl.org%2Flobid%2Fnwbib-spatial%23n18) can only be submitted via the "Regionen/Orte" tab.
- *subject classification*:  Queries of the form `http://lobid.org/nwbib/search?nwbibsubject={conceptURI}` (e.g. http://lobid.org/nwbib/search?nwbibsubject=http%3A%2F%2Fpurl.org%2Flobid%2Fnwbib%23s262012) can only be submitted via the "Sachgebiete" tab.
- Erweiterte Suche: Queries via advanced search always contain three search parameters. Examples:
  - http://lobid.org/nwbib/search?sort=newest&name=k%C3%B6ln&publisher=dumont&subject=karneval
  - http://lobid.org/nwbib/search?sort=newest&name=k%C3%B6ln+karneval&publisher=&subject=

**Comment by dr0i** [comment]
Done, check if http://stats.lobid.org/web-access/nwbib/issue_93/ satisfying.
Say *uh* if you want a monthly report.
Creating statistics, keep in mind:
It's right that there is only marginal usage of theses special queries - but they are 100% human invoked. So it should be set into the proper relation of overall usage of nwbib, and there 85.86% of the traffic comes alone from googlebot.

**Comment by acka47** [comment]
It's probably best to configure the stats for the classifications checking whether the referer is one of the two links provided for each classification in https://github.com/hbz/nwbib/issues/93#issue-66901524.

**Comment by acka47** [comment]
Also, we will have to check how tot create statistics on the usage of facetting options.

**Comment by dr0i** [comment]
Done re: classification and referer.
re: facets: see http://stats.lobid.org/web-access/nwbib/issue_93/2015-04-01_nwbibfacets.html . 
This statistic does not include resource facets done on the nwbib-set facetting ownership. Should this also be taken into account?

**Comment by acka47** [comment]
> This statistic does not include resource facets done on the nwbib-set facetting ownership. Should this also be taken into account? 

That's ok for now. I forgot the simple NWBib search. Can you please add statistics for this? Example query: http://lobid.org/nwbib/search?location=&q=k%C3%B6ln+karneval
URL pattern: `http://lobid.org/nwbib/search?location=&q={search terms}`

**Comment by acka47** [comment]
> I forgot the simple NWBib search. Can you please add statistics for this? Example query: http://lobid.org/nwbib/search?location=&q=k%C3%B6ln+karneval
URL pattern: `http://lobid.org/nwbib/search?location=&q={search terms}`

So we should add statistics on hits with a referer of the form `http://lobid.org/nwbib/search?location=&q={search terms}`.

**Comment by acka47** [comment]
For now I am happy with the stats. We will undoubtly have to improve the statistics in the future and will open new issues when needed. This will now be closed.

**Comment by dr0i** [comment]
Since our nfs, destination of the i.a. the logs, crashed the second time in two months we choose to mount weywot4 as nfs and store the logs there.
Should the newest stats not be build correctly consider this the cause.

**Comment by dr0i** [comment]
See also #91 .
