### ISSUE TITLE
Customization of number of results on list page

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#94]
As a user I want to choose a bigger number of results (options not clear yet, initial proposal: 25, 50, 100, 500) to be shown on one result list page so that I can get a better overview over results.

**Comment by fsteeg** [comment]
Deployed to staging: http://test.lobid.org/nwbib/search?q=ehrenfeld

**Comment by acka47** [comment]
Using the framed boxes adds another nav element typeto the page. I suggest just using links as for #95 and as we have for ranking type on production.

**Comment by fsteeg** [comment]
Redeployed to staging with nav pills as suggested: http://test.lobid.org/nwbib/search?q=ehrenfeld

**Comment by acka47** [comment]
+1
