### ISSUE TITLE
Enable combination of values from one facet to filter results

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#97]
As a user I want to combine several facets to filter a result set so that I can build a filter using related subjects.

**Comment by fsteeg** [comment]
Not sure I understand. Do you mean combining multiple values of the same facet type? E.g. to get documents that contain both subject A and subject B?

**Comment by acka47** [comment]
> Do you mean combining multiple values of the same facet type? E.g. to get documents that contain both subject A and subject B?

I guess this is what I meant and haven't expressed clearly enough. I am not sure where this issue originated. We should leave this for now and maybe ask customers at some point whether they want this.

**Comment by acka47** [comment]
Moving to backlog.

**Comment by acka47** [comment]
> I am not sure where this issue originated.

Now I know, see https://wiki1.hbz-nrw.de/x/FoDgAw, 4.2. Customers just repeated their wish to have this feature.

**Comment by fsteeg** [comment]
As mentioned on the phone earlier, I'd like to have some way to differentiate issues required for an official launch vs. further improvements. We could tag issues like this one `post-release` or similar, or the ones that need to be done to wrap up the beta as `beta` or similar.

**Comment by acka47** [comment]
In the end, customers decide which is which. I will soon schedule another meeting between us and the NWBib editors...

**Comment by acka47** [comment]
We will implement this pre-release. If we choose an AND query for value combination the list should update as soon as I have selected the first value to only show values that appear together with the first. It would be great to have the feature like this. If this doesn't work I would prefer an OR query.

**Comment by fsteeg** [comment]
Deployed to staging, see: http://test.lobid.org/nwbib

**Comment by fsteeg** [comment]
Redeployed with 1 change: 

Switch to relevance ranking on multi subject selection (as discussed offline).

See: http://test.lobid.org/nwbib

**Comment by fsteeg** [comment]
Redeployed with 1 change:

Add `onclick` handler to checkbox to fix Chromium issue (reported offline by @acka47).

See: http://test.lobid.org/nwbib

**Comment by acka47** [comment]
Some issues with this:

- Facetting doesn't work when I directly click on a box (not on the term itself) in Chromium although the ox i checked afterwards.
- I don't think, the relevance ranking works good. When I search 

There are several issues with GND subjects:
- GND subjects are taking way too long to load for bigger result lists (e.g. [search for "Kunst"](http://lobid.org/nwbib/search?location=&q=kunst)). (This problem existed before this change.) 
- Caching doesn't seem to work for bigger result lists:
   - When I select one, subjects don't load much quicker. (E.g. search for "Kunst" -> selecting "Sammlung"). The actual result page loads quick, though.
   - When I uncheck the selected subject, loading subjects again takes very long though the list should be cached.
   - Regarding the problematic size, I'd say one starts to notice with ~1.500 results (e.g. http://test.lobid.org/nwbib/search?q=dorf) and with ~2000 and more (e.g. http://test.lobid.org/nwbib/search?location=&q=bibliothek0) it definitely becomes a problem.

**Comment by acka47** [comment]
The relevance ranking works as expected. (Please ignore the half-written comment from the first version of my review comment which was sent by mail.)

**Comment by fsteeg** [comment]
I was not able to consistently reproduce the caching issue. Your `Kunst` -> `Sammlung` sample worked fine for me. Sporadically I did get the issue though. I've refactored the facet processing to avoid redundant label and icon calls and to cache the full labelled list (before, only the actual facet request and the individual label requests were cached). With this, I did not encounter long loading for the subject facet if I add or remove values only in the subject facet.

Deployed to staging: http://test.lobid.org/nwbib

**Comment by acka47** [comment]
Works better now. +1 for the add-on.

We still have something to work on regarding the GND facet. I must say that I am not happy with the overall experience especially when there is a very long GND subject list. Sorting the GND subjects by occurence (with the most appearing subjects on top) as most other systems do it would probably make this more user-friendly. Regarding NWBib classifications, the alphabetic sorting is ok, though.

**Comment by fsteeg** [comment]
Deployed to production, closing. See: http://lobid.org/nwbib
