### ISSUE TITLE
Add links between supplements and supplemented resources

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#98]
As done in https://github.com/hbz/lobid/issues/102 we now have links between supplements and the supplemented resource in lobid. These have to be shown in the NWBib views of the resources.

**Comment by acka47** [comment]
As far as I can see, we only have links from the supplemented resource to its supplements, e.g. http://lobid.org/resource/HT014630291/about (snippet):

```javascript
{
  "@graph" : [ {
    "@id" : "http://lobid.org/resource/HT014630291",
     "hasSupplement" : [ "http://lobid.org/resource/HT015855919", "http://lobid.org/resource/HT017317344", "http://lobid.org/resource/HT014507359" ],
  } ]
}
```

But there is no link back from the supplements, see e.g. http://lobid.org/resource/HT017317344 where HT014630291 isn't mentioned. Same in source data, where the link can only be found in the supplemented resource which isn't mentione din the supplement.

**Comment by dr0i** [comment]
This needs a lookup mechanism at some point:
1. when ETL data
2. when presenting on frontend

Following 1) we must come up with some performant way, following 2) we could something like http://lobid.org/resources?q=hasSupplement.id:%22http://lobid.org/resources/HT015855919%23!%22.

**Comment by acka47** [comment]
We don't need this. Closing.
