### ISSUE TITLE
Add schema.org markup to HTML

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#99]
Including alternate names for subject with property `schema:about`.

The easiest way to implement this is prbably by adding JSON-LD in a `<script>` tag. Google also supports this, see their ["About Schema.org" page](https://developers.google.com/structured-data/schema-org).

[Google's structured data testing tool](https://developers.google.com/structured-data/testing-tool/) also supports JSON-LD.

Regarding the mapping from our current RDF to schema.org, I'll make another issue as soon as starting work on this.

**Comment by acka47** [comment]
This was also requested by customers, see https://wiki1.hbz-nrw.de/x/DQBEB.

**Comment by acka47** [comment]
I created a first draft at https://wiki1.hbz-nrw.de/x/JwDDB.

**Comment by acka47** [comment]
The JSON-LD should be embedded in the HTML using `<script type="application/ld+json">` see https://developers.google.com/schemas/formats/json-ld?hl=de.

Assigning @fsteeg. You can start with a few properties like `title` `creator` and `publisher`. As soon as you have a working solution I can do the details adding the mapping for more properties.

**Comment by fsteeg** [comment]
Deployed an initial setup to staging.

See source of http://test.lobid.org/nwbib/HT018263803 (search for `ld+json`).

The embedded markup is valid JSON-LD, see http://tinyurl.com/q7eaxd3.

You can add type classes and properties in the template file at:
https://github.com/hbz/nwbib/blob/master/app/views/tags/schema_org.scala.html

**Comment by dr0i** [comment]
Is this functionality really nwbib specific or does it make sense to do this in lobid.org/api (and embed this in nwbib) ?

**Comment by acka47** [comment]
> Is this functionality really nwbib specific or does it make sense to do this in lobid.org/api (and embed this in nwbib) ?

I think this isn't important for lobid as it isn't really indexed in Google anyway (see https://www.google.de/search?q=site%3Alobid.org%2Fresource) in contrast to lobid.org/nwbib. 

Also, we currently don't serve any structured data at all in NWBib so it will be nice to at least serve some schema.org markup.

**Comment by acka47** [comment]
This will be ok for the start but we will get a much better result as soon as we have lobid API 2.0.

**Comment by fsteeg** [comment]
Deployed to production, closing. See source of:

http://lobid.org/nwbib/HT018263803
http://lobid.org/nwbib/HT018720169

**Comment by dr0i** [comment]
> I think this isn't important for lobid as it isn't really indexed in Google anyway

Yes, but what's with apps using lobid as an API - wouldn't it for them also of interest to enrich their websites with `schema.org`?

**Comment by acka47** [comment]
Let's discuss this after implementing API 2.0. For now, the schema.org markup isn't really useful anyway...
